### ISSUE TITLE
请问如何将lora微调后的模型转换成onnx模型呢

### ISSUE THREAD

**Issue by Franklinlifangcheng** [THUDM/ChatGLM3#1000]
我在尝试将微调后的权重与原始权重合并实现模型合并的效果，现在我可以将原始的chatglm3模型导出成onnx模型，但是不知道如何将微调后的模型导出成onnx，请问该如何实现呢？请问官方有合并的方法和转模型的脚本代码吗

**Comment by zRzRzRzRzRzRzR** [comment]
没有，我们没有针对onnx导出的代码

**Comment by Franklinlifangcheng** [comment]
> 没有，我们没有针对onnx导出的代码
那请问有没有合并微调后模型的代码吗

**Comment by Franklinlifangcheng** [comment]
> 没有，我们没有针对onnx导出的代码

那请问一下有没有合并微调后的模型的代码？

**Comment by yera12** [comment]
> 我在尝试将微调后的权重与原始权重合并实现模型合并的效果，现在我可以将原始的chatglm3模型导出成onnx模型，但是不知道如何将微调后的模型导出成onnx，请问该如何实现呢？请问官方有合并的方法和转模型的脚本代码吗

您好，可以发一下chatglm3模型导出成onnx模型的代码吗
