### ISSUE TITLE
在哪里对微调方法能进行修改呢？我们自己可否添加微调方法呢？

### ISSUE THREAD

**Issue by Duperr** [THUDM/ChatGLM3#1006]
### Feature request  / 功能建议

想要引入其他的微调方法

### Motivation / 动机

当前三种微调方法不适用

### Your contribution / 您的贡献

目前想对p-tuning v2进行修改然后尝试效果

**Comment by zRzRzRzRzRzRzR** [comment]
直接在finetune dmeo中改就行了，目前官方提供的demo只是最简单的demo
