### ISSUE TITLE
gradio界面的api接口调用显存泄漏

### ISSUE THREAD

**Issue by whiteless9** [THUDM/ChatGLM3#101]
使用gradio界面的api接口调用，会出现显存泄漏，显存慢慢占用变多，然后出现长文本推理异常。
环境包：gradio ==3.50.2,gradio_client==0.6.1,python==3.10
gradio接口：
client = Client("http://192.168.2.100:7860/")
result = client.predict(
		qusetion + "\n" + promot_str,	# str  in 'parameter_6' Textbox component
		"./output/test.json",	# str (filepath to JSON file) in 'parameter_2' Chatbot component
		8192,	# int | float (numeric value between 0 and 8192) in 'Maximum length' Slider component
		0.8,	# int | float (numeric value between 0 and 1) in 'Top P' Slider component
		0.95,	# int | float (numeric value between 0 and 1) in 'Temperature' Slider component
		fn_index=0
        )

**Comment by zRzRzRzRzRzRzR** [comment]
显存变多是因为历史记录的原因，需要固定清理历史才能保证显存不爆

**Comment by whiteless9** [comment]
> 显存变多是因为历史记录的原因，需要固定清理历史才能保证显存不爆

好的 谢谢

**Comment by liuchenbaidu** [comment]
> 显存变多是因为历史记录的原因，需要固定清理历史才能保证显存不爆

清理历史是怎么操作？

**Comment by zRzRzRzRzRzRzR** [comment]
有个清空历史吧

**Comment by liuchenbaidu** [comment]
gradio哪里有清空历史呢

**Comment by whiteless9** [comment]
> gradio哪里有清空历史呢

看webdemo的代码提交函数里面有个history的列表，赋空就行
