### ISSUE TITLE
98+多少=118？报错：Unexpected special token: <|assistant|>

### ISSUE THREAD

**Issue by sdcb** [THUDM/ChatGLM3#102]
有时会报错：
Unexpected special token: <|assistant|>

![image](https://github.com/THUDM/ChatGLM3/assets/1317141/78cd88ec-3f79-42c3-8ef9-e20ca1616bea)

**Comment by zRzRzRzRzRzRzR** [comment]
无法复现这个问题
![图片](https://github.com/THUDM/ChatGLM3/assets/93239683/60616276-c5d6-43f5-901a-2a38a5f43137)
请提供更多的信息

**Comment by zRzRzRzRzRzRzR** [comment]
请根据最新的issue模板，为我们提供一个最小复现，该issue先关闭，望理解
