### ISSUE TITLE
N卡的TensorRT-LLM无法使用chatglm3_6b_base构建推理引擎

### ISSUE THREAD

**Issue by cyx2000** [THUDM/ChatGLM3#1020]
### System Info / 系統信息

跟教程一致的docker环境

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在TensorRT-LLM使用
python3 build.py -m chatglm3_6b_base --output_dir trt_engines/chatglm3_6b_base/fp16/1-gpu
，会报如下的key错误：
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/chatglm/model.py", line 150, in __init__
    for key, value in self.default_config[self.model_name].__dict__.items():
KeyError: 'chatglm3_6b_base'

### Expected behavior / 期待表现

base模型也可以正常推理，使用chatglm3_6b_32k是可以推理的，看报错信息库文件这个default_config没有base的配置，只有chatglm3_6b和chatglm3_6b_32k
default_config["chatglm3_6b"] = default_config["chatglm2_6b"]
default_config["chatglm3_6b_32k"] = default_config["chatglm2_6b_32k"]

**Comment by zRzRzRzRzRzRzR** [comment]
没有base 要用chat模型

**Comment by cyx2000** [comment]
> 没有base 要用chat模型

好, 看教程里面有写, 还以为是后面更新没了

**Comment by cyx2000** [comment]
> 没有base 要用chat模型

好, 看教程里面有写, 还以为是后面更新没了

**Comment by wangqy1216** [comment]
> > 没有base 要用chat模型
> 
> 好, 看教程里面有写, 还以为是后面更新没了

请问这个build.py文件在什么位置，好像没找到
