### ISSUE TITLE
官方lora微调套件将lora更换为ptuningv2文件后微调进行预测时出现报错

### ISSUE THREAD

**Issue by tiamojames** [THUDM/ChatGLM3#1022]
### System Info / 系統信息

官方lora微调套件将lora更换为ptuningv2文件后微调进行预测时出现报错
把配置文件换了configs/ptuning-v2跑结果出现了报错
![bug2](https://github.com/THUDM/ChatGLM3/assets/110323095/a529f943-7dd8-4e01-a4a0-40e72fe38272)

### Who can help? / 谁可以帮助到您？

@Btlmd

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

官方的finetuning.ipnyb 修改configs/lora 为 configs/ptuningv2 微调出现报错
运行：
root@autodl-container-0e1740ab60-445bca8d:~/ChatGLM3/finetune_demo# python3 finetune_hf.py data/AdvertiseGen_fix/ /root/autodl-tmp/models/chatglm3-6b/ configs/ptuning_v2.yaml yes

错误信息：
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/ChatGLM3/finetune_demo/finetune_hf.py:550 in main                                          │
│                                                                                                  │
│   547 │   │   │   │   trainer.train(resume_from_checkpoint=checkpointdir)                        │
│   548 │   │   │   else:                                                                          │
│   549 │   │   │   │   # If not, start from scratch                                               │
│ ❱ 550 │   │   │   │   trainer.train()                                                            │
│   551 │   │   else:                                                                              │
│   552 │   │   │   # If it is a numerical value, select the corresponding checkpoint              │
│   553 │   │   │   if auto_resume_from_checkpoint.isdigit():                                      │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py:1624 in train              │
│                                                                                                  │
│   1621 │   │   │   finally:                                                                      │
│   1622 │   │   │   │   hf_hub_utils.enable_progress_bars()                                       │
│   1623 │   │   else:                                                                             │
│ ❱ 1624 │   │   │   return inner_training_loop(                                                   │
│   1625 │   │   │   │   args=args,                                                                │
│   1626 │   │   │   │   resume_from_checkpoint=resume_from_checkpoint,                            │
│   1627 │   │   │   │   trial=trial,                                                              │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py:2029 in                    │
│ _inner_training_loop                                                                             │
│                                                                                                  │
│   2026 │   │   │   │   │   self.state.epoch = epoch + (step + 1 + steps_skipped) / steps_in_epo  │
│   2027 │   │   │   │   │   self.control = self.callback_handler.on_step_end(args, self.state, s  │
│   2028 │   │   │   │   │                                                                         │
│ ❱ 2029 │   │   │   │   │   self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoc  │
│   2030 │   │   │   │   else:                                                                     │
│   2031 │   │   │   │   │   self.control = self.callback_handler.on_substep_end(args, self.state  │
│   2032                                                                                           │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py:2412 in                    │
│ _maybe_log_save_evaluate                                                                         │
│                                                                                                  │
│   2409 │   │                                                                                     │
│   2410 │   │   metrics = None                                                                    │
│   2411 │   │   if self.control.should_evaluate:                                                  │
│ ❱ 2412 │   │   │   metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)                     │
│   2413 │   │   │   self._report_to_hp_search(trial, self.state.global_step, metrics)             │
│   2414 │   │   │                                                                                 │
│   2415 │   │   │   # Run delayed LR scheduler now that metrics are populated                     │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/transformers/trainer_seq2seq.py:166 in evaluate    │
│                                                                                                  │
│   163 │   │   # We don't want to drop samples in general                                         │
│   164 │   │   self.gather_function = self.accelerator.gather                                     │
│   165 │   │   self._gen_kwargs = gen_kwargs                                                      │
│ ❱ 166 │   │   return super().evaluate(eval_dataset, ignore_keys=ignore_keys, metric_key_prefix   │
│   167 │                                                                                          │
│   168 │   def predict(                                                                           │
│   169 │   │   self,                                                                              │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py:3229 in evaluate           │
│                                                                                                  │
│   3226 │   │   start_time = time.time()                                                          │
│   3227 │   │                                                                                     │
│   3228 │   │   eval_loop = self.prediction_loop if self.args.use_legacy_prediction_loop else se  │
│ ❱ 3229 │   │   output = eval_loop(                                                               │
│   3230 │   │   │   eval_dataloader,                                                              │
│   3231 │   │   │   description="Evaluation",                                                     │
│   3232 │   │   │   # No point gathering the predictions if there are no metrics, otherwise we d  │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py:3520 in evaluation_loop    │
│                                                                                                  │
│   3517 │   │   │   │   │   EvalPrediction(predictions=all_preds, label_ids=all_labels, inputs=a  │
│   3518 │   │   │   │   )                                                                         │
│   3519 │   │   │   else:                                                                         │
│ ❱ 3520 │   │   │   │   metrics = self.compute_metrics(EvalPrediction(predictions=all_preds, lab  │
│   3521 │   │   else:                                                                             │
│   3522 │   │   │   metrics = {}                                                                  │
│   3523                                                                                           │
│                                                                                                  │
│ /root/ChatGLM3/finetune_demo/finetune_hf.py:425 in compute_metrics                               │
│                                                                                                  │
│   422 │   │   pred_tokens = list(jieba.cut(pred_txt))                                            │
│   423 │   │   label_tokens = list(jieba.cut(label_txt))                                          │
│   424 │   │   rouge = Rouge()                                                                    │
│ ❱ 425 │   │   scores = rouge.get_scores(' '.join(pred_tokens), ' '.join(label_tokens))           │
│   426 │   │   for k, v in scores[0].items():                                                     │
│   427 │   │   │   metrics_dct[k].append(round(v['f'] * 100, 4))                                  │
│   428 │   │   metrics_dct['bleu-4'].append(                                                      │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/rouge_chinese/rouge.py:116 in get_scores           │
│                                                                                                  │
│   113 │   │   assert(len(hyps) == len(refs))                                                     │
│   114 │   │                                                                                      │
│   115 │   │   if not avg:                                                                        │
│ ❱ 116 │   │   │   return self._get_scores(hyps, refs)                                            │
│   117 │   │   return self._get_avg_scores(hyps, refs)                                            │
│   118 │                                                                                          │
│   119 │   def _get_scores(self, hyps, refs):                                                     │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/rouge_chinese/rouge.py:129 in _get_scores          │
│                                                                                                  │
│   126 │   │   │                                                                                  │
│   127 │   │   │   for m in self.metrics:                                                         │
│   128 │   │   │   │   fn = Rouge.AVAILABLE_METRICS[m]                                            │
│ ❱ 129 │   │   │   │   sc = fn(                                                                   │
│   130 │   │   │   │   │   hyp,                                                                   │
│   131 │   │   │   │   │   ref,                                                                   │
│   132 │   │   │   │   │   raw_results=self.raw_results,                                          │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/rouge_chinese/rouge.py:54 in <lambda>              │
│                                                                                                  │
│    51 class Rouge:                                                                               │
│    52 │   DEFAULT_METRICS = ["rouge-1", "rouge-2", "rouge-l"]                                    │
│    53 │   AVAILABLE_METRICS = {                                                                  │
│ ❱  54 │   │   "rouge-1": lambda hyp, ref, **k: rouge_score.rouge_n(hyp, ref, 1, **k),            │
│    55 │   │   "rouge-2": lambda hyp, ref, **k: rouge_score.rouge_n(hyp, ref, 2, **k),            │
│    56 │   │   "rouge-3": lambda hyp, ref, **k: rouge_score.rouge_n(hyp, ref, 3, **k),            │
│    57 │   │   "rouge-4": lambda hyp, ref, **k: rouge_score.rouge_n(hyp, ref, 4, **k),            │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/rouge_chinese/rouge_score.py:253 in rouge_n        │
│                                                                                                  │
│   250 │     ValueError: raises exception if a param has len <= 0                                 │
│   251 │   """                                                                                    │
│   252 │   if len(evaluated_sentences) <= 0:                                                      │
│ ❱ 253 │   │   raise ValueError("Hypothesis is empty.")                                           │
│   254 │   if len(reference_sentences) <= 0:                                                      │
│   255 │   │   raise ValueError("Reference is empty.")                                            │
│   256                                                              
ValueError: Hypothesis is empty.
![Uploading bug2.png…]()

![ptuning](https://github.com/THUDM/ChatGLM3/assets/110323095/2a67683a-8843-4470-a2cf-f914f0672dc7)

### Expected behavior / 期待表现

希望可以得到解答

**Comment by zRzRzRzRzRzRzR** [comment]
你的依赖是？代码是前两天更新的这个版本么

**Comment by tiamojames** [comment]
> 你的依赖是？代码是前两天更新的这个版本么

我应该是2月底clone的没有变，具体依赖如下：
absl-py 1.4.0
accelerate 0.27.2
aiofiles 23.2.1
aiohttp 3.9.3
aiosignal 1.3.1
altair 5.2.0
annotated-types 0.6.0
anyio 3.6.2
argon2-cffi 21.3.0
argon2-cffi-bindings 21.2.0
arrow 1.2.3
arxiv 2.1.0
asttokens 2.2.1
async-timeout 4.0.3
attrs 22.2.0
Babel 2.11.0
backcall 0.2.0
beautifulsoup4 4.11.1
bleach 6.0.0
blinker 1.7.0
brotlipy 0.7.0
cachetools 5.3.0
certifi 2024.2.2
cffi 1.15.1
charset-normalizer 2.0.4
click 8.1.7
colorama 0.4.6
comm 0.1.2
conda 22.11.1
conda-content-trust 0.1.3
conda-package-handling 1.9.0
contourpy 1.0.7
cpm-kernels 1.0.11
cryptography 38.0.1
cycler 0.11.0
dataclasses-json 0.6.4
datasets 2.18.0
debugpy 1.6.6
decorator 5.1.1
deepspeed 0.13.4
defusedxml 0.7.1
dill 0.3.8
distro 1.9.0
executing 1.2.0
fastapi 0.110.0
fastjsonschema 2.16.2
feedparser 6.0.10
ffmpy 0.3.2
filelock 3.13.1
fonttools 4.38.0
fqdn 1.5.1
frozenlist 1.4.1
fsspec 2024.2.0
gitdb 4.0.11
GitPython 3.1.42
google-auth 2.16.0
google-auth-oauthlib 0.4.6
gradio 4.19.2
gradio_client 0.10.1
greenlet 3.0.3
grpcio 1.51.1
h11 0.14.0
hjson 3.1.0
httpcore 1.0.4
httpx 0.27.0
huggingface-hub 0.21.3
idna 3.4
importlib-metadata 7.0.1
importlib_resources 6.1.2
ipykernel 6.20.2
ipython 8.9.0
ipython-genutils 0.2.0
ipywidgets 8.0.4
isoduration 20.11.0
jedi 0.18.2
jieba 0.42.1
Jinja2 3.1.2
joblib 1.3.2
json5 0.9.11
jsonpatch 1.33
jsonpointer 2.3
jsonschema 4.17.3
jupyter 1.0.0
jupyter_client 8.6.0
jupyter-console 6.6.3
jupyter_core 5.1.5
jupyter-events 0.6.3
jupyter_server 2.1.0
jupyter_server_terminals 0.4.4
jupyterlab 3.5.3
jupyterlab-language-pack-zh-CN 3.5.post4
jupyterlab-pygments 0.2.2
jupyterlab_server 2.19.0
jupyterlab-widgets 3.0.5
kiwisolver 1.4.4
langchain 0.1.10
langchain-community 0.0.25
langchain-core 0.1.28
langchain-text-splitters 0.0.1
langchainhub 0.1.14
langsmith 0.1.13
latex2mathml 3.77.0
loguru 0.7.2
Markdown 3.4.1
markdown-it-py 3.0.0
MarkupSafe 2.1.2
marshmallow 3.21.0
matplotlib 3.6.3
matplotlib-inline 0.1.6
mdtex2html 1.3.0
mdurl 0.1.2
mistune 2.0.4
mpi4py 3.1.4
mpmath 1.3.0
multidict 6.0.5
multiprocess 0.70.16
mypy-extensions 1.0.0
nbclassic 0.5.1
nbclient 0.7.2
nbconvert 7.2.9
nbformat 5.7.3
nest-asyncio 1.5.6
networkx 3.2.1
ninja 1.11.1.1
nltk 3.8.1
notebook 6.5.2
notebook_shim 0.2.2
numpy 1.24.1
nvidia-cublas-cu12 12.1.3.1
nvidia-cuda-cupti-cu12 12.1.105
nvidia-cuda-nvrtc-cu12 12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12 8.9.2.26
nvidia-cufft-cu12 11.0.2.54
nvidia-curand-cu12 10.3.2.106
nvidia-cusolver-cu12 11.4.5.107
nvidia-cusparse-cu12 12.1.0.106
nvidia-nccl-cu12 2.19.3
nvidia-nvjitlink-cu12 12.3.101
nvidia-nvtx-cu12 12.1.105
oauthlib 3.2.2
openai 1.13.3
orjson 3.9.15
packaging 23.2
pandas 2.2.1
pandocfilters 1.5.0
parso 0.8.3
peft 0.7.1
pexpect 4.8.0
pickleshare 0.7.5
Pillow 9.4.0
pip 22.3.1
platformdirs 2.6.2
pluggy 1.0.0
prometheus-client 0.16.0
prompt-toolkit 3.0.36
protobuf 4.25.3
psutil 5.9.4
ptyprocess 0.7.0
pure-eval 0.2.2
py-cpuinfo 9.0.0
pyarrow 15.0.0
pyarrow-hotfix 0.6
pyasn1 0.4.8
pyasn1-modules 0.2.8
pycosat 0.6.4
pycparser 2.21
pydantic 2.6.3
pydantic_core 2.16.3
pydeck 0.8.1b0
pydub 0.25.1
Pygments 2.14.0
PyJWT 2.8.0
pynvml 11.5.0
pyOpenSSL 22.0.0
pyparsing 3.0.9
pyrsistent 0.19.3
PySocks 1.7.1
python-dateutil 2.8.2
python-json-logger 2.0.4
python-multipart 0.0.9
pytz 2022.7.1
PyYAML 6.0
pyzmq 25.0.0
qtconsole 5.5.1
QtPy 2.4.1
regex 2023.12.25
requests 2.31.0
requests-oauthlib 1.3.1
rfc3339-validator 0.1.4
rfc3986-validator 0.1.1
rich 13.7.1
rouge-chinese 1.0.3
rsa 4.9
ruamel.yaml 0.18.6
ruamel.yaml.clib 0.2.8
ruff 0.3.0
safetensors 0.4.2
scikit-learn 1.4.1.post1
scipy 1.12.0
semantic-version 2.10.0
Send2Trash 1.8.0
sentence-transformers 2.5.1
sentencepiece 0.2.0
setuptools 65.5.0
sgmllib3k 1.0.0
shellingham 1.5.4
six 1.16.0
smmap 5.0.1
sniffio 1.3.0
soupsieve 2.3.2.post1
SQLAlchemy 2.0.27
sse-starlette 2.0.0
stack-data 0.6.2
starlette 0.36.3
streamlit 1.31.1
sympy 1.12
tenacity 8.2.3
tensorboard 2.11.2
tensorboard-data-server 0.6.1
tensorboard-plugin-wit 1.8.1
terminado 0.17.1
threadpoolctl 3.3.0
tiktoken 0.6.0
timm 0.9.16
tinycss2 1.2.1
tokenizers 0.15.2
toml 0.10.2
tomli 2.0.1
tomlkit 0.12.0
toolz 0.12.0
torch 2.2.1
torchvision 0.17.1
tornado 6.2
tqdm 4.64.1
traitlets 5.8.1
transformers 4.38.2
triton 2.2.0
typer 0.9.0
types-requests 2.31.0.20240218
typing_extensions 4.10.0
typing-inspect 0.9.0
tzdata 2024.1
tzlocal 5.2
uri-template 1.2.0
urllib3 2.2.1
uvicorn 0.27.1
validators 0.22.0
watchdog 4.0.0
wcwidth 0.2.6
webcolors 1.12
webencodings 0.5.1
websocket-client 1.5.0
websockets 11.0.3
Werkzeug 2.2.2
wheel 0.37.1
widgetsnbextension 4.0.5
xxhash 3.4.1
yarl 1.9.4
zhipuai 2.0.1
zipp 3.17.0

**Comment by zRzRzRzRzRzRzR** [comment]
2月底bug确实有的，现在的最新代码已经修额了很多了，拉一下最新代码

**Comment by tiamojames** [comment]
> 2月底bug确实有的，现在的最新代码已经修额了很多了，拉一下最新代码

你好，现在可以进行测试了，但是测试过程不知为何产生了大量数据，50g的数据盘直接爆满导致训练报错。请问这些数据是什么，为何产生，以及我们应该如何解决这个问题
![正在上传 316468952...]![正在上传 316469185...]

**Comment by tiamojames** [comment]
> 2月底bug确实有的，现在的最新代码已经修额了很多了，拉一下最新代码

**Comment by tiamojames** [comment]
> 2月底bug确实有的，现在的最新代码已经修额了很多了，拉一下最新代码

root@autodl-container-988143ac05-0a41c588:~/autodl-tmp/ChatGLM3# cd finetune_demo/
root@autodl-container-988143ac05-0a41c588:~/autodl-tmp/ChatGLM3/finetune_demo# cd ..
root@autodl-container-988143ac05-0a41c588:~/autodl-tmp/ChatGLM3# du -sh finetune_demo/
50G     finetune_demo/
root@autodl-container-988143ac05-0a41c588:~/autodl-tmp/ChatGLM3# cd finetune_demo/
root@autodl-container-988143ac05-0a41c588:~/autodl-tmp/ChatGLM3/finetune_demo# ls
README.md  README_en.md  configs  data  finetune_hf.py  inference_hf.py  lora_finetune.ipynb  output  requirements.txt
root@autodl-container-988143ac05-0a41c588:~/autodl-tmp/ChatGLM3/finetune_demo# du -sh output/
50G     output/
output保存的checkpoint占用了大量存储空间，导致训练失败

**Comment by tiamojames** [comment]
> 2月底bug确实有的，现在的最新代码已经修额了很多了，拉一下最新代码

root@autodl-container-988143ac05-0a41c588:/autodl-tmp/ChatGLM3# cd finetune_demo/
root@autodl-container-988143ac05-0a41c588:/autodl-tmp/ChatGLM3/finetune_demo# cd ..
root@autodl-container-988143ac05-0a41c588:/autodl-tmp/ChatGLM3# du -sh finetune_demo/
50G finetune_demo/
root@autodl-container-988143ac05-0a41c588:/autodl-tmp/ChatGLM3# cd finetune_demo/
root@autodl-container-988143ac05-0a41c588:/autodl-tmp/ChatGLM3/finetune_demo# ls
README.md README_en.md configs data finetune_hf.py inference_hf.py lora_finetune.ipynb output requirements.txt
root@autodl-container-988143ac05-0a41c588:/autodl-tmp/ChatGLM3/finetune_demo# du -sh output/
50G output/
output保存的checkpoint占用了大量存储空间，导致训练失败
你好，现在可以进行测试了，但是测试过程不知为何产生了大量数据，50g的数据盘直接爆满导致训练报错。请问这些数据占据这么多空间是正常的吗？之前我使用lora训练并没有出现过硬盘空间不足问题，以及我们应该如何解决这个问题

**Comment by zRzRzRzRzRzRzR** [comment]
ptuning使用了全参微调的办法，因此单次保存就是一个12G的完整模型

**Comment by tiamojames** [comment]
> ptuning使用了全参微调的办法，因此单次保存就是一个12G的完整模型

明白了 谢谢
