### ISSUE TITLE
我Win10系统安装设置完成之后启动GBK报错

### ISSUE THREAD

**Issue by dugutianxue** [THUDM/ChatGLM3#1027]
![037{BP8_ZU)UX95G(Q~YFZG](https://github.com/THUDM/ChatGLM3/assets/22005496/05d00ee1-cdfa-4e90-9c7f-879ddc972cc9)
报错信息  一直不知道该如何解决

**Comment by zRzRzRzRzRzRzR** [comment]
你要使用utf8格式读取，或者在pyhton中写一行代码制定格式为gbk

**Comment by dugutianxue** [comment]
怎么使用UTF8格式读取
