### ISSUE TITLE
finetune_demo的readme.md文件，这一版好像删掉了“输入输出格式” 微调样例？

### ISSUE THREAD

**Issue by LuWanTong** [THUDM/ChatGLM3#1028]
### System Info / 系統信息

finetune_demo的readme.md文件，这一版好像删掉了“输入输出格式” 微调样例？记得前一版本还有一个脚本，专门将 adver数据集处理成 “输入输出格式” 格式

### Who can help? / 谁可以帮助到您？

无

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

无

**Comment by zRzRzRzRzRzRzR** [comment]
这里也是输入和输出，这个新的demo是对chat模型进行微调的，也不在区分base 和chat模型，同意使用了messages格式来存储

整理成这个新的格式，是为了更好的兼容常见的对话数据集，本质也是input 和 output（如果你对base模型进行微调）
