### ISSUE TITLE
在code interpreter 中运行报错

### ISSUE THREAD

**Issue by tomhup** [THUDM/ChatGLM3#103]
使用 python openai_api.py 启动。 设置set OPENAI_API_BASE=http://localhost:8000/v1 后， 

在interpreter 报错如下
  File "C:\ProgramData\Anaconda3\envs\python310\lib\site-packages\interpreter\utils.py", line 18, in merge_deltas
    original[key] += value
TypeError: can only concatenate str (not "NoneType") to str

**Comment by Roych13** [comment]
我记得，这个路径是要改成OpenAI的API接口地址的。这个你去platform.openai.com的API文档里查一下。
