### ISSUE TITLE
AdvertiseGen_fix下的数据集能微调，自己制作的数据集微调出错

### ISSUE THREAD

**Issue by jackyysu** [THUDM/ChatGLM3#1030]
### System Info / 系統信息

cuda: 12.1
transformers: 4.38.2
python: 3.10.13
os: win11中的wsl2

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 按jupyter notebook中的步骤，可以在AdvertiseGen_fix下的数据集上微调成功
2. 按AdvertiseGen的格式自己制作了数据集，微调时 val_dataset 和 test_dataset 的num_rows是0，信息如下：

```
train_dataset: Dataset({
    features: ['input_ids', 'labels'],
    num_rows: 269
})
val_dataset: Dataset({
    features: ['conversations'],
    num_rows: 0
})
test_dataset: Dataset({
    features: ['conversations'],
    num_rows: 0
})
```

造成后面验证步骤的时候出现以下错误：AttributeError: 'NoneType' object has no attribute 'pop'

3. 我检查了自己制作的 dev.json 文件，未发现错误，其中数据样例如下：

``{"conversations": [{"role": "user", "content": "提取下面文本中“病历”类型的实体，并严格按照JSON格式输出\n间断头晕2月，加重2天-缘于入院前约2月，患者无明显诱因出现头晕，伴视物旋转，无头痛，无恶心，无呕吐，发病时四肢麻木无力，意识清楚，无发热，无四肢抽搐，入院前2天，再次出现上述症状，今前来我院就诊，求进一步治疗，门诊以“短暂性脑缺血发作”收入我科。  自本次发病以来，患者精神差，饮食、睡眠可，大小便正常，体重无明显减轻。否认药物父母体健，兄弟姐妹体健，否认家族性遗传病史。  以上所述病史是否真实：            患者（家属）签字：既往高血压病史半年，最高血压198/100mmHg，口服苯磺酸氨氯地平血压控制不理想。否认肝炎结核等传染病病史，否认心脏病史，否认糖尿病及脑血管疾病，否认手术、外伤史,否认输血史，否认药物过敏史，预防接种史不详。 "}, {"role": "assistant", "content": "{\"收缩压\": \"198\", \"舒张压\": \"100\", \"头晕\": \"是\", \"手脚麻木\": \"是\", \"目眩\": \"是\", \"短暂性脑缺血发作（TIA）\": \"是\", \"高血压\": \"是\", \"体重明显下降\": \"否\", \"呕吐\": \"否\", \"头痛\": \"否\", \"恶心\": \"否\", \"睡眠质量\": \"良好\"}"}]}``

### Expected behavior / 期待表现

让自己的数据集能正常微调

**Comment by jackyysu** [comment]
我把可以正常训练的train.json复制为dev.json时，也会出现这样的问题（num_rows: 0），不清楚dev.json为什么不能正常加载

**Comment by zRzRzRzRzRzRzR** [comment]
格式是jsonl格式

**Comment by KerryElwood** [comment]
我也遇到了一模一样的问题，用自己的数据集
（该数据集与AdvertiseGen_fix格式一致，能够成功微调chatglm2）
之后用jupyter脚本转换数据集，遇到和楼主一样的问题。

我还看了一些之前的issue，说peft降到0.6.0，也不行。而且我看目前的requeirments.txt已经标注peft是0.10.0了

**Comment by zcs007** [comment]
调整下参数，max_input_length max_output_length 这两个参数太小了导致报错

**Comment by KerryElwood** [comment]
> 调整下参数，max_input_length max_output_length 这两个参数太小了导致报错

还真是，虽然还有其他报错，但这一步解决了
感谢感谢

**Comment by KerryElwood** [comment]
> 调整下参数，max_input_length max_output_length 这两个参数太小了导致报错

再反馈一下，max_input_length max_output_length必须严格大于等于数据集的最大输入和最大输出，否则验证集dev读入会有缺失。

十分感谢点拨

**Comment by syyou3** [comment]
> > 调整下参数，max_input_length max_output_length 这两个参数太小了导致报错
> 
> 再反馈一下，max_input_length max_output_length必须严格大于等于数据集的最大输入和最大输出，否则验证集dev读入会有缺失。
> 
> 十分感谢点拨

麻烦问一下 这两个参数最大只能设置2048吗？我的数据集里可能有超过2048token的

**Comment by zRzRzRzRzRzRzR** [comment]
可以，如果你显存够大就行了

**Comment by syyou3** [comment]
> 可以，如果你显存够大就行了

最大能设置多少呀？

**Comment by KerryElwood** [comment]
只要不报显存不够用的错应该都没事

**Comment by zRzRzRzRzRzRzR** [comment]
> > 可以，如果你显存够大就行了
> 
> 最大能设置多少呀？

模型支持多长就能设置到多长，比如chatglm3 就是你输入输出加起来8k
