### ISSUE TITLE
【关于模型推理加速】如何获取模型文件

### ISSUE THREAD

**Issue by zzisbeauty** [THUDM/ChatGLM3#1033]
### System Info / 系統信息

A100
CUDA 11.8

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

问题出在使用 TrtLLM进行模型推理加速过程中：

- [x] 已经准备好了微调（lora 微调，使用的是chatGLM3原始的 lora 配置文件）后存储下来的 checkpoint 模型文件
- [x] 已经准备好了基座模型，使用的是 32K 模型
- [x] 已经搭建好了 trt-llm 的 docker 镜像且已经启动了容器 

### 目前的推理过程

- [x] 我理解且正在运行的正常加载训练后的模型文件的过程：
i. 配置好原始的 32k 的基座模型路径（该路径是在微调得到的 checkpoint-steps 路径的adapter_config.json配置文件中配置） ；
ii. 配置好训练后使用的checkpoint-step模型文件
iii. 然后使用的是常规的如下命令即可加载训练后的模型进行推理：

```
model = AutoPeftModelForCausalLM.from_pretrained(model_dir, trust_remote_code=True, device_map='cuda:3')
```

### 我的问题

- [ ] 由于我采用的是lora微调32k，那么请问模型训练后得到的 checkpoint-step 路径下存储的是 lora 模型吗？
- [ ] 如果是，请问上面描述的基本的加载 checkpoint+base model 的过程是如果通过 AutoPeftModelForCausalLM.from_pretrained( ) 完成的模型融合。 就是说我不明白为什么这个命令就直接加载到了我微调后的模型
- [ ] 目前我准备使用 trt-llm进行 32k模型的加速，按照项目给的参考教程如下， 我肯定是使用的 【使用chatglm3_6b-32k模型】这个命令，对吗？：

```
# 构建一个默认的精度为fp16的引擎
python3 build.py -m chatglm3_6b --output_dir trt_engines/chatglm3_6b/fp16/1-gpu

# 构建一个默认的精度为fp16的引擎，并打开FMHA功能（详见下文）
python3 build.py -m chatglm3_6b --enable_context_fmha --output_dir trt_engines/chatglm3_6b/fp16/1-gpu

# 构建一个w8a16的引擎
python3 build.py -m chatglm3_6b --use_weight_only --output_dir trt_engines/chatglm3_6b/weight_only/1-gpu

# 构建一个默认的精度为fp16的引擎，并支持使用两个GPU
python3 build.py -m chatglm3_6b --world_size 2 --output_dir trt_engines/chatglm3_6b/fp16/2-gpu

# 使用chatglm3_6b_base模型
python3 build.py -m chatglm3_6b_base --output_dir trt_engines/chatglm3_6b_base/fp16/1-gpu

# 使用chatglm3_6b-32k模型
python3 build.py -m chatglm3_6b_32k --output_dir trt_engines/chatglm3_6b-32k/fp16/1-gpu
```

- [ ] 如果上述命令问题为：对。那么我使用 trt-llm build 也一定是需要 build 我微调后的model文件，但是我不清楚我该如何获得这个融合了 chekpoint-step + base model-32k 的文件。 

## 以上

- **请老师给我一些帮助** @zRzRzRzRzRzRzR  
- **期待得到老师的答复**

**Comment by zzisbeauty** [comment]
我突然意识到，要想使用 Trt-LLM进行模型加速，不会是必须要在微调之前就对 32k model 进行 build 吧。

**Comment by zRzRzRzRzRzRzR** [comment]
trt -llm 这个demo只能对原始模型进行处理，没有对微调后的模型进行处理

**Comment by zzisbeauty** [comment]
> trt -llm 这个demo只能对原始模型进行处理，没有对微调后的模型进行处理

那我现在的问题是，我需要对微调后的模型进行推理加速，我的处理流程应该是如何的呢？

**Comment by zzisbeauty** [comment]
另外我还想请教老师的是：

- 如果我放弃使用 trt 的方案，因为我需要对我微调后的模型进行加速。
- 那么我想尝试使用 vllm 的方案进行微调，前提依然是我需要将lora与基座进行 merge，但是 vllm 的方案我看到有文档说：`暂时不支持bnb和auto_gptq量化模型的merge lora, 这会产生较大的精度损失`  。 那么我想请问这里说的量化模型值得是哪个模型，是lora还是基座（抱歉我不太懂模型量化这里的问题）。 如果是指的基座模型的量化，请问glm3-32k的模型是什么量化。 如果指的是lora模型的量化，请问glm3的官方lora版本是什么量化方式，在哪里有配置说明glm3的lora量化采用的是什么方案？

还请老师帮助我。期待得到老师的答复。  @zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
我们不是量化模型，我们模型是fp16 /bf16 推理 ，不存在量化，也没有提供int4模型
