### ISSUE TITLE
macos上运行综合demo报huggingface-hub的错

### ISSUE THREAD

**Issue by Crispinli** [THUDM/ChatGLM3#1037]
### System Info / 系統信息

- m2 pro
- python 3.11

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

执行综合demo就会报错

### Expected behavior / 期待表现

Traceback (most recent call last):
  File "/miniconda3/envs/chatglm/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "/Downloads/projects/ChatGLM3/composite_demo/main.py", line 10, in <module>
    import demo_chat, demo_ci, demo_tool
  File "/Downloads/projects/ChatGLM3/composite_demo/demo_chat.py", line 4, in <module>
    from client import get_client
  File "/Downloads/projects/ChatGLM3/composite_demo/client.py", line 9, in <module>
    from huggingface_hub.inference._text_generation import TextGenerationStreamResponse, Token
ModuleNotFoundError: No module named 'huggingface_hub.inference._text_generation'

**Comment by zhxknb1** [comment]
<img width="1111" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/59738277/05649030-71db-4e44-b3ee-544276f6d79e">
已经安装了依赖，但这行代码报错
<img width="1244" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/59738277/baf4099b-ee70-4321-9647-031245398372">

**Comment by Crispinli** [comment]
> <img alt="image" width="1111" src="https://private-user-images.githubusercontent.com/59738277/317164143-05649030-71db-4e44-b3ee-544276f6d79e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjUzMzAsIm5iZiI6MTcxMTUyNTAzMCwicGF0aCI6Ii81OTczODI3Ny8zMTcxNjQxNDMtMDU2NDkwMzAtNzFkYi00ZTQ0LWIzZWUtNTQ0Mjc2ZjZkNzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA3MzcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZDk1ZDRlMjdjYjBhODM3MjU1ZTdlZDJlMGMxOWViODZiYjRhMjBiZWQ2ZTU4MWM0YWM5ZDM0MmYwYzMwNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uDjwo-OwpVDQrrGxFfMa1w1iOlID98vBwPYwra-Mx-0"> 已经安装了依赖，但这行代码报错

我已经解决了该问题，需要安装 huggingface-hub==0.20.3

**Comment by BrunoGao** [comment]
cool
