### ISSUE TITLE
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) 

### ISSUE THREAD

**Issue by maceygo** [THUDM/ChatGLM3#104]
我从modelscope上下了模型权重到服务器
运行如下两行时报错
tokenizer = AutoTokenizer.from_pretrained("/mnt/chatglm3-6b",trust_remote_code=True)
model = AutoModel.from_pretrained("/mnt/chatglm3-6b",trust_remote_code=True).cuda()

我应该重新下载权重吗？

(myenv_2) root@ai-v100-0823097:/mnt/ChatGLM3-main# python3 web_demo.py 
╭─────────────────── Traceback (most recent call last) ───────────────────╮
│ /mnt/ChatGLM3-main/web_demo.py:6 in <module>                            │
│                                                                         │
│     3 import mdtex2html                                                 │
│     4 from utils import load_model_on_gpus                              │
│     5 # ~/.cache/modelscope/hub/ZhipuAI/chatglm3-6b                     │
│ ❱   6 tokenizer = AutoTokenizer.from_pretrained("/mnt/chatglm3-6b")     │
│     7 model = AutoModel.from_pretrained("/mnt/chatglm3-6b").cuda()      │
│     8                                                                   │
│     9                                                                   │
│                                                                         │
│ /root/miniconda3/envs/myenv_2/lib/python3.8/site-packages/transformers/ │
│ models/auto/tokenization_auto.py:670 in from_pretrained                 │
│                                                                         │
│   667 │   │   │   tokenizer_class = None                                │
│   668 │   │   │   if tokenizer_auto_map is not None:                    │
│   669 │   │   │   │   if not trust_remote_code:                         │
│ ❱ 670 │   │   │   │   │   raise ValueError(                             │
│   671 │   │   │   │   │   │   f"Loading {pretrained_model_name_or_path} │
│   672 │   │   │   │   │   │   " repo on your local machine. Make sure y │
│   673 │   │   │   │   │   │   " then set the option `trust_remote_code= │
╰─────────────────────────────────────────────────────────────────────────╯
ValueError: Loading /mnt/chatglm3-6b requires you to execute the tokenizer 
file in that repo on your local machine. Make sure you have read the code 
there to avoid malicious use, then set the option `trust_remote_code=True` 
to remove this error.
(myenv_2) root@ai-v100-0823097:/mnt/ChatGLM3-main# python3 web_demo.py 
╭─────────────────── Traceback (most recent call last) ───────────────────╮
│ /mnt/ChatGLM3-main/web_demo.py:6 in <module>                            │
│                                                                         │
│     3 import mdtex2html                                                 │
│     4 from utils import load_model_on_gpus                              │
│     5 # ~/.cache/modelscope/hub/ZhipuAI/chatglm3-6b                     │
│ ❱   6 tokenizer = AutoTokenizer.from_pretrained("/mnt/chatglm3-6b",trus │
│     7 model = AutoModel.from_pretrained("/mnt/chatglm3-6b",trust_remote │
│     8                                                                   │
│     9                                                                   │
│                                                                         │
│ /root/miniconda3/envs/myenv_2/lib/python3.8/site-packages/transformers/ │
│ models/auto/tokenization_auto.py:693 in from_pretrained                 │
│                                                                         │
│   690 │   │   │   │   raise ValueError(                                 │
│   691 │   │   │   │   │   f"Tokenizer class {tokenizer_class_candidate} │
│   692 │   │   │   │   )                                                 │
│ ❱ 693 │   │   │   return tokenizer_class.from_pretrained(pretrained_mod │
│   694 │   │                                                             │
│   695 │   │   # Otherwise we have to be creative.                       │
│   696 │   │   # if model is an encoder decoder, the encoder tokenizer c │
│                                                                         │
│ /root/miniconda3/envs/myenv_2/lib/python3.8/site-packages/transformers/ │
│ tokenization_utils_base.py:1812 in from_pretrained                      │
│                                                                         │
│   1809 │   │   │   else:                                                │
│   1810 │   │   │   │   logger.info(f"loading file {file_path} from cach │
│   1811 │   │                                                            │
│ ❱ 1812 │   │   return cls._from_pretrained(                             │
│   1813 │   │   │   resolved_vocab_files,                                │
│   1814 │   │   │   pretrained_model_name_or_path,                       │
│   1815 │   │   │   init_configuration,                                  │
│                                                                         │
│ /root/miniconda3/envs/myenv_2/lib/python3.8/site-packages/transformers/ │
│ tokenization_utils_base.py:1975 in _from_pretrained                     │
│                                                                         │
│   1972 │   │                                                            │
│   1973 │   │   # Instantiate tokenizer.                                 │
│   1974 │   │   try:                                                     │
│ ❱ 1975 │   │   │   tokenizer = cls(*init_inputs, **init_kwargs)         │
│   1976 │   │   except OSError:                                          │
│   1977 │   │   │   raise OSError(                                       │
│   1978 │   │   │   │   "Unable to load vocabulary from file. "          │
│                                                                         │
│ /root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/token │
│ ization_chatglm.py:87 in __init__                                       │
│                                                                         │
│    84 │   │   self.name = "GLMTokenizer"                                │
│    85 │   │                                                             │
│    86 │   │   self.vocab_file = vocab_file                              │
│ ❱  87 │   │   self.tokenizer = SPTokenizer(vocab_file)                  │
│    88 │   │   self.special_tokens = {                                   │
│    89 │   │   │   "<bos>": self.tokenizer.bos_id,                       │
│    90 │   │   │   "<eos>": self.tokenizer.eos_id,                       │
│                                                                         │
│ /root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/token │
│ ization_chatglm.py:15 in __init__                                       │
│                                                                         │
│    12 │   def __init__(self, model_path: str):                          │
│    13 │   │   # reload tokenizer                                        │
│    14 │   │   assert os.path.isfile(model_path), model_path             │
│ ❱  15 │   │   self.sp_model = SentencePieceProcessor(model_file=model_p │
│    16 │   │                                                             │
│    17 │   │   # BOS / EOS token IDs                                     │
│    18 │   │   self.n_words: int = self.sp_model.vocab_size()            │
│                                                                         │
│ /root/miniconda3/envs/myenv_2/lib/python3.8/site-packages/sentencepiece │
│ /__init__.py:447 in Init                                                │
│                                                                         │
│    444 │     self._alpha = alpha                                        │
│    445 │     self._num_threads = num_threads                            │
│    446 │     if model_file or model_proto:                              │
│ ❱  447 │   │   self.Load(model_file=model_file, model_proto=model_proto │
│    448 │                                                                │
│    449 │                                                                │
│    450 │   def Encode(self,                                             │
│                                                                         │
│ /root/miniconda3/envs/myenv_2/lib/python3.8/site-packages/sentencepiece │
│ /__init__.py:905 in Load                                                │
│                                                                         │
│    902 │   │   raise RuntimeError('model_file and model_proto must be e │
│    903 │     if model_proto:                                            │
│    904 │   │   return self.LoadFromSerializedProto(model_proto)         │
│ ❱  905 │     return self.LoadFromFile(model_file)                       │
│    906                                                                  │
│    907                                                                  │
│    908 # Register SentencePieceProcessor in _sentencepiece:             │
│                                                                         │
│ /root/miniconda3/envs/myenv_2/lib/python3.8/site-packages/sentencepiece │
│ /__init__.py:310 in LoadFromFile                                        │
│                                                                         │
│    307 │   │   return _sentencepiece.SentencePieceProcessor_serialized_ │
│    308 │                                                                │
│    309 │   def LoadFromFile(self, arg):                                 │
│ ❱  310 │   │   return _sentencepiece.SentencePieceProcessor_LoadFromFil │
│    311 │                                                                │
│    312 │   def _EncodeAsIds(self, text, enable_sampling, nbest_size, al │
│    313 │   │   return _sentencepiece.SentencePieceProcessor__EncodeAsId │
╰─────────────────────────────────────────────────────────────────────────╯
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) 
[model_proto->ParseFromArray(serialized.data(), serialized.size())]

**Comment by maceygo** [comment]
我已经解决了

**Comment by LeonardMeagher2** [comment]
> I have solved it

How?

**Comment by maceygo** [comment]
> > I have solved it
> 
> How?

The model file stored in my model weight directory is incomplete. Recheck it and it will run normally.
