### ISSUE TITLE
问下vllm部署启动成功后支持api访问模式吗？为什么访问接口报404 INFO: 172.26.0.2:34438 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found

### ISSUE THREAD

**Issue by Andy1018** [THUDM/ChatGLM3#1040]
### System Info / 系統信息

 NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2  

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

vllm方式启动成功，访问接口报404
POST /v1/chat/completions HTTP/1.1" 404 Not Found

### Expected behavior / 期待表现

vllm模式部署成功能后，支持api接口调用

**Comment by zRzRzRzRzRzRzR** [comment]
支持，但是官方demo没有写，需要自己修改
