### ISSUE TITLE
请问 chatglm3的history是预先定义好吗？如果可以的话，应该怎么定义，格式是什么？

### ISSUE THREAD

**Issue by Zhangyiming0039** [THUDM/ChatGLM3#1043]
history=[
            ("question1","answer1"),
             ("question2","answer2"),
             ("question3","answer3"),
        ]
        response, history = model.chat(tokenizer, question1, history=None)
是上述方法定义的吗？

**Comment by zRzRzRzRzRzRzR** [comment]
是，
你可以可以直接用chat_template 构建，就是openai 的user assistant对话那套
