### ISSUE TITLE
chaGLM3-6B模型的任务类型

### ISSUE THREAD

**Issue by 12915494174** [THUDM/ChatGLM3#1046]
请问chaGLM3-6B模型支持的任务类型都有哪些（比如：CAUSAL_LM、SEQ_2_SEQ_LM、FEATURE_EXTRACTION等等）？

**Comment by zRzRzRzRzRzRzR** [comment]
CAUSAL_LM

**Comment by 12915494174** [comment]
> CAUSAL_LM

好的，谢谢！
