### ISSUE TITLE
130B 大模型不更新了吗？

### ISSUE THREAD

**Issue by yhyu13** [THUDM/ChatGLM3#105]
130B大模型训练一次要3个月左右吧，半年前就没更新过了吧

**Comment by FlatMapIO** [comment]
<img width="795" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/1720349/294f712c-03a6-4eb1-8b97-dc9d899e940a">

**Comment by yhyu13** [comment]
这个130B用的是glm3的最新技术？

**Comment by FlatMapIO** [comment]
6b 以上的版本用于商业化产品了.

**Comment by yhyu13** [comment]
ok
