### ISSUE TITLE
load_model_on_gpus 报错

### ISSUE THREAD

**Issue by hejianle** [THUDM/ChatGLM3#1054]
### System Info / 系統信息

ubuntu

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

_raceback (most recent call last):
  File "/root/ChatGLM3/finetune_chatmodel_demo/inferencev2.py", line 24, in <module>
    model = load_model_on_gpus(args.model, num_gpus=8)
  File "/root/ChatGLM3/finetune_chatmodel_demo/utils.py", line 51, in load_model_on_gpus
    model = dispatch_model(model, device_map=device_map)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/big_modeling.py", line 343, in dispatch_model
    check_device_map(model, device_map)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/modeling.py", line 1142, in check_device_map
    raise ValueError(
ValueError: The device_map provided does not give any device for the following parameters: transformer.embedding.word_embeddings.weight, transformer.rotary_pos_emb.inv_freq, transformer.encoder.layers.0.input_layernorm.weight, transformer.encoder.layers.0.self_attention.query_key_value.weight, transformer.encoder.layers.0.self_attention.query_key_value.bias, transformer.encoder.layers.0.self_attention.dense.weight, transformer.encoder.layers.0.post_attention_layernorm.weight, transformer.encoder.layers.0.mlp.dense_h_to_4h.weight, transformer.encoder.layers.0.mlp.dense_4h_to_h.weight, transformer.encoder.layers.1.input_layernorm.weight, transformer.encoder.layers.1.self_attention.query_key_value.weight, transformer.encoder.layers.1.self_attention.query_key_value.bias, transformer.encoder.layers.1.self_attention.dense.weight, transformer.encoder.layers.1.post_attention_layernorm.weight, transformer.encoder.layers.1.mlp.dense_h_to_4h.weight, transformer.encoder.layers.1.mlp.dense_4h_to_h.weight, transformer.encoder.layers.2.input_layernorm.weight, transformer.encoder.layers._

### Expected behavior / 期待表现

不报错

**Comment by zRzRzRzRzRzRzR** [comment]
你直接拉最新的代码呢，device map 设定为auto
