### ISSUE TITLE
.quantize(4)好像压缩不了模型

### ISSUE THREAD

**Issue by DeepAichemist** [THUDM/ChatGLM3#1059]
### System Info / 系統信息

model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).cuda().quantize(4)
model = model.eval()
如果我这样子运行，会显示我的GPU只有8G是运行不了的
model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).quantize(4).cuda()
model = model.eval()
我先.quantize(4)的时候，又会告诉我没有在CUDA设备上进行.quantize(4)。死锁了

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).cuda().quantize(4).eval()

model = model.eval()
response, history = model.chat(tokenizer, "你好", history=[])
print(response)

### Expected behavior / 期待表现

怎么解决这个内存大小不够的问题

**Comment by sslyc** [comment]
同样的问题，关注

**Comment by DeepAichemist** [comment]
![1711697910768](https://github.com/THUDM/ChatGLM3/assets/96474936/ac2f6df3-8bd4-401d-8dca-48ae09fac6b0)
大家可以找到quantization.py文件，然后去Hugging Face先把代码修改回来，就可以使用了。同时建议如果要使用网页UI也就是web_demo_gradio.py这个文件，最好使用git方法把代码模型全部下载下来，因为如果直接使用transformers 自动下载模型实现和参数，会有一部分的模型没有下载完全，并且下载下来的文件的名字是进过哈希转码后的，是不能使用网页demo的，会报错误说没有找到对应的文件

**Comment by suze985** [comment]
@zRzRzRzRzRzRzR 您好，请问您解决了吗，我也是相对其进行量化但是跑不起来
