### ISSUE TITLE
chat方法的history参数的默认类型有误

### ISSUE THREAD

**Issue by ito-integration** [THUDM/ChatGLM3#106]
chat方法的默认类型和chatglm2一样，为List[Tuple[str, str]]。但实际上，tokenizer.build_chat_input方法与chatglm2中的build_prompt并不相同。真正可用的history应该是List[Dict]，字典的格式如下：
{"role": "user", "content": query}
除了"role"和"content"，还可以添加名为"metadata"和"tools"的key

**Comment by duzx16** [comment]
感谢指出，已经修改了
