### ISSUE TITLE
使用推理脚本inference_hf时报错：AttributeError: can't set attribute 'eos_token'如何解决

### ISSUE THREAD

**Issue by MingjunHu** [THUDM/ChatGLM3#1063]
### System Info / 系統信息

python==3.10.14

transformers==4.39.2

torch==2.2.2+cu12.4

Centos8:

gpu：4090

cpu：14900k

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [x] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

微调使用官方脚本：超参设置如下，个别调整了：
ata_config:
  train_file: train.json
  val_file: dev.json
  test_file: dev.json
  num_proc: 16
max_input_length: 128
max_output_length: 256
training_args:
  # see `transformers.Seq2SeqTrainingArguments`
  output_dir: ./output
  max_steps: 150000
  # settings for data loading
  per_device_train_batch_size: 6 #24G显存可以设置到4到8
  dataloader_num_workers: 16
  remove_unused_columns: false
  # settings for saving checkpoints
  save_strategy: steps
  save_steps: 1000
  # settings for logging
  log_level: info
  logging_strategy: steps
  logging_steps: 10
  # settings for evaluation
  per_device_eval_batch_size: 16
  evaluation_strategy: steps
  eval_steps: 500
  # settings for optimizer
  # adam_epsilon: 1e-6
  # uncomment the following line to detect nan or inf values
  # debug: underflow_overflow
  predict_with_generate: true
  # see `transformers.GenerationConfig`
  generation_config:
    max_new_tokens: 256
  # set your absolute deepspeed path here
  #deepspeed: ds_zero_2.json
  # set to true if train with cpu.
  use_cpu: false
peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 8
  lora_alpha: 64
  lora_dropout: 0.1

训练后使用官方脚本推，理执行命令：
python inference_hf.py output/checkpoint-3000/ --prompt "类型#裙*版型#显瘦*材质#网纱*风格#性感*裙型#百褶*裙下摆#压 褶*裙长#连衣裙*裙衣门襟#拉链*裙衣门襟#套头*裙款式#拼接*裙款式#拉链*裙款式#木耳边*裙款式#抽褶*裙款式#不规则"

python inference_hf.py output/checkpoint-3000/ --prompt "类型#裙*版型#显瘦*材质#网纱"
报错：AttributeError: can't set attribute 'eos_token'

![image](https://github.com/THUDM/ChatGLM3/assets/9472965/4d462d0a-aac8-4662-8958-32c64cf1e8f3)

### Expected behavior / 期待表现

期望能正常进行推理，并告知原因和解决方案。
多谢

**Comment by zRzRzRzRzRzRzR** [comment]
是最新代码么

**Comment by MingjunHu** [comment]
上周4左右拉取的，3月28号左右

**Comment by MingjunHu** [comment]
和我的 r调整到16有关系吗？

**Comment by MingjunHu** [comment]
> 是最新代码么

应该是最新，能尽快给看看吗？

**Comment by ecsfu** [comment]
hf上下载最新的py和.json后没报这个错了，但是又出现cuda断言错误

**Comment by MingjunHu** [comment]
> hf上下载最新的py和.json后没报这个错了，但是又出现cuda断言错误

我用原模型推理也没有问题，就是用微调后的模型不行，报错

**Comment by ecsfu** [comment]
有没有可能是原模型里面的文件和微调时的文件存在变更，导致的不匹配。你是基于hf上最新的文件微调的么

**Comment by sanbei011** [comment]
> > hf上下载最新的py和.json后没报这个错了，但是又出现cuda断言错误
> 
> 我用原模型推理也没有问题，就是用微调后的模型不行，报错

我也是我也是,好奇怪,微调之后使用inference_hf.py脚本就会出现`"断言错误"`

**Comment by zRzRzRzRzRzRzR** [comment]
更新最新的github仓库，hugginfgface仓库，如果是老代码，你使用原始的chatglm3 tokenizer，删掉微调文件夹中的tokenizer就行

**Comment by MingjunHu** [comment]
重新下的代码和模型，重新训练，ok了
