### ISSUE TITLE
无法安装微调所需要的依赖

### ISSUE THREAD

**Issue by pencui** [THUDM/ChatGLM3#1064]
### System Info / 系統信息

系统信息，加微信14727136596可以获得虚拟机登录方式

Ubuntu 22.04 server 64bit with Tesla Driver 535.1
--
(jupyterLab) root@ecs-e2fa:~/ChatGLM3/finetune_demo# python --version
Python 3.10.13
(jupyterLab) root@ecs-e2fa:~/ChatGLM3/finetune_demo# nvidia-smi | grep -i cuda
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |

transformers              4.39.2

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

pip install -f finetune_demo/requirements.txt

Building wheels for collected packages: deepspeed, jieba, mpi4py
  Building wheel for deepspeed (setup.py) ... done
  Created wheel for deepspeed: filename=deepspeed-0.13.1-py3-none-any.whl size=1350305 sha256=caea77ea5ad0f1e8f6c67ecd1a00f8738f08aac38bb43fa1ea52e0c64a73f4c1
  Stored in directory: /root/.cache/pip/wheels/0f/fb/b5/b159b3500525eca167d8ca6e3a7e224b6075045cac90f47cf7
  Building wheel for jieba (setup.py) ... done
  Created wheel for jieba: filename=jieba-0.42.1-py3-none-any.whl size=19314458 sha256=5aa84ed9d26a22361d4606fc59eaec0fd26f30c305e2d79b277df2fefda419a0
  Stored in directory: /root/.cache/pip/wheels/c9/69/31/d56d90b22a1777b0b231e234b00302a55be255930f8bd92dcd
  Building wheel for mpi4py (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for mpi4py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [148 lines of output]
      running bdist_wheel
      running build
      running build_src
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/mpi4py
      copying src/mpi4py/__main__.py -> build/lib.linux-x86_64-cpython-310/mpi4py
      copying src/mpi4py/bench.py -> build/lib.linux-x86_64-cpython-310/mpi4py
      copying src/mpi4py/run.py -> build/lib.linux-x86_64-cpython-310/mpi4py
      copying src/mpi4py/__init__.py -> build/lib.linux-x86_64-cpython-310/mpi4py
      creating build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/futures/_lib.py -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/futures/__main__.py -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/futures/__init__.py -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/futures/aplus.py -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/futures/server.py -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/futures/pool.py -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/futures/_base.py -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/futures/_core.py -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      creating build/lib.linux-x86_64-cpython-310/mpi4py/util
      copying src/mpi4py/util/dtlib.py -> build/lib.linux-x86_64-cpython-310/mpi4py/util
      copying src/mpi4py/util/__init__.py -> build/lib.linux-x86_64-cpython-310/mpi4py/util
      copying src/mpi4py/util/pkl5.py -> build/lib.linux-x86_64-cpython-310/mpi4py/util
      copying src/mpi4py/MPI.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py
      copying src/mpi4py/__init__.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py
      copying src/mpi4py/__main__.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py
      copying src/mpi4py/run.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py
      copying src/mpi4py/bench.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py
      copying src/mpi4py/dl.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py
      copying src/mpi4py/py.typed -> build/lib.linux-x86_64-cpython-310/mpi4py
      copying src/mpi4py/MPI.pxd -> build/lib.linux-x86_64-cpython-310/mpi4py
      copying src/mpi4py/__init__.pxd -> build/lib.linux-x86_64-cpython-310/mpi4py
      copying src/mpi4py/libmpi.pxd -> build/lib.linux-x86_64-cpython-310/mpi4py
      creating build/lib.linux-x86_64-cpython-310/mpi4py/include
      creating build/lib.linux-x86_64-cpython-310/mpi4py/include/mpi4py
      copying src/mpi4py/include/mpi4py/mpi4py.h -> build/lib.linux-x86_64-cpython-310/mpi4py/include/mpi4py
      copying src/mpi4py/include/mpi4py/mpi4py.MPI_api.h -> build/lib.linux-x86_64-cpython-310/mpi4py/include/mpi4py
      copying src/mpi4py/include/mpi4py/mpi4py.MPI.h -> build/lib.linux-x86_64-cpython-310/mpi4py/include/mpi4py
      copying src/mpi4py/include/mpi4py/mpi4py.i -> build/lib.linux-x86_64-cpython-310/mpi4py/include/mpi4py
      copying src/mpi4py/include/mpi4py/mpi.pxi -> build/lib.linux-x86_64-cpython-310/mpi4py/include/mpi4py
      copying src/mpi4py/futures/__init__.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/futures/_lib.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/futures/__main__.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/futures/_core.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/futures/pool.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/futures/server.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/futures/aplus.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py/futures
      copying src/mpi4py/util/__init__.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py/util
      copying src/mpi4py/util/pkl5.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py/util
      copying src/mpi4py/util/dtlib.pyi -> build/lib.linux-x86_64-cpython-310/mpi4py/util
      running build_clib
      MPI configuration: [mpi] from 'mpi.cfg'
      checking for library 'lmpe' ...
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -c _configtest.c -o _configtest.o
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat _configtest.o -llmpe -o _configtest
      /root/anaconda3/envs/jupyterLab/compiler_compat/ld: cannot find -llmpe: No such file or directory
      collect2: error: ld returned 1 exit status
      failure.
      removing: _configtest.c _configtest.o
      building 'mpe' dylib library
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/src
      creating build/temp.linux-x86_64-cpython-310/src/lib-pmpi
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -c src/lib-pmpi/mpe.c -o build/temp.linux-x86_64-cpython-310/src/lib-pmpi/mpe.o
      creating build/lib.linux-x86_64-cpython-310/mpi4py/lib-pmpi
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -shared -Wl,-rpath,/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath-link,/root/anaconda3/envs/jupyterLab/lib -L/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath,/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath-link,/root/anaconda3/envs/jupyterLab/lib -L/root/anaconda3/envs/jupyterLab/lib -Wl,--no-as-needed build/temp.linux-x86_64-cpython-310/src/lib-pmpi/mpe.o -o build/lib.linux-x86_64-cpython-310/mpi4py/lib-pmpi/libmpe.so
      checking for library 'vt-mpi' ...
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -c _configtest.c -o _configtest.o
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat _configtest.o -lvt-mpi -o _configtest
      /root/anaconda3/envs/jupyterLab/compiler_compat/ld: cannot find -lvt-mpi: No such file or directory
      collect2: error: ld returned 1 exit status
      failure.
      removing: _configtest.c _configtest.o
      checking for library 'vt.mpi' ...
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -c _configtest.c -o _configtest.o
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat _configtest.o -lvt.mpi -o _configtest
      /root/anaconda3/envs/jupyterLab/compiler_compat/ld: cannot find -lvt.mpi: No such file or directory
      collect2: error: ld returned 1 exit status
      failure.
      removing: _configtest.c _configtest.o
      building 'vt' dylib library
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -c src/lib-pmpi/vt.c -o build/temp.linux-x86_64-cpython-310/src/lib-pmpi/vt.o
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -shared -Wl,-rpath,/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath-link,/root/anaconda3/envs/jupyterLab/lib -L/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath,/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath-link,/root/anaconda3/envs/jupyterLab/lib -L/root/anaconda3/envs/jupyterLab/lib -Wl,--no-as-needed build/temp.linux-x86_64-cpython-310/src/lib-pmpi/vt.o -o build/lib.linux-x86_64-cpython-310/mpi4py/lib-pmpi/libvt.so
      checking for library 'vt-mpi' ...
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -c _configtest.c -o _configtest.o
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat _configtest.o -lvt-mpi -o _configtest
      /root/anaconda3/envs/jupyterLab/compiler_compat/ld: cannot find -lvt-mpi: No such file or directory
      collect2: error: ld returned 1 exit status
      failure.
      removing: _configtest.c _configtest.o
      checking for library 'vt.mpi' ...
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -c _configtest.c -o _configtest.o
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat _configtest.o -lvt.mpi -o _configtest
      /root/anaconda3/envs/jupyterLab/compiler_compat/ld: cannot find -lvt.mpi: No such file or directory
      collect2: error: ld returned 1 exit status
      failure.
      removing: _configtest.c _configtest.o
      building 'vt-mpi' dylib library
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -c src/lib-pmpi/vt-mpi.c -o build/temp.linux-x86_64-cpython-310/src/lib-pmpi/vt-mpi.o
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -shared -Wl,-rpath,/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath-link,/root/anaconda3/envs/jupyterLab/lib -L/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath,/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath-link,/root/anaconda3/envs/jupyterLab/lib -L/root/anaconda3/envs/jupyterLab/lib -Wl,--no-as-needed build/temp.linux-x86_64-cpython-310/src/lib-pmpi/vt-mpi.o -o build/lib.linux-x86_64-cpython-310/mpi4py/lib-pmpi/libvt-mpi.so
      checking for library 'vt-hyb' ...
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -c _configtest.c -o _configtest.o
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat _configtest.o -lvt-hyb -o _configtest
      /root/anaconda3/envs/jupyterLab/compiler_compat/ld: cannot find -lvt-hyb: No such file or directory
      collect2: error: ld returned 1 exit status
      failure.
      removing: _configtest.c _configtest.o
      checking for library 'vt.ompi' ...
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -c _configtest.c -o _configtest.o
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat _configtest.o -lvt.ompi -o _configtest
      /root/anaconda3/envs/jupyterLab/compiler_compat/ld: cannot find -lvt.ompi: No such file or directory
      collect2: error: ld returned 1 exit status
      failure.
      removing: _configtest.c _configtest.o
      building 'vt-hyb' dylib library
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -c src/lib-pmpi/vt-hyb.c -o build/temp.linux-x86_64-cpython-310/src/lib-pmpi/vt-hyb.o
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -shared -Wl,-rpath,/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath-link,/root/anaconda3/envs/jupyterLab/lib -L/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath,/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath-link,/root/anaconda3/envs/jupyterLab/lib -L/root/anaconda3/envs/jupyterLab/lib -Wl,--no-as-needed build/temp.linux-x86_64-cpython-310/src/lib-pmpi/vt-hyb.o -o build/lib.linux-x86_64-cpython-310/mpi4py/lib-pmpi/libvt-hyb.so
      running build_ext
      MPI configuration: [mpi] from 'mpi.cfg'
      checking for dlopen() availability ...
      checking for header 'dlfcn.h' ...
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -I/root/anaconda3/envs/jupyterLab/include/python3.10 -c _configtest.c -o _configtest.o
      success!
      removing: _configtest.c _configtest.o
      success!
      checking for library 'dl' ...
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -I/root/anaconda3/envs/jupyterLab/include/python3.10 -c _configtest.c -o _configtest.o
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat _configtest.o -Lbuild/temp.linux-x86_64-cpython-310 -ldl -o _configtest
      success!
      removing: _configtest.c _configtest.o _configtest
      checking for function 'dlopen' ...
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -I/root/anaconda3/envs/jupyterLab/include/python3.10 -c _configtest.c -o _configtest.o
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat _configtest.o -Lbuild/temp.linux-x86_64-cpython-310 -ldl -o _configtest
      success!
      removing: _configtest.c _configtest.o _configtest
      building 'mpi4py.dl' extension
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -DHAVE_DLFCN_H=1 -DHAVE_DLOPEN=1 -I/root/anaconda3/envs/jupyterLab/include/python3.10 -c src/dynload.c -o build/temp.linux-x86_64-cpython-310/src/dynload.o
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -shared -Wl,-rpath,/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath-link,/root/anaconda3/envs/jupyterLab/lib -L/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath,/root/anaconda3/envs/jupyterLab/lib -Wl,-rpath-link,/root/anaconda3/envs/jupyterLab/lib -L/root/anaconda3/envs/jupyterLab/lib build/temp.linux-x86_64-cpython-310/src/dynload.o -Lbuild/temp.linux-x86_64-cpython-310 -ldl -o build/lib.linux-x86_64-cpython-310/mpi4py/dl.cpython-310-x86_64-linux-gnu.so
      checking for MPI compile and link ...
      gcc -pthread -B /root/anaconda3/envs/jupyterLab/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -O2 -isystem /root/anaconda3/envs/jupyterLab/include -fPIC -I/root/anaconda3/envs/jupyterLab/include/python3.10 -c _configtest.c -o _configtest.o
      _configtest.c:2:10: fatal error: mpi.h: No such file or directory
          2 | #include <mpi.h>
            |          ^~~~~~~
      compilation terminated.
      failure.
      removing: _configtest.c _configtest.o
      error: Cannot compile MPI programs. Check your configuration!!!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mpi4py
Successfully built deepspeed jieba
Failed to build mpi4py
ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects

### Expected behavior / 期待表现

安装成功

**Comment by lingdu5h** [comment]
我也遇到这样的问题，请问最终是如何解决的？

**Comment by yetzi1975** [comment]
装一个合适版本的mpich:
yum install mpich-3.2.x86_64

验证是否安装正确
which mpicc

如路径不对，则手工加mpicc的PATH
export PATH=$PATH:/data/anaconda3/bin

使路径生效
source ~/.bashrc

pip install mpi4py
