### ISSUE TITLE
微调时提示模型路径为None

### ISSUE THREAD

**Issue by pencui** [THUDM/ChatGLM3#1065]
### System Info / 系統信息

(myenv) root@ecs-e2fa:~/ChatGLM3/finetune_demo/chatglm3-6b# python --version
Python 3.11.7
(myenv) root@ecs-e2fa:~/ChatGLM3/finetune_demo/chatglm3-6b# nvidia-smi | grep -i cuda
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
(myenv) root@ecs-e2fa:~/ChatGLM3/finetune_demo/chatglm3-6b# pip list | grep transformers
sentence-transformers     2.6.1
transformers              4.39.2
(myenv) root@ecs-e2fa:~/ChatGLM3/finetune_demo/chatglm3-6b# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

!CUDA_VISIBLE_DEVICES=1 python finetune_hf.py  data/AdvertiseGen_fix  chatglm3-6b  configs/lora.yaml

我用print检查过modelDir 传的是chatglm3-6b不是None，不知道为啥到底层代码就变None了

chatglm内部代码报错：
/root/.pyenv/versions/3.11.7/lib/python3.11/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/root/.pyenv/versions/3.11.7/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /root/ChatGLM3/finetune_demo/finetune_hf.py:461 in main                      │
│                                                                              │
│   458                                                                        │
│   459 ):                                                                     │
│   460 │   ft_config = FinetuningConfig.from_file(config_file)                │
│ ❱ 461 │   tokenizer, model = load_tokenizer_and_model(model_dir, peft_config │
│   462 │   data_manager = DataManager(data_dir, ft_config.data_config)        │
│   463 │                                                                      │
│   464 │   train_dataset = data_manager.get_dataset(                          │
│                                                                              │
│ /root/ChatGLM3/finetune_demo/finetune_hf.py:390 in load_tokenizer_and_model  │
│                                                                              │
│   387 │   │   model_dir: str,                                                │
│   388 │   │   peft_config: Optional[PeftConfig] = None,                      │
│   389 ) -> tuple[PreTrainedTokenizer, nn.Module]:                            │
│ ❱ 390 │   tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_ │
│   391 │   if peft_config is not None:                                        │
│   392 │   │   if peft_config.peft_type.name == "PREFIX_TUNING":              │
│   393 │   │   │   config = AutoConfig.from_pretrained(model_dir, trust_remot │
│                                                                              │
│ /root/.pyenv/versions/3.11.7/lib/python3.11/site-packages/transformers/model │
│ s/auto/tokenization_auto.py:822 in from_pretrained                           │
│                                                                              │
│   819 │   │   │   _ = kwargs.pop("code_revision", None)                      │
│   820 │   │   │   if os.path.isdir(pretrained_model_name_or_path):           │
│   821 │   │   │   │   tokenizer_class.register_for_auto_class()              │
│ ❱ 822 │   │   │   return tokenizer_class.from_pretrained(                    │
│   823 │   │   │   │   pretrained_model_name_or_path, *inputs, trust_remote_c │
│   824 │   │   │   )                                                          │
│   825 │   │   elif config_tokenizer_class is not None:                       │
│                                                                              │
│ /root/.pyenv/versions/3.11.7/lib/python3.11/site-packages/transformers/token │
│ ization_utils_base.py:2086 in from_pretrained                                │
│                                                                              │
│   2083 │   │   │   else:                                                     │
│   2084 │   │   │   │   logger.info(f"loading file {file_path} from cache at  │
│   2085 │   │                                                                 │
│ ❱ 2086 │   │   return cls._from_pretrained(                                  │
│   2087 │   │   │   resolved_vocab_files,                                     │
│   2088 │   │   │   pretrained_model_name_or_path,                            │
│   2089 │   │   │   init_configuration,                                       │
│                                                                              │
│ /root/.pyenv/versions/3.11.7/lib/python3.11/site-packages/transformers/token │
│ ization_utils_base.py:2325 in _from_pretrained                               │
│                                                                              │
│   2322 │   │                                                                 │
│   2323 │   │   # Instantiate the tokenizer.                                  │
│   2324 │   │   try:                                                          │
│ ❱ 2325 │   │   │   tokenizer = cls(*init_inputs, **init_kwargs)              │
│   2326 │   │   except OSError:                                               │
│   2327 │   │   │   raise OSError(                                            │
│   2328 │   │   │   │   "Unable to load vocabulary from file. "               │
│                                                                              │
│ /root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/tokenizati │
│ on_chatglm.py:109 in __init__                                                │
│                                                                              │
│   106 │   ):                                                                 │
│   107 │   │   self.name = "GLMTokenizer"                                     │
│   108 │   │   self.vocab_file = vocab_file                                   │
│ ❱ 109 │   │   self.tokenizer = SPTokenizer(vocab_file)                       │
│   110 │   │   self.special_tokens = {                                        │
│   111 │   │   │   "<bos>": self.tokenizer.bos_id,                            │
│   112 │   │   │   "<eos>": self.tokenizer.eos_id,                            │
│                                                                              │
│ /root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/tokenizati │
│ on_chatglm.py:17 in __init__                                                 │
│                                                                              │
│    14 class SPTokenizer:                                                     │
│    15 │   def __init__(self, model_path: str):                               │
│    16 │   │   # reload tokenizer                                             │
│ ❱  17 │   │   assert os.path.isfile(model_path), model_path                  │
│    18 │   │   self.sp_model = SentencePieceProcessor(model_file=model_path)  │
│    19 │   │                                                                  │
│    20 │   │   # BOS / EOS token IDs                                          │
│ in isfile:30                                                                 │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: stat: path should be string, bytes, os.PathLike or integer, not 
NoneType

### Expected behavior / 期待表现

微调成功

**Comment by zRzRzRzRzRzRzR** [comment]
使用绝对地址
