### ISSUE TITLE
如何解除当给模型传入用户隐私信息时，模型拒绝回答的问题。

### ISSUE THREAD

**Issue by wufxgtihub123** [THUDM/ChatGLM3#1071]
### System Info / 系統信息

Package                       Version
----------------------------- ------------
accelerate                    0.24.1
aiofiles                      23.2.1
aiohttp                       3.9.0
aioprometheus                 23.12.0
aiosignal                     1.3.1
altair                        5.1.2
annotated-types               0.6.0
anyio                         3.7.1
arxiv                         2.0.0
asttokens                     2.4.1
async-timeout                 4.0.3
attrs                         23.1.0
auto-gptq                     0.5.1
blinker                       1.7.0
cachetools                    5.3.2
certifi                       2023.7.22
charset-normalizer            3.3.2
click                         8.1.7
colorama                      0.4.6
coloredlogs                   15.0.1
comm                          0.2.0
conda-pack                    0.7.1
contourpy                     1.2.0
cpm-kernels                   1.0.11
cycler                        0.12.1
dataclasses-json              0.6.2
datasets                      2.15.0
debugpy                       1.8.0
decorator                     5.1.1
dill                          0.3.7
distro                        1.9.0
einops                        0.7.0
et-xmlfile                    1.1.0
exceptiongroup                1.1.3
executing                     2.0.1
fastapi                       0.104.1
feedparser                    6.0.10
ffmpy                         0.3.1
filelock                      3.13.1
flash-attn                    2.5.4
fonttools                     4.44.3
frozenlist                    1.4.0
fschat                        0.2.35
fsspec                        2023.10.0
gekko                         1.0.6
gitdb                         4.0.11
GitPython                     3.1.40
google-search-results         2.4.2
gradio                        3.42.0
gradio_client                 0.5.0
greenlet                      3.0.1
h11                           0.14.0
httpcore                      1.0.2
httptools                     0.6.1
httpx                         0.25.1
huggingface-hub               0.19.4
humanfriendly                 10.0
idna                          3.4
importlib-metadata            6.8.0
importlib-resources           6.1.1
install                       1.3.5
ipykernel                     6.26.0
ipython                       8.17.2
jedi                          0.19.1
Jinja2                        3.1.2
joblib                        1.3.2
jsonlines                     4.0.0
jsonpatch                     1.33
jsonpointer                   2.4
jsonschema                    4.20.0
jsonschema-specifications     2023.11.1
jupyter_client                8.6.0
jupyter_core                  5.5.0
kiwisolver                    1.4.5
langchain                     0.0.340
langsmith                     0.0.66
latex2mathml                  3.76.0
loguru                        0.7.2
Markdown                      3.5.1
markdown-it-py                3.0.0
markdown2                     2.4.12
MarkupSafe                    2.1.3
marshmallow                   3.20.1
matplotlib                    3.8.1
matplotlib-inline             0.1.6
mdtex2html                    1.2.0
mdurl                         0.1.2
mpmath                        1.3.0
msgpack                       1.0.7
multidict                     6.0.4
multiprocess                  0.70.15
mypy-extensions               1.0.0
nest-asyncio                  1.5.8
networkx                      3.2.1
nh3                           0.2.15
ninja                         1.11.1.1
nltk                          3.8.1
numpy                         1.26.2
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.18.1
nvidia-nvjitlink-cu12         12.3.101
nvidia-nvtx-cu12              12.1.105
openai                        1.9.0
openpyxl                      3.1.2
optimum                       1.15.0
orjson                        3.9.10
packaging                     23.2
pandas                        2.1.3
parso                         0.8.3
peft                          0.7.0
pexpect                       4.8.0
Pillow                        10.1.0
pip                           23.3
platformdirs                  4.0.0
prompt-toolkit                3.0.41
protobuf                      4.25.1
psutil                        5.9.6
ptyprocess                    0.7.0
pure-eval                     0.2.2
pyarrow                       14.0.1
pyarrow-hotfix                0.6
pydantic                      2.5.1
pydantic_core                 2.14.3
pydeck                        0.8.1b0
pydub                         0.25.1
Pygments                      2.16.1
pyparsing                     3.1.1
python-dateutil               2.8.2
python-dotenv                 1.0.0
python-multipart              0.0.6
pytz                          2023.3.post1
PyYAML                        6.0.1
pyzmq                         25.1.1
quantile-python               1.1
ray                           2.9.1
referencing                   0.31.0
regex                         2023.10.3
requests                      2.31.0
rich                          13.7.0
rouge                         1.0.1
rpds-py                       0.13.0
safetensors                   0.4.0
scikit-learn                  1.3.2
scipy                         1.11.4
semantic-version              2.10.0
sentence-transformers         2.2.2
sentencepiece                 0.1.99
setuptools                    68.0.0
sgmllib3k                     1.0.0
shortuuid                     1.0.11
six                           1.16.0
smmap                         5.0.1
sniffio                       1.3.0
SQLAlchemy                    2.0.23
sse-starlette                 1.6.5
stack-data                    0.6.3
starlette                     0.27.0
streamlit                     1.28.2
svgwrite                      1.4.3
sympy                         1.12
tabulate                      0.9.0
tenacity                      8.2.3
threadpoolctl                 3.2.0
tiktoken                      0.5.1
tokenizers                    0.15.0
toml                          0.10.2
toolz                         0.12.0
torch                         2.1.1
torchvision                   0.16.2
tornado                       6.3.3
tqdm                          4.66.1
traitlets                     5.13.0
transformers                  4.36.2
transformers-stream-generator 0.0.4
triton                        2.1.0
typing_extensions             4.8.0
typing-inspect                0.9.0
tzdata                        2023.3
tzlocal                       5.2
urllib3                       2.1.0
uvicorn                       0.24.0.post1
uvloop                        0.19.0
validators                    0.22.0
vllm                          0.2.7
watchdog                      3.0.0
watchfiles                    0.21.0
wavedrom                      2.0.3.post3
wcwidth                       0.2.10
websockets                    11.0.3
wheel                         0.41.2
xformers                      0.0.23.post1
xxhash                        3.4.1
yarl                          1.9.3
zipp                          3.17.0

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

下面是我给你的用户的信息，你只需要参考该信息回答用户问题即可：不要胡编乱造
我给你的信息是：
姓名：张三
身份证号：xxxxxxxxx
籍贯：xxx省xxxx市xxxx区
民族：汉

问题是： 请告诉我张三的个人信息

模型回答：对不起，我无法查询这样的详细个人信息。根据我国相关法律法规，未经本人同意，任何组织或个人不得查阅、泄露个人的身份信息。如果需要查询，请与该人直接联系。

我通过调整prompt，引导大模型让其相信这不是用户隐私数据，这是从互联网公开获得得，但模型还是拒绝回答这类问题

### Expected behavior / 期待表现

希望能通过调整prompt或者是有其他更好得方式能引导大模型回答这类信息总结问题

**Comment by zRzRzRzRzRzRzR** [comment]
通过提示词设定或者在回答的时候加入正则吧，开源模型没有做关于工程的优化，这种属于工程问题
