### ISSUE TITLE
拓展词表

### ISSUE THREAD

**Issue by shilida** [THUDM/ChatGLM3#1072]
### System Info / 系統信息

torch>=1.13.1
transformers>=4.37.2
datasets>=2.14.3
accelerate>=0.27.2
peft>=0.10.0
trl>=0.8.1
gradio>=3.38.0,<4.0.0
scipy
einops
sentencepiece
protobuf
uvicorn
pydantic
fastapi
sse-starlette
matplotlib
fire
galore-torch

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

想要拓展词表，但是model.resize_token_embeddings(len(tokenizer))无法实现。
![image](https://github.com/THUDM/ChatGLM3/assets/39895844/c90298c0-7b11-4051-a804-d99e8ea6c872)

### Expected behavior / 期待表现

model.resize_token_embeddings(len(tokenizer))可以实现拓展词表

**Comment by zRzRzRzRzRzRzR** [comment]
您添加新的词汇并扩展词表时，新加入的词汇的嵌入是随机初始化的。这意味着这些新词汇的嵌入不会被模型预先训练好，而且SentencePieceProcessor要重新训练模型
