### ISSUE TITLE
API模式部署chatglm3后，多用户同时调用api_server.py文件中的接口，流式回复，会出现报错

### ISSUE THREAD

**Issue by RyanOvO** [THUDM/ChatGLM3#1075]
### System Info / 系統信息

硬件：A10

### Who can help? / 谁可以帮助到您？

报错内容如下：
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/apienv/lib/python3.10/site-packages/sse_starlette/sse.py", line 281, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/apienv/lib/python3.10/site-packages/sse_starlette/sse.py", line 270, in wrap
    await func()
  File "/home/apienv/lib/python3.10/site-packages/sse_starlette/sse.py", line 221, in listen_for_disconnect
    message = await receive()
  File "/home/apienv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 538, in receive
    await self.message_event.wait()
  File "/opt/conda/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fc04e909030

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/home/apienv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "/home/apienv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
  |     return await self.app(scope, receive, send)
  |   File "/home/apienv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/home/apienv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/apienv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/home/apienv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/home/apienv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
  |     await self.app(scope, receive, send)
  |   File "/home/apienv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/home/apienv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/apienv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/apienv/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/apienv/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
  |     await route.handle(scope, receive, send)
  |   File "/home/apienv/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
  |     await self.app(scope, receive, send)
  |   File "/home/apienv/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/home/apienv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/apienv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/apienv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
  |     await response(scope, receive, send)
  |   File "/home/apienv/lib/python3.10/site-packages/sse_starlette/sse.py", line 267, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/apienv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/apienv/lib/python3.10/site-packages/sse_starlette/sse.py", line 270, in wrap
    |     await func()
    |   File "/home/apienv/lib/python3.10/site-packages/sse_starlette/sse.py", line 251, in stream_response
    |     async for data in self.body_iterator:
    |   File "/home/apienv/lib/python3.10/site-packages/starlette/concurrency.py", line 65, in iterate_in_threadpool
    |     yield await anyio.to_thread.run_sync(_next, as_iterator)
    |   File "/home/apienv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |   File "/home/apienv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    |     return await future
    |   File "/home/apienv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    |     result = context.run(func, *args)
    |   File "/home/apienv/lib/python3.10/site-packages/starlette/concurrency.py", line 54, in _next
    |     return next(iterator)
    |   File "/home/chatglm3/api_server.py", line 418, in predict_stream
    |     for new_response in generate_stream_chatglm3(model, tokenizer, gen_params):
    |   File "/home/apienv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    |     response = gen.send(request)
    |   File "/home/chatglm3/utils.py", line 81, in generate_stream_chatglm3
    |     for total_ids in model.stream_generate(**inputs, eos_token_id=eos_token_id, **gen_kwargs):
    |   File "/home/apienv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    |     response = gen.send(request)
    |   File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1163, in stream_generate
    |     outputs = self(
    |   File "/home/apienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    |     return self._call_impl(*args, **kwargs)
    |   File "/home/apienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    |     return forward_call(*args, **kwargs)
    |   File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 941, in forward
    |     transformer_outputs = self.transformer(
    |   File "/home/apienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    |     return self._call_impl(*args, **kwargs)
    |   File "/home/apienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    |     return forward_call(*args, **kwargs)
    |   File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 834, in forward
    |     hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
    |   File "/home/apienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    |     return self._call_impl(*args, **kwargs)
    |   File "/home/apienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    |     return forward_call(*args, **kwargs)
    |   File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 641, in forward
    |     layer_ret = layer(
    |   File "/home/apienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    |     return self._call_impl(*args, **kwargs)
    |   File "/home/apienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    |     return forward_call(*args, **kwargs)
    |   File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 565, in forward
    |     mlp_output = self.mlp(layernorm_output)
    |   File "/home/apienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    |     return self._call_impl(*args, **kwargs)
    |   File "/home/apienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    |     return forward_call(*args, **kwargs)
    |   File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 499, in forward
    |     intermediate_parallel = self.activation_func(intermediate_parallel)
    |   File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 483, in swiglu
    |     return F.silu(x[0]) * x[1]
    | RuntimeError: CUDA error: device-side assert triggered
    | CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
    | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    | Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
    | 
    +------------------------------------
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [32,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

按api_demo文档部署api_server，多用户请求接口/v1/chat/completions，报错内容如上。单用户没问题，单机单卡部署。

### Expected behavior / 期待表现

解决此问题

**Comment by zRzRzRzRzRzRzR** [comment]
这个demo是面向单个用户的，多个用户的话要使用非流，这只是一个最简单的demo
