### ISSUE TITLE
新版微调代码测试无响应

### ISSUE THREAD

**Issue by yutong12** [THUDM/ChatGLM3#1079]
### System Info / 系統信息

cuda11.7
python3.10.12
torch2.2.1

### Who can help? / 谁可以帮助到您？

@Btlmd 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

完全按照官方的要求安装依赖，在一台云服务器上安装完成
使用示例广告数据集  减少数据量到 train 60条，dev 60条
在数据加载部分卡住 无错误信息
![测试](https://github.com/THUDM/ChatGLM3/assets/59248260/7cded693-e87b-4123-8627-0092a41ee929)
同时在ptuning微调时生成的全量参数 且无法用inference_hf.py进行预测
预测提示 tokenizer没有指定类
错误信息为：<transformers modules.checkpoint-10.configuration chatglm.chatGLMconfig'> 不是指定的方法

### Expected behavior / 期待表现

能正常响应

**Comment by zRzRzRzRzRzRzR** [comment]
已修复

**Comment by stephengineer** [comment]
在4090，cuda12.1没有问题，但是在A100上cuda11.3就没有响应。
