### ISSUE TITLE
问答过程中显存累积增长

### ISSUE THREAD

**Issue by simplystart-from-begining** [THUDM/ChatGLM3#108]
在NVIDIA3090单卡上测试，模型拉起后显存占用12200MiB，但在问答过程中显存累积增长，且每次问题结束后显存不降怎么处理？

**Comment by coderwpf** [comment]
我也遇到这个问题，然后32K超长后，显存GUP会爆掉内存溢出。

**Comment by zhaozhaoxia** [comment]
同上，这个问题要怎么解决？

**Comment by wzwtime** [comment]
怎么解决？

**Comment by zRzRzRzRzRzRzR** [comment]
定期清理History，这是目前比较好的解决方案

**Comment by Btlmd** [comment]
> 在NVIDIA3090单卡上测试，模型拉起后显存占用12200MiB，但在问答过程中显存累积增长，且每次问题结束后显存不降怎么处理？

能否提供具体的运行脚本名称，和一组可以导致超出显存的输入序列，便于我们定位问题？

**Comment by invokerbyxv** [comment]
> 定期清理History，这是目前比较好的解决方案

请问怎么清理History，torch.cuda.empty_cache()也没用。调用model.chat()方法传入的history也只是固定的一段system

**Comment by zhangweijian97** [comment]
同问。遇到相同问题，内存暴涨然后卡住。如何清理history？我只用单轮对话，每次chat，history都是空的。
