### ISSUE TITLE
请问chatglm中tokenizer(question)的结果是question+[gMASK]+<sop>，但是如果我自己进行tokenizer，设定为[gMASK]+<sop>+question，两种方式是否都可以。

### ISSUE THREAD

**Issue by shenhao-stu** [THUDM/ChatGLM3#1082]
请问chatglm中tokenizer(question)的结果是question+[gMASK]+<sop>，后续为生成的结果进行model.generation(**input_ids)，但是如果我自己进行tokenizer，设定为[gMASK]+<sop>+question，后续为模型回答的内容。两种方式是否都可以。
在llama-factory中采用了如下的模板：
_register_template(
    name="chatglm",
    format_user=StringFormatter(slots=["[Round {{idx}}]\n\n问：{{content}}\n\n答："]),
    format_system=StringFormatter(slots=[{"token": "[gMASK]"}, {"token": "<sop>"}, "{{content}}"]),
    format_separator=EmptyFormatter(slots=["\n\n"]),
    efficient_eos=True,
    force_system=True,
)

**Comment by shenhao-stu** [comment]
我想问的是chatglm1的chat函数，他的user字段为："[Round {{idx}}]\n\n问：{{content}}\n\n答："，在进行tokenizer(input)后，在结尾加上[gMASK]和sop。我想用自己的tokenizer函数，是否可以encode为[gMASK]+sop+input的形式。[gMASK]为生成模型的标志，sop为开始的标志。

- 对于chatglm3我知道需要<|user|>{{content}}<|assistant|>字段，同样的问题，我应该选择是[gMASK]+sop+<|user|>{{content}}<|assistant|>还是<|user|>{{content}}<|assistant|>[gMASK]+sop

![image](https://github.com/THUDM/ChatGLM3/assets/65658684/b0441ee7-66ff-4e2f-85d4-a427678f3747)

**Comment by zRzRzRzRzRzRzR** [comment]
[gMASK]sop<|user|> 是这样啊

**Comment by edc3000** [comment]
想问下我要做简单的指令微调（e.g., 帮我提取标题的人名）非对话，使用的是alpaca格式，tokenizer处理是这样吗：instrution +input +[gMASK] + sop +answer

**Comment by zRzRzRzRzRzRzR** [comment]
直接用 chat_template 构建
