### ISSUE TITLE
chatglm3-6b-128k需要多大的GPU才能跑起来啊？

### ISSUE THREAD

**Issue by zhidaoai** [THUDM/ChatGLM3#1086]
### Feature request  / 功能建议

如题

### Motivation / 动机

同上

### Your contribution / 您的贡献

谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
根据显存吧，没有测过。。。token越多显存占用越多

**Comment by xuwtgx** [comment]
使用默认配置24g很轻松
