### ISSUE TITLE
用这个去解析一些文本，发现速度有点慢，M1 pro 芯片

### ISSUE THREAD

**Issue by hellokuls** [THUDM/ChatGLM3#110]

**Comment by hellokuls** [comment]
大概有 1500tokens，耗时 13s

**Comment by hellokuls** [comment]
是不是换成别的，例如使用别的 GPU 的方式会更快？

**Comment by hydrahail** [comment]
Good to know

**Comment by Roych13** [comment]
我之前16G内存，跑chatglm2-6b，4位量化，半小时才能回答。后面直接租用一些云服务器来测试，秒出。如果你只是测试的话，建议租用吧，2块多一个小时，其实不算贵。搞好之后再让公司买硬件（不过前不久听说A800已经没货了）。
