### ISSUE TITLE
是否可以商用？

### ISSUE THREAD

**Issue by 239573049** [THUDM/ChatGLM3#1104]
### System Info / 系統信息

Window 11

### Who can help? / 谁可以帮助到您？

![image](https://github.com/THUDM/ChatGLM3/assets/61819790/dcbb60f4-c070-4887-b189-54efad8f7f4c)
这一句话是指学术研究商用还是都可以商用，到底是在玩文字游戏还是什么？是只有学术研究完全商用免费，还是填写问卷以后都可以免费？

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

我想知道他的许可到底是什么？

**Comment by zRzRzRzRzRzRzR** [comment]
填写问卷后可以商用（公司对内对外等）
学术届（用于跑分等）不用写问卷
