### ISSUE TITLE
chatGLM3-6b-32模型，cuda版本12.0.centOS系统，vllm版本0.2.7,当使用vllm对chatGLM3-6b-32K进行推理时，模型输出重复内容

### ISSUE THREAD

**Issue by zhoumz123** [THUDM/ChatGLM3#1109]
### System Info / 系統信息

chatGLM3-6b-32模型，cuda版本12.0.centOS系统，vllm版本0.2.7，Python 3.10,transformers  4.36.2

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1：下载chatGLM3-6b-32K
2：安装vllm 0.2.6
3：启动模型：python3 -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --port 9117 --model /data/models/chatglm3-32k --trust-remote-code
4:  测试模型，发现输出不对

### Expected behavior / 期待表现

希望vllm能正常推理chatGLM3，得到正常的反馈

**Comment by zRzRzRzRzRzRzR** [comment]
两个问题
1. vllm需要更新到最新版本，0.2.x版本应该没有glm3模板
2. 如果还不行，尝试将glm3-6b 的tokenizer_config 和 [tokenization_chatglm.py](https://huggingface.co/THUDM/chatglm3-6b/blob/main/tokenization_chatglm.py) 复制过去32k的文件夹下面
