### ISSUE TITLE
运行tools_using_demo/openai_api_demo.py的时候出错

### ISSUE THREAD

**Issue by wangdraco** [THUDM/ChatGLM3#1111]
### System Info / 系統信息

cuda12.3， pytorch2.2.1+cu121，python3.11，chatglm3-6b

### Who can help? / 谁可以帮助到您？

@abmfy

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

openai.UnprocessableEntityError: Error code: 422 - {'detail': [{'type': 'dict_type', 'loc': ['body', 'tools', 'dict[any,any]'], 'msg': 'Input should be a valid dictionary', 'input': ['random_number_generator', 'get_weather'], 'url': 'https://errors.pydantic.dev/2.6/v/dict_type'}, {'type': 'dict_type', 'loc': ['body', 'tools', 'list[dict[any,any]]', 0], 'msg': 'Input should be a valid dictionary', 'input': 'random_number_generator', 'url': 'https://errors.pydantic.dev/2.6/v/dict_type'}, {'type': 'dict_type', 'loc': ['body', 'tools', 'list[dict[any,any]]', 1], 'msg': 'Input should be a valid dictionary', 'input': 'get_weather', 'url': 'https://errors.pydantic.dev/2.6/v/dict_type'}]}

### Expected behavior / 期待表现

应该显示某个城市的天气

**Comment by zRzRzRzRzRzRzR** [comment]
这个怎么感觉是没有成功调用或者格式不符合呢？
这个返回也是错的

返回正确的也不是直接执行工具，而是返回工具名称和输入参数

**Comment by humphreyde** [comment]
> 这个怎么感觉是没有成功调用或者格式不符合呢？ 这个返回也是错的
> 
> 返回正确的也不是直接执行工具，而是返回工具名称和输入参数

你好，我也遇到同样的错误，请问怎么解决的呢？
