### ISSUE TITLE
能支持 DirectML 吗

### ISSUE THREAD

**Issue by rheros** [THUDM/ChatGLM3#1115]
### Feature request  / 功能建议

能支持使用 DirectML 设备吗
本人是 Windows 平台 AMD 6800xt 显卡，在使用 StableDiffusion 的时候有对应的 Directml 版本的仓库，ComfyUI 也有对 DirectML的支持，不然 CPU 跑这个实在是太慢了 T_T ，一个字一个字的蹦，所以希望能支持 DirectML。
我稍微改了一下加载
mport torch_directorml 
Dml=torch_directml. device() 
AutoModel. from retrained (MODEL_PATH, trust-remote_code=True). to (dml). eval() 
结果运行时报下面的错，提出问题后，会报，启动时没有问题。
Execution time report: expected key in DispatchKeySet (CPU, CUDA, HIP, XLA, MPS, IPU, XPU, HPU, Lazy, Meta) but got: PrivateUse1 

### Motivation / 动机

在 Pytorch 在 Windows 平台上不支持Rocm 的情况下，希望可以通过 DirectML 来拯救广大的 A 卡党

### Your contribution / 您的贡献

没有啥贡献，

**Comment by zRzRzRzRzRzRzR** [comment]
额，这个确实没有支持哦，Rocm 是支持，但是只能Linux
