### ISSUE TITLE
有关模型进行特定任务的处理逻辑分析？

### ISSUE THREAD

**Issue by mawenju203** [THUDM/ChatGLM3#112]
![image](https://github.com/THUDM/ChatGLM3/assets/30227934/cf3f4277-e34d-478e-be48-96a38f2fc854)

如图所示：列的数学方程式是正确的，python代码也是正确的；但是回答的结果是错误的
![image](https://github.com/THUDM/ChatGLM3/assets/30227934/54853dec-2528-4680-b17f-80169f9d0cfc)

**请问？模型是针对对应的文本直接进行文本的输出，并未进行相关的python代码的执行吗？**

如果我要设计一个问题，进行多个步骤依次执行，然后汇总；如何设计模型的训练数据呢？

**Comment by zRzRzRzRzRzRzR** [comment]
这里看上去是没有执行代码的，请确认使用的是否为综合demo
关于如何设计训练数据
你应该设计好连续对话数据，并按照我们提供的finetune demo来进行拼接，如果要调用工具，提示词应该拼接成Prompt.md中工具调用的提示词

**Comment by mawenju203** [comment]
@zRzRzRzRzRzRzR 谢谢您的回复，我理解您的意思，是使用多轮对话解决复杂问题，有点像https://finisky.github.io/process-supervision-reward-model/
