### ISSUE TITLE
chatglm3-6b-128k 无法多轮对话

### ISSUE THREAD

**Issue by bruleli** [THUDM/ChatGLM3#1120]
### System Info / 系統信息

cuda 11.7
Python 3.8.10
transformers 4.32.1
显存：24GB
langchain 0.0.335
torch 2.0.1
Windows10

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

本地部署chatglm3-6b后可以多轮对话，从chatglm3-6b切换到chatglm3-6b-128k后无法多轮对话，没有看到报错，显存是24GB，请问chatglm3-6b-128k支持多轮对话吗？还是切换过程中哪里出错了呢？

### Expected behavior / 期待表现

chatglm3-6b-128k 多轮对话

**Comment by zRzRzRzRzRzRzR** [comment]
那无法多轮对话是啥呢？没报错

**Comment by bruleli** [comment]
这里的多轮对话是指模型根据之前的对话内容理解和生成回应，切换chatglm3-6b-128k后，只能根据当前输入的prompt生成回应，失去了上下文的能力，在对话过程中没有看到报错。
举个例子，在一个对话中问：“谁是乔治·华盛顿？”然后接着说：“他是什么时候出生的？”，chatglm3-6b-128k没有根据上下文信息来理解“他”指的是乔治·华盛顿。

**Comment by zRzRzRzRzRzRzR** [comment]
估计是指令跟随不太行，这个好像确实有。。。确实效果不是很好

**Comment by lmxin123** [comment]
请问这个chatglm3-6b-128k模型支持量化不

**Comment by bruleli** [comment]
> 估计是指令跟随不太行，这个好像确实有。。。确实效果不是很好 你用的是哪个demo
请问 demo 指的是啥呢？

**Comment by zRzRzRzRzRzRzR** [comment]
> 请问这个chatglm3-6b-128k模型支持量化不

支持
