### ISSUE TITLE
Lora ChatGLM-B会出错

### ISSUE THREAD

**Issue by sunshinewhy** [THUDM/ChatGLM3#1123]
运行Lora命令 python .\inference_hf.py .\output\checkpoint-200\ --prompt "类型#裙*版型#显瘦*材质#网纱*风格#性 
感*裙型#百褶*裙下摆#压褶*裙长#连衣裙*裙衣门襟#拉链*裙衣门襟#套头*裙款式#拼接*裙款式#拉链*裙款式#木耳边*裙款式#抽褶*裙款式#不规则"
会报错
AttributeError: property 'eos_token' of 'ChatGLMTokenizer' object has no setter
Win10系统

**Comment by zRzRzRzRzRzRzR** [comment]
模型 / 代码都更新 了吗
