### ISSUE TITLE
关于工具调用数据集的构建，有所疑问

### ISSUE THREAD

**Issue by tiamojames** [THUDM/ChatGLM3#1128]
### System Info / 系統信息

[
    {
      "tools" : [
        {
            "name": "track",
            "description": "追踪指定股票的实时价格",
            "parameters": {
                "type": "object",
                "properties": {
                    "symbol": {
                        "description": "需要追踪的股票代码"
                    }
                },
                "required": ['symbol']
            }
        },
        {
            "name": "text-to-speech",
            "description": "将文本转换为语音",
            "parameters": {
                "type": "object",
                "properties": {
                    "text": {
                        "description": "需要转换成语音的文本"
                    },
                    "voice": {
                        "description": "要使用的语音类型（男声、女声等）"
                    },
                    "speed": {
                        "description": "语音的速度（快、中等、慢等）"
                    }
                },
                "required": ['text']
            }
        }
    ],

      "conversations": [
        {
          "role": "user",
          "content": "<user prompt text>"
        },
        {
          "role": "assistant",
          "content": "<assistant thought to text>"
        },
        {
          "role": "tool",
          "name": "<name of the tool to be called",
          "parameters": {
            "<parameter_name>": "<parameter_value>"
          },
          "observation": "<observation>"
          // don't have to be string
        },
        {
          "role": "assistant",
          "content": "<assistant response to observation>"
        }
      ]
    }
    // ...
  ]

1.请问关于readme微调套件中的tool数据集构建，以上json格式中我的“tool"部分是否正确

2.”conversations“部分的格式我不太能够理解，为什么一个input和一个output，最后一个conversation中有4个角色role，请问是否有参考的tool微调数据集可以帮助理解

3.请问现在还可以的代码中还可以正常进行工具微调吗？

### Who can help? / 谁可以帮助到您？

@Btlmd

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

希望可以解答我的疑问，感激不尽！

1.请问关于readme微调套件中的tool数据集构建，以上json格式中我的“tool"部分是否正确

2.”conversations“部分的格式我不太能够理解，为什么一个input和一个output，最后一个conversation中有4个角色role，请问是否有可参考的tool微调数据集可以帮助理解

3.请问现在还可以的代码中还可以正常进行工具微调吗？

**Comment by tiamojames** [comment]
请问有人回复吗，好像没人回答这个问题啊/(ㄒoㄒ)/~~

**Comment by zRzRzRzRzRzRzR** [comment]
1. 正确
2. 如果没有工具微调，就是只有输入输出，不然就需要工具的观察和反思
3. 不能进行工具微调

**Comment by tiamojames** [comment]
你好，请问是否有工具微调的示例数据集，以及工具微调的代码





------------------ 原始邮件 ------------------
发件人: zR ***@***.***&gt;
发送时间: 2024年4月15日 17:34
收件人: THUDM/ChatGLM3 ***@***.***&gt;
抄送: tiamojames ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [THUDM/ChatGLM3] 关于工具调用数据集的构建，有所疑问 (Issue #1128)





  
正确
 
如果没有工具微调，就是只有输入输出，不然就需要工具的观察和反思
 
不能进行工具微调

**Comment by zRzRzRzRzRzRzR** [comment]
这个确实没有，可以去魔搭社区找工具微调数据集，他们有整理好的，开源数据集，工具微调代码没有
