### ISSUE TITLE
调用工具是不是无法支持多跳的使用？

### ISSUE THREAD

**Issue by csn6666** [THUDM/ChatGLM3#113]
试了一下会直接出错了。但如果模型能够有多步推断或许是可以的（类似[ReAct](https://arxiv.org/abs/2210.03629)）。是否有办法实现？
![微信图片_20231101175405](https://github.com/THUDM/ChatGLM3/assets/3637463/11a0e823-7a08-42bf-a67a-da58fa4229b9)

**Comment by mawenju203** [comment]
我也想了解如何处理这个问题，如何设计训练的语料呢?

模型能否内部处理 
1. 北京的天气
2. 上海的天气
3. 北京的天气和上海的天气值的比较；



如果可以，训练语料要如何设计呢？

**Comment by 5663015** [comment]
`get_weather` 函数里要求输入是字符串，而不是列表，所以肯定会报错。如果想实现多步的推断，我理解可以写一个新的工具，或者直接在外层实现ReAct
