### ISSUE TITLE
模型路径为None

### ISSUE THREAD

**Issue by yangy996** [THUDM/ChatGLM3#1135]
### System Info / 系統信息

![image](https://github.com/THUDM/ChatGLM3/assets/15188456/4f5f250c-6b77-478d-ae93-c4f69cd1ea47)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

拉取huggingface，绝对路径导入就报这个错误

### Expected behavior / 期待表现

期待解决

**Comment by Miaotututu** [comment]
可能是你的chat-glm3-6b这个大模型没下全，你可以去比对一下仓库里的和运行服务器中的是否一致，这个估计有40+G

**Comment by Miaotututu** [comment]
> 可能是你的chat-glm3-6b这个大模型没下全，你可以去比对一下仓库里的和运行服务器中的是否一致，这个估计有40+G

我记得之前我就是这个原因 也是报的这个错

**Comment by yangy996** [comment]
> > 可能是你的chat-glm3-6b这个大模型没下全，你可以去比对一下仓库里的和运行服务器中的是否一致，这个估计有40+G
> 
> 我记得之前我就是这个原因 也是报的这个错

是这个问题，包太大了，没拉全
