### ISSUE TITLE
模型加载报错 safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by yanli789** [THUDM/ChatGLM3#1137]
### System Info / 系統信息

操作系统：Linux x86_64；Python 3.11.7；transformers 4.39.3；内存128G，没有CUDA，使用CPU
使用本地离线模型库/root/GLM3/chatglm3-6b/
模型配置如下：
MODEL_PATH = os.environ.get('MODEL_PATH', '/root/GLM3/chatglm3-6b/')
TOKENIZER_PATH = os.environ.get("TOKENIZER_PATH", MODEL_PATH)
tokenizer = AutoTokenizer.from_pretrained("/root/GLM3/chatglm3-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("/root/GLM3/chatglm3-6b", trust_remote_code=True).float()

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行basic_demo包下的python cli_demo.py会报错：
File "/root/GLM/basic_demo/cli_demo.py", line 8, in <module>
    model = AutoModel.from_pretrained("/root/GLM3/chatglm3-6b", trust_remote_code=True).float()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3531, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3938, in _load_pretrained_model
    state_dict = load_state_dict(shard_file, is_quantized=is_quantized)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 506, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### Expected behavior / 期待表现

期待大佬帮忙解答，万分感谢

**Comment by zRzRzRzRzRzRzR** [comment]
.float()是为啥
默认就是float 16了，这个好像是你模型太大了
（没用过CPU）
