### ISSUE TITLE
全量sft所需资源问题

### ISSUE THREAD

**Issue by Heathcliff-Zhao** [THUDM/ChatGLM3#1138]
感谢开源这个精彩的项目！

请问chatglm3-6b全量sft最少可以用多少资源训练？在我的数据集中prompt长度大致为1280~3000左右，answer为256以内。请问我是否可以使用1张80G A100或者8张24G 3090进行全量sft？

非常感谢您珍贵的时间！

**Comment by zRzRzRzRzRzRzR** [comment]
一张A100可以

**Comment by Heathcliff-Zhao** [comment]
感谢您的回复，我已解决我的问题。
