### ISSUE TITLE
存在回答不全的问题。问一个问题，结果只返回了部分答案，后面没动静了

### ISSUE THREAD

**Issue by Promise-W** [THUDM/ChatGLM3#1144]
### System Info / 系統信息

系统是mac os, m1 pro, 32g内存
![image](https://github.com/THUDM/ChatGLM3/assets/7625487/dd634160-5255-4457-b1bc-d9afe85f38f6)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

进入文件夹composite_demo， 然后运行 streamlit run main.py，浏览器页面打开以后，随便问一个问题，回答长的话，都会被截断，回答不全的问题

### Expected behavior / 期待表现

请尽快修复这个问题

**Comment by zRzRzRzRzRzRzR** [comment]
你换成chat模式试试
