### ISSUE TITLE
token模型 tokenizer.model 中有很多重复的token

### ISSUE THREAD

**Issue by seal-wang** [THUDM/ChatGLM3#1145]
### System Info / 系統信息

Ubuntu 22.04.1 LTS
transformers Version: 4.31.0
Python 3.10.12

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

从chatglm3的[modelscope](https://modelscope.cn/models/ZhipuAI/chatglm3-6b/files)上下载的token model文件，发现里面有很多重复的token，如‘首页’

<img width="299" alt="企业微信截图_17134089198949" src="https://github.com/THUDM/ChatGLM3/assets/167388817/41f1fa67-4160-4caa-981c-c9121fa1f3d5">

parse_tok.py

```
#!/usr/bin/env python3
from tokenization_chatglm import ChatGLMTokenizer

tok = ChatGLMTokenizer.from_pretrained('./', trust_remote_code=True, num_image_tokens=0)

print(tok.decode(33880))
print(tok.decode(45453))

if tok.decode(33880) == tok.decode(45453):
    print("True")
```
[tokenization_chatglm.py](https://modelscope.cn/api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=master&FilePath=tokenizer.model)
[tokenizer.model](https://modelscope.cn/api/v1/models/ZhipuAI/chatglm3-6b/repo?Revision=master&FilePath=tokenizer.model)

### Expected behavior / 期待表现

我认为 tokenizer.model中的token应该都是唯一的，不应该出现重复，但是实际发现有很多重复的，这是bug还是有意为之？

**Comment by seal-wang** [comment]
@zRzRzRzRzRzRzR 

> 1. 词语的编码结果与词语的位置相关

同一个中文词语，在句子的起始位置和非起始位置，encode后的token id是不同的，chatglm的token模型是有这样的设计吗？
下面是测试结果
```
 #!/usr/bin/env python3
  2 from tokenization_chatglm import ChatGLMTokenizer
  3
  4 tok = ChatGLMTokenizer.from_pretrained('./', trust_remote_code=True, num_image_tokens=0)
  5
  6 for tok_id in [33880, 45453]:
  7     print(f"tok_id:{tok_id}, tok:{tok.decode(33880)}")
  8 print()
  9
 10 for sentence in ["首页你好", "你好首页"]:
 11     print(sentence)
 12     for tok_id in tok(sentence).input_ids:
 13         print(f"tok_id:{tok_id}, tok:{tok.decode(tok_id)}")
 14     print()
```
output
```
tok_id:33880, tok:首页
tok_id:45453, tok:首页

首页你好
tok_id:64790, tok:[gMASK]
tok_id:64792, tok:sop
tok_id:45453, tok:首页
tok_id:39701, tok:你好

你好首页
tok_id:64790, tok:[gMASK]
tok_id:64792, tok:sop
tok_id:36474, tok:你
tok_id:54591, tok:好
tok_id:33880, tok:首页
```

> 2. 若词语的encode结果与位置相关，预训练时文本是如何切分成一个一个的sequence传入到模型的

如果词语encode结果与位置相关，那么将原始的文本切分成单个的sequence时，是否必须要严格按照完整的句子进行切分，即，一个sequence只能包含一个完整的句子，不能包含多个句子，同时也不允许将一个很长的句子切分为多个sequence。是这样吗？

**Comment by CNUIGB** [comment]
> @zRzRzRzRzRzRzR
> 
> > 1. 词语的编码结果与词语的位置相关
> 
> 同一个中文词语，在句子的起始位置和非起始位置，encode后的token id是不同的，chatglm的token模型是有这样的设计吗？ 下面是测试结果
> 
> ```
> #!/usr/bin/env python3
> from tokenization_chatglm import ChatGLMTokenizer
> 
> tok = ChatGLMTokenizer.from_pretrained('./', trust_remote_code=True, num_image_tokens=0)
> 
> for tok_id in [33880, 45453]:
>     print(f"tok_id:{tok_id}, tok:{tok.decode(33880)}")
> print()
> 
> for sentence in ["首页你好", "你好首页"]:
>     print(sentence)
>     for tok_id in tok(sentence).input_ids:
>         print(f"tok_id:{tok_id}, tok:{tok.decode(tok_id)}")
>     print()
> ```
> 
> output
> 
> ```
> tok_id:33880, tok:首页
> tok_id:45453, tok:首页
> 
> 首页你好
> tok_id:64790, tok:[gMASK]
> tok_id:64792, tok:sop
> tok_id:45453, tok:首页
> tok_id:39701, tok:你好
> 
> 你好首页
> tok_id:64790, tok:[gMASK]
> tok_id:64792, tok:sop
> tok_id:36474, tok:你
> tok_id:54591, tok:好
> tok_id:33880, tok:首页
> ```
> 
> > 2. 若词语的encode结果与位置相关，预训练时文本是如何切分成一个一个的sequence传入到模型的
> 
> 如果词语encode结果与位置相关，那么将原始的文本切分成单个的sequence时，是否必须要严格按照完整的句子进行切分，即，一个sequence只能包含一个完整的句子，不能包含多个句子，同时也不允许将一个很长的句子切分为多个sequence。是这样吗？

我最近也在重新在自己的语料上训练分词器，按我的理解来说，传入sentencepiece时应该是一行算是一个句子，如果不换行应该就是一个句子（猜测）

**Comment by zRzRzRzRzRzRzR** [comment]
这个部分没有公开技术部分，无法回答哦

**Comment by seal-wang** [comment]
> 这个部分没有公开技术部分，无法回答哦

在token model中，并没有重复的token，tokenizer.decode的结果去除了一些特殊符号（这些特殊符号通常表明英文token位于单词的首部或者中文token位于句子的首部），导致实际上两个不同的token id在decode后结果相同，所以我之前使用decode方法的结果来比较token之间的差异是错的，推荐用sentencepiece解析token model，这样可以得到完整准确的token。
