### ISSUE TITLE
4bit量化报错，已经是最新的quantization.py文件

### ISSUE THREAD

**Issue by aa644728538** [THUDM/ChatGLM3#1148]
### System Info / 系統信息

from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).quantize(4).cuda()
model = model.eval()
response, history = model.chat(tokenizer, "你好", history=[])
print(response)
response, history = model.chat(tokenizer, "晚上睡不着应该怎么办", history=history)
print(response)

quantization.py文件
class QuantizedLinear(torch.nn.Module):
    def __init__(self, weight_bit_width: int, weight, bias=None, device="cuda", dtype=None, empty_init=False):
        super().__init__()
        weight = weight.to(device)  # ensure the weight is on the cuda device
        assert str(weight.device).startswith('cuda'), 'The weights that need to be quantified should be on the CUDA device'
        self.weight_bit_width = weight_bit_width

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Traceback (most recent call last):
  File "/root/tsq_project/glm-inf.py", line 4, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).quantize(4).cuda()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm3-6b/103caa40027ebfd8450289ca2f278eac4ff26405/modeling_chatglm.py", line 1212, in quantize
    self.transformer.encoder = quantize(self.transformer.encoder, bits, empty_init=empty_init, device=device,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm3-6b/103caa40027ebfd8450289ca2f278eac4ff26405/quantization.py", line 154, in quantize
    layer.self_attention.query_key_value = QuantizedLinear(
                                           ^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm3-6b/103caa40027ebfd8450289ca2f278eac4ff26405/quantization.py", line 126, in __init__
    assert str(weight.device).startswith(
AssertionError: The weights that need to be quantified should be on the CUDA device

### Expected behavior / 期待表现

帮忙看看

**Comment by zRzRzRzRzRzRzR** [comment]
AssertionError: The weights that need to be quantified should be on the CUDA device
cpu是做不了的

**Comment by aa644728538** [comment]
我改成这样就可以了，--！
model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).quantize(bits=4, device="cuda").cuda()
