### ISSUE TITLE
用pt2进行微调以后，生成的checkpoint保存的是整个模型，我没有对finetune.py做修改啊？

### ISSUE THREAD

**Issue by Duperr** [THUDM/ChatGLM3#1149]
### Feature request  / 功能建议

我用lora做微调是正常的，checkpoint中保存的就是正常的参数。

### Motivation / 动机

pt2微调只能进行到checkpoint500就显示内存不足了，checkpoint500文件夹大小有16G

### Your contribution / 您的贡献

这是bug吗？还是什么问题，主要我对代码没有什么修改啊？为什么pt2和lora保存的不一样呢？

**Comment by zRzRzRzRzRzRzR** [comment]
pt2保存的是整个模型，用的是全参的调整方法
也就是说，你每次保存都是一个完整的glm3模型
