### ISSUE TITLE
请问如如何打印GLM3的参数结构？？

### ISSUE THREAD

**Issue by MathamPollard** [THUDM/ChatGLM3#1150]
### Feature request  / 功能建议

请问如如何打印GLM3的参数结构？？

### Motivation / 动机

想详细了解每一层是怎么样的

### Your contribution / 您的贡献

请问如如何打印GLM3的参数结构？？

**Comment by zRzRzRzRzRzRzR** [comment]
你用torch载入之后 print（model）就行了
