### ISSUE TITLE
https://open.bigmodel.cn/dev/api#nosdk中openai服务

### ISSUE THREAD

**Issue by dongfangduoshou123** [THUDM/ChatGLM3#1155]
### System Info / 系統信息

希望https://open.bigmodel.cn/dev/api#nosdk 云服务里提供openai格式的api接口调用，更方便的跟autogen等开源agent框架配合使用，同时可以吸引更多开发者

### Who can help? / 谁可以帮助到您？

希望https://open.bigmodel.cn/dev/api#nosdk 云服务里提供openai格式的api接口调用，更方便的跟autogen等开源agent框架配合使用，同时可以吸引更多开发者

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

希望https://open.bigmodel.cn/dev/api#nosdk 云服务里提供openai格式的api接口调用，更方便的跟autogen等开源agent框架配合使用，同时可以吸引更多开发者

### Expected behavior / 期待表现

希望https://open.bigmodel.cn/dev/api#nosdk 云服务里提供openai格式的api接口调用，更方便的跟autogen等开源agent框架配合使用，同时可以吸引更多开发者

**Comment by dongfangduoshou123** [comment]
因为这些框架一版只支持openai格式的调用，kimi现在支持openai的格式，可惜没有function call同能。

**Comment by zRzRzRzRzRzRzR** [comment]
你说的是glm-4 吗 glm4目前确实有这个问题，我们正在改进

**Comment by dongfangduoshou123** [comment]
@zRzRzRzRzRzRzR 对呀，大佬，glm4的云服务，只能通过zhipuAI的sdk访问，应该有很多人都想通过openai的sdk访问glm4呢。

**Comment by zRzRzRzRzRzRzR** [comment]
嗯，因为鉴权不一样，不兼容，我会帮忙反应这个问题
