### ISSUE TITLE
Chatglm3-6b使用官方的ptuning_v2.yaml进行微调，4090显卡报错显存不足

### ISSUE THREAD

**Issue by Ayanami233e** [THUDM/ChatGLM3#1166]
### System Info / 系統信息

![image](https://github.com/THUDM/ChatGLM3/assets/126251897/f3825090-82e6-4842-be1a-ac2037117608)
![image](https://github.com/THUDM/ChatGLM3/assets/126251897/86db02b2-1feb-42ac-8a51-a5bc05e2941e)
![image](https://github.com/THUDM/ChatGLM3/assets/126251897/2c9f06a2-f78f-4b7e-a477-ea813ef2e065)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python finetune_hf.py  data/  ../THUDM/chatglm3-6b  configs/ptuning_v2.yaml

### Expected behavior / 期待表现

我需要一份ptuning的微调教程，感谢

**Comment by zRzRzRzRzRzRzR** [comment]
#253
