### ISSUE TITLE
请教一下，如何正确的在system pormpt中正确的设置tools的描述，我在举例一个准确的地点时，不想调用查询天气的信息。

### ISSUE THREAD

**Issue by 512625100** [THUDM/ChatGLM3#1169]
### System Info / 系統信息

python 3.10.19
windows系统
A6000显卡

### Who can help? / 谁可以帮助到您？

coordinate_tool = {
        "type": "function",
        "function": {
            "name": "get_point_coordinate",
            "description": "首先明确系统的功能是提供位置信息查询，查找指定地点的位置信息,比如北京大学的具体坐标。选择与位置查询相关的关键词，如“在哪”、“哪里”、“地点”等",
            "parameters": {
                "type": "object",
                "properties": {
                    "place": {
                        "description": "需要查找的地点范围，如国家、省份、城市、街区等，或者只有一个地点。",
                        "type": "string"
                    }
                },
                "required": ["place"]
            }
        }
    }

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

当我提问的时候，只输入通州区，出现天气信息

### Expected behavior / 期待表现

输出地点信息

**Comment by 512625100** [comment]
其实我想问的是，只需要在description中修改描述，就可以吗？其他地方不用改，因为我改了很多次这个描述，但是都没有效果，不确定我修改的位置对不对

**Comment by zRzRzRzRzRzRzR** [comment]
是，但是这一代模型这个能力确实没有那么理想，工具调用在GLM4有更多优化

**Comment by 512625100** [comment]
> 是，但是这一代模型这个能力确实没有那么理想，工具调用在GLM4有更多优化

好的，明白了，谢谢
