### ISSUE TITLE
找到如何量化的方法了

### ISSUE THREAD

**Issue by shirubei** [THUDM/ChatGLM3#117]
本人小白一个。chatglm2我试用过量化版。
刚发现已经到chatglm3了，下了新的想试试看，结果跑web_demo.py的时候提示内存不够(1080Ti，11GB内存)。
按照2的时候的思路，需要一个4Bit版本，但是目前没找到。
只能死马当做活马医，把 quantize(4) 加上，没想到真的可用，哈哈哈。
具体就是，
model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).cuda()
改成
model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).quantize(4).cuda()
完了就应该能看到Gradio的界面，随便问个问题，能正常答复就OK

**Comment by shirubei** [comment]
#97

**Comment by shirubei** [comment]
#90

**Comment by shirubei** [comment]
#19

**Comment by shirubei** [comment]
#30

**Comment by shirubei** [comment]
#107

**Comment by 13832125696** [comment]
> 本人小白一个。chatglm2我试用过量化版。 刚发现已经到chatglm3了，下了新的想试试看，结果跑web_demo.py的时候提示内存不够(1080Ti，11GB内存)。 按照2的时候的思路，需要一个4Bit版本，但是目前没找到。 只能死马当做活马医，把 quantize(4) 加上，没想到真的可用，哈哈哈。 具体就是， model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).cuda() 改成 model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).quantize(4).cuda() 完了就应该能看到Gradio的界面，随便问个问题，能正常答复就OK

quantize(8)和不量化，哪个推理速度更快？

**Comment by zRzRzRzRzRzRzR** [comment]
通常来说，不量化的版本更快，但是不量化版本对硬件要求更高
如果硬件性能不足，只能做量化

**Comment by tanguofu** [comment]
> > 本人小白一个。chatglm2我试用过量化版。 刚发现已经到chatglm3了，下了新的想试试看，结果跑web_demo.py的时候提示内存不够(1080Ti，11GB内存)。 按照2的时候的思路，需要一个4Bit版本，但是目前没找到。 只能死马当做活马医，把 quantize(4) 加上，没想到真的可用，哈哈哈。 具体就是， model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).cuda() 改成 model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).quantize(4).cuda() 完了就应该能看到Gradio的界面，随便问个问题，能正常答复就OK
> 
> quantize(8)和不量化，哪个推理速度更快？

可以考虑 使用 transformer 这种方式 https://huggingface.co/docs/transformers/quantization?bnb=4-bit#autogptq 通过
```
# 使用transformer量化
... 
model.save_pretrained(save_dir)
tokenizer.save_pretrained(save_dir)
```
