### ISSUE TITLE
lora微调后怎么用网页版demo加载微调后的模型

### ISSUE THREAD

**Issue by dasaffa** [THUDM/ChatGLM3#1172]
下图是官方给的方法，但是看不到怎么把mode_dir更换成lora权重的目录
![image](https://github.com/THUDM/ChatGLM3/assets/75426990/eaa68c2d-efe0-4ff6-a447-cb6d723f5958)

**Comment by zRzRzRzRzRzRzR** [comment]
这个代码上面的model dir换成你微调check point 绝对路径
