### ISSUE TITLE
128k的模型使用lora微调后，进行推理的时候卡住怎么回事？

### ISSUE THREAD

**Issue by dazzlingCn** [THUDM/ChatGLM3#1181]
### System Info / 系統信息

cuda 11.7，t4卡，pytorch版本“1.11.0+cu113”

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用官方的微调脚本进行lora微调的：

1、微调：python finetune_hf.py data/xdd/ THUDM/chatglm3-6b-128k configs/lora.yaml 
没有报错，成功了

2、合并模型：python merge_model.py output/checkpoint-10000 THUDM/chatglm3-6b-128k-n2

3、推理过程：推理的时候，先是报了一个错误“AttributeError: can't set attribute 'eos_token'”，删除tokenizer_config.json中的eos_token、pad_token、unk_token就可以了，后面就是正常加载和推理，对于比较短的prompt（20个中文汉字以下），一般
可以正常推理，但是超过字数以后，会出现疑似卡死，推理半小时没有结果，但是显存占用基本拉满（24G），显存占用有时候还会变化。

### Expected behavior / 期待表现

希望正常在十几秒内返回推理结果

**Comment by zRzRzRzRzRzRzR** [comment]
你微调的长度多长呢，这个情况好像没遇到，初步怀疑是溢出

**Comment by dazzlingCn** [comment]
> 你微调的长度多长呢，这个情况好像没遇到，初步怀疑是溢出

请问什么溢出  显存溢出了吗 我应该怎么改呢

**Comment by zRzRzRzRzRzRzR** [comment]
是的显存溢出，你是什么显卡，你尝试一次推理短一点看是否正常，大概到大概2k字开始卡吗
