### ISSUE TITLE
ChatGLM3分词器的model.vocab能不能提供一下

### ISSUE THREAD

**Issue by CNUIGB** [THUDM/ChatGLM3#1184]
### Feature request  / 功能建议

ChatGLM3分词器的model.vocab能不能提供一下

### Motivation / 动机

我最近在用自己的语料库训练分词器，想看看GLM用的通用语料的分词结果和我专业语料库的分词结果差多少

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
无法提供
