### ISSUE TITLE
chatglm-6b库中ptuning/evaluate.sh&main.py可否直接用于chatglm3的LoRA微调的评估

### ISSUE THREAD

**Issue by CharonsPluto** [THUDM/ChatGLM3#1188]
非常感谢，如果这个issue不合适请告诉我，我会关闭这个issue

个人想要能够数据化评估微调前后模型性能，因此想到了能否用chatglm-6b的评估脚本来评估LoRA微调的chatglm3

**Comment by zRzRzRzRzRzRzR** [comment]
老代码那个我不知道。可以尝试，毕竟评估的话应该根据你的bench来啊

**Comment by CharonsPluto** [comment]
感谢
