### ISSUE TITLE
chatglm4啥时候开源？

### ISSUE THREAD

**Issue by njhouse365** [THUDM/ChatGLM3#1193]
### System Info / 系統信息

1

### Who can help? / 谁可以帮助到您？

1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1

### Expected behavior / 期待表现

1

**Comment by zRzRzRzRzRzRzR** [comment]
没有相关计划
