### ISSUE TITLE
是否和我想象的工具调用一样？

### ISSUE THREAD

**Issue by animalong** [THUDM/ChatGLM3#12]
首先，3比2在cpu运行的体验上提升了一大截，明显感觉快了很多，比1和2的体验明显，超赞。

工具调用是 向AI 提供一套 api调用接口 或 应用程序的启动参数说明，然后让AI根据我的需要去调用api和程序。
是这样的吗？

但我不会......，然后我问了chatglm3-6b，它好像也不知道，还是我提问的没有问道关键词？

![微信图片_20231027171422](https://github.com/THUDM/ChatGLM3/assets/38682998/01bd44dd-83b9-4cbc-9fa1-816d24b38d09)

**Comment by 948024326** [comment]
请问可以弄成服务器server嘛，就不是web服务

**Comment by duzx16** [comment]
通过代码的形式实现请参考 https://github.com/THUDM/ChatGLM3/blob/main/tool_using/README.md
支持工具调用和代码执行的 demo 正在开发中

**Comment by animalong** [comment]
其实我更想要的是像我在图片中提问那样，由模型自己告诉我怎么使用它，希望以后可以吧使用它的内容也加入到训练中
