### ISSUE TITLE
GLM大模型是Causal Language Model类型的模型么？

### ISSUE THREAD

**Issue by RyanOvO** [THUDM/ChatGLM3#1205]
### Feature request  / 功能建议

ChatGLM3/4 是Causal Language Model类型的模型么？

### Motivation / 动机

ChatGLM3/4 是Causal Language Model类型的模型么？

### Your contribution / 您的贡献

ChatGLM3/4 是Causal Language Model类型的模型么？

**Comment by zRzRzRzRzRzRzR** [comment]
开源的这个是
