### ISSUE TITLE
GLM2运行的好好的，这是什么情况？

### ISSUE THREAD

**Issue by lingyezhixing** [THUDM/ChatGLM3#121]
Traceback (most recent call last):
  File "D:\ChatGLM3-6B\glmenv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "D:\ChatGLM3-6B\web_demo2.py", line 72, in <module>
    for response, history, past_key_values in model.stream_chat(
  File "D:\ChatGLM3-6B\glmenv\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\31940/.cache\huggingface\modules\transformers_modules\ChatGLM3-6B-base\modeling_chatglm.py", line 1078, in stream_chat
    response, new_history = self.process_response(response, history)
  File "C:\Users\31940/.cache\huggingface\modules\transformers_modules\ChatGLM3-6B-base\modeling_chatglm.py", line 1004, in process_response
    metadata, content = response.split("\n", maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by sakela-wen** [comment]
在调试中发现modeling_chatGlm文件下的process_response方法中发现大模型在回复中会有标签加上《奇怪字符》的形式出现，导致代码片段
'''metadata, content = response.split("\n", maxsplit=1)'''
切分的时候报错，目前最简单直接的方法就是直接注释掉for循环即可
![屏幕截图 2023-11-02 013106](https://github.com/THUDM/ChatGLM3/assets/73175423/371ac639-1c1a-41ba-8f7e-b13fbb7e3edb)

**Comment by EdwardKSG** [comment]
嗯，遇到同样的问题

**Comment by qdchenxiaoyan** [comment]
应该是模型下载的时候中断了，我把中断的重新下载一遍就可以了

**Comment by Btlmd** [comment]
这可能是由于目前 tokenizer 中的 `process_response` 不支持处理尚未完全生成的工具调用。对于流式工具调用的实现，可以参考 [composite_demo](https://github.com/THUDM/ChatGLM3/tree/main/composite_demo) 。

> Traceback (most recent call last): File "D:\ChatGLM3-6B\glmenv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script exec(code, module.**dict**) File "D:\ChatGLM3-6B\web_demo2.py", line 72, in for response, history, past_key_values in model.stream_chat( File "D:\ChatGLM3-6B\glmenv\lib\site-packages\torch\utils_contextlib.py", line 35, in generator_context response = gen.send(None) File "C:\Users\31940/.cache\huggingface\modules\transformers_modules\ChatGLM3-6B-base\modeling_chatglm.py", line 1078, in stream_chat response, new_history = self.process_response(response, history) File "C:\Users\31940/.cache\huggingface\modules\transformers_modules\ChatGLM3-6B-base\modeling_chatglm.py", line 1004, in process_response metadata, content = response.split("\n", maxsplit=1) ValueError: not enough values to unpack (expected 2, got 1)

**Comment by wang-na** [comment]
请问大家，这个问题怎么解决的呢？
