### ISSUE TITLE
关于微调多轮对话生成的loss_mask格式问题

### ISSUE THREAD

**Issue by RyanOvO** [THUDM/ChatGLM3#1213]
ChatGLM3的多轮对话微调格式：
[gMASK]sop <|system|>xxx<|user|>xxx<|assistant|>xxx<|user|>xxx<|assistant|>xxx<|user|>xxx<|assistant|>xxx<eos>
所对应的loss_mask，只有<|assistant|>后的内容为true，其余的为false，即
![image](https://github.com/THUDM/ChatGLM3/assets/31231960/ad848ab1-4420-4dab-a4c2-6a30a968f639)

请问是这样的结构么？标黄的部分参与loss计算，一条这样的数据为一个conversations；最后以eos结尾。

**Comment by lilongxian** [comment]
简单介绍一下，
1.glm3这里使用GSG的自然语言模型MASK学习机制，对回复句的整个句子进行遮掩学习，因此对所有回复句计算训练损失，有利于更好对用户所有问句的连贯性逻辑理解更充分，是多轮对话中最好的mask学习机制。比只mask当前回复句更有效。
3.<eos>作停止符用
