### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'peft_type'

### ISSUE THREAD

**Issue by liuqi8827** [THUDM/ChatGLM3#1224]
### System Info / 系統信息

ubuntu

### Who can help? / 谁可以帮助到您？

@Btlmd

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=8  finetune_hf.py  data/AdvertiseGen/  /workspace/xxx/models/chatglm3-6b  configs/sft.yaml configs/ds_zero_3.json
2. 
<img width="1446" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/45791783/1b777b0e-82ac-4439-a23f-25857c537e0e">
3. 
<img width="1446" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/45791783/099cb4c6-c3f8-4815-9d31-91938bc7f2c9">

### Expected behavior / 期待表现

正常训练

**Comment by zRzRzRzRzRzRzR** [comment]
这不是模型没读入成功吗
<img width="762" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/93239683/823f961a-defe-4c32-a542-f37c9580dd96">

**Comment by liuqi8827** [comment]
感谢回复
1. 我要做SFT，所以把代码改成如下图所示，代码可能正常运行
<img width="1157" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/45791783/19beac72-440e-4f82-b29c-5b70bb735fb1">
2. **但是一直会报OutOfMemoryError: CUDA out of memory.的错误**
<img width="755" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/45791783/9e9f8f0a-e600-4ebe-8e19-223e7fb1e5e2">
<img width="503" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/45791783/f0bd57c1-bb62-4099-8269-29d2258634df">
<img width="1412" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/45791783/ee5f15aa-f2fb-495f-aca7-a7e21099880a">
<img width="1114" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/45791783/e356ac90-516e-4629-b9ce-3284cdf622c8">
<img width="1559" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/45791783/003392ad-2e3d-47a5-bd3f-5168b8731bca">
3. 计算资源如下图，运行时已经设置为--nproc_per_node=8：
<img width="809" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/45791783/aece5769-ba3f-4abe-965b-f38378d1f3bf">
4. 使用的是官方代码和官方给的数据集
5. SFT.yaml配置如下：
`data_config:
  train_file: train.json
  val_file: dev.json
  test_file: dev.json
  num_proc: 16
max_input_length: 256
max_output_length: 512
training_args:
  output_dir: ../output/chatgm3_6b_sft_20240521 # ./output
  max_steps: 3000
  learning_rate: 5e-5
  per_device_train_batch_size: 1 # 4
  dataloader_num_workers: 16
  remove_unused_columns: false
  save_strategy: steps
  save_steps: 500
  log_level: info
  logging_strategy: steps
  logging_steps: 10
  per_device_eval_batch_size: 2 # 16
  evaluation_strategy: steps
  eval_steps: 500
  predict_with_generate: true
  generation_config:
    max_new_tokens: 512
    deepspeed: /workspace/xxx/codes/ChatGLM3/finetune_demo/configs/ds_zero_2.json`
6. ds_zero_2.json配置如下：
`{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "bf16": {
        "enabled": "auto"
    },
    "zero_optimization": {
        "stage": 2,
        "allgather_partitions": true,
        "allgather_bucket_size": 5e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 5e8,
        "contiguous_gradients": true
    },

    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}`

7. ds_zero_3.json配置如下：
`{
  "train_micro_batch_size_per_gpu": "auto",
  "zero_allow_untested_optimizer": true,
  "bf16": {
    "enabled": "auto"
  },
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": "auto",
      "betas": "auto",
      "eps": "auto",
      "weight_decay": "auto"
    }
  },
  "zero_optimization": {
    "stage": 3,
    "allgather_partitions": true,
    "allgather_bucket_size": 5e8,
    "reduce_scatter": true,
    "contiguous_gradients": true,
    "overlap_comm": true,
    "sub_group_size": 1e9,
    "reduce_bucket_size": "auto",
    "stage3_prefetch_bucket_size": "auto",
    "stage3_param_persistence_threshold": "auto",
    "stage3_max_live_parameters": 1e9,
    "stage3_max_reuse_distance": 1e9,
    "stage3_gather_16bit_weights_on_model_save": true
  }
}`

8. 无论使用ds_zero_2.json还是ds_zero_3.json，dou都会报OutOfMemoryError: CUDA out of memory.的错误

**Comment by zRzRzRzRzRzRzR** [comment]
已经解决
