### ISSUE TITLE
api调用出错

### ISSUE THREAD

**Issue by llyllu** [THUDM/ChatGLM3#1225]
### System Info / 系統信息

阿里云上的DSW平台，在使用python api_severy.py 时出现
root@dsw-371315-5db5dd59d5-6n7zd:/mnt/workspace/ChatGLM3/openai_api_demo# python api_server.py
Traceback (most recent call last):
  File "/mnt/workspace/ChatGLM3/openai_api_demo/api_server.py", line 47, in <module>
    from tools.schema import tool_class, tool_def, tool_param_start_with
ModuleNotFoundError: No module named 'tools.schema'

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

root@dsw-371315-5db5dd59d5-6n7zd:/mnt/workspace/ChatGLM3/openai_api_demo# python api_server.py
Traceback (most recent call last):
  File "/mnt/workspace/ChatGLM3/openai_api_demo/api_server.py", line 47, in <module>
    from tools.schema import tool_class, tool_def, tool_param_start_with
ModuleNotFoundError: No module named 'tools.schema'

### Expected behavior / 期待表现

之前可以直接用，为啥该的不能用？？？

**Comment by zRzRzRzRzRzRzR** [comment]
恢复了之前的版本
