### ISSUE TITLE
ChatGLM3-6B 是标准的chat 版吗？

### ISSUE THREAD

**Issue by dongxinghua** [THUDM/ChatGLM3#123]

**Comment by zhaoxin** [comment]
这个模型本身就是for chat的。

**Comment by yeyupiaoling** [comment]
那ChatGLM3-6B和ChatGLM3-6B-Base的区别是什么，官方的解析如下，但是我看[榜单](https://opencompass.org.cn/leaderboard-llm)，ChatGLM3-6B得分要低很多。

>ChatGLM3-6B 的基础模型 ChatGLM3-6B-Base 采用了更多样的训练数据、更充分的训练步数和更合理的训练策略。在语义、数学、推理、代码、知识等不同角度的数据集上测评显示，ChatGLM3-6B-Base 具有在 10B 以下的基础模型中最强的性能。

**Comment by jiawei243** [comment]
base版本是没有针对chat 做微调的，比较适合做选择题。

**Comment by bonuschild** [comment]
> base版本是没有针对chat 做微调的，比较适合做选择题。

请教一下几个问题：
- 这个做选择题的直观含义或例子是？
- 6b-32k的版本是否不一定是最优部署？与6b、6b-base的应用差异体现在哪里？我实际应用中也没发现6b-32k能给我输出上万的文字呀~

**Comment by zRzRzRzRzRzRzR** [comment]
是标准的caht
32k的短文本效果不如6b 的标准模型
6b-base是基座模型
