### ISSUE TITLE
requirements.txt的问题

### ISSUE THREAD

**Issue by zhfish** [THUDM/ChatGLM3#1231]
### System Info / 系統信息

python3.12

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

pip install -r requirements.txt

### Expected behavior / 期待表现

torch>=2.3.0
vllm>=0.4.2

这两个有冲突
torch要求python12以上，vllm里的ray最高支持到11，我看issue说6月中旬才会支持12

**Comment by zRzRzRzRzRzRzR** [comment]
vllm 可以不装，装了实测不影响，本来想上一额vllm demo的，代码写的不够规范，暂时没有上
