### ISSUE TITLE
glm3-6b是在glm3-6b-base的关系和区别

### ISSUE THREAD

**Issue by zhaozhaoxia** [THUDM/ChatGLM3#124]
glm3-6b是在glm3-6b-base的基础上增加对话数据微调而来的吗？
为什么glm3-6b-base在开源数据集的评测效果比glm3-6b还要好很多？是否还有glm3-6b存在的意义了？
那么在一般场景中该如何选择模型了？

**Comment by yeyupiaoling** [comment]
那ChatGLM3-6B和ChatGLM3-6B-Base的区别是什么，官方的解析如下，但是我看[榜单](https://opencompass.org.cn/leaderboard-llm)，ChatGLM3-6B得分要低很多。

>ChatGLM3-6B 的基础模型 ChatGLM3-6B-Base 采用了更多样的训练数据、更充分的训练步数和更合理的训练策略。在语义、数学、推理、代码、知识等不同角度的数据集上测评显示，ChatGLM3-6B-Base 具有在 10B 以下的基础模型中最强的性能。
