### ISSUE TITLE
bug when running inference_hf.py after finetuning with lora.

### ISSUE THREAD

**Issue by RemiAlliah** [THUDM/ChatGLM3#1243]
### System Info / 系統信息

torch: 2.3.0+cu121
transformers: 4.40.0
python: 3.10
os: win10

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

 1.python .\inference_hf.py .\output\isign\checkpoint-3000\ --prompt "今天"周几"
![image](https://github.com/THUDM/ChatGLM3/assets/97057358/d21dc26a-ff30-4f24-85dc-d9ab1bcb7b61)
![image](https://github.com/THUDM/ChatGLM3/assets/97057358/e62cc5a7-dc11-4249-8f0d-b4da02219aa7)

### Expected behavior / 期待表现

希望可以顺利跑完推理

**Comment by daihuaiii** [comment]
#1300
参考
