### ISSUE TITLE
api模式下是不能实现工具调用吗？

### ISSUE THREAD

**Issue by 4ooooo** [THUDM/ChatGLM3#1249]
我在服务器上起server，然后在本地终端调用api，
response = client.chat.completions.create(
        model="chatglm3_6b",  # 填写需要调用的模型名称
        messages=messages,
        tools=tools,
        tool_choice="auto",
    )
这样是无法识别到工具的，请问有什么好的解决办法吗？需要通过api实现

**Comment by zRzRzRzRzRzRzR** [comment]
可以识别，但是不一定模型能正常调用和选择，可以使用最新一代的GLM-4模型，在fc上的效果有明显提升
