### ISSUE TITLE
执行了composition_demo，发现仅仅用了一个cpu去执行推理。速度非常慢。这个是什么原因导致的？

### ISSUE THREAD

**Issue by pengyuxiang1** [THUDM/ChatGLM3#1252]
### System Info / 系統信息

centos系统，CUDA Version: 11.7 

### Who can help? / 谁可以帮助到您？

@abmfy 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

安装官方指引去部署了chatGLM3。目前能执行起来了。
![image](https://github.com/THUDM/ChatGLM3/assets/38313899/c127a975-2e0e-4e9e-acfd-36646c20ce3c)

但是速度非常的慢，我用`top`看了一下，它仅仅用了我一个cpu，而我是10核的cpu的，所以速度变得特别慢，想问一下，这是为什么？
![企业微信截图_17174222484108](https://github.com/THUDM/ChatGLM3/assets/38313899/b93f1b15-8f4a-429b-b50a-736cd6d600e0)

看它执行程序的日志，看起来也是正常的：

![image](https://github.com/THUDM/ChatGLM3/assets/38313899/55fe56a5-3c70-4c3f-ba30-0d872f0df925)

### Expected behavior / 期待表现

虽然看起来我的cuda版本低，用不了gpu，但是cpu推理应该也不至于这么慢？

**Comment by zRzRzRzRzRzRzR** [comment]
cpu的话一秒大概1-2个字？
还是建议GPU吧
