### ISSUE TITLE
运行basic_demo下的web_demo_gradio.py程序报错ModuleNotFoundError: No module named 'peft'

### ISSUE THREAD

**Issue by miracles-zhang** [THUDM/ChatGLM3#1253]
### System Info / 系統信息

目前看应该不是硬件等问题

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 按照官方说明下载项目、模型文件，安装在云端服务器。
2. 相关包及依赖通过requirements.txt安装。
3. 运行basic_demo下的web_demo_gradio.py程序报错：
Traceback (most recent call last):

 File "/root/autodl-tmp/llm-project/ChatGLM3/basic_demo/web_demo_gradio.py", line 26, in <module>

  from peft import AutoPeftModelForCausalLM, PeftModelForCausalLM

ModuleNotFoundError: No module named 'peft'
4.为什么相关依赖包中没有指定perf，我单独使用pip命令安装perf，提示以下错误：下载源调整到清华、阿里、本身的源都不行
ERROR: Could not find a version that satisfies the requirement perf (from versions: none)
ERROR: No matching distribution found for perf

### Expected behavior / 期待表现

1.项目文件中应该解决这个程序不能运行的问题。

**Comment by zRzRzRzRzRzRzR** [comment]
只有微调后的模型需要使用peft，如果不使用peft微调不需要装这个库，直接用transofmrers载入模型

**Comment by miracles-zhang** [comment]
> 只有微调后的模型需要使用peft，如果不使用peft微调不需要装这个库，直接用transofmrers载入模型

如果后续要进行微调需要这个包，为什么pip下载不了了，有什么方法可以下载吗？

**Comment by zRzRzRzRzRzRzR** [comment]
可以啊 pip install peft
