### ISSUE TITLE
使用chatglm.cpp调用chatglm3-6b-32k时，非常容易触发无限循环的问题，repetition_penalty设置为2依然没有效果

### ISSUE THREAD

**Issue by zhoumz123** [THUDM/ChatGLM3#1257]
### System Info / 系統信息

Cuda 12.1，Python 3.8.10，transformers  4.36.2, 操作系统：ubuntu  

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1：启动服务：MODEL=/hy-tmp/chatglm.cpp/chatglm-ggml.bin uvicorn chatglm_cpp.openai_api:app --host 127.0.0.1 --port 8000
2：输入：李清照有哪些著名作品

### Expected behavior / 期待表现

无重复内容

**Comment by zRzRzRzRzRzRzR** [comment]
使用GLM-4开源模型解决该问题，或检查对话模板是否正确，stop id对了吗
