### ISSUE TITLE
如何增加工具，使得模型能够识别？

### ISSUE THREAD

**Issue by xxm1668** [THUDM/ChatGLM3#126]

**Comment by Btlmd** [comment]
可参考 [工具模式](https://github.com/THUDM/ChatGLM3/tree/main/composite_demo#%E5%B7%A5%E5%85%B7%E6%A8%A1%E5%BC%8F) 一节的说明

**Comment by xxm1668** [comment]
@register_tool
def get_estate_knowledge(
        query: Annotated[str, '查询知识库的query', True],
):
    if not isinstance(query, str):
        raise TypeError("City name must be a string")
    url = 'http://xxxxxxxx:32077/api/v1/llm/vector_search?city=nanjing3'
    headers = {
        'accept': 'application/json',
        'Content-Type': 'application/json'
    }

    # 创建一个包含请求体的字典，并将其转换为JSON格式
    data = query
    # json_data = json.dumps(data)

    response = requests.post(url, headers=headers, json=data)
    result = []
    if response.status_code == 200:
        result = response.json()['document']
        if len(result) != 0:
            result = response.json()['document']
    else:
        print(f"Request failed with status code {response.status_code}")
        print(response.text)
    if len(docs) == 0:
        return "未找到相关知识"
    return docs[0]
    
    
2023-11-02 14:57:37.924 Uncaught app exception
Traceback (most recent call last):
  File "/home/xxm/anaconda3/envs/chatglm3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/xxm/下载/ChatGLM3/composite_demo/main.py", line 11, in <module>
    import demo_chat, demo_ci, demo_tool
  File "/home/xxm/下载/ChatGLM3/composite_demo/demo_tool.py", line 10, in <module>
    from tool_registry import dispatch_tool, get_tools
  File "/home/xxm/下载/ChatGLM3/composite_demo/tool_registry.py", line 115, in <module>
    def get_estate_knowledge(
  File "/home/xxm/下载/ChatGLM3/composite_demo/tool_registry.py", line 15, in register_tool
    tool_description = inspect.getdoc(func).strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by xxm1668** [comment]
@Btlmd

**Comment by xxm1668** [comment]
少了文档的说明

**Comment by Btlmd** [comment]
定义工具时需要添加 docstring 作为工具说明。可以考虑改为
```python
@register_tool
def get_estate_knowledge(
    query: Annotated[str, '查询知识库的query', True],
):
    """
    查询知识库中的有关信息
    """
    ...
```

**Comment by hais1992** [comment]
简单写了个调用 微博api查询新闻的 工具，

```
@register_tool
def get_news(
    timeStr: Annotated[str, 'The time of the news to be queried', True],
) -> str:
    """
    Get the current time for `timeStr`
    """

    import requests
    url = f"https://weibo.com/ajax/side/hotSearch"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        news = [item['word'] for item in data['data']['realtime']]
        return timeStr+"的新闻有："+str(news)
    else:
        return str()

```

**Comment by xxm1668** [comment]
谢谢大家！

**Comment by yang1111-gif** [comment]
> 定义工具时需要添加 docstring 作为工具说明。可以考虑改为
> 
> ```python
> @register_tool
> def get_estate_knowledge(
>     query: Annotated[str, '查询知识库的query', True],
> ):
>     """
>     查询知识库中的有关信息
>     """
>     ...
> ```

您好，我加了文档的说明，但是为什么文档说明改成中文竟然报错，demo_chat has no attribute main.谢谢

**Comment by Btlmd** [comment]
这个错误应该刷新一次页面就能解决
