### ISSUE TITLE
ChatGLM3-6b微调之后再运行就会出错

### ISSUE THREAD

**Issue by AHPUymhd** [THUDM/ChatGLM3#1261]
### System Info / 系統信息

python：3.10

### Who can help? / 谁可以帮助到您？

@Btlmd

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我在微调自己的数据集之后再运行有很大几率会报如下错误：
![image](https://github.com/THUDM/ChatGLM3/assets/72792297/cc82f053-b3ce-4180-8065-f0c9cf02bd1c)
我看别人也有遇到这个问题的情况，说是替换hugface上面的代码，我也替换了configuration_chatglm.py，modeling_chatglm.py[quantization.py，tokenization_chatglm.py这四个代码，但是还是出现一样的问题，请问这个问题该如何解决呢，谢谢。

### Expected behavior / 期待表现

希望能解决这个bug

**Comment by zRzRzRzRzRzRzR** [comment]
这个位置大概是触发了工具调用的内容？
