### ISSUE TITLE
finetune_hf.py中的resume_from_checkpoint部分可能存在影响性能以及值得改进的地方

### ISSUE THREAD

**Issue by pandong2011** [THUDM/ChatGLM3#1272]
![WechatIMG80](https://github.com/THUDM/ChatGLM3/assets/100667564/b3517a7b-07bd-4656-89a6-33b398db43f3)
如图：
------红色部分的代码是为了寻找最新的checkpoint的step
------绿色1是从最新的checkpoint恢复训练
------绿色2是从指定的checkpoint恢复训练
一.如果从指定的checkpoint恢复训练执行绿色2的代码，实际上却先要去执行红色部分的代码来进行循环获取最新的checkpoint的step，如果这部分的checkpoint目录很多可能会大大延长训练的时间。而红色部分的代码实际是为绿色部分1服务的
二.黄色部分的代码是存在冗余，应该是可以抽取出来的

**Comment by zRzRzRzRzRzRzR** [comment]
啊，这个是我看到了这个需求，受理了，还没处理
欢迎给我们提交贡献😂。

**Comment by pandong2011** [comment]
@zRzRzRzRzRzRzR 那你分配给我吧
