### ISSUE TITLE
请问什么时候加入P-Tuning v2支持

### ISSUE THREAD

**Issue by x1nj3** [THUDM/ChatGLM3#129]
使用ChatGLM2-6B那个git项目中p-tuning文件夹中的代码进行微调，无法使用，报错。
请求制作ChatGLM3的p-tuning项目

**Comment by Harris-Xie** [comment]
+1

**Comment by ybdesire** [comment]
报错+1

**Comment by jinyuxiaoqiang** [comment]
+1

**Comment by Harris-Xie** [comment]
每日催更

**Comment by woodvillage** [comment]
日常催更

**Comment by lhtpluto** [comment]
+1

**Comment by Btlmd** [comment]
感谢关注，我们更新了 [ChatGLM3-6B 微调示例](https://github.com/THUDM/ChatGLM3/blob/main/finetune_demo/README.md)
