### ISSUE TITLE
API 服务一段时间不使用，就自动shutting down

### ISSUE THREAD

**Issue by MingyeXu** [THUDM/ChatGLM3#132]
相关的包：uvicorn = 0.23.2; torch=2.0.0; fastapi = 0.104.1
具体Log：
[root@youliang-qizai-nlg-7f9cd48b4b-zm57l ChatGLM3]# python openai_api.py
2023-11-02 12:48:07.046057: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████▀████████████████████████| 7/7 [00:08<00:00,  1.17s/it]
INFO:     Started server process [152948]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [152948]

**Comment by onlyyou1996** [comment]
Linux 下使用nohup执行 比如说nohup python openai_api.py &
