### ISSUE TITLE
langchain AttributeError: 'ChatGLM3' object has no attribute 'prompt'

### ISSUE THREAD

**Issue by bravelll** [THUDM/ChatGLM3#133]
运行 python main.py
AttributeError: 'ChatGLM3' object has no attribute 'prompt'

**Comment by hais1992** [comment]
+1

**Comment by OuHaoyun** [comment]
I got the same error. Would anyone be able to help? Thanks!

I am using an Apple Silicon M2 Chip. I have loaded the local ChatGLM3 successfully and changed 'cuda' to 'mps' when loading the model. Besides, I have set up the yaml file for Arxiv. 
![image](https://github.com/THUDM/ChatGLM3/assets/87372723/eb7ca8b6-b33d-4081-84c2-635e82c2bd3d)

**Comment by OuHaoyun** [comment]
> I got the same error. Would anyone be able to help? Thanks!
> 
> I am using an Apple Silicon M2 Chip. I have loaded the local ChatGLM3 successfully and changed 'cuda' to 'mps' when loading the model. Besides, I have set up the yaml file for Arxiv. ![image](https://user-images.githubusercontent.com/87372723/279915375-eb7ca8b6-b33d-4081-84c2-635e82c2bd3d.png)

I have solved this issue.
(1) make sure we have `cd langchain-demo` before running the main function of the demo.
(2) delete `self.` before the prompt. There is no need to add `self.` in print function.
```
    def _call(self, prompt: str, history: List = [], stop: Optional[List[str]] = ["<|user|>"]):
        print("======")
        print(prompt)
        print("======")
```
