### ISSUE TITLE
能否提供一下ChatGLM2一样的api.py

### ISSUE THREAD

**Issue by sxd1140** [THUDM/ChatGLM3#135]
直接复制[api.py](https://github.com/THUDM/ChatGLM2-6B/blob/main/api.py)改模型名能启动,但是一post就500.

谢谢

**Comment by YinSonglin1997** [comment]
> 直接复制[api.py](https://github.com/THUDM/ChatGLM2-6B/blob/main/api.py)改模型名能启动,但是一post就500.
> 
> 谢谢

我也遇到了同样的问题，请问你解决了吗？

**Comment by sxd1140** [comment]
直接复制后可以用,之前出现500是因为我的客户端问题.
