### ISSUE TITLE
工具模块的代码不太了解

### ISSUE THREAD

**Issue by succulen-plants** [THUDM/ChatGLM3#138]
chatglm工具部分代码：
天气查询： 今天郑州天气如何？
代码先调用 stream_generate将问题输入模型， 生成一个字符串:
 ```python
tool_call(location='郑州', unit='celsius')
```
然后将这两个参数传到工具查询的天气； 

为什么每次都能生成这样的字符串呢？ ```python
tool_call(location='郑州', unit='celsius')
```

**Comment by Btlmd** [comment]
在调用工具的模式下，模型被插入了一段告知模型可以使用工具来回答问题、以及说明有哪些可用工具的 system prompt，因此模型就会在认为用户的请求需要调用工具时，根据被训练的格式和可使用的工具，发出特定格式的工具调用。

**Comment by iwaitu** [comment]
这个信息确实没必要，不过要消除这个信息估计要重新训练模型，这个信息在执行function_call 之前就已经被打印出来了
