### ISSUE TITLE
chaglm3-6b GPU资源占用清理问题

### ISSUE THREAD

**Issue by zhaozhaoxia** [THUDM/ChatGLM3#139]
请教下，采用该模型部署服务，其GPU会一直占用资源直到打满，然后整个服务需要重启．请问有什么办法可以自动清理大模型所占用的资源吗？

**Comment by zRzRzRzRzRzRzR** [comment]
定期清理History，你需要定期的清空历史记录，这是目前最快的解决方案

**Comment by PeterXiaTian** [comment]
> 定期清理History，你需要定期的清空历史记录，这是目前最快的解决方案

是说把产生的log清理掉吗？登录服务器后，比如rm -rf xx.log
