### ISSUE TITLE
量化模型回答的时候会出现不断重复某个句子的情况

### ISSUE THREAD

**Issue by fryng** [THUDM/ChatGLM3#141]
量化模型回答的时候会出现不断重复某个句子的情况，一直不断重复，自己也不停止

**Comment by hais1992** [comment]
+1，我也是，然后尝试了ChatGPT3.5、4.0 ，Qwen-14B、百川，ChatGLM3-6b和32k的，等等市面上好像所有模型都会或多或少的重复~ 但是ChatGpt重复的概率好像少一些~

**Comment by zRzRzRzRzRzRzR** [comment]
请确认提示词模板是否是官方的，还是修改后接入的第三方框架

**Comment by zRzRzRzRzRzRzR** [comment]
目前在官方demo上没有复现出上述结果，如果还有出现，请按照issue模板提供最小复现，该issue关闭
