### ISSUE TITLE
设置多个GPU使用 cannot import name 'load_model_on_gpus' from 'utils 

### ISSUE THREAD

**Issue by LZZJ** [THUDM/ChatGLM3#142]
我按照以下的文档进行多卡部署了。[多卡部署](https://github.com/THUDM/ChatGLM3#%E5%A4%9A%E5%8D%A1%E9%83%A8%E7%BD%B2)
如果你有多张 GPU，但是每张 GPU 的显存大小都不足以容纳完整的模型，那么可以将模型切分在多张GPU上。首先安装 accelerate: pip install accelerate，然后通过如下方法加载模型：

from utils import load_model_on_gpus
model = load_model_on_gpus("THUDM/chatglm3-6b", num_gpus=2)

结果ImportError: cannot import name 'load_model_on_gpus' from 'utils' (/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/utils/__init__.py)
出现这个错误。该怎么解决？

**Comment by Btlmd** [comment]
这可能是本地安装的 utils 包出现了名称冲突，可以考虑修改 `utils.py` 的名称并从新名称 import ？

**Comment by 2264244232** [comment]
我这里也找不到
ImportError: cannot import name 'load_model_on_gpus' from 'utils'

**Comment by LZZJ** [comment]
> 我这里也找不到 ImportError: cannot import name 'load_model_on_gpus' from 'utils'

你试试上面那个大佬讲的修改一下utils的名称 然后从新名词导入。
