### ISSUE TITLE
gradio不生产共享链接

### ISSUE THREAD

**Issue by Rocky77JHxu** [THUDM/ChatGLM3#143]
在设置`demo.queue().launch(share=True, inbrowser=True)`后，gradio依旧只生成Local URL，不生成共享链接，运行也不报错，这导致我觉得应该不是gradio版本的问题，这应该怎么调？
![gradio URL](https://github.com/THUDM/ChatGLM3/assets/143877381/10a21383-533e-4a33-adc1-38bacfcba397)

**Comment by pofice** [comment]
gradio生成共享链接对NAT有要求，请检查网络NAT类型

**Comment by zRzRzRzRzRzRzR** [comment]
由于无法复现你提高的问题，如果还出现类似情况，请配上环境说明再次提出issue

**Comment by tianya332** [comment]
> 在设置`demo.queue().launch(share=True, inbrowser=True)`后，gradio仍然只生成本地URL，不生成共享链接，运行也不应该报错，这导致我觉得不是gradio版本的问题，这应该怎么调？ ![渐变 URL](https://private-user-images.githubusercontent.com/143877381/280013413-10a21383-533e-4a33-adc1-38bacfcba397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjUxNDEsIm5iZiI6MTcwMjM2NDg0MSwicGF0aCI6Ii8xNDM4NzczODEvMjgwMDEzNDEzLTEwYTIxMzgzLTUzM2UtNGEzMy1hZGMxLTM4YmFjZmNiYTM5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwNzA3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmY1ZmU0NzliY2U1ZTEzM2MzMzg2Yjk5Y2QxYWNlMjZmM2Y5NDk5N2ZmMDIxNGM1NzY5MjA0MTFiMTcyMWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VE1C_tvZg8e8_7WYU4wE6ZusU7BItcLX-C4Uq2lCP7M)

您好，有没有解决这个问题，我也遇到了同样的问题
