### ISSUE TITLE
chatglm3 Function call是否计划与openai的api完全兼容?

### ISSUE THREAD

**Issue by tylike** [THUDM/ChatGLM3#144]
我在c#中通过  [Betalgo.OpenAI](https://github.com/betalgo/openai) 调用chatgpt、chatglm3的普通聊天，是成功的，除了api url外，不需要修改任何代码，这很好！

然后说下但是:D

我在使用chatgpt的function call的时候，是可以正确调用的，但当我调用chatglm3-6b的时候，并没有接收到tools参数。

**以下是发送方传入的内容：**
<img width="1495" alt="openAIAPIFunctionCall" src="https://github.com/THUDM/ChatGLM3/assets/920370/5460b7e9-d0fc-4e7e-be79-1bcada709a9f">

**为了调试，我把119行处改成了如下内容，即增加了打印出传入的内容。**
@app.post("/v1/chat/completions", response_model=ChatCompletionResponse)
async def create_chat_completion(request: ChatCompletionRequest):
    global model, tokenizer
    
    print(request)

**以下是chatglm openai_api接收到的内容：**

D:\ChatGLM3>python openai_api.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:12<00:00,  1.78s/it]
INFO:     Started server process [20124]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
model='gpt-3.5-turbo' messages=[ChatMessage(role='user', content='数据库里有多少张表?', metadata=None, tools=None)] temperature=0.7 top_p=1.0 max_tokens=None stop=None stream=False stop_token_ids=None repetition_penalty=1.1 return_function_call=False
D:\ChatGLM3\openai_api.py:180: PydanticDeprecatedSince20: The `parse_obj` method is deprecated; use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
  task_usage = UsageInfo.parse_obj(response["usage"])
D:\ChatGLM3\openai_api.py:181: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
  for usage_key, usage_value in task_usage.dict().items():
INFO:     127.0.0.1:59055 - "POST /v1/chat/completions HTTP/1.1" 200 OK

<img width="1478" alt="chatglmOpenAIAPIArgs" src="https://github.com/THUDM/ChatGLM3/assets/920370/e3c69745-666e-45a1-83e2-e2974a063f2b">

希望可以兼容，谢谢！

**Comment by zRzRzRzRzRzRzR** [comment]
@xusenlinzy 方便看一下能支持么，感谢

**Comment by zRzRzRzRzRzRzR** [comment]
目前，由于GLM3-6B的Agent格式与OpenAI格式并不相同，我们还需要做进一步适配，之后如果有适配计划我们会及时更新到Github上，感谢理解
