### ISSUE TITLE
文本纠错能力 相对智谱清言 有些差距请问如何弥补？

### ISSUE THREAD

**Issue by vergil-ong** [THUDM/ChatGLM3#149]
<img width="942" alt="lQLPJwSh1EAuzXjNAtrNB1ywUjAMmv8nkEkFNmO2Z8CcAA_1884_730" src="https://github.com/THUDM/ChatGLM3/assets/25544312/4944a4c4-a7b3-4db9-8962-83ebfc6c072d">
<img width="819" alt="lQLPJwMIjmCixbjNAijNBmawXa-iovFDjMEFNmPZ00CcAA_1638_552" src="https://github.com/THUDM/ChatGLM3/assets/25544312/e142c976-af09-4944-b7eb-1be00c45c2dd">
这两个事 智谱清言和chatglm3-6b模型的对比，发现为文本纠错能力之间有差距。
请问一下 智谱清言用的是 chatglm3-6b吗？ chatglm3-6b 文本纠错能力 只能通过微调结局吗？

**Comment by 102286545** [comment]
智谱清言肯定用的是130b的。6b没有这么强的推理能力。
