### ISSUE TITLE
LLaMA-Factory lora 微调后 导出微调后的完整模型提示问题

### ISSUE THREAD

**Issue by 13051652726** [THUDM/ChatGLM3#150]
利用LLaMA-Factory导出微调后的完整模型提示
Some weights of the model checkpoint at /work/shared/llm/LLaMA-Factory/outs/chatglm3_sft_ckt_result were not used when initializing ChatGLMForConditionalGeneration: ['lm_head.weight']
- This IS expected if you are initializing ChatGLMForConditionalGeneration from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ChatGLMForConditionalGeneration from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
请问是微调没有起效果吗

**Comment by hiyouga** [comment]
该问题可以忽视，最新版代码微调后不会出现该警告
