### ISSUE TITLE
AttributeError: can't set attribute 'eos_token'

### ISSUE THREAD

**Issue by LZHgrla** [THUDM/ChatGLM3#152]
复现：
```python
import transformers
from transformers import AutoTokenizer

print(transformers.__version__)
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True)
tokenizer.save_pretrained("./saved_tokenizer")
saved_tokenizer = AutoTokenizer.from_pretrained("./saved_tokenizer", trust_remote_code=True)
```

输出：
```
4.35.0
Traceback (most recent call last):
  File "/mnt/142/linzhihao/xtuner/test.py", line 9, in <module>
    saved_tokenizer = AutoTokenizer.from_pretrained("./saved_tokenizer", trust_remote_code=True)
  File "/mnt/142/linzhihao/anaconda3/envs/xtuner/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 755, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/mnt/142/linzhihao/anaconda3/envs/xtuner/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2024, in from_pretrained
    return cls._from_pretrained(
  File "/mnt/142/linzhihao/anaconda3/envs/xtuner/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/linzhihao/.cache/huggingface/modules/transformers_modules/THUDM/chatglm3-6b/d3fe58f8a2c50bab217780ba8bd3ff76833d2d0c/tokenization_chatglm.py", line 93, in __init__
    super().__init__(padding_side=padding_side, clean_up_tokenization_spaces=clean_up_tokenization_spaces, **kwargs)
  File "/mnt/142/linzhihao/anaconda3/envs/xtuner/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 363, in __init__
    super().__init__(**kwargs)
  File "/mnt/142/linzhihao/anaconda3/envs/xtuner/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1604, in __init__
    super().__init__(**kwargs)
  File "/mnt/142/linzhihao/anaconda3/envs/xtuner/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 861, in __init__
    setattr(self, key, value)
AttributeError: can't set attribute 'eos_token'
```

`tokenizer_config.json`:
```
{
  "added_tokens_decoder": {},
  "auto_map": {
    "AutoTokenizer": [
      "THUDM/chatglm3-6b--tokenization_chatglm.ChatGLMTokenizer",
      null
    ]
  },
  "clean_up_tokenization_spaces": false,
  "do_lower_case": false,
  "eos_token": "</s>",
  "model_max_length": 1000000000000000019884624838656,
  "pad_token": "<unk>",
  "padding_side": "left",
  "remove_space": false,
  "tokenizer_class": "ChatGLMTokenizer",
  "unk_token": "<unk>"
}
```

原因分析：
https://github.com/huggingface/transformers/blob/552ff24488d4027590deded3b2b0d1716df341c3/src/transformers/tokenization_utils_base.py#L2384
`transformers` 的 `tokenizer` 会在 `save_pretrained` 时把 `self.special_tokens_map` 保存到 `tokenizer_config.json` 中，这就使得 `eos_token` 等冗余信息保存到了 `tokenizer_config.json`，而 ChatGLM 的 tokenizer 初始化不支持 `eos_token` 的输入。

**Comment by mike-2020** [comment]
这个问题为啥被关闭了？使用transformers-4.34.1也可以复现这个问题。看起来只有transformers-4.34.0才可以避免这个问题。

**Comment by zRzRzRzRzRzRzR** [comment]
> 这个问题为啥被关闭了？使用transformers-4.34.1也可以复现这个问题。看起来只有transformers-4.34.0才可以避免这个问题。

当时是看在xtuner中解决了，另外，我们当时用的是4.33应该，没有出现这个问题

**Comment by LZHgrla** [comment]
@zRzRzRzRzRzRzR 
xtuner 临时将 transformers 版本固定至 <= 4.34.0

https://github.com/InternLM/xtuner/pull/200

感觉不是个长久之计....

**Comment by Modas-Li** [comment]
same issue

**Comment by shihanmax** [comment]
transformers==4.36.2 也可以复现这个问题😭

**Comment by jingzl** [comment]
这个问题怎么解决？我这边也碰到，lora微调后，合并导出的模型，无法被载入

**Comment by TankNee** [comment]
@jingzl you can refer to this issue comment by LLaMA Factory https://github.com/hiyouga/LLaMA-Factory/issues/1307#issuecomment-1786558186

**Comment by zRzRzRzRzRzRzR** [comment]
fix it now

**Comment by ControllableGeneration** [comment]
> fix it now， update your huggingface file

What does this even mean? Can you describe the root cause of this issue, please?

**Comment by zRzRzRzRzRzRzR** [comment]
更新一下huggingface代码，应该解决了这个问题，不这个问题应该是微调的模型才有的吧

**Comment by danerlt** [comment]
@zRzRzRzRzRzRzR 我是使用openllm启动chatglm3-6b的模型报错的

**Comment by zRzRzRzRzRzRzR** [comment]
没用过这个测试，我在hf上是正常的诶

**Comment by Jason7even** [comment]
> 是的，是要去hf更新配置文件，权重不用更新，base好像确实没变，我明天看一下

请您有空的时候看一下base的配置文件吧，非常感谢！！！！！

**Comment by zRzRzRzRzRzRzR** [comment]
但是只有chat模型需要模板啊...

**Comment by Jason7even** [comment]
奥！不需要了。。。我之前设置MODEL_PATH设错了，所以报错了。。。现在已经可以正常微调并inference了，感谢！

**Comment by AI3181ZCC** [comment]
> 奥！不需要了。我之前设置MODEL_PATH设错了，所以报错了。现在已经可以正常参数并推理了，谢谢！

你好，我这边tansformer4.38.2版本也出现eostoken的问题，删掉那些字段，又报错NotImplementedError错误

**Comment by qianlongqf** [comment]
> hiyouga/LLaMA-Factory#1307 (comment)

我也一样原生的GLM3 lora finetune

**Comment by MrHuangZy** [comment]
我也是出现了eostoken问题，很奇怪，我最开始使用lora训练方式训练，然后使用lora模型可以很好的进行推理，随后我进行了合并模型，将Lora和基础模型合并，合并后就出现eostoken问题。后来无法解决这个问题，我又重新开始训练一个lora模型，结果新的lora模型也出现了eostoken问题。不知道这个问题该怎么解决，希望有人给一点儿帮助，

**Comment by JMDang** [comment]
> 我也是出现了eostoken问题，很奇怪，我最开始使用lora训练方式训练，然后使用lora模型可以很好的进行推理，随后我进行了合并模型，将Lora和基础模型合并，合并后就出现eostoken问题。后来无法解决这个问题，我又重新开始训练一个lora模型，结果新的lora模型也出现了eostoken问题。不知道这个问题该怎么解决，希望有人给一点儿帮助，

你好，这个问题解决了吗，解决的话怎么解决的呢，感谢

**Comment by MrHuangZy** [comment]
我解决这个问题了，这个问题我看了很多文章，听说是transformers的版本会将一些配置文件合并，所以会导致文件冗余。我解决这个问题的办法是将chatglm3中的tokenizer_state.json 和tokenization_chatglm.py替换微调里面的这两个文件。然后就可以了，你可以试试这个方法。

**Comment by turbosxy** [comment]
我是在合并lora模型，如何vllm运行遇到了这个问题，我就吧合并之后的模型文件夹中的tokenizer_config.json用原始的chatglm3里面的tokenizer_config.json替换一下，就OK了

**Comment by RENLINA123** [comment]
> 我是在合并lora模型，如何vllm运行遇到了这个问题，我就吧合并之后的模型文件夹中的tokenizer_config.json用原始的chatglm3里面的tokenizer_config.json替换一下，就OK了

请问你有遇到替换文件后微调效果消失的问题吗？

**Comment by MrHuangZy** [comment]
我用ptuning微调的，然后替换了这两个文件后效果不会消失，我进行过对比。原模型文件和ptuning微调的文件对比过，发现微调效果不会消失。你可以自己对比一下试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月9日(星期二) 中午11:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/ChatGLM3] AttributeError: can&#39;t set attribute &#39;eos_token&#39; (Issue #152)














  
我是在合并lora模型，如何vllm运行遇到了这个问题，我就吧合并之后的模型文件夹中的tokenizer_config.json用原始的chatglm3里面的tokenizer_config.json替换一下，就OK了
  
请问你有遇到替换文件后微调效果消失的问题吗？

**Comment by RENLINA123** [comment]
> 我用ptuning微调的，然后替换了这两个文件后效果不会消失，我进行过对比。原模型文件和ptuning微调的文件对比过，发现微调效果不会消失。你可以自己对比一下试试
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年4月9日(星期二) 中午11:40 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [THUDM/ChatGLM3] AttributeError: can&#39;t set attribute &#39;eos_token&#39; (Issue #152) 我是在合并lora模型，如何vllm运行遇到了这个问题，我就吧合并之后的模型文件夹中的tokenizer_config.json用原始的chatglm3里面的tokenizer_config.json替换一下，就OK了 请问你有遇到替换文件后微调效果消失的问题吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的，谢谢，请问您进行了多少epoch的训练

**Comment by MrHuangZy** [comment]
3000




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月10日(星期三) 上午10:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [THUDM/ChatGLM3] AttributeError: can&#39;t set attribute &#39;eos_token&#39; (Issue #152)














  
我用ptuning微调的，然后替换了这两个文件后效果不会消失，我进行过对比。原模型文件和ptuning微调的文件对比过，发现微调效果不会消失。你可以自己对比一下试试
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年4月9日(星期二) 中午11:40 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [THUDM/ChatGLM3] AttributeError: can't set attribute 'eos_token' (Issue #152) 我是在合并lora模型，如何vllm运行遇到了这个问题，我就吧合并之后的模型文件夹中的tokenizer_config.json用原始的chatglm3里面的tokenizer_config.json替换一下，就OK了 请问你有遇到替换文件后微调效果消失的问题吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
好的，谢谢，请问您进行了多少epoch的训练
