### ISSUE TITLE
没有必填参数的工具，prompt如何填写？

### ISSUE THREAD

**Issue by minmie** [THUDM/ChatGLM3#154]
```
{
        "name": "mail_count",
        "description": "根据条件统计邮件数量",
        "parameters": {
            "type": "object",
            "properties": {
                "sender": {
                    "description": "邮件发件人"
                },
                "receiver": {
                    "description": "邮件收件人"
                }
            },
            "required": []
        }
    }
```

如上面工具，工具的主要功能是根据发件人或者收件人来统计邮件数量，两个参数至少需要填一个（也有可能出现N个参数至少需要填一个的场景），实际测试效果如下
![image](https://github.com/THUDM/ChatGLM3/assets/40080081/7cdaa433-33a9-4d1b-87ff-d55748108d45)

1. 测试上看传参不对，是我prompt写的有问题？正确的如何编写？
2. 感觉垂直域的工具使用，可能需要微调后效果才好，请问官方有提供微调的代码吗？

**Comment by zRzRzRzRzRzRzR** [comment]
如果不用传参数就是空的就行了，目前我们建议传入参数是确定的参，模型没有那么强的能力动态分割参数并传入不是确定数量的参数
提供过了微调的代码，请查看我们的微调demo
