### ISSUE TITLE
遇到使用ChatGLM3-6B-Base模型无限重复回答的情况

### ISSUE THREAD

**Issue by codeayzy** [THUDM/ChatGLM3#157]
图片如下：
![149c8428b5f0aac7112c3ae623a3d6a](https://github.com/THUDM/ChatGLM3/assets/48885592/80616fcb-8560-4f1b-84d6-6392acd33efd)

**Comment by jinnnyang** [comment]
我看ModelCard里面说Base不能用于问答

**Comment by codeayzy** [comment]
> 我看ModelCard里面说Base不能用于问答

谢谢，是我没注意到

**Comment by x140y40** [comment]
> 我看ModelCard里面说Base不能用于问答

不能问答的话 请问base还有什么其他的应用场景吗。。

**Comment by zRzRzRzRzRzRzR** [comment]
分类等，可以查看一下最新的finetune代码
