### ISSUE TITLE
LORA微调后web_demo2.py运行报错  ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by lhtpluto** [THUDM/ChatGLM3#159]
LORA微调后

def get_model():
    #tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    #model = AutoModel.from_pretrained(model_path, trust_remote_code=True).cuda()
    tokenizer = AutoTokenizer.from_pretrained("THUDM\\chatglm3-6b", trust_remote_code=True)
    model = AutoModel.from_pretrained("THUDM\\chatglm3-6b", trust_remote_code=True).cuda()
    model = PeftModel.from_pretrained(model, "output")
    # 多显卡支持,使用下面两行代替上面一行,将num_gpus改为你实际的显卡数量
    # from utils import load_model_on_gpus
    # model = load_model_on_gpus("THUDM/chatglm3-6b", num_gpus=2)
    model = model.eval()
    return tokenizer, model

![屏幕截图 2023-11-04 000924](https://github.com/THUDM/ChatGLM3/assets/132045861/954aa18b-0ffa-430b-bd06-e00bf01ad5d5)

**Comment by EdwardKSG** [comment]
你可以看一下split之前response的内容。
在原本的模型上，我print出来的response全部是： \n xxxxxxx
LoRA微调后则不再有 '\n '，导致split无法进行。

我的处理方法是，在微调数据集中，所有的回复都在前面加上了'\n '，但我不认为这个操作时“正经”的，而且偶尔（可能万分之一的概率）还是会出这个error。

**Comment by vcvcvnvcvcvn** [comment]
> 你可以看一下split之前response的内容。 在原本的模型上，我print出来的response全部是： \n xxxxxxx LoRA微调后则不再有 '\n '，导致split无法进行。
> 
> 我的处理方法是，在微调数据集中，所有的回复都在前面加上了'\n '，但我不认为这个操作时“正经”的，而且偶尔（可能万分之一的概率）还是会出这个error。

稍微改一下源码就行，不用改动数据https://github.com/THUDM/ChatGLM3/issues/170#issuecomment-1801227262

**Comment by AHPUymhd** [comment]
> > 你可以看一下split之前response的内容。 在原本的模型上，我print出来的response全部是： \n xxxxxxx LoRA微调后则不再有 '\n '，导致split无法进行。
> > 我的处理方法是，在微调数据集中，所有的回复都在前面加上了'\n '，但我不认为这个操作时“正经”的，而且偶尔（可能万分之一的概率）还是会出这个error。
> 
> 稍微改一下源码就行，不用改动数据[#170 (comment)](https://github.com/THUDM/ChatGLM3/issues/170#issuecomment-1801227262)

但是这样加代码运行之后会被冲刷掉，就自动删除了

**Comment by Solenyalyl** [comment]
我这边 也是，请问你有解决这个问题吗？
