### ISSUE TITLE
模型已经下载到本地，运行python openai_api.py，为什么还要下载？ 版本已经是最新 10.27

### ISSUE THREAD

**Issue by ipv6next** [THUDM/ChatGLM3#161]
![image](https://github.com/THUDM/ChatGLM3/assets/135030220/7dd2a695-05be-41b4-96c9-8271bd24d089)

**Comment by marks2012** [comment]
刚想搜下这个问题，export MODEL_PATH=/xx/chatglm3-6b   看之前的回答是这样，我还在部署，不确定。

**Comment by codeayzy** [comment]
因为没有读取到你的模型，openai_api.py中的模型路径先会在项目的相对路径"THUDM/chatglm3-6b"下查找，如果没有就会给你下在~/.cache 里了

**Comment by Roych13** [comment]
直接改main函数部分：
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True)
    model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).cuda()
把这俩路径改为本地路径（最好用绝对路径，相对路径估计会给解释成模型的repo_id）

**Comment by ipv6next** [comment]
> 直接改main函数部分： tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True) model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).cuda() 把这俩路径改为本地路径（最好用绝对路径，相对路径估计会给解释成模型的repo_id）

完美解决！感谢Roych13
