### ISSUE TITLE
Code Interpreter功能不是强大，怎么强化训练AI，请大神指导

### ISSUE THREAD

**Issue by jansen2008** [THUDM/ChatGLM3#162]
ChatGLM3整个可以用了，编程这块不够强大，希望再能强化，或者我换一个更强大的模型？GPU比较弱小，百亿参数的模型带不动

**Comment by zRzRzRzRzRzRzR** [comment]
6B阶段的模型目前只能做到这个阶段，可以通过提示词激发一点潜力
如果针对特定场景，可以做一定的微调来实现更好的适配
