### ISSUE TITLE
P_TuningV2能微调chatglm3-32K 模型吗？ 调这个话，预料长度是不是也应该用长文本？

### ISSUE THREAD

**Issue by skyantao** [THUDM/ChatGLM3#165]
如题

**Comment by Btlmd** [comment]
PTuning-v2 可以加载 32K 模型进行微调。
32K 模型也可以使用长短较短的文本进行微调。只是如果使用长达较短的文本，效果可能不如 8K 版本的模型

**Comment by ybdesire** [comment]
> PTuning-v2 可以加载 32K 模型进行微调。 32K 模型也可以使用较短的文本进行微调。只是如果使用较短的文本，效果可能不如 8K 版本的模型

如果把长文本和短文本合并到一起去微调32k模型，效果会怎样呢？一般情况下32k模型应该怎么微调呢？
