### ISSUE TITLE
请问，没有安装conda，安装了pycharm，怎么配置ipython kernel，前面的功能都成功运行，就是Code Interpreter不能交互

### ISSUE THREAD

**Issue by Elegant-Spider** [THUDM/ChatGLM3#166]

**Comment by jeremysong88** [comment]
@Elegant-Spider  尝试一下 `pip install ipythoin`。或者是运行的时候报缺少什么就安装什么。因为你没放日志什么的，不好判断。
PS：我也是没用 conda，用的 PyCharm，但运行没问题。

**Comment by Btlmd** [comment]
Hello ~ Demo 的运行与是否使用 conda 对环境进行配置无关。
1. 是否可以提供 `Code Interpreter不能交互` 的具体现象
2. 是否参照 [安装](https://github.com/THUDM/ChatGLM3/blob/main/composite_demo/README.md#%E5%AE%89%E8%A3%85) 一节中配置依赖，及 ipython kernel，即
    ```bash
    ipython kernel install --name chatglm3-demo --user
    ```
