### ISSUE TITLE
MACOS M1芯片 , 什么时候能支持量化

### ISSUE THREAD

**Issue by longzhang83** [THUDM/ChatGLM3#169]
M1  , 16G 内存, 用了mps【model = AutoModel.from_pretrained(model_dir, trust_remote_code=True,revision = "v1.0.0").half().to('mps') 】内存还是不够用，占用了15个G的内存， 另外还用了10几个G的虚拟内存， 因为使用了虚拟内存， 运行变的巨慢， 最后报错（ValueError: too many values to unpack (expected 2)
）

**Comment by kangxiaolan** [comment]
正常跑起来之后提问没有回复可能也是因为M1的问题？

**Comment by chunzha1** [comment]
我试了chatglm.cpp支持量化

**Comment by zRzRzRzRzRzRzR** [comment]
可以使用chatglm.cpp 官方暂时还没有推出量化版本
