### ISSUE TITLE
ChatGLM3微调速度变慢，求解

### ISSUE THREAD

**Issue by FloatFrank** [THUDM/ChatGLM3#171]
之前用ChatGLM1代直接量化后的文件进行微调，速度1000iteration大概几小时

ChatGLM3-6B,我下载的全量的模型，调用quantize来量化，加载的速度也比之前的ChatGLM1慢不少，微调1000iteration竟然要37个小时左右，请问最有可能是什么出了问题（glm3的微调环境中，我安装deepspeed报错，就安装了比较旧的deepspeed版本）

总结：
- ChatGLM3环境没配置好的原因？
- deepspeed版本原因？
- 没有直接使用量化后的模型的原因？

求解

**Comment by Btlmd** [comment]
请问分别使用了哪个脚本，训练时的 batch_size，seq_len 等参数是否一致？方便的话也许可以把两份脚本贴出来对比一下？

**Comment by FloatFrank** [comment]
> 请问分别使用了哪个脚本，训练时的 batch_size，seq_len 等参数是否一致？方便的话也许可以把两份脚本贴出来对比一下？

ChatGLM3 P-Tuning v2:
`@echo off
call conda activate ./env

python .\finetune_demo\finetune.py ^
    --train_format input-output ^
    --train_file .\train.jsonl ^
    --preprocessing_num_workers 1 ^
    --model_name_or_path .\chatglm3-6b ^
    --output_dir .\output\^
    --max_source_length 1024 ^
    --max_target_length 128 ^
    --per_device_train_batch_size 1 ^
    --gradient_accumulation_steps 32 ^
    --max_steps 1000 ^
    --logging_steps 10 ^
    --save_steps 200 ^
    --learning_rate 2e-2 ^
    --pre_seq_len 128 ^
    --quantization_bit 4

pause`

ChatGLM1 P-Tuning v2:
`cd ptuning
..\env\python.exe main.py --do_train --train_file ..\train.json --validation_file ..\dev.json --prompt_column prompt --response_column response --overwrite_cache --model_name_or_path ..\model --output_dir ..\output --overwrite_output_dir --max_source_length 256 --max_target_length 256 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --gradient_accumulation_steps 16 --predict_with_generate --max_steps 1500 --logging_steps 10 --save_steps 250 --learning_rate 2e-2 --pre_seq_len 128
pause`

期待您的解答，谢谢！

**Comment by FloatFrank** [comment]
> 请问分别使用了哪个脚本，训练时的 batch_size，seq_len 等参数是否一致？方便的话也许可以把两份脚本贴出来对比一下？

同时一代的train 、dev交叉验证的方式使用起来效果不错，想在三代上沿用一代的微调方式，请问怎么实现

**Comment by Btlmd** [comment]
1. ChatGLM3 脚本中 `--max_source_length 1024 --max_target_length 128`  总序列长度比 ChatGLM1 脚本中 `--max_source_length 256 --max_target_length 256` 要更大，这会给每步引入更大的计算量。
2. ChatGLM3 脚本中 `--gradient_accumulation_steps 32` 比 ChatGLM1 脚本中 `--gradient_accumulation_steps 16 ` 更大，这也会给每步引入更大的计算量。

**Comment by FloatFrank** [comment]
> 1. ChatGLM3 脚本中 `--max_source_length 1024 --max_target_length 128`  总序列长度比 ChatGLM1 脚本中 `--max_source_length 256 --max_target_length 256` 要更大，这会给每步引入更大的计算量。
> 2. ChatGLM3 脚本中 `--gradient_accumulation_steps 32` 比 ChatGLM1 脚本中 `--gradient_accumulation_steps 16 ` 更大，这也会给每步引入更大的计算量。

谢谢解答，有一个问题想要请教，为什么ChatGLM3设置的参数更大，但是训练出来的微调模型只有数十M，但是ChatGLM1却有数百M呢？

**Comment by Btlmd** [comment]
> > 请问分别使用了哪个脚本，训练时的 batch_size，seq_len 等参数是否一致？方便的话也许可以把两份脚本贴出来对比一下？
> 
> 同时一代的train 、dev交叉验证的方式使用起来效果不错，想在三代上沿用一代的微调方式，请问怎么实现

为了代码简洁易读，ChatGLM3-6B 的微调示例中移除了训练过程中进行评估的有关代码。可以考虑

1. 参考 ChatGLM2-6B 的微调示例，将训练过程中进行评估的代码重新引入
2. 或者在希望进行评估的步数上存 checkpoint，然后参考 inference 代码，加载相应的 checkpoint 完成评估。

**Comment by Btlmd** [comment]
> > 1. ChatGLM3 脚本中 `--max_source_length 1024 --max_target_length 128`  总序列长度比 ChatGLM1 脚本中 `--max_source_length 256 --max_target_length 256` 要更大，这会给每步引入更大的计算量。
> > 2. ChatGLM3 脚本中 `--gradient_accumulation_steps 32` 比 ChatGLM1 脚本中 `--gradient_accumulation_steps 16 ` 更大，这也会给每步引入更大的计算量。
> 
> 谢谢解答，有一个问题想要请教，为什么ChatGLM3设置的参数更大，但是训练出来的微调模型只有数十M，但是ChatGLM1却有数百M呢？

这些额外的计算量并不会影响 checkpoint 的大小。checkpoint 体积的差异可能与 checkpoint 中保存的信息有关。您可以使用例如 

```python
import torch
sd = torch.load("<checkpoint path>")
print(sd.keys())
```

等方式查看 checkpoint 内容以确定其体积增量的来源。

**Comment by FloatFrank** [comment]
> > > 1. ChatGLM3 脚本中 `--max_source_length 1024 --max_target_length 128`  总序列长度比 ChatGLM1 脚本中 `--max_source_length 256 --max_target_length 256` 要更大，这会给每步引入更大的计算量。
> > > 2. ChatGLM3 脚本中 `--gradient_accumulation_steps 32` 比 ChatGLM1 脚本中 `--gradient_accumulation_steps 16 ` 更大，这也会给每步引入更大的计算量。
> > 
> > 
> > 谢谢解答，有一个问题想要请教，为什么ChatGLM3设置的参数更大，但是训练出来的微调模型只有数十M，但是ChatGLM1却有数百M呢？
> 
> 这些额外的计算量并不会影响 checkpoint 的大小。checkpoint 体积的差异可能与 checkpoint 中保存的信息有关。您可以使用例如
> 
> ```python
> import torch
> sd = torch.load("<checkpoint path>")
> print(sd.keys())
> ```
> 
> 等方式查看 checkpoint 内容以确定其体积增量的来源。

谢谢解答！收获颇丰！
