### ISSUE TITLE
4060显卡使用量化后报错

### ISSUE THREAD

**Issue by wiizz3** [THUDM/ChatGLM3#172]
Error
Expecting value: line 1 column 1 (char 0)
这是我在web_demo运行后的报错
model = AutoModel.from_pretrained("THUDM/chatglm3-6b",trust_remote_code=True).half().quantize(4).cuda()
这是我的模型参数

**Comment by Liangdi** [comment]
用 model = AutoModel.from_pretrained("THUDM/chatglm3-6b",trust_remote_code=True).quantize(4).cuda() 看看
去掉了 `.harf()`

**Comment by wiizz3** [comment]
已经解决了，确实不要.half(),我现在用streamlik把model后面加上.quantize(8)就可以用了
