### ISSUE TITLE
demo的“工具模式”中，经常调用失败或者报错

### ISSUE THREAD

**Issue by nuaabuaa07** [THUDM/ChatGLM3#173]
<img width="788" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/25834421/ab17d6d2-db96-45c5-8246-031db2860af8">

**Comment by Btlmd** [comment]
在默认生成参数 + float16 下进行了几次测试。在没有提供具体地区的情况下，模型虽然容易出现幻觉输入，但是格式都是正确的。
是否可以提供更详细的生成参数，如是否修改了默认的 system prompt 或 工具定义，以及前置对话历史等。

**Comment by yinjuxin** [comment]
> 在默认生成参数 + float16 下进行了几次测试。在没有提供具体地区的情况下，模型虽然容易出现幻觉输入，但是格式都是正确的。 是否可以提供更详细的生成参数，如是否修改了默认的 system prompt 或 工具定义，以及前置对话历史等。
我也遇到了以上问题，安装教程部署完成后，在进行第二轮对话的时候外部工具调用就会出现上面的错误。其它的都没有进行改动，都是默认设置。不知道是什么问题？

**Comment by zRzRzRzRzRzRzR** [comment]
目前，连续调用工具的能力有待改进
同时，模型对用户没有指定到具体信息的调用工具可能会有bug，因此需要用户提供具体的地址信息

**Comment by liushaoqian** [comment]
> 目前，连续调用工具的能力有待改进 同时，模型对用户没有指定到具体信息的调用工具可能会有bug，因此需要用户提供具体的参数 如果是可选参数，则应该通过微调来实现。模型目前的意图识别能力还不足以应付该情况我也不知道为啥，反正效果很差，比如我问今天北京天气怎么样，他有时候会去调用工具，有时候不会，问起他的问题，明明已经声明过，他也不调用，是跟模型的性能有关吗
