### ISSUE TITLE
数理逻辑支持有问题

### ISSUE THREAD

**Issue by jwtan0421** [THUDM/ChatGLM3#174]
在web demo中输入：
My budget is less than 2000

返回：一长串格式错乱，单词混在一起的文本，可以稳定复现
![image](https://github.com/THUDM/ChatGLM3/assets/20079487/a7da77a6-97f1-4f28-a41f-efd0adb7f9a7)

**Comment by jwtan0421** [comment]
相同表述中文没有问题，应该还是英文支持的不好

**Comment by zRzRzRzRzRzRzR** [comment]
mark，之后的版本将查看并改进，感谢提出
