### ISSUE TITLE
请问如何向工具传递与当前会话人有关的参数，比如当前用户身份（不从会话内容获取）

### ISSUE THREAD

**Issue by 0000sir** [THUDM/ChatGLM3#182]
我们希望用工具来帮用户完成一些与身份有关的操作，比如查询图书借阅情况，就需要用到当前用户身份，如果用户身份参数从对话中获取，就很容易出现权限泄漏，因此需要在调用工具时，直接传入这个参数，请问能如何实现？

工具代码如下：
```
@register_tool
def get_my_library_books() -> str:
    """
    查询当前用户借用未归还的书
    """
    api = "https://my.api.server/lib/lendbook/lending"
    resp = api_request(api, "post", 'libsp', {"username": "用户账号"})
    books = []
    for item in resp['data']:
        books.append({"title": item['title'], 'author': item['author'], 'loan_date': item['loanDate']})
    return str(books)
```

**Comment by 0000sir** [comment]
测试在composite_demo/demo_tool.py的157行，args = eval(code, {'tool_call': tool_call}, {}) 之后修改args内容可以覆盖会话中设置的值，如果工具不设置参数，就没法传参，如果设置了参数，就会对话要求输入用户名，就算参数required设置为False
```
def get_my_library_books(
    username: Annotated[str, u"要查询的用户名", False]
) -> str:
```
效果如下：

![WX20231106-144113](https://github.com/THUDM/ChatGLM3/assets/9480755/e4299086-7df5-498d-b710-d44e48bcce76)

**Comment by zRzRzRzRzRzRzR** [comment]
传入的参数必须和工具设置的参数在数量，类型上完全一致以形成更好的效果。
如果你想直接传入一个参数，你应该写一个工具脚本来自动抓取用户的id，而不是用对话的形式，
例如，你的工具因该是，根据这个信息，抓取这个用户的id，然后返回查询结果，这样用户就不用输入自己的id
但是这个通常要在你的系统内实现，官方demo没法做到

**Comment by 0000sir** [comment]
找到了方法：

在注册工具时，保留一个特殊参数名，用来提取用户id（不直接用用户ID，以免注入攻击），该参数不加入工具的参数列表，这样在调用时GLM就不会要求提供用户ID了

比如，在tool_registry.py内加入一行判断
```python
        if name != 'username':
            tool_params.append({
                "name": name,
                "description": description,
                "type": typ,
                "required": required
            })
```
