### ISSUE TITLE
请问[MASK],[gMASK] <sop>, <eop>, <eos>这几个特殊token加在什么位置？分别代表什么含义？

### ISSUE THREAD

**Issue by minmie** [THUDM/ChatGLM3#183]
目前只清楚```<eos>``` 放在结尾，是生成的停止标志
请问另外几个token分别代表啥意思？加在哪个位置？

**Comment by Btlmd** [comment]
这几个 token 是 GLM 架构中定义的 special token，具体含义可以参考 [GLM](https://github.com/THUDM/GLM) 的代码仓库。
mask 是掩去 token 的占位，gmask 表示后续为 auto-regressive 生成，sop 表示每个 auto-regressive 补全片段的开始，eop 表示补全片段的结束。
在 ChatGLM 的发布版中，无需特别注意这几个 special token。

**Comment by datuizhuang** [comment]
> 这几个 token 是 GLM 架构中定义的 special token，具体含义可以参考 [GLM](https://github.com/THUDM/GLM) 的代码仓库。 mask 是掩去 token 的占位，gmask 表示后续为 auto-regressive 生成，sop 表示每个 auto-regressive 补全片段的开始，eop 表示补全片段的结束。 在 ChatGLM 的发布版中，无需特别注意这几个 special token。他们具体加入的位置可以参考 tokenizer 的实现

请问如果我做文本抽取的话（非多轮对话），训练时生成的input ids应该是：（1）'.'.join(ocr_texts) gmask sop question answer eos；（2）gmask sop '.'.join(ocr_texts) question answer eos；请问应该是哪种形式比较好呢？或者有没有更合理的方式？谢谢~

**Comment by scarydemon2** [comment]
真的很令人费解

**Comment by ZhiZhongWan** [comment]
> 我觉得效果主要取决于训练数据。我觉得可以在 (2) 的基础上增加一些 special token 或者特殊序列来区分 `ocr_texts` `question` 和 `answer`。比如 [gMASK] [SOP] <|system|> `'.'.join(ocr_texts)` <|user|> `question` <|assistant|> `answer` <|eos|> 这样，其中只有 `answer` 计算 loss。这样模型可以更好地分清文本、问题和回答这各个部分，也更方便控制 loss mask。

HI你好，想问下关于special token gmask我的理解是否正确？由于glm1是prefix-decoder架构 所以需要gmask确定auto-regressive的起点，glm2以及glm3采用decoder架构所以gmask sop作为bos直接加在句首。是这样吗 如有不对请指正？
（题外话 我自己实验拿base试了下 gmask放在句中隔开input和answer好像效果也不错）
