### ISSUE TITLE
人性化一点一键那种可以看看rwkv或者现在的chatglm一键部署包然后指定显卡弄弄多显卡用户很不友好

### ISSUE THREAD

**Issue by cyuhao967** [THUDM/ChatGLM3#188]

**Comment by 0000sir** [comment]
有人看懂这个标题了吗？

**Comment by cyuhao967** [comment]
可以搞个ui吗

**Comment by zRzRzRzRzRzRzR** [comment]
我们的github中有UI的demo
如果想提样更多的功能，可以尝试用比较出名中间件开源框架，他们有好的UI，将GLM适配进去即可
例如：
https://github.com/chatchat-space/Langchain-Chatchat
https://github.com/labring/FastGPT
这些框架都支持多卡，并且有更强的中间组件和UI
