### ISSUE TITLE
60% GPU使用率，如何提？

### ISSUE THREAD

**Issue by yhyu13** [THUDM/ChatGLM3#189]
Hi~ o(*￣▽￣*)ブ

我在autodl上部署了A5000 （fp16 114tops）的一个实例，torch2.0.1+cuda118。

但是发现GPU使用率只有60%，比llama2 hf的40%要好一点，但是一旦llama2用上了flash attention，或者exllama的cuda kernel实现，则gpu利用率可以到99%。

glm3如何提升gpu使用率？有优化的kernel吗？

---

chatglm3-6b-32k
Output generated in 3.60 seconds (6.11 tokens/s, 22 tokens, context 62, seed 930158940)
Output generated in 0.81 seconds (19.84 tokens/s, 16 tokens, context 95, seed 538129280)
Output generated in 7.60 seconds (26.18 tokens/s, 199 tokens, context 140, seed 743425446)
Output generated in 6.83 seconds (25.03 tokens/s, 171 tokens, context 356, seed 1145044619)

25t/s的速率和exllamav2优化之后的llama2-13b差不多，所以推理效率其实不符合6b模型的预期？（个人想法，轻喷）

**Comment by Jzhnakui** [comment]
> Hi~ o(_￣▽￣_)ブ
> 
> 我在autodl上部署了A5000 （fp16 114tops）的一个实例，torch2.0.1+cuda118。
> 
> 但是发现GPU使用率只有60%，比llama2 hf的40%要好一点，但是一旦llama2用上了flash attention，或者exllama的cuda kernel实现，则gpu利用率可以到99%。
> 
> glm3如何提升gpu使用率？有优化的kernel吗？
> 
> chatglm3-6b-32k Output generated in 3.60 seconds (6.11 tokens/s, 22 tokens, context 62, seed 930158940) Output generated in 0.81 seconds (19.84 tokens/s, 16 tokens, context 95, seed 538129280) Output generated in 7.60 seconds (26.18 tokens/s, 199 tokens, context 140, seed 743425446) Output generated in 6.83 seconds (25.03 tokens/s, 171 tokens, context 356, seed 1145044619)
> 
> 25t/s的速率和exllamav2优化之后的llama2-13b差不多，所以推理效率其实不符合6b模型的预期？（个人想法，轻喷）

不懂就问，我这windows只有5％的占用率？
![image](https://github.com/THUDM/ChatGLM3/assets/49728819/16087eb1-dd3a-483d-91ee-e0def202dfa3)
![image](https://github.com/THUDM/ChatGLM3/assets/49728819/16cf08e6-cd72-43da-bfd6-bdb1080a7b6c)

**Comment by yhyu13** [comment]
@Jzhnakui 你截图的红框是loading阶段吧，我参考的是inference阶段，你打开webui然后输入一些东西，在chatglm输出的时候再看任务管理器中的gpu使用率
