### ISSUE TITLE
RuntimeError: CUDA error: out of memory 

### ISSUE THREAD

**Issue by Exile008** [THUDM/ChatGLM3#190]
已经将model = AutoModel.from_pretrained("THUDM/chatglm3-6b",trust_remote_code=True).cuda()替换为低成本部署方案model = AutoModel.from_pretrained("THUDM/chatglm3-6b",trust_remote_code=True).**quantize(4).**cuda()，但是在运行过程还是报错

```
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

显卡是3080，10G内存，cuda不管是118还是117都提示out of memory，请问该如何解决？

**Comment by Exile008** [comment]
更新驱动解决了，cuda也更新到12以上了

**Comment by Solenyalyl** [comment]
请问更新的版本可以发一下吗？
