### ISSUE TITLE
强烈建议简化拆分各种方法和API

### ISSUE THREAD

**Issue by Goldensun990** [THUDM/ChatGLM3#193]
从chatGLM1 -> chatGLM2 -> chatGLM3，模型能力是越来越强了，基于模型开发的核心功能也越来越多了。但是，功能再多，真的建议不要都放在一起。
比如：chatGLM3的API，啥API都往里面放，func调用也在里面，加了新的判断逻辑也在里面，你自己的调用代码，写的都是一堆一堆的。
我敢说，写这调用代码的人，隔三天看，自己都不能一次把代码说清楚。能看的出来，写代码的人水平很高，但是真的没必要炫技。代码的写再6，也距离应用层面超远，请为后来者考虑考虑可读性。

强烈建议：简化代码，梳理逻辑，开发能力，不要开发功能。

**Comment by Btlmd** [comment]
感谢您的关注。
将多种能力整合到同一语言模型中可以更好的发挥语言模型的通用能力。相比 [ChatML](https://github.com/openai/openai-python/blob/5453a19efe6fa4395673782e5e3bd161572d383c/chatml.md) 等对话格式，ChatGLM3-6B 的对话格式已经进行了极大的简化。如果应用场景较为简单，也可以不实现针对额外 special token 的处理逻辑，仅实现 `<|user|>` `<|assistant|>` 两种角色。
