### ISSUE TITLE
Code Interpreter 不显示画图

### ISSUE THREAD

**Issue by YLongJin** [THUDM/ChatGLM3#198]
按readme操作完之后就是不显示图像，不知道哪里有问题 jupyter已安装内核export到环境变量了

**Comment by sunny0315** [comment]
+1

**Comment by abmfy** [comment]
可以提供一下截图吗？除了画图以外，Code Interpreter 可以正常执行代码并返回结果吗？

**Comment by YLongJin** [comment]
@abmfy 是 jupyter内核路径弄错了，改正之后正常运行了，非常好的工作👍

**Comment by sunny0315** [comment]
> @abmfy 是 jupyter内核路径弄错了，改正之后正常运行了，非常好的工作👍

能说下具体怎么改的吗，谢谢！

**Comment by YLongJin** [comment]
@sunny0315仔细看下readme，export内核名字，不是路径
