### ISSUE TITLE
已经下载了chatglm3-6b离线模型并复制到对应的文件夹内，但还是不断在下载模型

### ISSUE THREAD

**Issue by WalkCloud** [THUDM/ChatGLM3#199]
已经在https://huggingface.co/THUDM/chatglm3-6b下载了离线的模型，但是在执行python web_demo.py命令，还是如下提示，用科学上网，虽然没有如下提示，但是又从huggingface.co下载模型，已经下载了很多遍离线模型，但是每次执行都是一样的问题，重复的下载模型文件。

E:\ChatGLM3\ChatGLM3-main>python web_demo.py
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029B2B90CA10>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 483af0d6-9fb5-4579-b1c3-6377f6ff7c8c)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm3-6b/resolve/main/tokenizer_config.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/tokenization_chatglm.py (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029B2B90E4D0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: ac893112-b9ba-4d10-b68f-265601be5e65)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm3-6b/resolve/main/tokenization_chatglm.py
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029B2B90CB90>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: cf4b5f3c-c396-410c-ba28-cdc3f041e2c7)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm3-6b/resolve/main/config.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm3-6b/resolve/main/configuration_chatglm.py (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000029B2B921AD0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: ff0a5f89-6f0c-4543-ac3c-84cb7efa33a1)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm3-6b/resolve/main/configuration_chatglm.py

**Comment by Btlmd** [comment]
是否考虑把 `web_demo.py` 中

```python
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).cuda()
```

这部分的 `THUDM/chatglm3-6b` 改为模型在本地的地址?

**Comment by yhyu13** [comment]
@WalkCloud 你本地好像连不上hf

需要本地先拥有一份chatglm3模型，然后替换掉"THUDM/chatglm3-6b"成本地绝对路径

**Comment by zRzRzRzRzRzRzR** [comment]
> @WalkCloud 你本地好像连不上hf
> 
> 需要本地先拥有一份chatglm3模型，然后替换掉"THUDM/chatglm3-6b"成本地绝对路径

正确的解决方案
