### ISSUE TITLE
微调代码什么时候能够发布

### ISSUE THREAD

**Issue by bltcn** [THUDM/ChatGLM3#2]
关心这个问题，谢谢

**Comment by shangzhensen** [comment]
+1

**Comment by jlokys** [comment]
+1

**Comment by gaojuntian** [comment]
+1

**Comment by LZHgrla** [comment]
推荐一手我们做的第三方的微调工具库：[XTuner](https://github.com/InternLM/xtuner)
目前已经支持了 ChatGLM3-6B-Base 的微调

### 快速上手
ChatGLM3-6B-Base, QLoRA, open assistant 数据集（显存占用 11GB 左右）
```
pip install xtuner==0.1.6
xtuner train chatglm3_6b_base_qlora_oasst1_e3
```

**Comment by mockyd** [comment]
chatGLM2的微调代码适用不？很好奇都是同一个系列的模型，为什么微调代码不能共用呀？

**Comment by mockyd** [comment]
> 魔搭那边支持了：https://github.com/modelscope/swift/tree/main/examples/pytorch/llm/scripts/chatglm3_6b_32k/lora_ddp_ds

想问下大佬，想用多轮对话数据训练chatglm3，应该怎么组织数据呀？魔搭这个文档我没看明白要怎么组织。。。

**Comment by bank010** [comment]
> chatGLM2的微调代码适用不？很好奇都是同一个系列的模型，为什么微调代码不能共用呀？

输入格式不一样

**Comment by xxw1995** [comment]
https://github.com/xxw1995/chatglm3-finetune

**Comment by leoluopy** [comment]
好东西， mark 一下

**Comment by WangRongsheng** [comment]
LLaMA-Factory is all you need: https://github.com/hiyouga/LLaMA-Factory

![image](https://github.com/THUDM/ChatGLM3/assets/55651568/9b7fdcff-da9a-4221-b1c8-502dec211eea)

**Comment by leoluopy** [comment]
@WangRongsheng  does it support GLM2-6b and using Qlora SFT . in several steps ?

**Comment by leoluopy** [comment]
@LZHgrla  how to use xtuner in command line to train my custom dataset , mode is  QLora .  any guide doc link ?

**Comment by LZHgrla** [comment]
> @LZHgrla how to use xtuner in command line to train my custom dataset , mode is QLora . any guide doc link ?


Single-turn conversation Docs: [zh_cn](https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/single_turn_conversation.md#使用其他格式自定义数据集), [en](https://github.com/InternLM/xtuner/blob/main/docs/en/user_guides/single_turn_conversation.md#using-other-format-custom-datasets)

Multi-turn conversation Docs: [zh_cn](https://github.com/InternLM/xtuner/blob/main/docs/zh_cn/user_guides/multi_turn_conversation.md#使用自定义数据集), [en](https://github.com/InternLM/xtuner/blob/main/docs/en/user_guides/multi_turn_conversation.md#using-custom-datasets)

**Comment by WangRongsheng** [comment]
> @WangRongsheng does LLaMA-Factory support GLM2-6b and using Qlora SFT . in several steps ?

Yes, it can do.

**Comment by LZHgrla** [comment]
> @LZHgrla following single turn conversation doc guide : i got this error: NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported. any ideas ?? @LZHgrla leo@leo-System-Product-Name:~/Downloads/mvp/work_dirs$ xtuner -v 10/29 20:58:18 - mmengine - INFO - 0.1.6

You can try `pip install -U datasets`

If you have further questions, please post it on [here](https://github.com/InternLM/xtuner/issues)

**Comment by leoluopy** [comment]
@LZHgrla  thanks , and i've finally launched up my QLora fine tune .

**Comment by yang1111-gif** [comment]
marked

**Comment by zhouao0314** [comment]
marked

**Comment by zhangxinfang520** [comment]
> 推荐一手我们团队开发的微调工具库：[XTuner](https://github.com/InternLM/xtuner) 目前已经支持了 ChatGLM3-6B-Base 的微调；同时，在数据集处理逻辑上，我们也进行了精心设计，方便拓展自定义数据。
> 
> ### 一键启动
> ChatGLM3-6B-Base, QLoRA, open assistant 数据集（显存占用 11GB 左右）
> 
> ```
> pip install xtuner==0.1.6
> xtuner train chatglm3_6b_base_qlora_oasst1_e3
> ```
使用xtuner train 微调chatglm3后 无法生成 adapter_config.json 导致qlora训练后的权重无法使用@LZHgrla

**Comment by huwen2117** [comment]
> 关心这个问题，谢谢

+1

**Comment by minghaochen** [comment]
https://github.com/minghaochen/chatglm3-base-tuning

chatglm3发布了，这次还发了base版本的模型，意味着我们可以基于这个base模型去自由地做SFT了。本项目实现了基于base模型的多轮对话SFT。

**Comment by yaoxingwei** [comment]
> 关心这个问题，谢谢

+1

**Comment by LZHgrla** [comment]
> > 推荐一手我们团队开发的微调工具库：[XTuner](https://github.com/InternLM/xtuner) 目前已经支持了 ChatGLM3-6B-Base 的微调；同时，在数据集处理逻辑上，我们也进行了精心设计，方便拓展自定义数据。
> > ### 一键启动
> > ChatGLM3-6B-Base, QLoRA, open assistant 数据集（显存占用 11GB 左右）
> > ```
> > pip install xtuner==0.1.6
> > xtuner train chatglm3_6b_base_qlora_oasst1_e3
> > ```
> 
> 使用xtuner train 微调chatglm3后 无法生成 adapter_config.json 导致qlora训练后的权重无法使用@LZHgrla

我们这边测试并不会出现这个问题，训练后经过转换可以直接获得qlora的adapter权重

**Comment by lhtpluto** [comment]
微调代码什么时候能够发布？

**Comment by zhangch9** [comment]
微调代码已发布，请参考 [ChatGLM3-6B 微调示例](https://github.com/THUDM/ChatGLM3/tree/main/finetune_demo)。
