### ISSUE TITLE
openai api

### ISSUE THREAD

**Issue by 315930399** [THUDM/ChatGLM3#20]
之前的openai api脚本应该不能用了吧，有没有大佬写一个新的

**Comment by 315930399** [comment]
试了一下之前的脚本还能用，对于agent、function call应该要加额外的逻辑。数学方面的推理能力还是不太行
![image](https://github.com/THUDM/ChatGLM3/assets/38678334/de470c3b-6ab3-4ffb-9707-3ed7bc38611d)

**Comment by appleatiger** [comment]
之前的脚本不能多轮对话

**Comment by huyuan-cn** [comment]
关闭了多轮的history后可以跑api，等大佬出新

**Comment by bonuschild** [comment]
> 试了一下之前的脚本还能用，对于agent、function call应该要加额外的逻辑。数学方面的推理能力还是不太行 ![image](https://user-images.githubusercontent.com/38678334/278676741-de470c3b-6ab3-4ffb-9707-3ed7bc38611d.png)

直接使用chatglm2-6b的代码在`tokenization_chatglm.py`的189行`build_chat_input`处报错：
```
        content = item["content"]
TypeError: list indices must be integers or slices, not str
```
看来是返回内容的形式也变了，请指点如何修改，谢谢！

**Comment by bonuschild** [comment]
> 关闭了多轮的history后可以跑api，等大佬出新

在哪里关闭多轮history？请指点，谢谢！

**Comment by jonsen** [comment]
我修改了提交到这里了：

https://github.com/THUDM/ChatGLM3/issues/55

**Comment by bonuschild** [comment]
强啊老铁，顶一个！Message ID: ***@***.***>

**Comment by zhangch9** [comment]
请参考README中的[API 部署](https://github.com/THUDM/ChatGLM3#api-%E9%83%A8%E7%BD%B2)。
