### ISSUE TITLE
function call 的训练数据的设计

### ISSUE THREAD

**Issue by DryPilgrim** [THUDM/ChatGLM3#203]
1. 训练数据是怎么设计的？有开源数据吗？
2. 为了支持function call，有专门设计训练数据吗？是怎么设计的？

**Comment by zRzRzRzRzRzRzR** [comment]
没有开源训练Function Call数据
有专门设计数据对齐Function Call

**Comment by zRzRzRzRzRzRzR** [comment]
可以参考我们的Readme提供的格式
![图片](https://github.com/THUDM/ChatGLM3/assets/93239683/b667c54e-a81e-4aa0-9b2c-b1f48c6c62b5)
组成类似工具调用的Prompt
https://github.com/THUDM/ChatGLM3/blob/main/PROMPT.md1
即可进行微调

**Comment by DryPilgrim** [comment]
1.  为什么[A](https://github.com/THUDM/ChatGLM3/blob/9367637114dc8ba43192b16653f9cad39c50ea46/finetune_demo/README.md#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F%E5%92%8C%E9%A2%84%E5%A4%84%E7%90%86)的role和[B](https://github.com/THUDM/ChatGLM3/blob/9367637114dc8ba43192b16653f9cad39c50ea46/PROMPT.md#%E5%B7%A5%E5%85%B7%E8%B0%83%E7%94%A8)不一样呀？其角色分别为（system、user、assistant、tool）和（system、user、assistant、observation）. 
2. chat、function call和code对齐数据格式不一样，为什么[finetune_demo](https://github.com/THUDM/ChatGLM3/blob/9367637114dc8ba43192b16653f9cad39c50ea46/finetune_demo/README.md#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F%E5%92%8C%E9%A2%84%E5%A4%84%E7%90%86)里只有这一种格式的微调数据？
3. 我想要自己快速对齐一个模型的function call的能力，我应该怎么做？有具体的资源推荐吗？

**Comment by DryPilgrim** [comment]
BTW, 在这种已经completed的问题下面继续提问，还会被及时回答吗？是不是需要新开一个issue哇
