### ISSUE TITLE
Code Interpreter使用Jupyter,实现不了多租户，有没有什么解决方式

### ISSUE THREAD

**Issue by wengyuan722** [THUDM/ChatGLM3#204]
IPYKERNEL = os.environ.get('IPYKERNEL', 'python3')
connection_file = find_connection_file()
km = KernelManager(kernel_name=IPYKERNEL, connection_file=connection_file)
km能不能构建多租户的kernel,如实现不了有没有其他解决方式

**Comment by abmfy** [comment]
我们的 demo 只是一个简单的演示，因此并没有考虑多用户使用的情况。如果希望在当前 demo 代码的基础上实现多用户，可以添加一个 Jupyter Kernel 池。
需要注意的是，使用 Jupyter Kernel 并不安全，因为代码是直接在当前环境执行的。如果希望实现多用户的 CodeInterpreter，最好使用 Docker 来隔离不同用户之间的环境。

**Comment by wengyuan722** [comment]
docker目前实现了单步执行，多步执行，不知道如何实现保留上一把执行的变量，希望能够分享一下解决思路

**Comment by abmfy** [comment]
如果每轮对话保持一个 docker，应该可以实现变量等执行环境的保持？

**Comment by wengyuan722** [comment]
我参考autogen，会每轮形成一个新的container，可能要看下其他方式

**Comment by wengyuan722** [comment]
notebook的方法直接结合docker，和一次性的确实不好弄

**Comment by ezhishui** [comment]
> 我们的 demo 只是一个简单的演示，因此并没有考虑多用户使用的情况。如果希望在当前 demo 代码的基础上实现多用户，可以添加一个 Jupyter Kernel 池。 需要注意的是，使用 Jupyter Kernel 并不安全，因为代码是直接在当前环境执行的。如果希望实现多用户的 CodeInterpreter，最好使用 Docker 来隔离不同用户之间的环境。

如果面向普通用户，这个成本会很大吧？一个用户一个docker，而且还存在用户上下文的问题需要绑定一个docker一段时间（这样就要考虑docker的释放机制），这个用户多的话有么有什么好办法能优化呢？
