### ISSUE TITLE
system人设

### ISSUE THREAD

**Issue by ZTurboX** [THUDM/ChatGLM3#207]
system设置人设后，还是会回答chatglm3等内容

**Comment by zRzRzRzRzRzRzR** [comment]
这是正常的，如果要彻底不回答，需要进行微调

**Comment by zRzRzRzRzRzRzR** [comment]
你可以设置回复语气， 但是靠提示词无法完全屏蔽glm3的回答，如果你需要彻底洗掉glm3的介绍，必须微调
