### ISSUE TITLE
想让模型具有多跳思维能力，应该如何构造数据去训练？

### ISSUE THREAD

**Issue by minmie** [THUDM/ChatGLM3#209]
假如有如下两个场景：
1.用户问今天天气如何->模型去查询天气并回答
2. 用户问今天出门需要带伞吗？->模型查询天气->模型给出答案需要带伞

如上，如何让模型具有第二个场景这种多跳的思维能力？

**Comment by zRzRzRzRzRzRzR** [comment]
用连续对话数据进行微调
你需要自己设计这样的数据并按照我们Prompt.md中的提示词进行微调获得更好的效果
