### ISSUE TITLE
工具调用具体执行API/函数的代码在哪里？

### ISSUE THREAD

**Issue by ZSCDumin** [THUDM/ChatGLM3#21]

**Comment by Btlmd** [comment]
我们更新了更为完善的 Demo，可以参考 [综合 Demo](https://github.com/THUDM/ChatGLM3/tree/main/composite_demo) 中 [tool_registry.py](https://github.com/THUDM/ChatGLM3/blob/main/composite_demo/tool_registry.py) 的实现。
