### ISSUE TITLE
对于多轮对话数据格式感到困惑，希望能加一个具体的说明示例，感谢！（现有的这个示例连接，看了后更困惑）

### ISSUE THREAD

**Issue by huwen2117** [THUDM/ChatGLM3#210]
如题，对于多轮对话数据格式感到困惑，希望能加一个具体的说明示例，感谢！（现有的这个示例连接，看了后更困惑）

**Comment by zRzRzRzRzRzRzR** [comment]
微调的么

**Comment by zRzRzRzRzRzRzR** [comment]
建议放在讨论区讨论这个问题，该问题不属于issue问题，目前官方也暂时没有推出示例的计划，如有，github文档会进行更新。敬请期待。
