### ISSUE TITLE
求问， 想在P-Tuning v2 微调的 输入输出中 添加history，应该如何设置格式？

### ISSUE THREAD

**Issue by Magicsmx** [THUDM/ChatGLM3#215]
对于输入-输出格式，样例采用如下输入格式：
[
  {
    "prompt": "<prompt text>",
    "response": "<response text>"
  }
  // ...
]

我想像chatglm2-6b 微调那样在json中添加history_column，
我的样式设置如下：但好像训练出的模型没什么效果
[
    {
        "prompt": "<prompt text>",
        "response": "<response text>",
        "history": [
            {
                "role": "user",
                "content": "text"
            },
            {
                "role": "assistant",
                "content": "text"
            }
        ]
    }
]
finetune中貌似没有处理history的代码，请问input-output训练模式是否支持这种格式的训练？感谢。

**Comment by zRzRzRzRzRzRzR** [comment]
![图片](https://github.com/THUDM/ChatGLM3/assets/93239683/2b2f0dd6-619c-4698-81eb-4b54fd56f6d9)

这一段conversation是可以叠加的，就是历史
