### ISSUE TITLE
单条提示语推理没问题，多条提示语批量推理时文末不能正常结束。

### ISSUE THREAD

**Issue by yxh6067** [THUDM/ChatGLM3#216]
![image](https://github.com/THUDM/ChatGLM3/assets/74161805/26997bbb-77ca-4466-8067-f672ccbc7c74)
![image](https://github.com/THUDM/ChatGLM3/assets/74161805/f4ce6071-4936-4703-984b-388c67e96165)
代码完全相同的情况下：
      进行单条提示语预测时，效果几乎和官方一样
      进行批量预测时，效果明显下降，并且不能以正常的结尾结束
想知道这是为什么。。。

**Comment by zRzRzRzRzRzRzR** [comment]
这个问题不是官方的代码提供的，您可以在Discussion提出讨论，大家看看有没有提升方案
