### ISSUE TITLE
多 Function 调用要怎么实现呢

### ISSUE THREAD

**Issue by AllernChen** [THUDM/ChatGLM3#217]
我想实现多多 Function 调用，open ai可用用response.tool_calls查看调用的tool和结果，glm3我看是直接返回一个结构体{“name”:xx,"parameters":xx}

**Comment by zRzRzRzRzRzRzR** [comment]
您是想要单次对话调用多个工具（同时），还是能够以cot的方式连续调用多个工具，但是每次只调用一个
