### ISSUE TITLE
请问两张3060显卡下最大能支持多少用户同时使用

### ISSUE THREAD

**Issue by yanshuilong** [THUDM/ChatGLM3#218]
请问两张NVIDIA3060显卡（12G）运行ChatGLM3最大能支持多少个用户同时使用，怎么调整优化。另外GLM3能在vLLM上运行了吗，如果能这种方案是优选吗？

**Comment by zRzRzRzRzRzRzR** [comment]
我们还在适配vLLM，后续我们将推出相关的文档
目前，在没有vLLM的支持下，两张显卡走模型并行，能达到的回答上限用户数量并没有明确的数字。由于我们没有测过该显卡的并发量，我们并不能给出负责任的预估，因此无法回答这个问题。
在硬件不变的情况下，一种可行的方法是自行复现模型推理并使用TensorRT-LLM来加速模型的推理。这样将能大幅度提升模型的推理速度。
感谢你的提问

**Comment by yanshuilong** [comment]
好的，谢谢，期待后续版本的更新。
