### ISSUE TITLE
PyTorch版本对推理性能的影响具体是在哪些方面？

### ISSUE THREAD

**Issue by mockyd** [THUDM/ChatGLM3#22]
萌新~请教各位大佬，我看到文档中说需要torch2.0以上达到最佳推理性能，请问是体现在速度方面吗？会不会影响模型的推理效果呢？
谢谢大佬们！

**Comment by duzx16** [comment]
主要是 PyTorch 2.0 以后的版本才有 Flash Attention实现，会影响 attention 的速度和显存占用， 不会影响结果。
