### ISSUE TITLE
本地部署 chatglm3 6B， api 官方案列，关闭流式回复就出错

### ISSUE THREAD

**Issue by YunFenLei** [THUDM/ChatGLM3#220]
OS： Ubuntu 22.04.2 LTS
GPU: 3090 
描述：按照官方指导部署在本地，
以下为示例代码：
import openai
if __name__ == "__main__":
    openai.api_base = "http://192.168.100.118:8000/v1"
    openai.api_key = "none"
    for chunk in openai.ChatCompletion.create(
        model="chatglm3-6b",
        messages=[
            {"role": "user", "content": "李焕英"}
        ],
        stream=False
    ):
        if hasattr(chunk.choices[0].delta, "content"):
            print(chunk.choices[0].delta.content, end="", flush=True)

如果   stream=True  那回复内容正常。
如果    stream=False
就会出错,信息如下：

Traceback (most recent call last):
  File "D:\python提交到qingyingkj\ooo.py", line 12, in <module>
    if hasattr(chunk.choices[0].delta, "content"):
AttributeError: 'str' object has no attribute 'choices'

**Comment by zRzRzRzRzRzRzR** [comment]
mark，我们关注一下

**Comment by zRzRzRzRzRzRzR** [comment]
没有办法复现出来，我们已经测试了这个接口，能够返回stream为false的情况，为完整的一句。
传入内容如下：
```
data = {
        "model": model,
        "messages": messages,
        "stream": False,
        "temperature": 0.8,
        "top_p": 0.8,
    }
```
执行请求：
```
python try_openai.py

{'model': 'gpt-3.5-turbo', 'object': 'chat.completion', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': '\n 从前有个美丽的村庄，里面住着一个勇敢善良的少年。他叫小明，为人正直，乐于助人。使得村民们生活陷入困境，缺乏水源和食物。\n\n为了拯救村子，小明决定冒险爬上山去寻找其他水源。经过几天的艰苦努力，他终于找到了一条清澈见底的小溪。他带着水回到村子，将水井填满，解决了村民们的饮水问题。同时，他还tion_call': None}, 'finish_reason': 'stop'}], 'created': 1699597387, 'usage': {'prompt_tokens': 54, 'total_tokens': 216, 'completion_tokens': 162}}
```

**Comment by zRzRzRzRzRzRzR** [comment]
如果存在更多问题，请按照issue模板提交最小复现代码，本issue已经关闭

**Comment by YunFenLei** [comment]
> 如果存在更多问题，请按照issue模板提交最小复现代码，本issue已经关闭

import openai
if name == "main":
openai.api_base = "http://192.168.100.118:8000/v1"
openai.api_key = "none"
for chunk in openai.ChatCompletion.create(
model="chatglm3-6b",
messages=[
{"role": "user", "content": "李焕英"}
],
stream=False
):
if hasattr(chunk.choices[0].delta, "content"):
print(chunk.choices[0].delta.content, end="", flush=True)


以上为我构建在py里的全部内容

**Comment by wanglaiqi** [comment]
如果关闭流式输出的话需要修改一下代码，下面是非流式输出的代码：

`def openai_infer():
    response = openai.ChatCompletion.create(
        model="string",
        messages=[{"role": "user", "content": "中国大蒜之乡是哪里?"}],
        do_sample=True,
        top_p=0,
        stream=False)
    print(response.choices[0].message.content)`
