### ISSUE TITLE
分词&输出格式问题

### ISSUE THREAD

**Issue by TheLolita** [THUDM/ChatGLM3#224]
1.我使用的是chatglm3 全量微调input-output格式：
首条打印信息为
![image](https://github.com/THUDM/ChatGLM3/assets/59789293/e8d53339-a780-4635-85ba-a2625f747737)
我想知道这条打印信息是对的吗，我看给出的示例是这样的：
![image](https://github.com/THUDM/ChatGLM3/assets/59789293/a775a6e0-2bc9-453b-a309-f7a546fede17)
标红的是多轮对话形式才有的吗

2.我调出来的结果跟我训练语料中限定的输出格式完全不一样，现在的输出格式很多时候会出现
{"name":"", "content":""}这样的形式，而name和content在我的训练语料中完全不存在

**Comment by TheLolita** [comment]
还有一个问题是输出会重复，![image](https://github.com/THUDM/ChatGLM3/assets/59789293/432264d8-5113-47e3-9cb0-aaa64c6e57d3)

**Comment by zRzRzRzRzRzRzR** [comment]
@Btlmd 能帮忙看一下第一个问题么
第二个问题，我们想知道以下使用的是原始模型还是微调模型，使用的是官方框架吗

**Comment by nlp4whp** [comment]
缺system和assistant应该是数据里少了`{'role': 'system'}`和`{'role': 'assistant'}`的`item`吧

**Comment by zRzRzRzRzRzRzR** [comment]
建议加入系统提示，就跟openai一样，可以没有，但是有更好

**Comment by Btlmd** [comment]
> 1.我使用的是chatglm3 全量微调input-output格式： 首条打印信息为 ![image](https://user-images.githubusercontent.com/59789293/281441917-e8d53339-a780-4635-85ba-a2625f747737.png) 我想知道这条打印信息是对的吗，我看给出的示例是这样的： ![image](https://user-images.githubusercontent.com/59789293/281442218-a775a6e0-2bc9-453b-a309-f7a546fede17.png) 标红的是多轮对话形式才有的吗
> 
> 2.我调出来的结果跟我训练语料中限定的输出格式完全不一样，现在的输出格式很多时候会出现 {"name":"", "content":""}这样的形式，而name和content在我的训练语料中完全不存在

1. 看起来是正确的。输入输出格式中没有添加 special tokens。这些 角色的 special token 是对话模式才有的
2. 是否可以给一些意外出现 name & content 的输入输出的具体例子和微调时训练语料输入输出的例子？

**Comment by Btlmd** [comment]
> 还有一个问题是输出会重复，![image](https://user-images.githubusercontent.com/59789293/281590045-432264d8-5113-47e3-9cb0-aaa64c6e57d3.png)

是所有 prompt 都出现重复无法停止，还是只有某些问题？对于 finetune 后的模型，如果遇到与训练分布差异很大的 prompt，模型就很容易重复
