### ISSUE TITLE
strongly need chatglm3-6b int4 version

### ISSUE THREAD

**Issue by Mrfranken** [THUDM/ChatGLM3#226]
hi team, I would like to ask if there is any chance to release an int4 version?  I've tried many way to quantize your models to int4, but all of them failed.

Br,
Vince

**Comment by zRzRzRzRzRzRzR** [comment]
We are sorry to inform you that at this time, we have no plans to release an official int4 version of the model, so please stay tuned to our project. We will update github and huggingface as soon as a new model is released!
You can follow the readme to quantize your own model for the time being.
