### ISSUE TITLE
发么用代码执行（Code Interpreter）

### ISSUE THREAD

**Issue by 245680** [THUDM/ChatGLM3#23]
如题

**Comment by Btlmd** [comment]
我们更新了更为完善的 Demo，可以参考 [ChatGLM3 对话格式](https://github.com/THUDM/ChatGLM3/blob/main/PROMPT.md)  和 [综合 Demo](https://github.com/THUDM/ChatGLM3/tree/main/composite_demo) 中对 Code Interpreter 的实现。
