### ISSUE TITLE
有权威的、支持function call的模型榜单吗

### ISSUE THREAD

**Issue by DryPilgrim** [THUDM/ChatGLM3#234]
1. 如题, 对于function call, 各个论文中的测评数据和方法都不一样，有权威的测评吗？
2. 如果没有权威的榜单，现有的主流测评方法有哪些呀？
非常感谢您的解答：）

**Comment by zRzRzRzRzRzRzR** [comment]
暂时没有针对这一个能力的榜单，不过确实有Agent 榜单
国内的Agent榜单 主流的例如[SuperCLUE-Agent](https://github.com/CLUEbenchmark/SuperCLUE-Agent)
AgentBench(https://llmbench.ai/agent/data)
