### ISSUE TITLE
function calling问题

### ISSUE THREAD

**Issue by lzw12138** [THUDM/ChatGLM3#240]
在官方例子中，天气的tool，我输入今天天气怎么样，他把天气当作城市参数了。有木有办法固定参数的范围阿，比如我就指定参数只能输出北京/上海/武汉，其他的城市都输出null，这个怎么写呢

**Comment by zRzRzRzRzRzRzR** [comment]
修改工具的实现而不是修改调用工具
例如，当传入的参不是北京上海的时候工具实现返回大模型null 大模型在转告给用户
