### ISSUE TITLE
对txt文本文件微调

### ISSUE THREAD

**Issue by YLongJin** [THUDM/ChatGLM3#241]
请问，如果我想对三国演义这本书进行微调，我该怎么做呢

**Comment by minmie** [comment]
你们真的是一点代码都不懂吗

**Comment by YLongJin** [comment]
@minmie 请问要怎么做呢

**Comment by minmie** [comment]
先明确你想做什么事，再根据微调文档针对性训练

**Comment by YLongJin** [comment]
@minmie 我想训练三国演义这种txt格式的，不是对话形式，把知识库训练到模型里面去

**Comment by zRzRzRzRzRzRzR** [comment]
非对话形式不能再chat模型上微调
你必须先对文本去构造对话，例如根据某一章节构造数十个或者几百个对话
另外，你这种情况最好使用知识库来完成任务
