### ISSUE TITLE
针对function call的对齐数据和评估方法

### ISSUE THREAD

**Issue by DryPilgrim** [THUDM/ChatGLM3#245]
1. 为什么[A](https://github.com/THUDM/ChatGLM3/blob/9367637114dc8ba43192b16653f9cad39c50ea46/finetune_demo/README.md#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F%E5%92%8C%E9%A2%84%E5%A4%84%E7%90%86)的role和[B](https://github.com/THUDM/ChatGLM3/blob/9367637114dc8ba43192b16653f9cad39c50ea46/PROMPT.md#%E5%B7%A5%E5%85%B7%E8%B0%83%E7%94%A8)的role的命名不一样呀？其角色分别为（system、user、assistant、tool）和（system、user、assistant、observation）.

2. chat、function call和code对齐数据格式不一样，为什么[finetune_demo](https://github.com/THUDM/ChatGLM3/blob/9367637114dc8ba43192b16653f9cad39c50ea46/finetune_demo/README.md#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F%E5%92%8C%E9%A2%84%E5%A4%84%E7%90%86)里只有一种格式的微调数据？

3. 我想要自己快速对齐一个模型的function call的能力，我应该怎么做？有具体的资源推荐吗？（针对function call对齐数据的构建和评估方法）

**Comment by zRzRzRzRzRzRzR** [comment]
问题一解答：
1. 在训练代码中，tools角色是工具，接下来的内容是工具传入的参数，你会发现这里面有observation
2. 在推理代码中，模型会自动输出tool_use，然后根据提示词（注册工具后）自己选择对应的模型，tool_use是模型自己输出的，还需要外挂截断点才能正常使用tool，然后得到<observation>
问题二解答：
这一种格式的数据集就能微调chat Function call两种，目前没有开放code微调
问题三不方便解答，因为我们的技术报告尚未公开

**Comment by xxllp** [comment]
不知道技术报告啥时候公开呢

**Comment by zRzRzRzRzRzRzR** [comment]
公开后会第一时间更新github上的公告，敬请期待
