### ISSUE TITLE
在client.py中的self.model = AutoModel.from_pretrained(model_path, trust_remote_code=True)后面加.float()后，demo直接被kill掉

### ISSUE THREAD

**Issue by hhk1994** [THUDM/ChatGLM3#246]
### System Info / 系統信息

python==3.10, transformer==4.30.2

### Who can help? / 谁可以帮助到您？

@abmfy

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

如题，加float()是为了解决跑composite demo的时候出现的addmm_impl_cpu_" not implemented for 'Half'报错。但是加了float()之后demo直接被kill掉。

### Expected behavior / 期待表现

如题，加float()是为了解决跑composite demo的时候出现的addmm_impl_cpu_" not implemented for 'Half'报错。但是加了float()之后demo直接被kill掉。请问是什么原因呢？

**Comment by zRzRzRzRzRzRzR** [comment]
mark，正在解决，您可以查看一下是否与之前的issue中的问题类似，我们方便一起定位

**Comment by hhk1994** [comment]
您好，我的问题与 issue #177 相关，算是这个issue的后续问题。

**Comment by Btlmd** [comment]
请问您的操作系统是什么？内存有多道？这个被 kill 掉有什么具体表现吗？有没有可能是 .float() 之后内存不足导致被 kill?

**Comment by zRzRzRzRzRzRzR** [comment]
在client,py中的self.model = AutoModel.from_pretrained(model_path, trust remote_code=True)后面加.float()后
demo直接被kill掉，应该是内存不足被kill了

**Comment by hhk1994** [comment]
好的谢谢，已解决

**Comment by chenqihui** [comment]
> 好的谢谢，已解决

WARNING:root:Some parameters are on the meta device device because they were offloaded to the cpu and disk.
已杀死

是这种情况么？请问你咋解决的？
