### ISSUE TITLE
基于base微调的输入format问题

### ISSUE THREAD

**Issue by nlp4whp** [THUDM/ChatGLM3#252]
您好，我想确认下：

1. finetune的示例代码是和`chatglm3`的chat保持格式一致，用同样格式微调，就可以复用chat方法
2. 但`chatglm3-base`是**没有经过chat格式训练过的**，因此我可以沿用chat格式，也可以自定义其他格式（不用user, system这些）
3. 如果2我理解的没错，那获得`-base`的预训练阶段应该是只用了`eos_token_id`这一个special_tokens，是这样嘛?

**Comment by zRzRzRzRzRzRzR** [comment]
官方暂时还不提供基于base微调的技术报告，我们只有基于chat微调的方案，base方案需要你自行参考其他的开源方案尝试。
你可以在Discussion中与其他用户进行讨论，该issue关闭，望理解。
