### ISSUE TITLE
从调用OPENAI_API_KEY转投调用本地ChatGLM3

### ISSUE THREAD

**Issue by danfouer** [THUDM/ChatGLM3#255]
### Feature request  / 功能建议

从调用OPENAI_API_KEY转投调用本地ChatGLM3遇到不知如何通讯的困难

### Motivation / 动机

我之前参考[用chatgpt来整理录音转文字后的内容（编程小白版）](https://zhuanlan.zhihu.com/p/632719633?utm_id=0)实现了了一个调用OPENAI_API_KEY整理逐字稿的任务，现在我在本地通过运行openai_api.py部署了ChatGLM3，然后参考
LLM_MODEL = "gpt-3.5-turbo"
API_KEY = 'sk-PjDisw70wxoSRoiFB4A6B11693614251A6C59825D06631E0'   # 随意设定一个key
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions":"http://127.0.0.1:8000/v1/chat/completions"}  # 注意端口号
将调用OPENAI_API_KE的代码openai.api_key  = os.getenv('OPENAI_API_KEY')后面加了一句
openai.api_url_redirect = {"https://api.openai.com/v1/chat/completions":"http://127.0.0.1:8000/v1/chat/completions"} ，代码没有报错，但是仍然调用OPENAI_API_KEY来执行任务

我想知道怎么从调用OPENAI_API_KEY转投调用本地ChatGLM3

### Your contribution / 您的贡献

https://github.com/danfouer

**Comment by zRzRzRzRzRzRzR** [comment]
这个key无意义，你直接写xx应该就行？

**Comment by danfouer** [comment]
> 这个key无意义，你直接写xx应该就行？

我的openai.api_key = os.getenv('OPENAI_API_KEY')是对的，我是希望openai.api_url_redirect = {"[https://api.openai.com/v1/chat/completions":"http://127.0.0.1:8000/v1/chat/completions"}]这句能起作用，但是没作用，还是转到openAI 去了 我参考的是这个https://github.com/binary-husky/gpt_academic/wiki/%E9%80%82%E9%85%8DRWKV-Runner

**Comment by zRzRzRzRzRzRzR** [comment]
哦那肯定不行啊url都错了，要直接把https改成glm的

**Comment by danfouer** [comment]
> 哦那肯定不行啊url都错了，要直接把https改成glm的

具体怎么改，能给个例子吗？

**Comment by zRzRzRzRzRzRzR** [comment]
最新的官方代码给出了一个示例请求的py文件
