### ISSUE TITLE
输出无限循环或者输出文章不完整，或者一篇文章不输出直接下一篇文章

### ISSUE THREAD

**Issue by wxchjay** [THUDM/ChatGLM3#262]
### System Info / 系統信息

python3.8.5
NVIDIA-SMI 535.86.05
Driver Version: 535.86.05
CUDA Version: 12.2
model：chatglm3-6b-32k，chatglm3-6b

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用cli_demo.py，进行批量生成文章的时候，会出现输出死循环或者重复语句及只生成一句话结束问题出现，大约1000篇文章里面会出现10次这类错误
![3d0300462363a2b32ea514e4df05b36](https://github.com/THUDM/ChatGLM3/assets/150489977/626412da-eff1-438d-b208-cc5463b45646)
![be8e733c9852098bc0422337284d75b](https://github.com/THUDM/ChatGLM3/assets/150489977/baf04a21-8ff2-4cc4-858e-e291abdb19bf)
![RM`B)GTKSR`U}E4YMN7I RX](https://github.com/THUDM/ChatGLM3/assets/150489977/a07fe454-fb99-48db-bad4-771d8629f9bb)
![Q5YOM9VU $FGWDDANFTD~HR](https://github.com/THUDM/ChatGLM3/assets/150489977/08fe60cc-374a-4cf3-9c1e-b3c4177d32e7)
![T1J7SLFH LIFHS6}%XEHVO7](https://github.com/THUDM/ChatGLM3/assets/150489977/594c0ac7-6ee2-4c26-ab19-ce6504f6b03c)

### Expected behavior / 期待表现

正常输出！

**Comment by wxchjay** [comment]
![图片](https://github.com/THUDM/ChatGLM3/assets/150489977/ae4a3004-4cee-40d4-b67d-eb3c0dc76e55)

**Comment by zRzRzRzRzRzRzR** [comment]
mark

**Comment by wxchjay** [comment]
> mark

请问cli_demo.py里面并没有：top p、惩罚系数该如何来搞？

**Comment by zRzRzRzRzRzRzR** [comment]
在这里修改代码并传入top_p
![图片](https://github.com/THUDM/ChatGLM3/assets/93239683/ce75f3ca-4fbe-450d-9d06-708fd1c7cfc1)
cli_demo确实没有repetition_penalty，这个参数在openai_demo中有实现

**Comment by wxchjay** [comment]
> 在这里修改代码并传入top_p ![图片](https://user-images.githubusercontent.com/93239683/282993673-ce75f3ca-4fbe-450d-9d06-708fd1c7cfc1.png) cli_demo确实没有repetition_penalty，这个参数在openai_demo中有实现

请问这个图片里面是加在哪个位置上

**Comment by zRzRzRzRzRzRzR** [comment]
```
for response, history, past_key_values in model.stream_chat(tokenizer, query, history=history,
                                                                    past_key_values=past_key_values,
                                                                    return_past_key_values=True):
```
在这里，加上top p

**Comment by wxchjay** [comment]
> ```
> for response, history, past_key_values in model.stream_chat(tokenizer, query, history=history,
>                                                                     past_key_values=past_key_values,
>                                                                     return_past_key_values=True):
> ```
> 
> 在这里，加上top p

能不能发我下 图片里面的这段代码我直接复制黏贴上去。。

**Comment by wxchjay** [comment]
> ```
> for response, history, past_key_values in model.stream_chat(tokenizer, query, history=history,
>                                                                     past_key_values=past_key_values,
>                                                                     return_past_key_values=True):
> ```
> 
> 在这里，加上top p

![图片](https://github.com/THUDM/ChatGLM3/assets/150489977/19db9f3d-14aa-46ab-8a5a-87faee11849e)
这段代码

**Comment by zRzRzRzRzRzRzR** [comment]
```
for response, history, past_key_values in model.stream_chat(tokenizer, query, history=history, top_p=1,
                                                                    temperature=0.01,
                                                                    past_key_values=past_key_values,
                                                                    return_past_key_values=True):
```
举一个例子，cli只能做到这样目前，如果遇到相关问题，请到讨论区，我们会记录下讨论区的问题，请记得提供最小代码，提示词并稳定复现的例子，这将能帮助我们改善模型

**Comment by wxchjay** [comment]
> ```
> for response, history, past_key_values in model.stream_chat(tokenizer, query, history=history, top_p=1,
>                                                                     temperature=0.01,
>                                                                     past_key_values=past_key_values,
>                                                                     return_past_key_values=True):
> ```
> 
> 举一个例子，cli只能做到这样目前，如果遇到相关问题，请到讨论区，我们会记录下讨论区的问题，请记得提供最小代码，提示词并稳定复现的例子，这将能帮助我们改善模型

更新到最新代码，还是发现此类问题
