### ISSUE TITLE
使用苹果芯片的Mac本地部署出现报错

### ISSUE THREAD

**Issue by lsmegranate** [THUDM/ChatGLM3#265]
### Feature request  / 功能建议

如题，使用 mps 后端：

model = AutoModel.from_pretrained("your local path", trust_remote_code=True).to('mps')

后，虽然可以运行，但是会出现下面报错，看是否有优化方法。

loc("mps_matmul"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/75428952-3aa4-11ee-8b65-46d450270006/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":39:0)): error: 'anec.matmul' op Invalid configuration for the following reasons: Tensor dimensions N1D1C4096H1W27392 are not within supported range, N[1-65536]D[1-16384]C[1-65536]H[1-16384]W[1-16384].

### Motivation / 动机

希望模型能在更多本地环境运行调试。

### Your contribution / 您的贡献

暂无。

**Comment by longxtx** [comment]
Apple M2 Max 已经部署成功，正常都能跑通，几乎未做修改。部署前需要先要按下面的指示执行PyTorch的操作
https://developer.apple.com/metal/pytorch/

**Comment by sept31** [comment]
> ### Feature request / 功能建议
> 如题，使用 mps 后端：
> 
> model = AutoModel.from_pretrained("your local path", trust_remote_code=True).to('mps')
> 
> 后，虽然可以运行，但是会出现下面报错，看是否有优化方法。
> 
> loc("mps_matmul"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/75428952-3aa4-11ee-8b65-46d450270006/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":39:0)): error: 'anec.matmul' op Invalid configuration for the following reasons: Tensor dimensions N1D1C4096H1W27392 are not within supported range, N[1-65536]D[1-16384]C[1-65536]H[1-16384]W[1-16384].
> 
> ### Motivation / 动机
> 希望模型能在更多本地环境运行调试。
> 
> ### Your contribution / 您的贡献
> 暂无。

M2 Pro 上出现同样错误 ，即使按照 https://developer.apple.com/metal/pytorch/ 更新了相应库也是一样。模型可以运行，但是仍然报这个错
