### ISSUE TITLE
Function calling 返回tool时解析错误

### ISSUE THREAD

**Issue by tanyinyan** [THUDM/ChatGLM3#27]
当识别到某个tool时，直接输出了tool名字，没有\n，导致split出错！
![image](https://github.com/THUDM/ChatGLM3/assets/11512384/8a16aaa7-197e-49cf-9ced-7f95e010cee2)

**Comment by mMrBun** [comment]
你好，我这边在跑官方示例，我这边response一直是str不是dict，你是用的cli_demo的示例代码吗？

**Comment by mMrBun** [comment]
下面是我自己定的tool测试时模型返回内容



```bash
您可以使用以下API来查询北京的天气：

https://api.openweathermap.org/data/2.5/weather?q=Beijing&appid=YOUR_API_KEY


请将`YOUR_API_KEY`替换为您的OpenWeatherMap API密钥。您可以通过购买API密钥或使用免费试用来获得API密钥。

API响应将包括以下信息：

- location: 北京的英文名称
- country: 中国
- date: 查询当天的日期
- main: 天气主标签，包括温度、降水概率、风速等
- weather: 天气现象的列表
- city: 北京的中文名称
- sunrise: 查询当天的日出时间
- sunset: 查询当天的日落时间
- temperature: 查询当天的最高温度和最低温度
- feel_temp: 查询当天的感觉温度
- wind_direction: 查询当天的风向
- wind_speed: 查询当天的风力大小

您可以根据需要解析这些信息。
```

**Comment by tanyinyan** [comment]
> 你好，我这边在跑官方示例，我这边response一直是str不是dict，你是用的cli_demo的示例代码吗？

试了一下，应该是stream_chat现在还不支持function calling。
前面截图用的model.stream_chat，返回的是str，所以解析错误。换成model.chat，可以返回dict了。

**Comment by mMrBun** [comment]
> > 你好，我这边在跑官方示例，我这边response一直是str不是dict，你是用的cli_demo的示例代码吗？
> 
> 试了一下，应该是stream_chat现在还不支持function calling。 前面截图用的model.stream_chat，返回的是str，所以解析错误。换成model.chat，可以返回dict了。

我之前用的32k的模型，不行，换成8k的就好了

**Comment by duzx16** [comment]
因为工具调用的结果需要在生成内容的基础上做一些后处理，所以不能支持流式输出。
32K 模型的主要使用场景是长文档问答，所以没有进行工具调用的训练。
