### ISSUE TITLE
推理时的外挂阶段点

### ISSUE THREAD

**Issue by DryPilgrim** [THUDM/ChatGLM3#275]
问题一解答：
1. 在训练代码中，tools角色是工具，接下来的内容是工具传入的参数，你会发现这里面有observation
2. 在推理代码中，模型会自动输出tool_use，然后根据提示词（注册工具后）自己选择对应的模型，tool_use是模型自己输出的，还需要外挂截断点才能正常使用tool，然后得到<observation>

问题二解答：
这一种格式的数据集就能微调chat Function call两种，目前没有开放code微调

问题三不方便解答，因为我们的技术报告尚未公开

_Originally posted by @zRzRzRzRzRzRzR in https://github.com/THUDM/ChatGLM3/issues/245#issuecomment-1806660788_

**Comment by DryPilgrim** [comment]
1. 没有理解 **问题一解答的第2点** TnT
2. 请问**外挂截断点**是什么意思呀

**Comment by zRzRzRzRzRzRzR** [comment]
了解到请求
1. tool_use 这一个关键词，大模型在输出工具的时候一定会出现 tool_use 这个关键词
外挂截断点就是对这里进行截断，意味着要调用工具了，在这边截断大模型的输出
工具调用结束后，会自己接上一个observation作为观察结果
