### ISSUE TITLE
【请教问题】多轮对话，不用tools的数据格式是怎么样的？

### ISSUE THREAD

**Issue by echoht** [THUDM/ChatGLM3#277]
### System Info / 系統信息

【请教问题】多轮对话，不用tools的数据格式是怎么样的？

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

demo例子

**Comment by zRzRzRzRzRzRzR** [comment]
把tools的内容删掉就行了，然后接着写user assistent

**Comment by zRzRzRzRzRzRzR** [comment]
![图片](https://github.com/THUDM/ChatGLM3/assets/93239683/7aebb5fb-d4a1-499b-bcf3-39c1775e5c2c)
如上，system可选

**Comment by echoht** [comment]
@zRzRzRzRzRzRzR 感谢！

每种角色可以附带一个 bool 类型的 loss 字段，表示该字段所预测的内容是否参与 loss 计算。若没有该字段，样例实现中默认对 system, user 不计算 loss，其余角色则计算 loss。

**Comment by zRzRzRzRzRzRzR** [comment]
可以这么理解
