### ISSUE TITLE
能不能一个应用同时运行webdeom和openapi.deom

### ISSUE THREAD

**Issue by hhtao** [THUDM/ChatGLM3#278]
### Feature request  / 功能建议

能不能一个应用同时运行webdeom和openapi.deom
请高手指点一下

### Motivation / 动机

能不能一个应用同时跑webdeom和openapi.deom
请高手指点一下

### Your contribution / 您的贡献

能不能一个应用同时跑webdeom和openapi.deom
请高手指点一下

**Comment by zRzRzRzRzRzRzR** [comment]
在官方代码中不行，如果您要基于此二次开发，您可以在社群内寻求帮助
