### ISSUE TITLE
多卡微调失败

### ISSUE THREAD

**Issue by cui-z** [THUDM/ChatGLM3#281]
### System Info / 系統信息

python3.10  单机双卡3090
多卡微调修改了NUM_GPUS=2  报超时的错误
![image](https://github.com/THUDM/ChatGLM3/assets/58731051/0978a8df-2304-451e-998b-675c211b5dc3)

### Who can help? / 谁可以帮助到您？

@B

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/THUDM/ChatGLM3/assets/58731051/7f90b3ef-1ad9-4c48-be2d-d5b48a6ce9d0)

### Expected behavior / 期待表现

解决一下这个问题

**Comment by Yuang-Deng** [comment]
用deepspeed试试？

**Comment by zzutligang** [comment]
请教一下，你的微调脚本用的是哪个？数据格式是什么样的？我看ChatGLM3没有提供微调工具脚本。

**Comment by Btlmd** [comment]
请问您使用了哪个微调脚本？

> ### System Info / 系統信息
> python3.10 单机双卡3090 多卡微调修改了NUM_GPUS=2 报超时的错误 ![image](https://user-images.githubusercontent.com/58731051/282380078-0978a8df-2304-451e-998b-675c211b5dc3.png)
> 
> ### Who can help? / 谁可以帮助到您？
> @b
> 
> ### Information / 问题信息
> * [x]  The official example scripts / 官方的示例脚本
> * [ ]  My own modified scripts / 我自己修改的脚本和任务
> 
> ### Reproduction / 复现过程
> ![image](https://user-images.githubusercontent.com/58731051/282380054-7f90b3ef-1ad9-4c48-be2d-d5b48a6ce9d0.png)
> 
> ### Expected behavior / 期待表现
> 解决一下这个问题

**Comment by Btlmd** [comment]
> 请教一下，你的微调脚本用的是哪个？数据格式是什么样的？我看ChatGLM3没有提供微调工具脚本。

目前在 [finetune_demo](https://github.com/THUDM/ChatGLM3/tree/main/finetune_demo) 中提供了微调示例

**Comment by cui-z** [comment]
> 请问您使用了哪个微调脚本？
> 
> > ### System Info / 系統信息
> > python3.10 单机双卡3090 多卡微调修改了NUM_GPUS=2 报超时的错误 ![image](https://user-images.githubusercontent.com/58731051/282380078-0978a8df-2304-451e-998b-675c211b5dc3.png)
> > ### Who can help? / 谁可以帮助到您？
> > @b
> > ### Information / 问题信息
> > 
> > * [x]   The official example scripts / 官方的示例脚本
> > * [ ]   My own modified scripts / 我自己修改的脚本和任务
> > 
> > ### Reproduction / 复现过程
> > ![image](https://user-images.githubusercontent.com/58731051/282380054-7f90b3ef-1ad9-4c48-be2d-d5b48a6ce9d0.png)
> > ### Expected behavior / 期待表现
> > 解决一下这个问题

你好 用的finetune_pt.sh  把里面gpu_nums改成了我这里卡的数量 单机多卡

**Comment by Btlmd** [comment]
`finetune_pt.sh` 确实没有在多卡上测试过。试着加上 `--deepspeed configs/deepspeed.json` 看看能不能 work？

**Comment by cui-z** [comment]
> `finetune_pt.sh` 确实没有在多卡上测试过。试着加上 `--deepspeed configs/deepspeed.json` 看看能不能 work？

您好 我试了 还是报同样的问题 感觉是GPU之间通信的问题

**Comment by yhyu13** [comment]
用Lightning Ai Fabric包一下吧，这个很好用

**Comment by shenmadouyaowen** [comment]
同错

**Comment by cui-z** [comment]
> 同样的问题，你们解决了吗？怎么解决的？

没有解决呢

**Comment by cui-z** [comment]
> 用Lightning Ai Fabric包一下吧，这个很好用

你好 你已经试过了是吧

**Comment by zRzRzRzRzRzRzR** [comment]
该issue暂时无法解决，请在 #310 中提出，Discussion中的微调问题会被加入参考
