### ISSUE TITLE
请问ChatGLM3的微调工具用什么？用ChatGLM2里提供的微调工具吗？

### ISSUE THREAD

**Issue by zzutligang** [THUDM/ChatGLM3#287]
### System Info / 系統信息

ChatGLM3

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

请教

### Expected behavior / 期待表现

请教

**Comment by zRzRzRzRzRzRzR** [comment]
官方提供了微调代码
