### ISSUE TITLE
chatglm3-6b-32k不能实现对tool支持

### ISSUE THREAD

**Issue by wengyuan722** [THUDM/ChatGLM3#29]
发现chatglm3-6b可以跑出json，chatglm3-6b-32k跑不出json

**Comment by davidlvxin** [comment]
当前版本的32K模型主要集中于长文本的问答等场景，我们会在后续增加对于tool的支持~

**Comment by ocheng2005** [comment]
今天跑了一天，发现不行，原来32K不支持，麻烦在readme 说明一下。

**Comment by dayphosphor** [comment]
难受  搞了半天 居然这个版本的不支持。

**Comment by miandai** [comment]
ChatGLM3-6B-32K 不支持 tool 调用，有必要在 Readme 里提醒下，免得更多人踩坑。ps：耗费上午一个多小时时间，没有工具调用，还以为是其它地方问题，排查好一会。

**Comment by zRzRzRzRzRzRzR** [comment]
好的，我们会在下一个版本内完善readme
