### ISSUE TITLE
chatglm3-6b-base AttributeError: can't set attribute

### ISSUE THREAD

**Issue by xiaohangguo** [THUDM/ChatGLM3#290]
### System Info / 系統信息

全量微调以后 tokenizer 和词表好像发生了变化，并且微调后的tokenizer和以往的同名，总之就是用不了，建议修复下
https://github.com/InternLM/xtuner/issues/221#issue-1990824363

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [x] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

微调chatglm3 6b base，然后转为hf的模型，对训练后的模型进行automodel autotokenizer解析

### Expected behavior / 期待表现

希望修改一下tokenizer，还有词表的这些逻辑

**Comment by Btlmd** [comment]
微调后可以直接加载原有的 tokenizer 来避免这个问题；`finetune_demo` 中就是这样实现的。

**Comment by xiaohangguo** [comment]
虽然能这么避开问题，但是微调以后对话模板变了，modeling_chatglm.py在解析的时候会错

**Comment by Btlmd** [comment]
那可能自己重写一个类似 `chat` 的函数来处理输入输出会比较方便

**Comment by shihanmax** [comment]
求问微调为什么会改变tokenizer的行为呢？这个是否合理？

**Comment by sevenandseven** [comment]
> ### System Info / 系統信息
> 全量微调以后 tokenizer 和词表好像发生了变化，并且微调后的tokenizer和以往的同名，总之就是用不了，建议修复下 [InternLM/xtuner#221 (comment)](https://github.com/InternLM/xtuner/issues/221#issue-1990824363)
> 
> ### Who can help? / 谁可以帮助到您？
> _No response_
> 
> ### Information / 问题信息
> * [ ]  The official example scripts / 官方的示例脚本
> * [x]  My own modified scripts / 我自己修改的脚本和任务
> 
> ### Reproduction / 复现过程
> 微调chatglm3 6b base，然后转为hf的模型，对训练后的模型进行automodel autotokenizer解析
> 
> ### Expected behavior / 期待表现
> 希望修改一下tokenizer，还有词表的这些逻辑

请问base模型微调时的数据格式可以提供一下吗？
