### ISSUE TITLE
下载大模型的疑问

### ISSUE THREAD

**Issue by JonSmall** [THUDM/ChatGLM3#293]
### Feature request  / 功能建议

AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
1. 这里是否有方法可以将下载地址指向魔塔社区去下载模型，也就是model_path是否可以更改，而不是从huggingface
2. 如果从魔塔社区下载，下载的地址放在哪里，上面model_path又该如何改，可以加载本地存在的模型，是否可以给个代码例子

### Motivation / 动机

痛点：
1. 默认连huggfaceing去下载
2. 自己下载的模型，不清楚代码该怎么指定这个路径

### Your contribution / 您的贡献

1

**Comment by zyqlerry** [comment]
所以路径问题你是怎么解决的？

**Comment by ROY-SNN** [comment]
求助：加载本地token，路径的问题解决了吗
