### ISSUE TITLE
streamlit run web_demo2.py启动成功后，返回html内容：You need to enable JavaScript to run this app.

### ISSUE THREAD

**Issue by scauwjh** [THUDM/ChatGLM3#294]
### System Info / 系統信息

centos7
conda python10.13

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

按照教程，使用conda环境启动
streamlit run web_demo2.py
结果无法渲染web界面，显示You need to enable JavaScript to run this app.

### Expected behavior / 期待表现

正常启动web ui

**Comment by zRzRzRzRzRzRzR** [comment]
这个是streamlit和操作系统上的适配问题，与框架没有关系
