### ISSUE TITLE
请问有工具的一些文档吗？

### ISSUE THREAD

**Issue by kaixinjiuhao123** [THUDM/ChatGLM3#298]
### Feature request  / 功能建议

请问有工具的一些文档吗？

### Motivation / 动机

有没有工具列表之类的，目前从文档中都无法知道这些工具来自哪里，功能作用是什么？

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
可以查看源码，本github源码上有工具的实现和注册
