### ISSUE TITLE
回答问题时中英文结合

### ISSUE THREAD

**Issue by WageningenKing** [THUDM/ChatGLM3#300]
### System Info / 系統信息

![d2028d56b967ed7e5a6e368f43b132f](https://github.com/THUDM/ChatGLM3/assets/93059562/40e3da40-15b7-4e97-96ff-f4b3bed6db30)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

正常问问题就会出现这个问题。

### Expected behavior / 期待表现

权重文件有所改善。

**Comment by zRzRzRzRzRzRzR** [comment]
mark，这是一个bad case，可以在discussion中创建一个bad case 目前没有太多好的解决方案
