### ISSUE TITLE
openai 接口 是否支持最新的1.2版本？

### ISSUE THREAD

**Issue by bravelll** [THUDM/ChatGLM3#301]
### System Info / 系統信息

openai 接口 是否支持最新的1.2版本

### Who can help? / 谁可以帮助到您？

openai 接口 是否支持最新的1.2版本

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

openai 接口 是否支持最新的1.2版本

### Expected behavior / 期待表现

openai 接口 是否支持最新的1.2版本

**Comment by yyq** [comment]
我在这个 PR https://github.com/THUDM/ChatGLM3/pull/285 更新了一部分支持新版 openai API 的代码，不知道是不是符合你的需求。等作者什么时候 merge 吧

**Comment by zRzRzRzRzRzRzR** [comment]
已经合并，非常感谢你的PR
