### ISSUE TITLE
按照提供的微调脚本运行会报错，错误来源包括调用本地模型路径和训练数据

### ISSUE THREAD

**Issue by zerolovesea** [THUDM/ChatGLM3#302]
### System Info / 系統信息

Python  3.10(ubuntu22.04)
Cuda  11.8
RTX 3090(24GB) 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

@yincf 根据文档中所示的路径下载AdvertiseGen/train.json并修改为prompt/response格式后，训练会报错：scripts/formatted_data/train.json: line 1: [: missing `]'
scripts/formatted_data/train.json: line 235: syntax error: unexpected end of file

同样的，调用本地模型时，如果在脚本里改BASE_MODEL_PATH为模型的相对路径，训练时会报错：It's a directory。
暂时的解决方法是直接改脚本就可以运行
例如：
torchrun --standalone --nnodes=1 --nproc_per_node=$NUM_GPUS finetune.py \
    --train_format input-output \
    --train_file scripts/formatted_data/formal_dataset.json \
    --preprocessing_num_workers 1 \
    --model_name_or_path ../../chatglm3-6b-32k \

### Expected behavior / 期待表现

目前官方是不是还不支持qlora？

**Comment by zRzRzRzRzRzRzR** [comment]
还不支持
支持后会进行更新
