### ISSUE TITLE
在t4上推理速度会越来越慢

### ISSUE THREAD

**Issue by erdongchendou** [THUDM/ChatGLM3#303]
### System Info / 系統信息

在t4上跑chatglm3提供的openai_api.py，跑着跑着推理速度会越来越慢，但是之前在t4上跑视觉模型就没出现过这个情况，是啥原因？

显卡Driver Version: 470.199.02   CUDA Version: 11.4   
系统: ubuntu 18.04
python3.8

### Reproduction / 复现过程

1、在t4上运行openai_api.py
2、然后通过openai接口调用，进行推理

### Expected behavior / 期待表现

推理速度一直保持不变

**Comment by zRzRzRzRzRzRzR** [comment]
检查一下显存，我们这边没有出现这种情况
我们没有T4显卡，使用的系统也不是这个，能不能提供一个复现

**Comment by erdongchendou** [comment]
不好意思，原因找到了，是显卡出问题了，换个显卡处理速度是稳定的，没有变慢。

**Comment by zRzRzRzRzRzRzR** [comment]
好的
