### ISSUE TITLE
可以提供域适应的demo么，指导一下如何将指定领域的资料补充进模型

### ISSUE THREAD

**Issue by 13661172102** [THUDM/ChatGLM3#304]
我有一些专业领域的资料，希望补充到模型中，要怎么实现呢

**Comment by 13661172102** [comment]
还有embedded的demo，对于模型的适应性调整也很有意义

**Comment by zRzRzRzRzRzRzR** [comment]
两个问题的回答如下：
1. 你想进行微调吗，微调的代码和框架我们已经提供了
2. 尚不能提供

**Comment by 13661172102** [comment]
您好，我是陆泽，邮寄已收到，谢谢

**Comment by 13661172102** [comment]
嗯，您提供的微调代码我试了，但是这个是基于提示词的，是个监督训练的过程，我希望单纯的将资料加入模型，比如一本书，一些论文，这样也可以用咱们的微调代码实现么

**Comment by 13661172102** [comment]
我看您还参与了另外一个项目，https://github.com/chatchat-space/Langchain-Chatchat， 这个项目支持使用chatglm3-6b模型么，如果可以的话，是不是可以基于这个项目做embedded？
