### ISSUE TITLE
运行composite_demo main.py 报错

### ISSUE THREAD

**Issue by huwen2117** [THUDM/ChatGLM3#308]
### System Info / 系統信息

Python==3.9.16
transformers==4.32.0
streamlit==1.28.2
CUDA==11.7

### Who can help? / 谁可以帮助到您？

@abmfy 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行 MODEL_PATH="..." PT_PATH="..." streamlit run main.py
出现报错

Script execution error
File "/home/ChatGLM3-main/composite_demo/main.py", line 48
  match tab:
-------^
SyntaxError: invalid syntax

### Expected behavior / 期待表现

能正常运行就行

**Comment by zRzRzRzRzRzRzR** [comment]
match 语句在 Python 3.10 及更高版本中引入
在 Python 3.9 或更早的版本中，match 关键字不是有效的语法。

两个解决方案
1. 升级 Python 版本： 可以将 Python 环境升级到 3.10 或更高版本
2. 修改代码以避免使用 match 语句：修改代码，用其他构造（如 if-elif-else 语句）替换 match 语句。

**Comment by huwen2117** [comment]
感谢

**Comment by zzzcccxx** [comment]
我的python是Python 3.10.13但也出现这个报错

**Comment by xuanyuanaosheng** [comment]
![image](https://github.com/THUDM/ChatGLM3/assets/4197714/45e37bc8-0ef8-42d1-809b-ba14677b6615)

python 版本：
```
# python -V
Python 3.10.14
```

**Comment by wccccc** [comment]
我这边是这样的。
执行`which streamlit`
我这的结果是`/usr/local/bin/streamlit`
然后cat streamlit文件发现文件内容如下
```bash
#!/usr/local/opt/python@3.9/bin/python3.9
# -*- coding: utf-8 -*-
import re
import sys
from streamlit.web.cli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

```

文件的开头指定了使用3.9版本的python 所以一直报错。
需要把让streamlit命令使用正确版本的streamlit文件。

```bash
# 文件路径按实际的来，别抄我的
cd /usr/local/bin
rm streamlit
rm streamlit.cmd
# 指定streamlit命令使用/opt/anaconda3/bin/下的文件
ln -s /opt/anaconda3/bin/streamlit /usr/local/bin/streamlit
ln -s /opt/anaconda3/bin/streamlit.cmd /usr/local/bin/streamlit.cmd
```

**Comment by RonWuzh** [comment]
![image](https://github.com/user-attachments/assets/0fd492d9-3327-4ea4-9f6e-d54ed58c9f65)
也是类似的问题，有人知道怎么解决吗

**Comment by yzc091244280** [comment]
> ![image](https://private-user-images.githubusercontent.com/4197714/323118442-45e37bc8-0ef8-42d1-809b-ba14677b6615.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjA2ODQsIm5iZiI6MTczMzIyMDM4NCwicGF0aCI6Ii80MTk3NzE0LzMyMzExODQ0Mi00NWUzN2JjOC0wZWY4LTQyZDEtODA5Yi1iYTE0Njc3YjY2MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDNUMTAwNjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjM4ODkwMzJmZWM5ZDgxMTA4MjUyM2M2MzE3NTM2NTk4ZjI1ZTVmZmIzNzhjMzliYWJkMTEyOWExNWM5NGJkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.y4p1IuQA90zXAOvVeIlsU9McD388gXwN1r9y2hM5gcA)
> 
> python 版本：
> 
> ```
> # python -V
> Python 3.10.14
> ```
> 
> 同样在 `Python 3.12.2` 产生同样的报错。
请问你解决了吗 我也遇到这个问题
