### ISSUE TITLE
请问如何输入调用插件的提示词

### ISSUE THREAD

**Issue by xs818818** [THUDM/ChatGLM3#31]
我想部署在如vllm的平台上，请问如何通过对话模型输入提示词的方式，将工具的设定输入

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM3/blob/main/tool_using/README.md

**Comment by Btlmd** [comment]
我们更新了更为完善的 Demo，可以参考 [ChatGLM3 对话格式](https://github.com/THUDM/ChatGLM3/blob/main/PROMPT.md) 和 [综合 Demo](https://github.com/THUDM/ChatGLM3/tree/main/composite_demo) 中对 Tool Call 的实现。
