### ISSUE TITLE
ChatGLM3 composite_demo 工具调用的问题

### ISSUE THREAD

**Issue by CNUIGB** [THUDM/ChatGLM3#312]
### System Info / 系統信息

环境为A40 GPU 显存48G，其他都为官方推荐

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我在使用工具调用时发现，模型并不能进行工具调用

例如：
北京天气怎么样？

chatglm3：抱歉，我无法实时获取天气信息。您可以使用上述提供的工具中的“get_weather”函数来查询特定城市的天气。请将“city_name”替换为“北京”，并设置其他参数（如时间范围等）以获得更准确的结果。

### Expected behavior / 期待表现

按照官方给出的效果应该是会调用 get_current_weather这个工具去查询天气，但是模型并没有按期望的进行调用

**Comment by CNUIGB** [comment]
![微信截图_20231115115525](https://github.com/THUDM/ChatGLM3/assets/103934790/6de93e1b-3880-4c1d-aa64-cbee18e2ef03)

**Comment by Roych13** [comment]
提问方式不正确。应该指定日期，例如：北京明天天气怎么样？南京后天天气怎么样？
不提及日期的话，经常“抱歉”的。

**Comment by CNUIGB** [comment]
> 提问方式不正确。应该指定日期，例如：北京明天天气怎么样？南京后天天气怎么样？ 不提及日期的话，经常“抱歉”的。

好的好的，我试一下

**Comment by CNUIGB** [comment]
> 提问方式不正确。应该指定日期，例如：北京明天天气怎么样？南京后天天气怎么样？ 不提及日期的话，经常“抱歉”的。

还是不可以，我之前好像是按官方给的动图里一模一样的话提问的，也还是不行。

**Comment by JadeLuo** [comment]
ipython没装吧

**Comment by JadeLuo** [comment]
工具调用执行代码需要借助ipython内核

**Comment by liushaoqian** [comment]
> > 提问方式不正确。应该指定日期，例如：北京明天天气怎么样？南京后天天气怎么样？ 不提及日期的话，经常“抱歉”的。
> 
> 还是不可以，我之前好像是按官方给的动图里一模一样的话提问的，也还是不行。

 你解决了吗，我也出现了这样的问题，但是我安装了ipython内核啊
