### ISSUE TITLE
按文档运行提示libcublas.so.*[0-9] not found in the system path

### ISSUE THREAD

**Issue by zzutligang** [THUDM/ChatGLM3#317]
### System Info / 系統信息

Ubuntu 18.04.6 LTS \n \l
显卡 Tesla T4 16G
输入 nvidia-smi可以显示显卡信息，可以看到最高支持CUDA到11.4
安装cuda9，通过nvcc -V显示
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
python=3.10，环境使用miniconda构建的

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

按文档把模型下载到本地，然后
pip install -r requirements.txt
下载正常，使用中科大镜像，但会提示依赖有冲突，使用
pip install -r requirements.txt --no-deps
安装完成
进到composite_demo文件夹运行 streamlit run main.py
提示成功，但浏览器输入地址，页面提示
ValueError: libcublas.so.*[0-9] not found in the system path ['main.py', '', '/home/hfwy/miniconda/envs/chatglm3/bin', '/home/hfwy/miniconda/envs/chatglm3/lib/python310.zip', '/home/hfwy/miniconda/envs/chatglm3/lib/python3.10', '/home/hfwy/miniconda/envs/chatglm3/lib/python3.10/lib-dynload', '/home/hfwy/miniconda/envs/chatglm3/lib/python3.10/site-packages']
控制台有两个错误：
第一处错误提示：OSError: libcufft.so.11: cannot open shared object file: No such file or directory
第二处错误提示：ValueError: libcublas.so.*[0-9] not found in the system path ['main.py', '', '/home/hfwy/miniconda/envs/chatglm3/bin', '/home/hfwy/miniconda/envs/chatglm3/lib/python310.zip', '/home/hfwy/miniconda/envs/chatglm3/lib/python3.10', '/home/hfwy/miniconda/envs/chatglm3/lib/python3.10/lib-dynload', '/home/hfwy/miniconda/envs/chatglm3/lib/python3.10/site-packages']
第二处错误提示和页面提示一样。

### Expected behavior / 期待表现

猜测应该是cuda没安装对，我的显卡提示最高cuda支持到11.4
因为安装哪个版本的cuda呢？怎么安装比较保险呢？

**Comment by zRzRzRzRzRzRzR** [comment]
cuda 我们推荐12.0 +  你的显卡提示是因为你的驱动太老了，更新驱动

**Comment by zRzRzRzRzRzRzR** [comment]
方便的话可以提供官方要求下的环境，并提供更多系统信息后再次提出issue，确定系统华宁变量正确后提出最小复现，该issue关闭
