### ISSUE TITLE
请问能在插件对话前面增加意图分析吗，这样我可以根据需要，选择对话聊天还是调工具。

### ISSUE THREAD

**Issue by xs818818** [THUDM/ChatGLM3#318]
### Feature request  / 功能建议

请问能在插件对话前面增加意图分析吗，这样我可以根据需要，选择对话聊天还是调工具。

### Motivation / 动机

请问能在插件对话前面增加意图分析吗，这样我可以根据需要，选择对话聊天还是调工具。

### Your contribution / 您的贡献

curl http://192.168.43.87:3000/v1/chat/completions \
 -H "Authorization: Bearer sk-8Zan2c6Y7qtO89i8D80a23E8Bb454496914a66B02640C23a" \
 -H "Content-Type: application/json" \
 -d '{
 "model": "chatglm3",
 "messages": [{"role": "user", "content": "你是对话分类助手，只返回分类结果。可返回的类别：1.日常聊天2.网页操作。现在对话是：打开案例查询页面的火焰案例"}]}'

**Comment by zRzRzRzRzRzRzR** [comment]
这个模型的意图识别较差，我们已经进行了尝试，目前不太现实
