### ISSUE TITLE
ChatDev.gitopenai api缺少send_message接口，

### ISSUE THREAD

**Issue by favouriter** [THUDM/ChatGLM3#319]
### System Info / 系統信息

openai api缺少send_message
[send_message](https://github.com/OpenBMB/ChatDev.git)这个项目调用openai api是调用send_message报错，
 - "POST /send_message HTTP/1.1" 404 Not Found

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

添加send_message接口

**Comment by zRzRzRzRzRzRzR** [comment]
我们用的是1.0 以上的openai库
传入方式应该看我们的openai_api_demo
