### ISSUE TITLE
chatGLM3延时问题

### ISSUE THREAD

**Issue by zls130921** [THUDM/ChatGLM3#323]
### System Info / 系統信息

使用chatGLM做信息抽取，同一个问题有时1-3s出结果，有时1min还没有结果，这个是什么原因呢？

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

一直无响应

### Expected behavior / 期待表现

我的显卡是32G的，希望大佬给与指导

**Comment by zRzRzRzRzRzRzR** [comment]
给一个最小的复现例子

**Comment by zRzRzRzRzRzRzR** [comment]
这个问题估计不是bug，如果你能稳定复现，可以到讨论区提出讨论，该issue关闭
