### ISSUE TITLE
Windows系统可以微调吗

### ISSUE THREAD

**Issue by AHPUymhd** [THUDM/ChatGLM3#326]
### System Info / 系統信息

我看微调实例里面是sh命令，这个是linux的命令呀，请问我在Windows本地部署的ChatGLM3可以进行微调吗

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

谢谢

### Expected behavior / 期待表现

谢谢

**Comment by phpdancer** [comment]
sh里也是python脚本，直接执行那个脚本就可以了

**Comment by AHPUymhd** [comment]
> sh里也是python脚本，直接执行那个脚本就可以了

非常感谢！

**Comment by zRzRzRzRzRzRzR** [comment]
d

**Comment by AHPUymhd** [comment]
> sh里也是python脚本，直接执行那个脚本就可以了

您好，请问您的Windows系统怎么微调的，例如官方的P-tuning微调，我尝试在Git上面运行sh文件报错没解决掉，在conda中尝试运行也没有成功，麻烦您可以告诉我Windows怎么微调的吗，我提问了，官方的回答是运行py文件，我也不知道是哪个，您可以告诉我吗，谢谢了！

**Comment by zRzRzRzRzRzRzR** [comment]
运行py文件的名字叫做finetune.py 这个文件的参数就是脚本中的参数

**Comment by AHPUymhd** [comment]
谢谢您啦，今天上午已经摸索出来了，真的很感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "THUDM/ChatGLM3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月24日(星期五) 晚上6:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [THUDM/ChatGLM3] Windows系统可以微调吗 (Issue #326)





 
运行py文件的名字叫做finetune.py 这个文件的参数就是脚本中的参数

**Comment by makeukus** [comment]
> 谢谢您啦，今天上午已经摸索出来了，真的很感谢！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "THUDM/ChatGLM3" ***@***.***&gt;; 发送时间:&nbsp;2023年11月24日(星期五) 晚上6:32 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [THUDM/ChatGLM3] Windows系统可以微调吗 (Issue #326) 运行py文件的名字叫做finetune.py 这个文件的参数就是脚本中的参数 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以分享下么
