### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by yunhao233** [THUDM/ChatGLM3#327]
### System Info / 系統信息

CUDA Version: 12.3
Python：3.9.10
pytorch2.1
Transformer version==4.33.3
OS：Linux

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

`prompt = item['question']
response,history = model.chat(tokenizer, prompt, history=[])`
使用的数据集是addSub，将其中的question作为问题调用chat接口时提示这个错误
![image](https://github.com/THUDM/ChatGLM3/assets/44170254/d98ad7d6-9ff7-488c-ba66-2ea85a0eb2fd)

### Expected behavior / 期待表现

修改代码为print(model.chat(tokenizer, prompt, history=[])) 也同样会遇到这个问题，请问如何解决，这是程序内部问题导致的么

**Comment by zRzRzRzRzRzRzR** [comment]
你没有传入role啊

**Comment by zRzRzRzRzRzRzR** [comment]
> 我也遇到了同样的问题，有人解决了吗，我运行的是官方的示例代码

哪一份，给个复现

**Comment by yunhao233** [comment]
> 你没有传入role啊

谢谢谢谢，已解决

**Comment by yunhao233** [comment]
> 你没有传入role啊

你好，我在显式地传入role为"user"后尝试也有这个问题，并且发现提问的是英文问题，但是回答输出有时候会翻译为中文并输出乱码的字符
![image](https://github.com/THUDM/ChatGLM3/assets/44170254/ab8f3607-44aa-4fd7-923a-97b948859853)
