### ISSUE TITLE
在tool里如何提升function调用的准确度？

### ISSUE THREAD

**Issue by si1mon2** [THUDM/ChatGLM3#328]
自己定义了几个不同功能的function，但是在用tool功能进行function调用的时候，经常会调用到不相关的function，即使在prompt里明确指定了“使用名为xx的function，完成xx的任务”，还是会出现调用到其他不相关的function的情况，每次只有提前注释掉不相关的function，保留想用的function才能完全避免上述的问题，感觉很不方便。

**Comment by zRzRzRzRzRzRzR** [comment]
这个不属于bug
但是模型调不准Function是一个bad case，这个目前只能通过优化提示词和减少工具的总数量来解决
可以移步讨论区找到对应的话题并记录
