### ISSUE TITLE
请问history中的metadata有什么作用？

### ISSUE THREAD

**Issue by LuckyJianan** [THUDM/ChatGLM3#33]
{'role': 'assistant', 'metadata': '', 'content': '你好世界'}

**Comment by Btlmd** [comment]
目前，metadata 可用于 assistant 指明调用外部资源的类型。如 code interpreter 中为 `interpreter`，在工具调用时则为工具的名称。具体的格式约定可以参见 [ChatGLM3 对话格式](https://github.com/THUDM/ChatGLM3/blob/main/PROMPT.md)
