### ISSUE TITLE
finetune_ds_multiturn.sh微调增加参数--quantization_bit 8报错，是不支持量化吗

### ISSUE THREAD

**Issue by childlong** [THUDM/ChatGLM3#332]
### System Info / 系統信息

set -ex

LR=1e-4
NUM_GPUS=1
MAX_SEQ_LEN=1024
DEV_BATCH_SIZE=1
GRAD_ACCUMULARION_STEPS=16
MAX_STEP=200
SAVE_INTERVAL=50

DATASTR=`date +%Y%m%d-%H%M%S`
RUN_NAME=tool_alpaca_ft
DATASET_PATH=formatted_data/tool_alpaca.jsonl

BASE_MODEL_PATH=/xxxx/ChatGLM3-main/chatglm3-6b
OUTPUT_DIR=output/${RUN_NAME}-${DATASTR}-${LR}

mkdir -p $OUTPUT_DIR

torchrun --standalone --nnodes=1 --nproc_per_node=$NUM_GPUS finetune.py \
    --train_format multi-turn \
    --train_file $DATASET_PATH \
    --max_seq_length $MAX_SEQ_LEN \
    --preprocessing_num_workers 1 \
    --model_name_or_path $BASE_MODEL_PATH \
    --output_dir $OUTPUT_DIR \
    --per_device_train_batch_size $DEV_BATCH_SIZE \
    --gradient_accumulation_steps $GRAD_ACCUMULARION_STEPS \
    --max_steps $MAX_STEP \
    --logging_steps 1 \
    --save_steps $SAVE_INTERVAL \
    --fp16 \
    <font color="red">**--quantization_bit 8**</font>
    --deepspeed configs/deepspeed.json 2>&1 | tee ${OUTPUT_DIR}/train.log

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/THUDM/ChatGLM3/assets/10560793/027beb59-92ab-4394-95e1-973e45413ae4)
看了下原因是finetune.py 110行把模型转float()了； 这行代码去掉又会报以下错误

![Uploading image.png…]()

### Expected behavior / 期待表现

运行正常

**Comment by zRzRzRzRzRzRzR** [comment]
没有int8量化
