### ISSUE TITLE
关于模型对数据简单分析时，存在错误性描述，这个怎么解决，如果做大规模微调，能不能调整过来

### ISSUE THREAD

**Issue by wengyuan722** [THUDM/ChatGLM3#337]
### System Info / 系統信息

时间	销量	同比
2023年9月	2019445	-11.25%
2023年8月	1922495	-13.39%
2023年7月	1781580	-16.20%
2023年6月	1894250	-12.54%
2023年5月	1685966	6.91%
2023年4月	1635995	73.57%
2023年3月	1593454	-12.44%
2023年2月	1396501	-3.78%
2023年1月	1295097	-39.48%
请对以上数据进行分析

模型回答
从以上数据可以看出，2023年我国某产品的销量总体呈下降趋势。具体分析如下：

2023年1月销量最低，为1295097台，相比2019年9月销量最高时的2019445台，下降了39.48%。这可能说明该产品在2023年1月的市场需求较低。

从2023年2月至2023年6月，销量有所回升，但总体仍呈下降趋势。其中，2023年4月销量增长最为明显，相比2023年1月增长73.57%，但相较于2019年9月的最高销量，仍有一定差距。

2023年7月至2023年9月，销量再次出现下降，分别较2023年6月下降12.54%和11.25%。这可能说明市场需求在这段时间内有所减少。

综上所述，该产品的销量在2023年整体呈下降趋势。虽然2023年4月销量有所回升，但相较于2019年的最高销量，仍有一定差距。需要关注市场动态，进一步分析原因，并采取相应措施提高销量。

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

目前chatglm3的表现已经很厉害，就是想在一些简单的应用场景结合，不知道如果完善

### Expected behavior / 期待表现

处理数据描述性问题时，尽量不说不符合逻辑的，特别是同比，环比这些常见的分析时，尽可能符合逻辑

**Comment by zRzRzRzRzRzRzR** [comment]
这个估计有一点幻觉
如果提示词不行的话考虑微调，但是6B的数学能力有待提升
无法保证微调能不能成功

**Comment by zRzRzRzRzRzRzR** [comment]
关于更多非bug的微调问题，可以在讨论区和微信中进行讨论，本issue关闭
