### ISSUE TITLE
运行composite_demo/main.py报AttributeError: module 'demo_chat' has no attribute 'main'

### ISSUE THREAD

**Issue by zzutligang** [THUDM/ChatGLM3#338]
### System Info / 系統信息

ubuntu20.4
CUDA12.2
cudnn8.9.6
显卡Tesla T4 16G显存
显卡驱动535.129.03

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

安装完所有依赖，没有报错，进入到composite_demo文件夹，运行streamlit run main.py正常
浏览器访问http://192.168.0.61:8501/，后台看到加载模型通过，但立马报了
  File "/home/hfwy/ChatGLM3/composite_demo/main.py", line 54, in <module>
    demo_chat.main(top_p, temperature, system_prompt, prompt_text, repetition_penalty)
    ^^^^^^^^^^^^^^
AttributeError: module 'demo_chat' has no attribute 'main'
查看demo_chat.py，里面确实定义的有main函数。

### Expected behavior / 期待表现

期待解惑

**Comment by zRzRzRzRzRzRzR** [comment]
更新一下最新代码？这个情况没有出现过

**Comment by zzutligang** [comment]
又重新拉了一下代码，现在可以执行了。感谢！

**Comment by pomeloCui** [comment]
进入到composite_demo文件下，pip install -r requirements.txt
