### ISSUE TITLE
Benchmark result reproducibility 关于 Benchmark 结果的复现的方法

### ISSUE THREAD

**Issue by siriusctrl** [THUDM/ChatGLM3#34]
感谢 release 了一个非常强大的模型，想问一下 readme 中的 benchmark result 如何进行复现呢？我尝试使用了和 huggingface leaderboard 或提供在原本论文/repo中类似的测试方加 greedy decoding 的方法进行测试。经过一些调试，可以复现 Llama2 文章中提到的大部分分数。但是在测试 ChatGLM3 时发现，除了 AGI_Eval 的分数较为接近外，大部分分数都有 10-20 分以上的差距，尤其是 GSM8K 的 exact match 只有 47.8 分，即使是检测 contains，也只有 51 分。是否可以分享下复现 benchmark 结果的方法？谢谢

**Comment by duzx16** [comment]
测评代码整理之后会发布。需要先确认一下你测的是 ChatGLM3-6B-Base 这个模型吗

**Comment by siriusctrl** [comment]
> 测评代码整理之后会发布。

好的，感谢。

> 需要先确认一下你测的是 ChatGLM3-6B-Base 这个模型吗

是的

**Comment by siriusctrl** [comment]
请问测评方法发布了吗？没有在 repo 中找到相关信息
