### ISSUE TITLE
求轻量化微调ChatGLMForSequenceClassification的方法

### ISSUE THREAD

**Issue by derrickcyt** [THUDM/ChatGLM3#341]

**Comment by zRzRzRzRzRzRzR** [comment]
我们提供了微调脚本，你需要再我们的脚本上进行改进

**Comment by lyyztt67** [comment]
请问大佬说的是cookbook\finetune_muti_classfication.ipynb这个脚本，做微调ChatGLMForSequenceClassification吗？
