### ISSUE TITLE
工具微调的格式和工具调用的格式不一致

### ISSUE THREAD

**Issue by leuvenxp** [THUDM/ChatGLM3#343]
### System Info / 系統信息

Hi 老师你好，我想做一个glm3的微调数据训练集。@Btlmd

我看微调的例子中是这么写的
"tools": [
         // available tools, format is not restricted
      ],
      "conversations": [
         {
            "role": "system",
            "content": "<system prompt text>"
         },

在bili的视频教程里面工具的调用是写在system里面的：
< system>
Answer the following questions as best as you can. You have access to the following tools:
[
{
  "name": "track",
  "description"：“追踪指定股票的实时价格"，
  "parameters": {
  "type": "object",
  "properties": {
  "symbol": {
  "description": "追踪的股票代码"
  },
  
  "required": ['symbol']
}
调用和训练的格式就是不一致么？Tool到底应该是在conversation里面，还是在外面呢？

### Who can help? / 谁可以帮助到您？

@Btlmd

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

空

### Expected behavior / 期待表现

期待能更清晰的写明微调数据的例子，包括system里面是否也需要把tool的信息加上，向调用方法里的例子一样。

**Comment by zRzRzRzRzRzRzR** [comment]
调用和微调是不一样的，微调的数据格式只看微调的例子

**Comment by leuvenxp** [comment]
需要在微调的数据集的system中再加入工具的信息么？

**Comment by zRzRzRzRzRzRzR** [comment]
要，那边是完整的工具列表

**Comment by leuvenxp** [comment]
在训练集的system中也要这么写嘛？
< system>
Answer the following questions as best as you can. You have access to the following tools:
[
{
"name": "track",
"description"：“追踪指定股票的实时价格"，
"parameters": {
"type": "object",
"properties": {
"symbol": {
"description": "追踪的股票代码"
},

"required": ['symbol']
}

**Comment by zRzRzRzRzRzRzR** [comment]
![图片](https://github.com/THUDM/ChatGLM3/assets/93239683/809836df-510d-477a-ab06-29baa02f1ea5)
理论上没有限制，
![图片](https://github.com/THUDM/ChatGLM3/assets/93239683/c3a7451c-d685-42fc-830b-76a628474791)
anzh澳这个格式更好，你这个应该也是可以的

**Comment by zRzRzRzRzRzRzR** [comment]
这个格式转成json的格式

**Comment by zRzRzRzRzRzRzR** [comment]
```
{'description': 'Get the current weather for `city_name`',
 'name': 'get_weather',
 'params': [{'description': 'The name of the city to be queried',
             'name': 'city_name',
             'required': True,
             'type': 'str'}]}
```      
 这是在langchain demo中转成的json格式，这个格式跟你的差不多，应该效果是差不多的

**Comment by leuvenxp** [comment]
谢谢啦。
总结一下的话，完整的训练集就要像下面这样咯？

{
    "tools":[
        "GetWeather:获取指定城市的当前天气信息
        \nParameters:{
            \"city_name\": \". 指定的城市名称. \"
        }
    ]
    "conversations": [
        {
            "role":"system",
            "content":"你是一个智能助理，可以根据用户的要求控制工具。请使用以下工具做应用控制。：
                {'description': 'Get the current weather for `city_name`',
                'name': 'get_weather',
                 'params': [{'description': 'The name of the city to be queried',
                   'name': 'city_name',
                   'required': True,
                   'type': 'str'}]}   "

        },
        {
            "role": "user",
            "content": "context"
        },
        {
            "role": "tool",
            "name": "GetWeather",
            "parameters": {
                "city_name": "北京",
            }, 
            "observation": "…… "
        },
        {
            "role": "assistant",
            "content": "…… "
         }

    ]
}

**Comment by zRzRzRzRzRzRzR** [comment]
"observation": "…… "要有东西，就是工具观察的结果，其他应该是可以的，可以先调一版，如果不行，可以到讨论区讨论（微调效果确实是很玄学的问题），这个issue关闭了❤️
