### ISSUE TITLE
inference不能使用bad_words_ids

### ISSUE THREAD

**Issue by CinderellaCc** [THUDM/ChatGLM3#347]
### System Info / 系統信息

No

### Who can help? / 谁可以帮助到您？

No

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

No

### Expected behavior / 期待表现

No

**Comment by zRzRzRzRzRzRzR** [comment]
能提供一下代码吗
是否与https://github.com/huggingface/transformers/issues/14206 有关

**Comment by zRzRzRzRzRzRzR** [comment]
查看一下最新更新的代码的basic_demo，是否解决了你的问题,如果没有，请提出最小复现，方便我们寻找错误
