### ISSUE TITLE
[BUG]composite_demo/client.py 中generate_stream实现chat_history时，未考虑role为tool时的tool信息拼接

### ISSUE THREAD

**Issue by wuzhiye7** [THUDM/ChatGLM3#348]
### System Info / 系統信息

环境无关

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/THUDM/ChatGLM3/assets/20206364/8059cc4f-7db1-4792-9cc8-d8913860d2b6)

当role为Role.TOOL时，tool信息未被接入历史对话。可能导致训练预测不一致
 Conversation(role=<Role.TOOL: X>, content='```python\ntool_call()\n```', tool='xxxxx', image=None)

### Expected behavior / 期待表现

拼接tool信息到历史对话中

chat_history.append({
                'role': str(conversation.role).removeprefix('<|').removesuffix('|>'),
                'content': conversation.content,
                ‘metadata’:conversation.tool
            })

**Comment by zRzRzRzRzRzRzR** [comment]
tools是不会被传入历史对话的，历史中不会被记录之前调用的工具，只记录人和助理的结果的对话

**Comment by wuzhiye7** [comment]
> tools是不会被传入历史对话的，历史中不会被记录之前调用的工具，只记录人和助理的结果的对话

有一种情况是非历史对话，拿到tool的返回结果时，需要再次生成回复。这种情况不能规避tool轮

**Comment by zRzRzRzRzRzRzR** [comment]
就是根据Observation的结果再次回复吗，工具Observation作为一个角色会吧信息传给assistant，在那一轮对话下会有回复，但是之后的话不会去参考之前对话中工具调用的结果

**Comment by quzx** [comment]
composite_demo/client.py中，很明确地把 role:  tool 加入到 history，并且带到了下一个 generate-stream

**Comment by wuzhiye7** [comment]
> 就是根据Observation的结果再次回复吗，工具Observation作为一个角色会吧信息传给assistant，在那一轮对话下会有回复，但是之后的话不会去参考之前对话中工具调用的结果

训练时：
<|system|> answer the ... tools:\n[...]
<|user|>\n北京天气怎么样？
<|assistant|>\n我需要调用天气预报工具获取天气信息。
<|assistant|>get_weather\n```python\ntool_call(location="北京")```
<|observation|>\n{“temp”:32}
<|assistant|>\n根据天气工具的信息，北京气温是xxx。

预测时，因为没有tool API信息变成，input变成了：
<|system|> answer the ... tools:\n[...]
<|user|>\n北京天气怎么样？
<|assistant|>\n我需要调用天气预报工具获取天气信息。
<|assistant|>\n```python\ntool_call(location="北京")```              # tool 轮信息，缺少API get_weather
<|observation|>\n{“temp”:32}
<|assistant|>

**Comment by zRzRzRzRzRzRzR** [comment]
我们今天在查看这个情况，应该是要加入observation，已经加入工作任务中，之后估计会有一版新的微调代码。该issue关闭，更多微调问题和badcase 请在 #310 中提出
