### ISSUE TITLE
Something went wrong Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by heiheiheibj** [THUDM/ChatGLM3#35]
输出什么内容，都是出错
![image](https://github.com/THUDM/ChatGLM3/assets/6910198/173b7f43-f074-422b-bbdd-2f64fc9c7af7)

![image](https://github.com/THUDM/ChatGLM3/assets/6910198/4f3fc2bb-784a-4b08-9ba1-7e38a9a3d6b9)
控制台中没有错误信息显示，谢谢

**Comment by heiheiheibj** [comment]
系统是WIN10,运行的程序是web_demo.py，用CPU跑的
跑了6B2，一切都正常

**Comment by my6889** [comment]
我也遇到的相同的情况。
**复现方式**
在web_demo.py最后一行中
```
demo.queue().launch(share=False, inbrowser=True)
```
设定server_name或server_port后，比如这样
```
demo.queue().launch(server_name="0.0.0.0", server_port=8080, share=False, inbrowser=True)
```
启动后浏览器会自动弹出，在提交完问题后就会出现这样的情况，并且终端无任何提示或报错。

**Comment by scut-pzy** [comment]
超简单，你开梯子了，关掉就行，原理我不知道，希望有大佬讲解

**Comment by heiheiheibj** [comment]
多谢，难道是因为向外网发什么请求了，因为梯子被屏蔽无正确响应，所以出错了？
发现上着梯子，好多国内网站不让访问.

**Comment by Yumeka999** [comment]
> 超简单，你开梯子了，关掉就行，原理我不知道，希望有大佬讲解

Right, That's it!
