### ISSUE TITLE
测试了很多场景，总结下是一个没有人情味的工具机器人

### ISSUE THREAD

**Issue by fryng** [THUDM/ChatGLM3#350]
### System Info / 系統信息

例如写作文，写心得体会，讲笑话，写新闻需要一些文采和语言组织能力的场景，明显不如baichuan2-7B。工具调用，代码，总结分析等方面确实有优势。

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

变得更有人情味

**Comment by zRzRzRzRzRzRzR** [comment]
尝试一下系统提示词和微调，模型能力上限不是当前能解决的问题，如果还不行可以提到badcase，附上复现和测试代码

**Comment by yhyu13** [comment]
@fryng temperature设置是多少，越高语言更丰富吧

**Comment by zRzRzRzRzRzRzR** [comment]
提高temperature能提升丰富度，但是调用工具的能力可能会减弱，如果还需要调知识库，这会是一个很大的挑战

**Comment by zzutligang** [comment]
楼主是百川的粉丝来踢场子的吧

**Comment by fryng** [comment]
baichuan2-7b-int4测试场景
![baichuan7b-1](https://github.com/THUDM/ChatGLM3/assets/25688907/92273246-bfe7-4cde-bb1f-6bad9d60ed2c)
![baichuan7b-2](https://github.com/THUDM/ChatGLM3/assets/25688907/0d4927e4-3f3b-4681-b4dd-371b143dbc97)
![baichuan7b-3](https://github.com/THUDM/ChatGLM3/assets/25688907/1c09292e-bb34-42a2-a18d-dccaf1b74ae5)
chatglm3-6b-int4测试场景
![glm36b](https://github.com/THUDM/ChatGLM3/assets/25688907/66a22d0e-7f33-4e33-a880-cafce29edb2b)
![glm36b1](https://github.com/THUDM/ChatGLM3/assets/25688907/52e3e9ea-0468-42ec-965a-4eabf9aa0b0c)
![glm36b2](https://github.com/THUDM/ChatGLM3/assets/25688907/c578665a-9e94-45fc-8a94-b70075c01d40)
@zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
模型各有优劣，在你的截图中存在的例如中英文混合输出的bad case我们已经在Discussion记录，这部分内容将会在未来的模型改进。
我们和llama和国内其他知名开源大模型系列的模型和训练数据并不相似，因此，使用适合他们的提示词不一定能适合我们
关于你提到的关于任何政治方面的问题，模型已经做了对齐。
希望这能帮到你。
我们推荐开发者使用适合自己的模型，如果你觉得友商的模型更好，可以先使用他们的模型，我们也将不断改进。
感谢支持
