### ISSUE TITLE
运行streamlit run main.py，使用Tool时提示：NameError: name 'length_penalty' is not defined

### ISSUE THREAD

**Issue by GoodHope** [THUDM/ChatGLM3#351]
### System Info / 系統信息

Cuda 12，Python 3.11，Ubuntu 20.4

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1，进入composite_demo目录，执行：streamlit run main.py
2，在浏览器中访问：http://localhost:8501/，并选择“Tool”
3，在页面下方输入框中输入：北京天气如何？
即报错如下：
NameError: name 'length_penalty' is not defined
Traceback:
File "/usr/local/conda/envs/chatglm3/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
File "/data/llm/ChatGLM3/composite_demo/main.py", line 56, in <module>
    demo_tool.main(top_p, temperature, prompt_text, repetition_penalty)
File "/data/llm/ChatGLM3/composite_demo/demo_tool.py", line 121, in main
    length_penalty=length_penalty,
                   ^^^^^^^^^^^^^^

### Expected behavior / 期待表现

修复bug

**Comment by JosenJin** [comment]
确实是这样：File "D:\ai\ChatGLM3\ChatGLM3\composite_demo\demo_tool.py", line 121, in main
    length_penalty=length_penalty,
                   ^^^^^^^^^^^^^^

**Comment by zRzRzRzRzRzRzR** [comment]
❤️ bug修复了，非常感谢提出的问题
