### ISSUE TITLE
兼容openAI的代码什么时候开发？

### ISSUE THREAD

**Issue by coderwpf** [THUDM/ChatGLM3#36]
兼容openAI的代码什么时候开发？

**Comment by bonuschild** [comment]
+1, 直接使用chatglm2-6b的代码在`tokenization_chatglm.py`的189行`build_chat_input`处报错：
```
        content = item["content"]
TypeError: list indices must be integers or slices, not str
```
看来是返回内容的形式也变了，请指点如何修改，谢谢！

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM3#api-%E9%83%A8%E7%BD%B2
