### ISSUE TITLE
词表的前三项都为‘’

### ISSUE THREAD

**Issue by JaheimLee** [THUDM/ChatGLM3#363]
使用tokenizer.convert_ids_to_tokens时，0,1,2三个id的输出都是空，从3开始才有结果

**Comment by zRzRzRzRzRzRzR** [comment]
你所遇到的现象是正常的，对于GLM和类似的大型语言模型来说，词表中的前几个条目通常是保留的特殊token或未使用的空位。
+ 这些token用于表示特定的控制功能或元信息。这些特殊token帮助模型处理文本、理解文本段落的开始和结束
+ 词表的开始部分，有一些未被映射到实际词汇的ID。这些空位可能是为将来模型升级或特殊用途预留的。也可能用不到。
+ 前三个之后，会出现 <0x00>, <0x01>等词表，这些应该用于内部处理或特殊情况的控制字符（我也不是核心算法，不知道）。
总结，你通常不需要关注这些特殊或空白的token。只要关注实际表示词汇的token就行。

**Comment by JaheimLee** [comment]
> 你所遇到的现象是正常的，对于GLM和类似的大型语言模型来说，词表中的前几个条目通常是保留的特殊token或未使用的空位。
> 
> * 这些token用于表示特定的控制功能或元信息。这些特殊token帮助模型处理文本、理解文本段落的开始和结束
> * 词表的开始部分，有一些未被映射到实际词汇的ID。这些空位可能是为将来模型升级或特殊用途预留的。也可能用不到。
> * 前三个之后，会出现 <0x00>, <0x01>等词表，这些应该用于内部处理或特殊情况的控制字符（我也不是核心算法，不知道）。
>   总结，你通常不需要关注这些特殊或空白的token。只要关注实际表示词汇的token就行。

但是eos的id是2，如果像继续预训练些数据，而不是sft，那应该使用哪个eos token啊
