### ISSUE TITLE
更新了新代码，还是发生重复语句及要求中文给我生成英文的问题

### ISSUE THREAD

**Issue by wxchjay** [THUDM/ChatGLM3#365]
### System Info / 系統信息

python3.8.5
NVIDIA-SMI 535.86.05
Driver Version: 535.86.05
CUDA Version: 12.2
model：chatglm3-6b-32k，chatglm3-6b

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![febcdb522573093b381f7bf0af9f637b](https://github.com/THUDM/ChatGLM3/assets/150489977/5817d4bf-3ce1-4264-9b9e-15d90daf96e6)

不全部生成，直接下一篇

![c31a47969b17cd3f989bbb24385d5677](https://github.com/THUDM/ChatGLM3/assets/150489977/ecd5ed90-84bc-4475-a4b9-69163b606799)

我要求中文，给我生成英文
![1769dfcc8f9c25321ea25ab646dd7da7](https://github.com/THUDM/ChatGLM3/assets/150489977/140481ce-9039-4e26-b168-4251c6a62c8f)

重复语句

我给你们下我这边用的关键词以及批量生成的py文件，你们这边跑一下，就可以复现问题了
复现流程：进行多篇文章一直生成就会发生此类问题发生
因附件无法发出，麻烦给下你们的邮件，我这边发给你们，你们可以试一下，就能复现此类问题

### Expected behavior / 期待表现

正常输出

**Comment by zRzRzRzRzRzRzR** [comment]
中英文这个是个bad case，这一代模型解决不了

**Comment by wxchjay** [comment]
> 中英文这个是个bad case，这一代模型解决不了

麻烦给个邮箱 我发你附件 你就能复现以上问题

**Comment by wxchjay** [comment]
总共2个附件，基本上可以复现出以上几个问题，你这边可以跑下看看，基本上1000篇左右会出现10次以上这种问题

封情のあい
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "THUDM/ChatGLM3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月19日(星期天) 中午11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [THUDM/ChatGLM3] 更新了新代码，还是发生重复语句及要求中文给我生成英文的问题 (Issue #365)





 
中英文这个是个bad case，这一代模型解决不了

**Comment by zRzRzRzRzRzRzR** [comment]
Yuxuan.Zhang@student.xjtlu.edu.cn
或者微信我zR_ZYX

**Comment by sevenandseven** [comment]
> 中英文这个是个bad case，这一代模型解决不了 可以理解为输出中英文混搭在这一代模型是正常现象，你把对应的提示词发我邮箱，我github的邮箱

你好，请问一下4月份的新模型可以解决这个中英文混搭的问题吗？
