### ISSUE TITLE
请问是否可提供一个CoT的多轮工具调用示例

### ISSUE THREAD

**Issue by xqe2011** [THUDM/ChatGLM3#366]
### Feature request  / 功能建议

请问是否可提供一个CoT的多轮工具调用示例，通过多轮的对话调用不同的工具解决同一个问题？我测试过程中发现模型似乎总是倾向于只使用一次工具。

### Motivation / 动机

尝试让模型从数据源获取资料后控制画图工具画图

### Your contribution / 您的贡献

暂无

**Comment by zRzRzRzRzRzRzR** [comment]
6B模型还不具备多轮调用工具的能力，目前做不了，要等模型更新
