### ISSUE TITLE
openai_API.py 开启多work报 “NameError: name 'model' is not defined”

### ISSUE THREAD

**Issue by huyuan-cn** [THUDM/ChatGLM3#368]
### System Info / 系統信息

torch                          2.1.0+cu121
torchaudio                     2.1.0+cu121
torchvision                    0.16.0+cu121
transformers                   4.32.0

### Who can help? / 谁可以帮助到您？

调整worker数量后，需要调整代码
原
uvicorn.run(app, host='0.0.0.0', port=8001, workers=1)
修改为
uvicorn.run('__main__:app', host='0.0.0.0', port=8001, workers=2)
启动正常后推理报“NameError: name 'model' is not defined”

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

原
uvicorn.run(app, host='0.0.0.0', port=8001, workers=1)
修改为
uvicorn.run('__main__:app', host='0.0.0.0', port=8001, workers=2)
启动正常后推理报“NameError: name 'model' is not defined”

### Expected behavior / 期待表现

实现OPENAI API多worker模式

**Comment by zRzRzRzRzRzRzR** [comment]
wokers应该目前只能为1 把，没做并发

**Comment by zzutligang** [comment]
> wokers应该目前只能为1 把，没做并发

如果想做并发，应该怎么搞？另外，如果项多轮对话，历史对话怎么传递？例子里没有。感谢！

**Comment by ffayr** [comment]
删掉main方法，把模型加载代码放到外面，然后使用uvicorn openai_api:app --host 0.0.0.0 --port 8003 --workers 2执行，但我这样做好像并发效率提升很小，不知道是不是我显卡性能不够的问题

**Comment by zRzRzRzRzRzRzR** [comment]
并发建议用中间框架，比如fschat等框架，优化会好很多，官方demo的作用是帮大部分开发者从入门到基础，精通还得用一些专业的框架

**Comment by huyuan-cn** [comment]
> 删掉main方法，把模型加载代码放到外面，然后使用uvicorn openai_api:app --host 0.0.0.0 --port 8003 --workers 2执行，但我这样做好像并发效率提升很小，不知道是不是我显卡性能不够的问题

我就是想这样试试看，现在并发有点弱，主要gpu上不去
