### ISSUE TITLE
怎么做到仅json输出，而不返回无关文字，或者让他不要把指定的json结构的参数以自然语言显示在额外文字而没有显示在我指定的json结构里

### ISSUE THREAD

**Issue by BEILOP** [THUDM/ChatGLM3#369]
### System Info / 系統信息

无

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

怎么做到仅json输出，而不返回无关文字，或者让他不要把指定的json结构的参数以自然语言显示在额外文字而没有显示在我指定的json结构里

**Comment by zRzRzRzRzRzRzR** [comment]
6B的对齐能力有限，指令跟随效果没有那么强，估计要微调和不断重试直到成功

**Comment by 1014670860** [comment]
期待格式输出更强的chatGML出现
