### ISSUE TITLE
数据集格式问题

### ISSUE THREAD

**Issue by Fmaj7** [THUDM/ChatGLM3#370]
现有规章制度为一批docx文档，约50个，内容格式包含章、条款，如下图，现需要用这些数据做微调训练，希望实现问答文档相关内容，请问数据集应该如何设置
![(6COJ }TL66$CMZLZ0R}{UL](https://github.com/THUDM/ChatGLM3/assets/50041220/abb92471-8fcd-4553-9ac2-e9908499011a)

**Comment by shenmadouyaowen** [comment]
我也想找一个文档直接能生成微调格式的模型或者库
现在用的办法是文章复制给大模型，然后根据文章内容提问，返回自己需要的格式

**Comment by Fmaj7** [comment]
这种方法试过了，让模型根据内容生成问题以及对应的答案，错漏还是比较多

**Comment by zRzRzRzRzRzRzR** [comment]
这种要用知识库，不适合微调

**Comment by Fmaj7** [comment]
就是检索匹配了？

**Comment by Fmaj7** [comment]
请问有没类似的案例可参考？

**Comment by zRzRzRzRzRzRzR** [comment]
可以去中间件的仓库，例如langchain-chatchat,db-gpt的社群寻求更多案例

**Comment by Fmaj7** [comment]
谢谢，找到langchain-chatchat社群了
