### ISSUE TITLE
请问我用git运行P-Tuning v2 微调的脚本文件出现这个问题该怎么解决？

### ISSUE THREAD

**Issue by CapenZen** [THUDM/ChatGLM3#372]
Capen@DESKTOP-67HE1T7 MINGW64 /c/ChatGLM3-main/finetune_demo
$ ./scripts/finetune_pt.sh
++ PRE_SEQ_LEN=128
++ LR=2e-2
++ NUM_GPUS=1
++ MAX_SOURCE_LEN=1024
++ MAX_TARGET_LEN=128
++ DEV_BATCH_SIZE=1
++ GRAD_ACCUMULARION_STEPS=32
++ MAX_STEP=1000
++ SAVE_INTERVAL=500
+++ date +%Y%m%d-%H%M%S
++ DATESTR=20231120-121515
++ RUN_NAME=advertise_gen_pt
++ BASE_MODEL_PATH=C://ChatGLM3-main//THUDM//chatglm3-6b//
++ DATASET_PATH=C://ChatGLM3-main//finetune_demo//AdvertiseGen//advertise_gen.jsonl
++ OUTPUT_DIR=output/advertise_gen_pt-20231120-121515-128-2e-2
++ mkdir -p output/advertise_gen_pt-20231120-121515-128-2e-2
++ torchrun --standalone --nnodes=1 --nproc_per_node=1 finetune.py --train_format input-output --train_file C://ChatGLM3-main//finetune_demo//AdvertiseGen//advertise_gen.jsonl --preprocessing_num_workers 1 --model_name_or_path C://ChatGLM3-main//THUDM//chatglm3-6b// --output_dir output/advertise_gen_pt-20231120-121515-128-2e-2 --max_source_length 1024 --max_target_length 128 --per_device_train_batch_size 1 --gradient_accumulation_steps 32 --max_steps 1000 --logging_steps 1 --save_steps 500 --learning_rate 2e-2 --pre_seq_len 128
++ tee output/advertise_gen_pt-20231120-121515-128-2e-2/train.log
failed to create process.

**Comment by zRzRzRzRzRzRzR** [comment]
未能复现，请提供一下你的错误代码和更多环境信息

**Comment by CapenZen** [comment]
> 未能复现，请提供一下你的错误代码和更多环境信息
你好，我是在win10环境下使用git运行finetune_demo来微调模型，但出现了failed to create process这一行报错，无法成功进行微调。但还是在生成了output文件夹下的train.log这个文件，这个日志文件里也只有failed to create process这一行。请问是什么原因？

**Comment by CapenZen** [comment]
#! /usr/bin/env bash

set -ex

PRE_SEQ_LEN=128
LR=2e-2
NUM_GPUS=1
MAX_SOURCE_LEN=1024
MAX_TARGET_LEN=128
DEV_BATCH_SIZE=1
GRAD_ACCUMULARION_STEPS=32
MAX_STEP=1000
SAVE_INTERVAL=500

DATESTR=`date +%Y%m%d-%H%M%S`
RUN_NAME=advertise_gen_pt

BASE_MODEL_PATH=C:\\ChatGLM3-main\\THUDM\\chatglm3-6b\\
DATASET_PATH=C:\\ChatGLM3-main\\finetune_demo\\AdvertiseGen//advertise_gen.jsonl
OUTPUT_DIR=output/${RUN_NAME}-${DATESTR}-${PRE_SEQ_LEN}-${LR}

mkdir -p $OUTPUT_DIR

torchrun --standalone --nnodes=1 --nproc_per_node=$NUM_GPUS finetune.py \
    --train_format input-output \
    --train_file $DATASET_PATH \
    --preprocessing_num_workers 1 \
    --model_name_or_path $BASE_MODEL_PATH \
    --output_dir $OUTPUT_DIR \
    --max_source_length $MAX_SOURCE_LEN \
    --max_target_length $MAX_TARGET_LEN \
    --per_device_train_batch_size $DEV_BATCH_SIZE \
    --gradient_accumulation_steps $GRAD_ACCUMULARION_STEPS \
    --max_steps $MAX_STEP \
    --logging_steps 1 \
    --save_steps $SAVE_INTERVAL \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN 2>&1 | tee ${OUTPUT_DIR}/train.log   这是我的finetune_demo文件下的内容，我并未做太多修改。

**Comment by zhengheji** [comment]
咋解决的啊，有没有大佬说一下，我也这个问题
