### ISSUE TITLE
ModuleNotFoundError: No module named 'mdtex2html'

### ISSUE THREAD

**Issue by SwarmKit** [THUDM/ChatGLM3#373]
### System Info / 系統信息

CentOS 7.9
Python 3.10.13
Driver Version: 515.43.04
CUDA Driver Version: 11.7

### Who can help? / 谁可以帮助到您？

NO

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

(ChatGLM3) [root@ChatGLM3-6B basic_demo]# python web_demo.py 
Traceback (most recent call last):
  File "/data/ChatGLM3/basic_demo/web_demo.py", line 3, in <module>
    import mdtex2html
ModuleNotFoundError: No module named 'mdtex2html'

### Expected behavior / 期待表现

NO ERROR

**Comment by zRzRzRzRzRzRzR** [comment]
pip install md2html
