### ISSUE TITLE
ChatGLM3微调轮次

### ISSUE THREAD

**Issue by CNUIGB** [THUDM/ChatGLM3#374]
### System Info / 系統信息

python 3.11.5 其余为官方推荐
![微信截图_20231120140024](https://github.com/THUDM/ChatGLM3/assets/103934790/03296a30-b0d2-46b2-a7b2-892119e26b94)
这里的轮次是在哪里调整？

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![微信截图_20231120140032](https://github.com/THUDM/ChatGLM3/assets/103934790/603756ed-d981-4ca9-bc12-a4af1a185e56)
我并没有在这里找到轮次相关的参数

### Expected behavior / 期待表现

希望能有大佬解释一下

**Comment by zRzRzRzRzRzRzR** [comment]
max_step, 这里应该把这个地方设置小，如果数据很大，文档应该有出入，我改一下

**Comment by CNUIGB** [comment]
> max_step, 这里应该把这个地方设置小，如果数据很大，文档应该有出入，我改一下

为什么是这样呀，数据量越少，max_step越大，可以解释一下吗

**Comment by zRzRzRzRzRzRzR** [comment]
数据太少，学不会

**Comment by Circle1688** [comment]
这个轮次就是设置max_step吗？例如1万条数据，max_step推荐为2的意思？

**Comment by CNUIGB** [comment]
> 这个轮次就是设置max_step吗？例如1万条数据，max_step推荐为2的意思？

应该不是吧，这里说是有出入，可以看看新文档，作者已经更新了
