### ISSUE TITLE
ChatGLM-Efficient-Tuning是否可以进行微调GLM3

### ISSUE THREAD

**Issue by YMXT** [THUDM/ChatGLM3#378]
### Feature request  / 功能建议

有人试过吗

### Motivation / 动机

微调GLM3框架

### Your contribution / 您的贡献

无

**Comment by lwj2001** [comment]
那名作者做了另外一个工程：https://github.com/hiyouga/LLaMA-Factory，这里似乎可以微调chatglm3

**Comment by lwj2001** [comment]
那名作者做了另外一个工程：https://github.com/hiyouga/LLaMA-Factory
这里似乎可以微调chatglm3

**Comment by zRzRzRzRzRzRzR** [comment]
用这个 https://github.com/hiyouga/LLaMA-Factory 可以
