### ISSUE TITLE
chat-glm3 6B  和 chat-glm3 6B Base 什么区别？ 我看是分开放模型的

### ISSUE THREAD

**Issue by leoluopy** [THUDM/ChatGLM3#38]
如题

**Comment by leoluopy** [comment]
ChatGLM3系列有三个版本：基础大语言模型ChatGLM3-6B-Base、对话调优大语言模型ChatGLM3-6B和长文本对话大语言模型ChatGLM3-6B-32K

**Comment by darkwhale** [comment]
我的理解是base版本的是指经过预训练的，chat版本的使用了sft指令微调和强化学习进行了对齐，不知道理解的对不对
