### ISSUE TITLE
openai_api_demo/openai_api.py 里面没有observation

### ISSUE THREAD

**Issue by quzx** [THUDM/ChatGLM3#381]
### System Info / 系統信息

transformer 4.32.2

### Who can help? / 谁可以帮助到您？

@abmfy   openai_api_demo/openai_api.py 里面没有observation ,那如何用tool?

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

openai_api_demo/openai_api.py 里面没有observation

### Expected behavior / 期待表现

请介绍一下

**Comment by longerking** [comment]
在openai_api_demo/utill.py下有， openai_api.py 调用了 utils.py 的方法 ，同时模型中observation role，对应到model是function role！
