### ISSUE TITLE
多卡部署时显存无法充分利用

### ISSUE THREAD

**Issue by LeoLeeYM** [THUDM/ChatGLM3#383]
### System Info / 系統信息

Cuda：12.2
Python：3.11
System：Windows Server 2022

CPU：Intel i7-8700K
GPU：NVIDIA P104-100 *3
RAM：Kingston 2666 DDR4 8G *3

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在使用openai_api示例中，我将显卡调用数量调整为三张，我的设备上有3张正常工作的NVIDIA P104-100，但我发现模型无法将显卡显存充分利用，当调用数量为2张时，平均每张显卡占用6.5/8GB，而3张显卡时仅有4.4/8GB，会随着显卡使用的数量而降低显卡的现存利用率，但Cuda性能可以充分利用。

### Expected behavior / 期待表现

应当充分利用GPU的显存

**Comment by zRzRzRzRzRzRzR** [comment]
多卡并发建议使用专用的并发框架，官方框架仅仅是能跑，在专用框架下自己稍作修改能实现更好的并发
