### ISSUE TITLE
希望chatglm3增加S-LoRA功能

### ISSUE THREAD

**Issue by wengyuan722** [THUDM/ChatGLM3#384]
### Feature request  / 功能建议

这个功能目前刚起步，可以使用有关主模型叠加多个lora同时跑，希望这个项目能够适配这个功能

### Motivation / 动机

多个lora同时跑，这个方案类似rag，会比rag更强，希望能够支持

### Your contribution / 您的贡献

原项目：https://github.com/S-LoRA/S-LoRA

**Comment by zRzRzRzRzRzRzR** [comment]
目前官方暂时没有关于该功能的计划，您可以提出一个完整的PR方案，这将推动我们往这方向进行适配

**Comment by junior-zsy** [comment]
@wengyuan722 https://github.com/Yard1/vllm/tree/multi_lora 这个可以满足你的需要，vllm 加速 和 S-LoRA ，支持 chatglm 系列
