### ISSUE TITLE
SFT训练数据加反例

### ISSUE THREAD

**Issue by quzx** [THUDM/ChatGLM3#385]
### Feature request  / 功能建议

之前在这里，还是chatglm，issues，看到了说SFT效果不理想，可以加反例，大致这个意思，不是这么说的；现在找不到出处了，哪位能够介绍一下吗？非常感谢。

### Motivation / 动机

提高微调质量

### Your contribution / 您的贡献

暂无

**Comment by zRzRzRzRzRzRzR** [comment]
目前微调都是正样本，没有负样本，代码是这么设计的
