### ISSUE TITLE
请教demo_tool.py

### ISSUE THREAD

**Issue by quzx** [THUDM/ChatGLM3#388]
### System Info / 系統信息

transformer 4.32.2

### Who can help? / 谁可以帮助到您？

@abmfy   demo_tool.py   148行，已经添加了历史，用role.tool,  175行又用role.observation(本质function) 添加了历史；
我看很多应用都只做了后面动作，没有前者， 而且在tool_using/readme 中也没有用到前者，请问为何？谢谢

https://github.com/xusenlinzy/api-for-open-llm/blob/master/examples/chatglm3/tool_using.py  也没有出现这里的148行，只有175行的内容。

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

demo.tool.py 148行

### Expected behavior / 期待表现

越来越好

**Comment by abmfy** [comment]
148 行是将模型给出的工具调用添加到历史中，175 行添加的是工具执行的结果。这里手动维护历史是为了在 UI 中区别显示（因为 streamlit 的一些奇怪的渲染特性）。
tool_using 中直接让模型 model.chat 函数来维护历史，因此调用 model.chat 后如果模型调用了工具，返回的 history 中会正确更新角色为 tool 的一轮对话，因此实际上也是有用到前者的。
api-for-open-llm 似乎使用了不一样的交互格式，在 37-43 行中，添加的一轮对话同时包含了调用的工具和结果。
总之只需要让模型以给定的格式看到调用了工具 (角色为 <|assistant|>[tool_name]）和结果（角色为 observation）即可

**Comment by quzx** [comment]
谢谢
