### ISSUE TITLE
微调报错

### ISSUE THREAD

**Issue by stingbo** [THUDM/ChatGLM3#391]
### System Info / 系統信息

pip install transformers[torch]
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: transformers[torch] in /opt/work/miniconda3/lib/python3.10/site-packages (4.30.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/work/miniconda3/lib/python3.10/site-packages (from transformers[torch]) (6.0)
Requirement already satisfied: safetensors>=0.3.1 in /opt/work/miniconda3/lib/python3.10/site-packages (from transformers[torch]) (0.3.1)
Requirement already satisfied: numpy>=1.17 in /opt/work/miniconda3/lib/python3.10/site-packages (from transformers[torch]) (1.25.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /opt/work/miniconda3/lib/python3.10/site-packages (from transformers[torch]) (0.13.3)
Requirement already satisfied: requests in /opt/work/miniconda3/lib/python3.10/site-packages (from transformers[torch]) (2.28.1)
Requirement already satisfied: tqdm>=4.27 in /opt/work/miniconda3/lib/python3.10/site-packages (from transformers[torch]) (4.65.0)
Requirement already satisfied: packaging>=20.0 in /opt/work/miniconda3/lib/python3.10/site-packages (from transformers[torch]) (23.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /opt/work/miniconda3/lib/python3.10/site-packages (from transformers[torch]) (0.15.1)
Requirement already satisfied: filelock in /opt/work/miniconda3/lib/python3.10/site-packages (from transformers[torch]) (3.12.2)
Requirement already satisfied: regex!=2019.12.17 in /opt/work/miniconda3/lib/python3.10/site-packages (from transformers[torch]) (2023.6.3)
Requirement already satisfied: accelerate>=0.20.2 in /opt/work/miniconda3/lib/python3.10/site-packages (from transformers[torch]) (0.24.1)
Requirement already satisfied: torch!=1.12.0,>=1.9 in /opt/work/miniconda3/lib/python3.10/site-packages (from transformers[torch]) (2.0.1)
Requirement already satisfied: psutil in /opt/work/miniconda3/lib/python3.10/site-packages (from accelerate>=0.20.2->transformers[torch]) (5.9.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/work/miniconda3/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.14.1->transformers[torch]) (4.8.0)
Requirement already satisfied: fsspec in /opt/work/miniconda3/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.14.1->transformers[torch]) (2023.6.0)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (10.9.0.58)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (11.7.4.91)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (11.7.91)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (10.2.10.91)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (11.10.3.66)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (11.7.101)
Requirement already satisfied: sympy in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (1.12)
Requirement already satisfied: jinja2 in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (3.1.2)
Requirement already satisfied: networkx in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (3.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (11.7.99)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (8.5.0.96)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (2.14.3)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (11.4.0.1)
Requirement already satisfied: triton==2.0.0 in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (2.0.0)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /opt/work/miniconda3/lib/python3.10/site-packages (from torch!=1.12.0,>=1.9->transformers[torch]) (11.7.99)
Requirement already satisfied: wheel in /opt/work/miniconda3/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch!=1.12.0,>=1.9->transformers[torch]) (0.38.4)
Requirement already satisfied: setuptools in /opt/work/miniconda3/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch!=1.12.0,>=1.9->transformers[torch]) (65.6.3)
Requirement already satisfied: cmake in /opt/work/miniconda3/lib/python3.10/site-packages (from triton==2.0.0->torch!=1.12.0,>=1.9->transformers[torch]) (3.26.4)
Requirement already satisfied: lit in /opt/work/miniconda3/lib/python3.10/site-packages (from triton==2.0.0->torch!=1.12.0,>=1.9->transformers[torch]) (16.0.6)
Requirement already satisfied: charset-normalizer<3,>=2 in /opt/work/miniconda3/lib/python3.10/site-packages (from requests->transformers[torch]) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/work/miniconda3/lib/python3.10/site-packages (from requests->transformers[torch]) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /opt/work/miniconda3/lib/python3.10/site-packages (from requests->transformers[torch]) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/work/miniconda3/lib/python3.10/site-packages (from requests->transformers[torch]) (3.4)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/work/miniconda3/lib/python3.10/site-packages (from jinja2->torch!=1.12.0,>=1.9->transformers[torch]) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /opt/work/miniconda3/lib/python3.10/site-packages (from sympy->torch!=1.12.0,>=1.9->transformers[torch]) (1.3.0)

which python
/opt/work/miniconda3/bin/python

uname -a
Linux VM-0-4-ubuntu 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

./scripts/finetune_pt_multiturn.sh 
+ PRE_SEQ_LEN=128
+ LR=2e-2
+ NUM_GPUS=1
+ MAX_SEQ_LEN=2048
+ DEV_BATCH_SIZE=1
+ GRAD_ACCUMULARION_STEPS=16
+ MAX_STEP=1000
+ SAVE_INTERVAL=500
++ date +%Y%m%d-%H%M%S
+ DATESTR=20231121-151111
+ RUN_NAME=tool_alpaca_pt
+ BASE_MODEL_PATH=/opt/projects/chatglm3-6b
+ DATASET_PATH=/opt/projects/chatglm3-test/data/tuning_dish_data.json
+ OUTPUT_DIR=output/tool_alpaca_pt-20231121-151111-128-2e-2
+ mkdir -p output/tool_alpaca_pt-20231121-151111-128-2e-2
+ torchrun --standalone --nnodes=1 --nproc_per_node=1 finetune.py --train_format multi-turn --train_file /opt/projects/chatglm3-test/data/tuning_dish_data.json --max_seq_length 2048 --preprocessing_num_workers 1 --model_name_or_path /opt/projects/chatglm3-6b --output_dir output/tool_alpaca_pt-20231121-151111-128-2e-2 --per_device_train_batch_size 1 --gradient_accumulation_steps 16 --max_steps 1000 --logging_steps 1 --save_steps 500 --learning_rate 2e-2 --pre_seq_len 128
+ tee output/tool_alpaca_pt-20231121-151111-128-2e-2/train.log
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
Traceback (most recent call last):
  File "finetune.py", line 165, in <module>
    main()
  File "finetune.py", line 53, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/hf_argparser.py", line 346, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 116, in __init__
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/training_args.py", line 1340, in __post_init__
    and (self.device.type != "cuda")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/training_args.py", line 1764, in device
    return self._setup_devices
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/transformers/training_args.py", line 1672, in _setup_devices
    raise ImportError(
ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.20.1`: Please run `pip install transformers[torch]` or `pip install accelerate -U`
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2385755) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-21_15:11:18
  host      : localhost.localdomain
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2385755)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

### Expected behavior / 期待表现

希望找到原因

**Comment by zRzRzRzRzRzRzR** [comment]
大概率是pytorch问题，将这个错误上网查询一下，
另外，你是多卡的话才要分布启动

**Comment by stingbo** [comment]
> 大概率是pytorch问题，将这个错误上网查询一下， 另外，你是多卡的话才要分布启动

嗯嗯 ，谢谢！
我现在手动启动：
python scripts/finetune.py --train_format input-output --train_file /opt/projects/chatglm3-test/data/tuning_dish_data.json --preprocessing_num_workers 1 --model_name_or_path /opt/projects/chatglm3-6b --output_dir output/tool_dish_pt-20231121-153251-128-2e-2 --max_source_length 1024 --max_target_length 128 --per_device_train_batch_size 1 --gradient_accumulation_steps 32 --max_steps 1000 --logging_steps 1 --save_steps 500 --learning_rate 2e-2 --pre_seq_len 128

报错：
Traceback (most recent call last):
  File "/opt/projects/chatglm3-test/scripts/finetune.py", line 171, in <module>
    main()
  File "/opt/projects/chatglm3-test/scripts/finetune.py", line 137, in main
    print(train_dataset[0]['input_ids'])
  File "/opt/projects/chatglm3-test/scripts/preprocess_utils.py", line 127, in __getitem__
    a_ids = self.tokenizer.encode(text=data_item['prompt'], add_special_tokens=True, truncation=True,
KeyError: 'prompt'

我调试打印是在这个里面：
    with open(data_args.train_file, "r", encoding="utf-8") as f:
        if data_args.train_file.endswith(".json"):
            train_data = json.load(f)
        elif data_args.train_file.endswith(".jsonl"):
            train_data = [json.loads(line) for line in f]

    if data_args.train_format == "multi-turn":
        train_dataset = MultiTurnDataset(
            train_data,
            tokenizer,
            data_args.max_seq_length,
        )
    elif data_args.train_format == "input-output":
        train_dataset = InputOutputDataset(
            train_data,
            tokenizer,
            data_args.max_source_length,
            data_args.max_target_length,
        )
    else:
        raise ValueError(f"Unknown train format: {data_args.train_format}")

    print("--------------------------:")
    print(train_data)
    print(train_dataset)
    print(train_dataset[0]['input_ids'])
    print(train_dataset[0]['labels'])
    if training_args.local_rank < 1:
        sanity_check(train_dataset[0]['input_ids'], train_dataset[0]['labels'], tokenizer)

打印结果：
[{'conversations': [{'role': 'system', 'content': '你是一名资深大厨，对做菜使用的食材了如指掌，现在你掌握了食材列表：[白条鸡,鸡胸肉,鸡翅,其他鸡肉类,鸡腿,鸡爪,鸡脖子,鸡翅根,鸡冠,鸡架,鸡脚筋,鸡皮,鸡肉串,鸡头,鸡胸软骨,鸡腰子,鸡油,鸡杂,鸡胗,掌中宝,五花肉,臀尖,里脊肉,其他猪肉类,猪副产品,前腿肉,猪肩颈肉,猪肉类,后腿肉,奶脯肉,乳猪,糟头肉,整头猪,正宝肋,猪白条,猪腱子,猪肉串,猪碎肉,鹌鹑肉,鳄鱼肉,鹿肉,驴肉,骆驼肉,鸵鸟肉,鹧鸪肉,牛腱子肉,牛腩,牛肋条,牛排,肥牛,其他牛肉类,牛肉类,牛里脊,牛上脑,牛眼肉,牛副产品,牛霖,牛肉串,牛肉卷,牛碎肉,牛仔骨,雪花牛肉,鸡蛋,鸭蛋,其他蛋类,鹌鹑蛋,鹅蛋,鸽子蛋,甲鱼蛋,皮蛋,特种蛋,咸蛋,种蛋,鳊鱼,草鱼,鲳鱼,带鱼,桂鱼,黄鱼,黄辣丁,黄鳝,鲫鱼,鲤鱼,鳢鱼,鲢鱼,鲈鱼,鳗鱼,泥鳅,鲶鱼,青鱼,石斑鱼,银鱼,金枪鱼,小龙虾,对虾,海鳖虾,海麻虾,红虾,虎虾,基围虾,九节虾,老虎虾,蛎虾,龙虾,蝼蛄虾,米虾,牡丹虾,皮皮虾,青虾,大闸蟹,蟛蜞,青蟹,软壳蟹,沙蟹,山螃蟹,石蟹,梭子蟹,铁蟹,蛙型蟹,香槟蟹,雪蟹,岩头蟹,长脚蟹,招潮蟹,珍宝蟹,水饺,蒸饺,包子/馒头,馅饼,其他面点,馄饨/云吞,特色甜点,米制品,羊肉串类,牛肉串类,鸡肉串类,其他串类,鱼糜类,肉糜类,其他丸滑,虾滑,猪肉类菜,鸡肉类,牛羊肉类,其他预制菜,水产类,素菜类,鸡肉类菜,白菜,菠菜,菜苔儿菜,春菜,豆瓣菜,番杏,荠菜,芥菜,菊苣,空心菜,藜蒿,萝卜菜,麻叶菜,木耳菜,牛皮菜,芹菜,生菜,水晶菜,丝瓜尖,塌菜,茼蒿,娃娃菜,莴笋,苋菜,香菜,小白菜,银丝菜,油麦菜,玉兰菜,紫菘,板薯,佛手瓜根,葛根魔芋,根芹,广芋,红薯,胡萝卜,姜薯,芥菜头,凉薯,芦笋,萝卜,毛薯,木薯,糯米薯,盘菜,山药,山药豆,甜菜头,土豆,土耳茗,鲜百合,雪莲果,芋头,竹笋,竹芋,紫薯,茄子,辣椒,秋葵,西红柿,鲜玉米,玉米笋,白玉豆,扁豆,蚕豆,刀豆,豆角,狗爪豆,荷兰豆,毛豆,四季豆,四棱豆,豌豆,油豆角,白参菌,白葱菌,白灵菇,白蚁谷堆伞,白玉菇,鲍鱼菇,北虫草,剥皮菇,草菇,茶树菇,赤松茸,大球盖菇,鹅蛋菌,凤尾菇,干巴菌,海鲜菇,荷灵菇,荷叶蘑,褐蘑,红菇,猴脑菌,猴头菇,虎奶菇,虎松茸,虎掌菌,花脸蘑,滑子菇,桦剥管菌,黄蘑,鸡枞菌,鸡腿菇,姬菇,姬松茸,见手青,金针菇,喇叭菌,老人头菌,梨菇,荔枝菌,栗蘑,灵芝菇,硫磺菌,柳花菜,柳香蘑,龙爪菇,鹿茸菇,马鞍菌,马勃菇,马桑菌,毛尖蘑,铆钉菇,密环菌,蘑菇,奶浆菌,牛肝菌,牛舌菌,平菇,青杠菌,青头菌,清头菌,扫把菇,珊瑚菌,扇贝菇,石耳,树秋菌,双孢菇,思壮赤菇,松露,松蘑,松茸,松乳菇,松树菌,乌米菌,乌油菌,虾米菇,香菇,香菇脚,香乳菇,蟹味菇,杏鲍菇,熊掌菇,秀珍菇,绣球菌,雪莲菇,羊肚耳,羊肚菌,银耳,银盘蘑菇,隐孔菌,榆耳,元蘑,榛蘑,猪肚菇,猪苓菌,竹菌,紫丁香蘑,紫花菌,调味酱,调味汁,榨菜/腌菜,调味料,香辛料,海产干货,山珍干货,滋补干货,粉丝粉条,面粉,大米,杂粮,其他米面杂粮,菜籽油,大豆油,稻米油,调和油,橄榄油,核桃油,花生油,葵花籽油,其他油种,山茶油,亚麻籽油,玉米油,其他豆腐,豆腐干,豆腐皮,其他豆制品,小食,肠类,酱卤类,火腿培根,汉堡饼,蛋制品,其他调理品,海参,海肠,海胆,海兔,海蜇,蚂蟥,墨鱼,泥丁,海螺,沙虫,鱿鱼,章鱼,黄油,奶酪,稀奶油,其他奶制品,蚌,鲍鱼,蛏子,淡水螺,蛤蜊,海鲜礼盒装,鸟贝,七彩贝,青口,扇贝,生蚝,蚬子,象拔蚌,珍珠贝,竹蛏,紫石房蛤,芭蕉花,菜用金雀花,核桃花,槐树花,黄瓜花,黄花菜,火龙果花,韭菜花,苦刺花,南瓜花,棠梨花,野葱花,夜兰花,夜香花,摘蒙花,葱头,葱仔,大葱,大蒜,风姜,茖葱,红球姜,韭菜,韭黄,韭苔,蕌头,南姜,沙葱,沙姜,山姜,生姜,蒜荅,蒜黄,蒜苗,小葱,阳荷,洋葱,洋姜,野蒜,紫（黑）姜,白条鹅,鹅肉类,包菜,花菜,芥蓝,苤蓝,西兰花,西兰苔,橙子,柑桔,金桔,柠檬,柚子,菜瓜,地蒲,冬瓜,杜瓜,佛手瓜,红瓜,葫芦,瓠瓜,黄瓜,金丝绞瓜,苦瓜,南瓜,梢瓜,蛇瓜,丝瓜,套菜,西葫芦,八月瓜,地稍瓜,哈密瓜,火参果,九月瓜,甜瓜,西瓜,刺梨,钙果,拐枣,海棠果,黑老虎,红参果,红毛丹,黄皮果,黄桃,梨,李子,毛桃,蜜桃,蟠桃,枇杷,苹果,青梅,人参果,沙果,山楂,蛇皮果,石榴,释迦果,西梅,鲜枣,杏,杨梅,樱桃,油桃,淡奶油,烘焙调味,烘焙辅料,其他原料,食品添加,糖粉/糖霜,馅料,白刺果,百香果,草莓,杈杷果,灯笼果,姑娘果,黑果花楸果,黑莓,蓝靛果,蓝莓,马蹄,蔓越莓果,猫屎瓜,猕猴桃,牛奶果,葡萄,桑葚,沙棘果,神秘果,圣女果,柿子,树莓,树葡萄,桃金娘,无花果,仙人掌果,羊奶果,野地瓜,芭蕉,菠萝,菠萝蜜,大果藤黄,蛋黄果,番石榴,甘蔗,橄榄,黄晶果,火龙果,金心果,荔枝,莲雾,榴莲,榴莲蜜,龙功果,龙眼,妈咪果,芒果,木鳖果,木瓜,牛油果,诺丽果,苹婆果,人心果,山竹,香蕉,杨桃,椰子,余甘果,慈菇,浒苔,茭白,莲藕,莲蓬,菱角,鹿角菜,藕带,蒲菜,芡实杆,鲜芡实,荇菜,白条鸭,其他鸭肉类,鸭脖子,鸭肠,鸭翅,鸭翅根,鸭架,鸭肉类,鸭舌,鸭头,鸭腿,鸭血,鸭腰子,鸭油,鸭杂,鸭掌,鸭胗,刺老芽,豆芽,佛手瓜藤尖,枸杞芽,花椒芽,花生芽,柳蒿芽,龙柏芽,萝卜芽,木兰芽,苜蓿芽,嫩豆苗,荞麦芽,芹芽,桑芽,沙松尖,松柳芽,甜菜苗,豌豆苗,香椿芽,小麦芽,油葵芽,芋芽,其他羊肉类,羊排,羊腿肉,羊肉类,白条羊,羊副产品,羊肉串,羊肉卷,羊碎肉,芭蒿,白蒿菜,宝塔菜,冰草,臭菜,莼菜,刺芹,刺五加菜,大叶芹,地莲花,地皮菜,刁草,东风菜,冬寒菜,发菜,富贵菜,贡菜,构树穗,姑娘菜,红薯叶,猴腿菜,黄须菜,黄芽杆,灰灰菜,茴香,茴香头,火镰菜,碱蓬草,金花菜,救心菜,蕨菜,苦菜,苦楮果,苦菊,苦老芽,苦藤花,苦叶菜,苦斋菜,苦子,辣根,辣木菜,郎菜,簕菜,龙蒿,芦苇笋,罗勒,马齿苋,马兰头,马蹄叶,猫爪子,迷迭香,面条菜,南瓜藤,柠檬叶,牛尾菜,蒲公英菜,青蒿,清明菜,曲曲菜,人参菜,扫帚菜,山根菜,山胡萝卜,山露菜,山蚂蚱菜,山苜楂,山苏菜,山野菜,山油菜,山萮菜,珊瑚菜,伤力草,树花菜,树仔菜,水香菜,田七菜,薇菜,芗草,香茅草,象耳朵叶,象牙菜,小蓟草,新鲜板蓝根,新鲜紫苏,雪樱子,血通菜,洋蓟,野莲,野芹菜,野苋菜,银条菜,鱼腥草,榆钱,芋梗,云参,长寿菜,蜇麻子菜,珍珠花菜,芝麻菜,芝麻叶,紫背天葵,棕包,鸽肉,猪排骨,猪蹄,猪骨头,猪肘子,喉头,其他猪副产品,猪鞭,猪肠,猪肠衣,猪蛋,猪肚,猪耳朵,猪肥膘,猪肺,猪肝,猪骨髓,猪黃喉,猪金钱,猪卵子,猪脑,猪皮,猪皮冻,猪舌,猪蹄筋,猪天梯,猪尾巴,猪心,猪心管,猪血,猪眼睛,猪腰子,猪油,猪杂,猪嘴,毛肚,牛百叶,牛鞭,牛肠,牛肚,牛耳,牛肺管,牛睾丸,牛骨,牛骨髓,牛黄喉,牛脊骨,牛筋,牛肋排,牛脑,牛皮,牛舌,牛肾,牛蹄,牛蹄筋,牛天梯,牛尾,牛血,牛眼睛,牛油,牛杂,牛嘴巴,其他牛副产品,羊蝎子,其他羊副产品,羊百叶,羊宝,羊脖子,羊肠,羊肠衣,羊肚,羊骨,羊筋,羊脸,羊脑,羊皮,羊蹄,羊头,羊尾巴,羊心管,羊血,羊眼睛,羊腰,羊油,羊杂,兔肉,鸡肾,鸭心,鹅肝,鹅肠,鹅掌,鹅头,鹅舌,鹅胗,鹅血,鹅脖,鹅心,鹅翅,鹅肾,石蛋,毛蛋,牛蛙,青蛙,石蛙,美蛙,蟾蜍,林蛙,腐竹,木耳,海带,其他蔬菜,白鳝,钳鱼,胖头鱼,半边鱼,其他鱼类,三文鱼,鲷鱼,鳕鱼,秋刀鱼,鳜鱼,清江鱼,巴沙鱼,罗非鱼,多春鱼,龙利鱼,甲鱼,波士顿龙虾,斑节虾,罗氏虾,其他蟹类,其他贝类,鱼豆腐,豆腐乳,冻豆腐,豆腐泡,千页豆腐,日本豆腐,鲜豆腐,老豆腐,卷饼,面筋,拉面,意大利面,焖面,烩面,方便面,炸酱面,凉面/冷面,拌面,其他面条,面包蟹,面包,比萨,炒饭,螺蛳粉,肠粉,凉粉,盖饭,肉夹馍,花生,粥类,猪头肉,牛头肉,叉烧饭,其他米饭,烧麦,其他菜类,耗儿鱼,油条,千张,臭豆腐,黄花鱼,多宝鱼,蒲公英,米线,鮰鱼,知了,刀鱼,蚕蛹,蜂蛹,牛心,折耳根,羊鞭,河豚,鲟鱼,马步鱼,牛胸腹肉,羊里脊,粽子,鱼胶,捞饭,河粉,泡菜,拌饭,其他水果,其他海鲜,咸菜,裙带菜,紫菜,龙须菜,海白菜,寿司,海带菜,海带芽,海带花,凉皮,灌汤包,水母,鱼皮,北极虾,鱼杂,羊腩,其他菌菇,金耳,鲮鱼,鲥鱼,其他粉丝,年糕,马面鱼,青团,青斑,沙丁鱼,龙头鱼,红娘鱼,银鳕鱼,鸡心,带子螺,鳐鱼,豇豆,养心菜,白鱼,牛丸,煎饺,羊肝,冬虫夏草,其他虾类,牛肩颈肉,青占鱼,热狗,豆腐脑,鹰嘴豆,鲣鱼,疙瘩汤,鸡三角,饭团,玉女瓜,板栗,臭豆干,豆花,翘嘴鲌,人参,牛肝,比目鱼,羊上脑,羊心,艾蒿,酸菜,羊拐,猪脸,牛头皮,白水鱼,羊角蜜,郡把,郡把,其他豆类,其他果类,鲱鱼,北极贝,拉皮,石斛,蚶子,红杉鱼,酸辣汤,素肉,馓子,夜来香,白瓜,鸡肉丸,鲅鱼,郡把,藠头,牛护心肉,猪护心肉]，请仔细遵循用户的说明，只从食材列表里选择食材，使用json格式进行响应。'}, {'role': 'user', 'content': '你好，资深大厨，从你掌握的食材列表里选择菜品：[1250汁烧三文鱼腩寿司]的主要食材， 且只选择一个主要食材，返回json格式：{"dish_name":"菜品名称", "dish_main_material":"主要食材"}，不要其它说明'}, {'role': 'assistant', 'content': '{"dish_name": 1250汁烧三文鱼腩寿司, "dish_main_material": 三文鱼}'}, {'role': 'user', 'content': '你好，资深大厨，从你掌握的食材列表里选择菜品：[腊味红菜柳]的主要食材， 且只选择一个主要食材，返回json格式：{"dish_name":"菜品名称", "dish_main_material":"主要食材"}，不要其它说明'}, {'role': 'assistant', 'content': '{"dish_name": 腊味红菜柳, "dish_main_material": 菜苔儿菜}'}, {'role': 'user', 'content': '你好，资深大厨，从你掌握的食材列表里选择菜品：[红菜柳]的主要食材， 且只选择一个主要食材，返回json格式：{"dish_name":"菜品名称", "dish_main_material":"主要食材"}，不要其它说明'}, {'role': 'assistant', 'content': '{"dish_name": 红菜柳, "dish_main_material": 菜苔儿菜}'}, {'role': 'user', 'content': '你好，资深大厨，从你掌握的食材列表里选择菜品：[清炒菜柳]的主要食材， 且只选择一个主要食材，返回json格式：{"dish_name":"菜品名称", "dish_main_material":"主要食材"}，不要其它说明'}, {'role': 'assistant', 'content': '{"dish_name": 清炒菜柳, "dish_main_material": 菜苔儿菜}'}, {'role': 'user', 'content': '你好，资深大厨，从你掌握的食材列表里选择菜品：[铜锅滋补羊肉汤（永）【卡斯炉加长柄公勺】]的主要食材， 且只选择一个主要食材，返回json格式：{"dish_name":"菜品名称", "dish_main_material":"主要食材"}，不要其它说明'}, {'role': 'assistant', 'content': '{"dish_name": 铜锅滋补羊肉汤（永）【卡斯炉加长柄公勺】, "dish_main_material": 羊肉类}'}, {'role': 'user', 'content': '你好，资深大厨，从你掌握的食材列表里选择菜品：[份 干煸豆角 （小份菜）]的主要食材， 且只选择一个主要食材，返回json格式：{"dish_name":"菜品名称", "dish_main_material":"主要食材"}，不要其它说明'}, {'role': 'assistant', 'content': '{"dish_name": 份 干煸豆角 （小份菜）, "dish_main_material": 豆角}'}]}]
<preprocess_utils.InputOutputDataset object at 0x7fa81274c6a0>

这两个好像都是空的：
    print(train_dataset[0]['input_ids'])
    print(train_dataset[0]['labels'])
    
请问，是我的样本数据格式有问题吗？

**Comment by stingbo** [comment]
但是奇怪的是使用shell脚本启动报错，手动执行没问题

**Comment by zRzRzRzRzRzRzR** [comment]
微调的问题移动到 #253 一起解决，目前我们暂时无法复现你的情况，可能需要社区一起参与解决

**Comment by stingbo** [comment]
求教，假如微调之后保存的目录是output/test，然后怎么使用微调的结果呢？有没有使用示例？
@zRzRzRzRzRzRzR
