### ISSUE TITLE
MultiTurnDataset 疑问

### ISSUE THREAD

**Issue by blackxer** [THUDM/ChatGLM3#396]
您好 ，请问，MultiTurnDataset 实现代码， finetune_demo/preprocess_utils.py 文件第 97 行
```
target_based_loss_mask = [False] + loss_masks[:-1]
```
为什么要在开头加个 False 呢？

**Comment by BlueBlueFF** [comment]
同问

**Comment by zRzRzRzRzRzRzR** [comment]
loss mask是自动分配的

**Comment by valkryhx** [comment]
> loss mask是自动分配的

我想问下[False] + loss_masks[:-1]
这个第一个false对应的token是gmask吗？另外这里list去掉了loss masks的最后一个值 我想问下这个最后的值对应什么token呢 为何要把这个token的loss mask去掉呢
