### ISSUE TITLE
excel表格

### ISSUE THREAD

**Issue by ZTurboX** [THUDM/ChatGLM3#397]
用chatglm3如何对表格问答？excel表格模型输入形式是怎样的

**Comment by zRzRzRzRzRzRzR** [comment]
开源模型的目前没有官方代码支持，要自己做外设插件

**Comment by ZTurboX** [comment]
> 开源模型的目前没有官方代码支持，要自己做外设插件

可以请教一下，对于表格，模型的输入格式哪种会比较合适呢
