### ISSUE TITLE
model paths in web demos are pointing to local path

### ISSUE THREAD

**Issue by linzeyang** [THUDM/ChatGLM3#4]
In both web_demo.py and web_demo2.py the paths to ChatGLM3 model are pointing to a local path ```"/mnt/vepfs/workspace/zxdu/chatglm3-6b"```

eg.
```python
tokenizer = AutoTokenizer.from_pretrained("/mnt/vepfs/workspace/zxdu/chatglm3-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("/mnt/vepfs/workspace/zxdu/chatglm3-6b", trust_remote_code=True).cuda()
```

They probably should be corrected to hugging face hub format, like ```"THUDM/chatglm3-6b"```

**Comment by duzx16** [comment]
感谢指出，已修复
