### ISSUE TITLE
模型输出差异过大且与事实不符

### ISSUE THREAD

**Issue by Isaiah1013** [THUDM/ChatGLM3#401]
### System Info / 系統信息

![Screenshot from 2023-11-22 11-39-00](https://github.com/THUDM/ChatGLM3/assets/37605784/488e8aeb-23cc-4ec3-993f-53c79bfe8b6a)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1、在composite_demo文件下，修改client.py，使其支持多卡GPU推理，
2、执行streamlit run main.py 打开web ui
3、在Chat功能下，直接输入“讲述负荆请罪的故事”，其输出结果不符，可以从上传的图片看到，明显在乱说，
![Screenshot from 2023-11-22 11-46-43](https://github.com/THUDM/ChatGLM3/assets/37605784/2b2e088a-9125-406e-8513-5ed0c4a1edff)
而且夹杂中英文

### Expected behavior / 期待表现

能够正确输出结果

**Comment by zRzRzRzRzRzRzR** [comment]
中英文问题 请在 #225 提出更多例子
 差异过大需要降低温度
 与事实不符的话可能是模型训练中没有训练相关数据，建议外挂知识库
