### ISSUE TITLE
openai_api.py中是否可以添加个/v1/embeddings接口

### ISSUE THREAD

**Issue by shenyanping** [THUDM/ChatGLM3#402]
### Feature request  / 功能建议

openai_api.py中是否可以添加个/v1/embeddings接口

### Motivation / 动机

由于我们目前项目是采用openai的embeddings接口，当前想把openai替换为chatglm3，但是发现其并没有embeddings接口

### Your contribution / 您的贡献

https://github.com/THUDM/ChatGLM3/blob/main/openai_api_demo/openai_api.py

**Comment by zRzRzRzRzRzRzR** [comment]
我们没有embed模型呀，然后模型embed层的huggingface实现有点问题，接不上去
