### ISSUE TITLE
使用p-tuning的检查点进行推理时，pre-seq-len不一致

### ISSUE THREAD

**Issue by github-cuijian** [THUDM/ChatGLM3#404]
### System Info / 系統信息

Loading checkpoint shards: 100%|█████████████████████████████████████████| 7/7 [00:09<00:00,  1.40s/it]
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /data4/cuij_data/files/chatglm_model/chatglm3-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/home/cuij/ChatGLM3/finetune_demo/inference.py", line 28, in <module>
    model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
  File "/home/cuij/miniconda3/envs/chatglm3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PrefixEncoder:
	size mismatch for embedding.weight: copying a param with shape torch.Size([256, 14336]) from checkpoint, the shape in current model is torch.Size([128, 14336]).

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1、使用ptuning v2进行微调时，设定pre-seq-len为256。
2、使用如下指令加载检查点进行推理
```shell
python inference.py \
        --pt-checkpoint /home/cuij/chatglm_tune/checkpoint-2000 \
        --model /data4/cuij_data/files/chatglm_model/chatglm3-6b \
        --pt-pre-seq-len 256
```

### Expected behavior / 期待表现

我查看了inference.py，代码里虽然设置了--pt-pre-seq-len，但在加载模型时并没有使用，而是指定了pre-seq-len为128。inference.py中的具体代码如下，希望能修复。
```python
parser.add_argument("--pt-pre-seq-len", type=int, default=128, help="The pre-seq-len used in p-tuning")
……
if args.pt_checkpoint:
    tokenizer = AutoTokenizer.from_pretrained(args.tokenizer, trust_remote_code=True)
    config = AutoConfig.from_pretrained(args.model, trust_remote_code=True, pre_seq_len=128)
```

**Comment by zRzRzRzRzRzRzR** [comment]
mark，我们查看后会修复这个bug

**Comment by zRzRzRzRzRzRzR** [comment]
bug已经修复，感谢提出的issue
