### ISSUE TITLE
model.gradient_checkpointing_enable()出现错误

### ISSUE THREAD

**Issue by QDPeng** [THUDM/ChatGLM3#406]
### System Info / 系統信息

Centos7，python3.10，torch2.1，ChatGLM3-6b模型

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

首先是转换数据
./scripts/format_tool_alpaca.py --path "ToolAlpaca/data/train_data.json"

然后使用下载的glm3-6b模型进行微调训练
./scripts/finetune_pt_multiturn.sh

### Expected behavior / 期待表现

[WARNING|modeling_utils.py:3952] 2023-11-22 17:15:21,039 >> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /data1/liushunpeng/GitHub/SeawayBuild/ChatLM/GLM/zzmodel/chatglm3-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[INFO|modeling_utils.py:3525] 2023-11-22 17:15:21,041 >> Generation config file not found, using a generation config created from the model config.
Sanity Check >>>>>>>>>>>>>
           '[gMASK]':  64790 ->   -100
               'sop':  64792 ->   -100
        '<|system|>':  64794 ->   -100
                  '':  30910 ->   -100
                '\n':     13 ->   -100
            'Answer':  20115 ->   -100
               'the':    267 ->   -100
         'following':   1762 ->   -100
         'questions':   2554 ->   -100
                'as':    362 ->   -100
              'best':   1077 ->   -100
                'as':    362 ->   -100
               'you':    344 ->   -100
               'can':    457 ->   -100
                 '.':  30930 ->   -100
               'You':    809 ->   -100
              'have':    431 ->   -100
            'access':   1675 ->   -100
                'to':    289 ->   -100
               'the':    267 ->   -100
         'following':   1762 ->   -100
             'tools':   4159 ->   -100
                 ':':  30954 ->   -100
                '\n':     13 ->   -100
                 '[':  30995 ->   -100
                '\n':     13 ->   -100
               '   ':    296 ->   -100
......

finetune_demo/finetune.py", line 158, in main
model.gradient_checkpointing_enable()
TypeError: ChatGLMPreTrainedModel._set_gradient_checkpointing() got an unexpected keyword argument 'enable'

使用ToolAlpaca和AdvertiseGen都会出现这个错误：
**ChatGLMPreTrainedModel._set_gradient_checkpointing() got an unexpected keyword argument 'enable'**

**Comment by zRzRzRzRzRzRzR** [comment]
我在微调的时候是把这句话删掉了好像能用，你可以在我们推出的新推理框架试试？
今天会放上去

**Comment by CapenZen** [comment]
我之前也遇到过，你试试换不同版本的transformers，我用transformers==4.33.0没问题。
