### ISSUE TITLE
[Bug]：composite/demo-tools多轮对话function_call工具调用异常

### ISSUE THREAD

**Issue by longerking** [THUDM/ChatGLM3#408]
### System Info / 系統信息

ubuntu22.04

### Who can help? / 谁可以帮助到您？

@abmfy @zRzRzRzRzRzRzR 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

复现步骤：
1.  运行样例compose_demo样例：streamlit run main.py
2.  选择Tools对话，并设置参数为：top_p=0.99  temperature=0.01 repetition_penalty=1.00
3.  tools对话框里面输入，多轮对话工具调用function_call，如下所示，出现报错 `Failed to parse tool call` 如下图所示：
![image](https://github.com/THUDM/ChatGLM3/assets/37200736/a057d9e9-6eba-40a2-8a6d-e5700fe54d26)

相关讨论：https://github.com/THUDM/ChatGLM3/discussions/335

原因：输出解析在第二轮function_call丢失tools_name：
第一轮function_call output:
```
=== Output:
random_number_generator
 ```python
tool_call(seed=1, range=(0, 11))
```
......

第二轮function_call output:
```
=== Output:

 ```python
tool_call(seed=3, range=(10, 20))
 
```

并不是模型输出时候没有给出，tool_name。而是在获取到第一轮function_call调用之后，进行工具function_call解析之后，构建历史对话 history: list[Conversation] 时，没有把模型完整的输出放入历史对话。

当前错误的历史对话。
```
    {
        "role": "user", 
        "content": "生成一个0-10的随机数，随机种子为1，得到结果后，在生成一个10-20的随机数，随机种子为3，这两个随机数相加为多少？"
    }, 
    
    {
        "role": "assistant", 
        "content": "```python\ntool_call(seed=1, range=(0, 10))\n```"
    }
```

正确的历史对话应该为，包含Tools：
```
    {"role": "user", "content": "生成一个0-10的随机数，随机种子为1，得到结果后，再生成一个10-20的随机数，随机种子为3，这两个随机数相加为多少？"}, 
    
    {"role": "assistant", "content": "random_number_generator\n ```python\ntool_call(seed=1, range=[0, 10])\n```"}, 
    
    {"role": "observation", "content": "2"}, 
    
    {"role": "assistant", "content": "\n random_number_generator\n ```python\ntool_call(seed=3, range=[10, 20])\n```"}, 
    
    {"role": "observation", "content": "13"}, 
    
    {"role": "assistant", "content": "random_number_generator\n ```python\ntool_call(seed=1, range=[0, 10])\n```"}, 
    
    {"role": "user", "content": "再生成一个100-200的随机数，随机种子为3。加上之前生成的两个随机数，和为多少？"}, 
    
    {"role": "assistant", "content": "\n random_number_generator\n ```python\ntool_call(seed=3, range=[100, 200])\n```"}, 
    
    {"role": "observation", "content": "130"}
```

### Expected behavior / 期待表现

相关修改已经提交PR ： https://github.com/THUDM/ChatGLM3/pull/407
正常执行，已经支持多轮对话function_call。

![image](https://github.com/THUDM/ChatGLM3/assets/37200736/928c0b78-4f93-478c-828e-f156859458e1)

**Comment by zRzRzRzRzRzRzR** [comment]
按照你的操作更改后
![图片](https://github.com/THUDM/ChatGLM3/assets/93239683/eb26f7d6-0b86-4ce3-b89f-357356ec5a62)
仍然会出现这种错误
