### ISSUE TITLE
需要样例代码，让我们更好的使用，调用ChatGLM3。

### ISSUE THREAD

**Issue by coderwpf** [THUDM/ChatGLM3#41]
需要样例代码，让我们更好的使用，调用ChatGLM3：

**Comment by bonuschild** [comment]
+1, 直接使用chatglm2-6b的代码在`tokenization_chatglm.py`的189行`build_chat_input`处报错：
```
        content = item["content"]
TypeError: list indices must be integers or slices, not str
```
看来是返回内容的形式也变了，请指点如何修改，谢谢！

**Comment by coderwpf** [comment]
> +1, 直接使用chatglm2-6b的代码在`tokenization_chatglm.py`的189行`build_chat_input`处报错：
> 
> ```
>         content = item["content"]
> TypeError: list indices must be integers or slices, not str
> ```
> 
> 看来是返回内容的形式也变了，请指点如何修改，谢谢！

官方代码已经更新了我就关闭了

**Comment by bonuschild** [comment]
> > +1, 直接使用chatglm2-6b的代码在`tokenization_chatglm.py`的189行`build_chat_input`处报错：
> > ```
> >         content = item["content"]
> > TypeError: list indices must be integers or slices, not str
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看来是返回内容的形式也变了，请指点如何修改，谢谢！
> 
> 官方代码已经更新了我就关闭了

嗯嗯，谢谢啦！已经看到有了。
