### ISSUE TITLE
调用api，生成的回答会多一个空行

### ISSUE THREAD

**Issue by weiSENshu** [THUDM/ChatGLM3#410]
### System Info / 系統信息

Transformers==4.34.1
cuda==11.8
python=3.9.18

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

```
           openai.api_base="http://127.0.0.1:8000/v1"
           openai.api_key="xxxxx"
            response=openai.ChatCompletion.create(
                model="gpt-3.5-turbo",#chatglm3的版本model为gpt-3.5-turbo,不是chatglm3-6b
                messages=[
                    {"role": "user", 
                     "content":"你好“
                    }
                ],
                temperature=0.8,
                top_p = 0.7
            )["choices"][0]["message"]["content"]
```
将输出的response保存到文件中，发现多了一个空行
![屏幕截图 2023-11-22 185309](https://github.com/THUDM/ChatGLM3/assets/62413717/aaab5bec-b6ca-404d-a60c-e1cc1ab061cc)

### Expected behavior / 期待表现

每次输出都有空行，希望能删去多余的空行

**Comment by weiSENshu** [comment]
使用Zotero的翻译插件中的GPT翻译引擎时，同样会产生多余的空行
![image](https://github.com/THUDM/ChatGLM3/assets/62413717/fcdd6e3d-c649-4412-bc5c-96b4278636cc)
不过，通过修改openai_api.py文件的第188行`previous_text=""`,添加一个空格修改为`previous_text=" "`,空行就消失了
![image](https://github.com/THUDM/ChatGLM3/assets/62413717/c27a468b-7cb0-4716-9bf7-99012d7f3bf3)

**Comment by zRzRzRzRzRzRzR** [comment]
我们在测试时候没有多出来的空行，你在命令行测试api会有吗

**Comment by weiSENshu** [comment]
![image](https://github.com/THUDM/ChatGLM3/assets/62413717/1e25f9f8-7d78-47e1-b785-d6ebcf500465)
会自动有个\n

**Comment by ffayr** [comment]
我也有这个问题，回答开头多个\n和空格

**Comment by zRzRzRzRzRzRzR** [comment]
昂我看一下啊

**Comment by stingbo** [comment]
我也是

**Comment by zRzRzRzRzRzRzR** [comment]
问题解决
