### ISSUE TITLE
字典信息获取报错

### ISSUE THREAD

**Issue by lldreamvip** [THUDM/ChatGLM3#413]
### System Info / 系統信息

linux 系统，python3.10.6

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

代码出处：[ChatGLM3](https://github.com/THUDM/ChatGLM3/tree/main)/[openai_api_demo](https://github.com/THUDM/ChatGLM3/tree/main/openai_api_demo)
/utils.py   ，  193行：role, content, func_call = m.role, m.content, m.function_call

提示没有role，将字典key的获取统一改为m.get(“role”)就好了

### Expected behavior / 期待表现

期待搞明白原官方代码报错的原因

**Comment by zRzRzRzRzRzRzR** [comment]
你用哪一个代码执行的时候报错的。确然一下库的版本对不对

**Comment by lldreamvip** [comment]
已解决，源代码无问题。是我自己对调用接口重新实现了，m的实现不小心改为dict，不是原本的ChatMessage类，导致这一行报错了
