### ISSUE TITLE
请问我在没有做ChatGLM3模型量化的情况下，为什么本地模型推理速度慢呢

### ISSUE THREAD

**Issue by zhanghaotian123** [THUDM/ChatGLM3#420]
### Feature request  / 功能建议

我在openai_api_request.py基础上做了一个计时，问了模型”你好“，以下是返回日志用时为16s

开始询问的时间： 2023-11-23 13:27:01.588865
{'model': 'chatglm3-6b', 'object': 'chat.completion', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': '你好👋！我是ChatGLM3，有什么可以帮助您的吗？', 'name': None, 'function_call': None}, 'finish_reason': 'stop'}], 'created': 1700717237, 'usage': {'prompt_tokens': 43, 'total_tokens': 65, 'completion_tokens': 22}}
你好👋！我是ChatGLM3，有什么可以帮助您的吗？
询问完成的时间： 2023-11-23 13:27:17.827963   
耗时： 0:00:16.239098 s

### Motivation / 动机

怎样才能让本地模型快一些，期望回复，谢谢

### Your contribution / 您的贡献

1

**Comment by zhanghaotian123** [comment]
我的显卡显存为8G，模型为chatglm3-6b，未做量化

**Comment by zRzRzRzRzRzRzR** [comment]
8G不可能带得动没有量化的模型，你大概是用CPU跑了

**Comment by zhanghaotian123** [comment]
![14e41114542c4830675f136b9d6fd77](https://github.com/THUDM/ChatGLM3/assets/59438626/65fb9e85-3ba2-41fb-bef1-18173cc655e6)
非常感谢您的回复！我也不知道我的显卡是否能真正做到这些，我用的是chatglm3-6b这个模型，我确实是在显卡上将他跑起来了。我想知道它的简单推理速度在10s+是否是正常的，如果不正常会是什么原因导致的呢？感谢回复

**Comment by sdzbzj0406** [comment]
我本地加载做简单推理的速度还挺快的，基本在1秒左右就会有响应结果。建议确认下是否用到GPU，或者cudn等版本是否match。

**Comment by jayxuz** [comment]
windows下超出显存部分会，默认借用“内存”当做显存（即任务管理器中的共享GPU显存），而非全部模型加载到显存上，因此输出时速度受限。

**Comment by zhanghaotian123** [comment]
@jayxuz 谢谢大佬，看完您的回答我悟了，确实如此

**Comment by cutoutsy** [comment]
想问下，正常需要显卡多少显存，量化后需要多少

**Comment by zRzRzRzRzRzRzR** [comment]
这类问题可以查看我们的[官方文档](https://lslfd0slxc.feishu.cn/wiki/WvQbwIJ9tiPAxGk8ywDck6yfnof?from=from_copylink)
本Issue关闭
