### ISSUE TITLE
p-tuning训练中间结果参数转推理模型

### ISSUE THREAD

**Issue by whiteless9** [THUDM/ChatGLM3#424]
请问怎么样实现p-tuning训练中间结果参数转推理模型结果（training_args.bin 转pytorch_model.bin）。想测试训练过程中输出的模型

**Comment by zRzRzRzRzRzRzR** [comment]
这个就是命名而已啊，你想输出的是完整的模型是吗

**Comment by whiteless9** [comment]
> 这个就是命名而已啊，你想输出的是完整的模型是吗

是的，我看源码，然后尝试了几种方法都没实现

**Comment by zRzRzRzRzRzRzR** [comment]
确实，我们暂时没有提供合并模型输出的方法，这个你得基于huggingface自己改了
之后我们可能考虑做一个合并模型的脚本。

**Comment by whiteless9** [comment]
> 确实，我们暂时没有提供合并模型输出的方法，这个你得基于huggingface自己改了 之后我们可能考虑做一个合并模型的脚本。

好的，感谢
