### ISSUE TITLE
我使用openai_api.py 开启服务后，使用流式接口时，无法流式响应

### ISSUE THREAD

**Issue by sxxAaron** [THUDM/ChatGLM3#426]
### System Info / 系統信息

我使用openai_api.py 开启服务后，使用流式接口时，无法流式响应，是生成结束后一次性返回所有结果，用openai_api_request.py 测试的。
启动web_ui 是可以流式的

python:3.10
cuda:12.1
torch:2.1

不知是什么原因

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

用openai_api_request.py 测试的。
启动web_ui 是可以流式的

### Expected behavior / 期待表现

寻求帮助

**Comment by bh4rep** [comment]
这个问题上上一个版本出现过,但是两天后被修复,这个版本又出这个错误,那就再等两天吧.

**Comment by zRzRzRzRzRzRzR** [comment]
未能复现上述问题，确保你严格按照我们提供的openai的示例请求执行

**Comment by lwxBlue** [comment]
请问下解决了吗，我目前也发现这个问题了
