### ISSUE TITLE
微调指令出错

### ISSUE THREAD

**Issue by AHPUymhd** [THUDM/ChatGLM3#428]
### System Info / 系統信息

![image](https://github.com/THUDM/ChatGLM3/assets/72792297/36b7473d-8a1b-4abd-a363-49f5a8cdb6d4)

### Who can help? / 谁可以帮助到您？

@Btlmd  您好，我首先进入conda中chatglm3-demo环境，进入模型微调的目录，按照对话微调指令./scripts/finetune_pt.sh，然后就出现如图 的问题，请问Windows系统不能进行微调吗，我是Windows系统本地部署的。

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/THUDM/ChatGLM3/assets/72792297/266919ff-0b60-4486-90d4-66bd4c003f3e)

### Expected behavior / 期待表现

在此谢谢大家的解答

**Comment by zRzRzRzRzRzRzR** [comment]
这是linux系统的指令，windows系统下无法使用脚本，需要自己运行py代码

**Comment by AHPUymhd** [comment]
> 这是linux系统的指令，windows系统下无法使用脚本，需要自己运行py代码

请问py代码怎么运行，这个文件夹里面有吗，还是要自己写呢

**Comment by AHPUymhd** [comment]
@zRzRzRzRzRzRzR 麻烦您能详细说一下Windows部署的环境下微调P-Tuning v2吗，我看微调代码的脚本是.sha啊，怎么运行py代码，可以详细说一下吗，谢谢。
