### ISSUE TITLE
Windows系统在Git中微调

### ISSUE THREAD

**Issue by AHPUymhd** [THUDM/ChatGLM3#429]
### System Info / 系統信息

![image](https://github.com/THUDM/ChatGLM3/assets/72792297/f13598dd-cfc9-443f-a500-7801a90c07ef)
![image](https://github.com/THUDM/ChatGLM3/assets/72792297/1ffd92eb-1b2c-4d5b-84b8-1361301dbf37)
![image](https://github.com/THUDM/ChatGLM3/assets/72792297/c46f7317-d202-42fa-b5c4-282609b1ef20)
![image](https://github.com/THUDM/ChatGLM3/assets/72792297/53037c15-bfa2-45ba-b947-df0a18402657)
![image](https://github.com/THUDM/ChatGLM3/assets/72792297/246cab08-dccc-4eae-b23a-3d398bb438ed)
![image](https://github.com/THUDM/ChatGLM3/assets/72792297/ff247a0f-1044-429e-8e61-b4890022fbc8)
您好，我在Git上运行./scripts/finetune_pt.sh的微调代码，然后就出现了如上图的报错信息，请问是什么原因呢，我是Windows系统。

### Who can help? / 谁可以帮助到您？

@Btlmd 
![image](https://github.com/THUDM/ChatGLM3/assets/72792297/895c3503-65b7-488d-acc0-f0723bd885d2)
如上图报错信息在微调代码的116行，说是字符编码报错，这个错误应该怎么修改呢

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

谢谢

### Expected behavior / 期待表现

谢谢大家的帮助

**Comment by zRzRzRzRzRzRzR** [comment]
这个是因为你没有用正确的编码 ，确保你的jsonl中的所有汉字和内容使用都是utf8编码，而不是其他编码
