### ISSUE TITLE
使用langchain官方案例时，远程部署显示404

### ISSUE THREAD

**Issue by estuday** [THUDM/ChatGLM3#431]
### System Info / 系統信息

None

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

langchain的官方示例代码：
```python
from langchain.chains import LLMChain
from langchain.llms import ChatGLM
from langchain.prompts import PromptTemplate
endpoint_url = "http://remote_ip:8000"
template = """{question}"""
prompt = PromptTemplate(template=template, input_variables=["question"])
llm = ChatGLM(
    endpoint_url=endpoint_url,
    max_token=80000,
    history=[
        ["我将从美国到中国来旅游，出行前希望了解中国的城市", "欢迎问我任何问题。"]
    ],
    top_p=0.9,
    model_kwargs={"sample_model_args": False},
)
llm_chain = LLMChain(prompt=chat_template, llm=llm)
question = "北京和上海两座城市有什么不同？"
llm_chain.run(question)
```
远程显示404
![image](https://github.com/THUDM/ChatGLM3/assets/45581281/adb714c7-21f8-489f-a931-7f4cbd0e5072)

### Expected behavior / 期待表现

None

**Comment by zRzRzRzRzRzRzR** [comment]
你这是哪里的官方代码，我怎么没有找到

**Comment by estuday** [comment]
> 你这是哪里的官方代码，我怎么没有找到

https://python.langchain.com/docs/integrations/llms/chatglm 是langchain提供的示例代码

**Comment by zRzRzRzRzRzRzR** [comment]
这套代码是必须在localhost才能跑的

**Comment by estuday** [comment]
> 这套代码是必须在localhost才能跑的，另外，我们官方仓库有更新的官方代码，调用方式与老模型不同，并不兼容，请查看我们官方的最新调用代码

好的，感谢
