### ISSUE TITLE
听闻有问必答啊，能不能麻烦大佬指点工具调用该如何上手呢？

### ISSUE THREAD

**Issue by SolarKnight1** [THUDM/ChatGLM3#439]
### System Info / 系統信息

如果能写篇教学自然是最好，若是没工夫，也可以为小弟多推荐几个易懂的文章学习一下

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

.

### Expected behavior / 期待表现

.

**Comment by zRzRzRzRzRzRzR** [comment]
欢迎访问[技术文档](https://lslfd0slxc.feishu.cn/wiki/HIj5wVxGqiUg3rkbQ1OcVEe5n9g)这里有完整的教程，关于教程的问题可以在这里访问，详细讲述了每个demo的原理和教程

**Comment by jiawei243** [comment]
也可以看这个视频教程：https://www.bilibili.com/video/BV1uC4y1J7yA/
