### ISSUE TITLE
API调用chatglm_turbo，速度太慢

### ISSUE THREAD

**Issue by Chunhui-Zou** [THUDM/ChatGLM3#440]
### Feature request  / 功能建议

通过sse调用chatglm_turbo，返回的速度太慢，这一块可能加快吗，或者有别的更快的调用方式？
另外没用完的token可以延期吗？

### Motivation / 动机

aip优化

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
API问题需要去开放平台提工单，开源不负责APi部分
