### ISSUE TITLE
执行api_request报错

### ISSUE THREAD

**Issue by QingChengLineOne** [THUDM/ChatGLM3#444]
### System Info / 系統信息

4小时之前的代码运行还是可以的，但是现在调用会报错

### Who can help? / 谁可以帮助到您？

![image](https://github.com/THUDM/ChatGLM3/assets/111961874/68a4a66f-ca7a-4739-ae54-80d85b1a2622)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

是bug还是什么

**Comment by zRzRzRzRzRzRzR** [comment]
openai版本不对吧，升级到1.3
