### ISSUE TITLE
chatGLM3有内存溢出问题

### ISSUE THREAD

**Issue by zls130921** [THUDM/ChatGLM3#446]
### System Info / 系統信息

python:3.8.10   显卡内存是64G的

当前问题是：部署后，单元测试没有问题，但是批量数据（类似for 循环，数据量超过1000）调用接口会出现内存快速上升的现象，从而导致问题不能回复，长达十分钟无响应，请问作者有遇到过吗？

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我们是银行内部部署应用，无法提供复现数据

### Expected behavior / 期待表现

期待您的回复

**Comment by zRzRzRzRzRzRzR** [comment]
你是并发还是顺发，建议改成顺发试试，顺序执行
#306 你的问题可以在这里留言
