### ISSUE TITLE
err code in get_prompt for p-tuning?

### ISSUE THREAD

**Issue by jiqizaisikao** [THUDM/ChatGLM3#447]
I see,I misunderstood

**Comment by Btlmd** [comment]
`.split(2)` does not split the tensor in `dim=0` into two half tensors. Rather, it splits the tensor into a group, where each element has size `2` along `dim=0`. If you found the code snippet not functioning correctly, please provide sufficient information for us to reproduce the result, like the full exception traceback, `input_ids` and which script and command is executed. Thanks 😃
