### ISSUE TITLE
一键安装包碰到问题~我想注册一个工具检索本地excel文件里面的数据~但是无法导入openpyxl~然后我去scripts想安装 但是路径是绝对路径报错了~

### ISSUE THREAD

**Issue by hechushitaoyuan** [THUDM/ChatGLM3#448]
### System Info / 系統信息

windows11

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![2eb4f06d26d56f38be184be07f35c81](https://github.com/THUDM/ChatGLM3/assets/109302248/7b1dc712-0de4-4d4a-b559-685034d40ef8)
![89a30a433ea08b6cc70a74ea5b67d20](https://github.com/THUDM/ChatGLM3/assets/109302248/52e428b8-f5a5-484b-bf85-b76281028759)

### Expected behavior / 期待表现

请问如何才能解决呢~~谢谢~~

**Comment by zRzRzRzRzRzRzR** [comment]
一键安装包碰到问题不由官方进行维护，也不具有太多的扩展性，如果要装具有扩展性的，请源码安装尝试

**Comment by hechushitaoyuan** [comment]
> 一键安装包碰到问题不由官方进行维护，也不具有太多的扩展性，如果要装具有扩展性的，请源码安装尝试

官方发的一键安装包咯~~
我捣腾好了~本地把安装好的依赖包拷贝glm3相对应的文件夹即可~

**Comment by zRzRzRzRzRzRzR** [comment]
Bilibili那个是吧，那个就是能用，没有可扩展性
