### ISSUE TITLE
not all arguments converted during string formatting

### ISSUE THREAD

**Issue by xiaodou2021** [THUDM/ChatGLM3#451]
### System Info / 系統信息

ubuntu20.04
GPU RTX 4090(24GB) 
CPU12 vCPU Intel(R) Xeon(R) Platinum 8352V CPU @ 2.10GHz
内存90GB
PyTorch  2.0.0
Python  3.10
Cuda  11.8
transformers:4.30.2

### Who can help? / 谁可以帮助到您？

@Btlmd ，你好
在基于api部署后，通过Python3 openai_api.py启动，使curl 方式请求接口/v1/chat/completions时，报如下错误：

Traceback (most recent call last):
  File "/root/miniconda3/envs/pt_env1/lib/python3.10/logging/__init__.py", line 1105, in emit
    msg = self.format(record)
  File "/root/miniconda3/envs/pt_env1/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/root/miniconda3/envs/pt_env1/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/root/miniconda3/envs/pt_env1/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

按官网提供的微调示例进行微调后，以api部署的方式进行启动，通过curl的方式调用接口，报上面的错误

### Expected behavior / 期待表现

给出具体解决方式

**Comment by zRzRzRzRzRzRzR** [comment]
跑官方request代码能成功吗

**Comment by xiaodou2021** [comment]
请求没问题，能收到响应，但每次请求都会报这个错



发自我的iPhone


------------------ Original ------------------
From: zR ***@***.***&gt;
Date: Fri,Nov 24,2023 10:49 PM
To: THUDM/ChatGLM3 ***@***.***&gt;
Cc: xiaodou2021 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [THUDM/ChatGLM3] not all arguments converted during stringformatting (Issue #451)





 
跑官方request代码能成功吗

**Comment by zRzRzRzRzRzRzR** [comment]
我们下周测一下，

**Comment by zRzRzRzRzRzRzR** [comment]
官方的代码没有这个错误，甚至没有log代码，如果是用我们的官方代码，你能复现一下是在哪里出错吗

**Comment by xiaodou2021** [comment]
> 官方的代码没有这个错误，甚至没有log代码，如果是用我们的官方代码，你能复现一下是在哪里出错吗

我是在用输入输出格式数据集进行微调完成后，然后在openai_api.py文件中调整了如下代码：
    model_path = "本地模型路径"
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    model = AutoModel.from_pretrained(model_path, trust_remote_code=True).cuda()
    checkpoint_path = "微调后的权重文件"
    model.load_state_dict(torch.load(checkpoint_path), strict=False)

然后再通过python3 openai.py 部署后，访问接口就会报错，然后出错的文件是/root/miniconda3/envs/pt_env1/lib/python3.10/logging/__init__.py，在1100行，执行msg = self.format(record)时报的错

**Comment by zRzRzRzRzRzRzR** [comment]
这你微调的代码在微调demo 的inference能正常吗

**Comment by xiaodou2021** [comment]
正常

> 这你微调的代码在微调demo 的inference能正常吗

**Comment by zRzRzRzRzRzRzR** [comment]
试试这里的方案
```
if args.pt_checkpoint:
    tokenizer = AutoTokenizer.from_pretrained(args.tokenizer, trust_remote_code=True)
    config = AutoConfig.from_pretrained(args.model, trust_remote_code=True, pre_seq_len=args.pt_pre_seq_len)
    model = AutoModel.from_pretrained(args.model, config=config, trust_remote_code=True).cuda()
    prefix_state_dict = torch.load(os.path.join(args.pt_checkpoint, "pytorch_model.bin"))
    new_prefix_state_dict = {}
    for k, v in prefix_state_dict.items():
        if k.startswith("transformer.prefix_encoder."):
            new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
    model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
else:
    tokenizer = AutoTokenizer.from_pretrained(args.tokenizer, trust_remote_code=True)
    model = AutoModel.from_pretrained(args.model, trust_remote_code=True)
```
这是inference的导入方式，你试试这样导入会不会出现问题，我这边复现不了
