### ISSUE TITLE
运行ChatGLM3-main\composite_demo main.py 时画爱心，代码可以跑，但图型出不来

### ISSUE THREAD

**Issue by jeffreychen567** [THUDM/ChatGLM3#452]
### System Info / 系統信息

环境
python 3.10  nvdia 546的驱动 ，cuda 12.3  3080显卡，torch   2.1.0+cu118，transformers         4.35.0

故障如图所示，代码没改动，就是python执行器的结果不返回
<img width="680" alt="屏幕截图 2023-11-24 233436" src="https://github.com/THUDM/ChatGLM3/assets/30716650/ab3b365d-8936-418c-bd33-87622fe1b4eb">
<img width="748" alt="屏幕截图 2023-11-24 233744" src="https://github.com/THUDM/ChatGLM3/assets/30716650/dc7c4999-be28-4b2f-b115-5c2a4bfe00f8">
<img width="323" alt="屏幕截图 2023-11-24 233913" src="https://github.com/THUDM/ChatGLM3/assets/30716650/748a9bbd-dca7-4b69-a1c7-cd0a0f7db49d">

### Who can help? / 谁可以帮助到您？

 运行ChatGLM3-main\composite_demo main.py 
命令行如下  streamlit.cmd run .\main.py
爱心图画不出来，代码复制到python环境可以画出来
<img width="680" alt="屏幕截图 2023-11-24 233436" src="https://github.com/THUDM/ChatGLM3/assets/30716650/5c5e5955-fbf6-478d-a0a1-f176c537beb6">
<img width="748" alt="屏幕截图 2023-11-24 233744" src="https://github.com/THUDM/ChatGLM3/assets/30716650/2da3496a-0045-4eae-91b6-b8346824b6ab">
<img width="323" alt="屏幕截图 2023-11-24 233913" src="https://github.com/THUDM/ChatGLM3/assets/30716650/b71756bd-3be8-4ed6-9b2d-05155b43c431">

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

 运行ChatGLM3-main\composite_demo main.py 
命令行如下  streamlit.cmd run .\main.py
爱心图画不出来，代码复制到python环境可以画出来

### Expected behavior / 期待表现

我希望代码执行结果能返回到web界面上

**Comment by jeffreychen567** [comment]
装过了的，同样的代码，环境，有的电脑能跑出图形，更多的是跑不出来![Uploading 屏幕截图 2023-11-26 003024.png…]()

**Comment by zRzRzRzRzRzRzR** [comment]
随机事件吗，我是ubuntu的系统稳定能画，你试试降低温度

**Comment by zRzRzRzRzRzRzR** [comment]
相似Issue已经移动到讨论区 #459 可以在这里上提出你的badcase

**Comment by longerking** [comment]
我猜测是你的创建的conda 环境名称和默认名称不一样，而且没有把IPYKERNEL设置为环境变量。
比如Readme中：https://github.com/THUDM/ChatGLM3/blob/33953b119e794f4af81ce5200343eeea8c72994c/composite_demo/README.md?plain=1#L35

创建的环境为chatglm3-demo
```
conda create -n chatglm3-demo python=3.10
conda activate chatglm3-demo
pip install -r requirements.txt

ipython kernel install --name chatglm3-demo --user

# 确保 export IPYKERNEL=<kernel_name>   这里的kerner_name就是你创建的conda环境名称，也是你的ipython kernel name
export IPYKERNEL=chatglm3-demo
```
为什么要保持同步？因为在/demo_ci.py 中调用jupyter的桓环境是使用的IPYKERNEL环境变量，代码如下：
```
IPYKERNEL = os.environ.get('IPYKERNEL', 'chatglm3-demo')
```

所以当你创建的conda环境名称不一样时，需要设置
```
ipython kernel install --name <your_conda_env_name> --user
export IPYKERNEL=<your_conda_env_name>
```
这样才能确保/demo_ci.py 中能够调用到IPYKERNEL绘制图像 @jeffreychen567

**Comment by jeffreychen567** [comment]
@longerking @zRzRzRzRzRzRzR ，，@longerking  你说的是正确的，我在原机器是用目录来建的虚拟环境，复制到别的机器后就不行了，环境路径确实不一样了， 谢谢！！！

**Comment by jeffreychen567** [comment]
@longerking 
<img width="710" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/30716650/2a1a7623-86ad-4e3a-8aa8-6b145ad72303">
我改成这样可是还是不行
