### ISSUE TITLE
streamlit的webui没有tools和代码编译器等按钮

### ISSUE THREAD

**Issue by stingtam** [THUDM/ChatGLM3#455]
### System Info / 系統信息

新手，chatglm3的web_demo2打开只有干净的chat模式，我看介绍还有tools和代码编译等功能，可是我没有这几个按钮，请大佬执教。谢谢。
![web_demo2](https://github.com/THUDM/ChatGLM3/assets/85009451/8f9dc6c0-9fd3-4c1f-958f-eca4b098de7d)

### Who can help? / 谁可以帮助到您？

@THUDM

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

新人求教

### Expected behavior / 期待表现

希望有人解答

**Comment by zRzRzRzRzRzRzR** [comment]
composite demo，你打开错了
