### ISSUE TITLE
半精度改为4-bit 量化后，推理反而变慢

### ISSUE THREAD

**Issue by youarenowhere** [THUDM/ChatGLM3#456]
### System Info / 系統信息

我在colab使用（T4显卡、8cpu、51g内存，166g磁盘）进行推理
chatglm3-6b推理内容如下：
`response, history = model.chat(tokenizer, "如何学习ChatGLM", history=[])
`
【1】半精度推理时间：14s
`model = AutoModel.from_pretrained(repo_model).half().cuda()
`
<img width="992" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/16035966/de3ab434-d5c6-44c6-aa44-f3165b1cfc72">

【2】4bit量化推理时间：48s
`model = AutoModel.from_pretrained(repo_model).quantize(4).cuda()`
<img width="1109" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/16035966/b821e1f3-a7bc-424e-8c6d-c0b6016a56a5">

相同配置，量化后变的更慢了

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

import locale
locale.getpreferredencoding = lambda: "UTF-8"

!pip install transformers sentencepiece  sse_starlette

#4精度需要安装
!pip install cpm_kernels

#!pip install accelerate cpm_kernels protobuf

import torch,gc

repo_model="THUDM/chatglm3-6b"
local_model_dir="/content/"

#清除显存
def clear_gpu_memory():
  gc.collect()
  torch.cuda.empty_cache()
  torch.cuda.ipc_collect()

'''
手动下载版本
'''
from huggingface_hub import snapshot_download

snapshot_download(repo_id=repo_model, local_dir=local_model_dir+repo_model)

from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained(repo_model,trust_remote_code=True)

#默认情况下，模型以 FP16 精度加载，运行上述代码需要大概 13GB 显存。

model = AutoModel.from_pretrained(local_model_dir+repo_model).half().cuda()

#如果你的 GPU 显存有限，可以尝试以量化方式加载模型，使用方法如下：
#model = AutoModel.from_pretrained(local_model_dir+repo_model).quantize(4).cuda()

model = model.eval()

response, history = model.chat(tokenizer, "如何学习ChatGLM", history=[])
print(response)

### Expected behavior / 期待表现

期待推理速度更快

**Comment by zRzRzRzRzRzRzR** [comment]
如果我没记错的话，确实是FP16更快，正常现象
