### ISSUE TITLE
如何隐藏调用工具链的显示

### ISSUE THREAD

**Issue by blackwhites** [THUDM/ChatGLM3#458]
### Feature request  / 功能建议

<img width="1711" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/5109753/083d3746-98e8-4b52-893c-686692294986">
对于最终客户只关心结果并不关心调用哪个tool，如何隐藏调用工具等信息，只返回最终结果。

### Motivation / 动机

客户并不关心你调用的tools

### Your contribution / 您的贡献

能不能提供修改代码？

**Comment by zRzRzRzRzRzRzR** [comment]
需要自行修改
