### ISSUE TITLE
ChatGPT-Next-Web请官方支持，感激不尽！！！

### ISSUE THREAD

**Issue by coderwpf** [THUDM/ChatGLM3#46]
ChatGPT-Next-Web请官方支持，感激不尽！！！

**Comment by bonuschild** [comment]
+1, 直接使用chatglm2-6b的代码在`tokenization_chatglm.py`的189行`build_chat_input`处报错：
```
        content = item["content"]
TypeError: list indices must be integers or slices, not str
```
看来是返回内容的形式也变了，请指点如何修改，谢谢！

**Comment by bonuschild** [comment]
而且容易出现Next-Web报的`network error`，多试几次就没问题，但不知是什么原因耦合的

**Comment by coderwpf** [comment]
官方版本已经有支持openapi的接口了，但是还需要微调才能运行。感谢
