### ISSUE TITLE
Deepspeed Zero 3支持

### ISSUE THREAD

**Issue by Liu-yuliang** [THUDM/ChatGLM3#465]
### System Info / 系統信息

应该不是环境的问题，其他模型如Yi，LLaMA均可使用

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

请问 ChatGLM3-6B是不支持deepspeed zero3吗，同样的配置只有该模型遇到了问题

报错为：

`NotImplementedError: Cannot copy out of meta tensor; no data!`

config为：

`{
    "flops_profiler": {
        "enabled": true,
        "profile_step": 50,
        "module_depth": -1,
        "top_modules": 1,
        "detailed": true,
        "output_file": "profile.log"
    },
    "zero_optimization": {
        "stage": 3,
        "allgather_partitions": true,
        "allgather_bucket_size": 5e8,
        "reduce_scatter": true,
        "reduce_bucket_size": "auto",
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 0,
        "stage3_prefetch_bucket_size": 0,
        "stage3_param_persistence_threshold": 0,
        "stage3_max_live_parameters": 0,
        "stage3_max_reuse_distance": 0,
        "stage3_gather_16bit_weights_on_model_save": true,
        "offload_param": {
            "device": "cpu"
        },
        "offload_optimizer": {
            "device": "cpu"
        }
    },
    "scheduler": {
        "type": "WarmupDecayLR",
        "params": {
            "warmup_min_lr": "auto",
            "warmup_max_lr": "auto",
            "warmup_num_steps": "auto",
            "total_num_steps": "auto"
        }
    },
    "fp16": {
        "enabled": false,
        "auto_cast": false,
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 32,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "bf16": {
        "enabled": true
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "weight_decay": "auto",
            "betas": "auto",
            "eps": "auto",
            "torch_adam": true,
            "adam_w_mode": true
        }
    },
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 1000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}`

### Expected behavior / 期待表现

确认问题即可

**Comment by zRzRzRzRzRzRzR** [comment]
与[相关问题](https://github.com/microsoft/DeepSpeed/issues/3517) 相似，可以尝试他的解决方案

**Comment by yuweikun** [comment]
fintune.py中的77行
model = AutoModel.from_pretrained(model_args.model_name_or_path, config=config, trust_remote_code=True,empty_init=False)
加一个empty_init=False似乎可以
