### ISSUE TITLE
为什么我用LoRA微调ChatGLM3做对话任务，损失下降后又上升呢？收敛不了，是不是我的对话数据没处理好

### ISSUE THREAD

**Issue by shehuiwojiege** [THUDM/ChatGLM3#467]
### System Info / 系統信息

transformers 版本4.30.2
torch 版本2.0.1

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

111

### Expected behavior / 期待表现

用LoRA微调chatglm3不收敛

**Comment by shehuiwojiege** [comment]
![image](https://github.com/THUDM/ChatGLM3/assets/39643399/36394153-e64d-4ff5-8f41-8ab49689ea0c)
搞不懂为啥训练到后面损失一直上升

**Comment by zRzRzRzRzRzRzR** [comment]
损失上升是不对的，检查一下你的学习率和batchsize，你先跑个100个step看看规律

**Comment by shehuiwojiege** [comment]
> 损失上升是不对的，检查一下你的学习率和batchsize，你先跑个100个step看看规律

我尝试过很小的lr， step也100多，但损失一直上升，我怀疑是我数据处理那里出问题了，多轮对话设计如Q1A1Q2A2Q3A3，我这里计算的是A1A2A3的损失，但我用百川就能跑出效果，chatglm3损失却一直提升。

**Comment by shehuiwojiege** [comment]
> 损失上升是不对的，检查一下你的学习率和batchsize，你先跑个100个step看看规律

这是我跑的损失，真的很奇葩，直接从高处降到0.0
![image](https://github.com/THUDM/ChatGLM3/assets/39643399/90d2c4b3-82c2-4d15-bc09-76c21c2c4b22)

**Comment by zRzRzRzRzRzRzR** [comment]
emm，暂时也没办法定位到问题所在，有试过第三方框架如 llamafactory这类框架也会出现上述情况吗

**Comment by zRzRzRzRzRzRzR** [comment]
> > 损失上升是不对的，检查一下你的学习率和batchsize，你先跑个100个step看看规律
> 
> 我尝试过很小的lr， step也100多，但损失一直上升，我怀疑是我数据处理那里出问题了，多轮对话设计如Q1A1Q2A2Q3A3，我这里计算的是A1A2A3的损失，但我用百川就能跑出效果，chatglm3损失却一直提升。

我们自己的样例数据确实没有出现这类情况，你试试数据减少一点看看呢

**Comment by zRzRzRzRzRzRzR** [comment]
另外，我记得我们只有提供lora 的base脚本，如果你是用lora调chat，可能出现一定问题。

**Comment by shehuiwojiege** [comment]
> emm，暂时也没办法定位到问题所在，有试过第三方框架如 llamafactory这类框架也会出现上述情况吗

没尝试这个 之前设置的batch_size是10，当我设置batch_size为4的时候，发现它又可以收敛了，暂时不知道啥情况

**Comment by zRzRzRzRzRzRzR** [comment]
你的batchsize调整的同时，学习率记得成倍调整，你应该根据[技术文档](https://lslfd0slxc.feishu.cn/wiki/YInmwPmyii67VRkzU3BchPNzncg)提到的更多技术细节来完善微调，更多微调问题可以移步讨论区解决，我们在讨论区开了一个专门的微调栏，各类微调问题在那边提出，由社群和官方人员一起解答

**Comment by shehuiwojiege** [comment]
> 你的batchsize调整的同时，学习率记得成倍调整，你应该根据[技术文档](https://lslfd0slxc.feishu.cn/wiki/YInmwPmyii67VRkzU3BchPNzncg)提到的更多技术细节来完善微调，更多微调问题可以移步讨论区解决，我们在讨论区开了一个专门的微调栏，各类微调问题在那边提出，由社群和官方人员一起解答

是的 学习率我这边没多大变动 但损失下降到了0.02左右 降低了batch_size之后没有出现不收敛现象 不知道为什么
