### ISSUE TITLE
Glm3推理速度很慢，并且不能指定显卡

### ISSUE THREAD

**Issue by zhengyangyong** [THUDM/ChatGLM3#468]
### System Info / 系統信息

CentOS8
CUDA11.2
模型：GLM3-6B-32K
显卡是2080TI * 4

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 按照手册README中启动openai_api_demo中的[openai_api.py](https://github.com/THUDM/ChatGLM3/blob/main/openai_api_demo/openai_api.py)，命令为：
```shell
CUDA_VISIBLE_DEVICES=3 python3 openai_api.py
```
启动成功，但是推理速度是特别的慢，基本需要两分钟，使用`nvida-smi`观察到的现象为：
```
0   N/A  N/A   2607799      C   /opt/media/MediaServer            370MiB
```
即：
- 进程没有分配到第4块显卡上，但是Glm2这么做是没问题的
- 内存占用只有370M，明显很低

之后修改openai_api.py代码使用多卡，启动的两个进程仍然是370M，速度仍然很慢

### Expected behavior / 期待表现

1. 按CUDA_VISIBLE_DEVICES的指示启动在规定显卡上
2. 推理速度比GLM2快，目前使用的GLM2启动在同一台服务器上使用2块2080TI显卡，推理结果速度大致在15秒左右，GLM2情况如下：

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
| 50%   71C    P2    65W / 250W |   6087MiB / 11019MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:03:00.0 Off |                  N/A |
| 44%   60C    P8    21W / 250W |   5006MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |

**Comment by zRzRzRzRzRzRzR** [comment]
你是多卡加载吗，多卡加载很慢的，你得单卡加载

**Comment by zhengyangyong** [comment]
我定位问题了，配置不太对所以启动的时候，检查驱动不够新，切换到CPU模式了，建议增加一个提示，没有使用GPU而是使用的CPU，不只是提示驱动不够新而已
