### ISSUE TITLE
微调之后找不到tokenizer_chatglm.py

### ISSUE THREAD

**Issue by liudasha** [THUDM/ChatGLM3#470]
### System Info / 系統信息

和requirements一样

### Who can help? / 谁可以帮助到您？

@Btlmd

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

这是全量微调的sh文件：
#! /usr/bin/env bash

set -ex

LR=5e-5
NUM_GPUS=4
MAX_SOURCE_LEN=1024
MAX_TARGET_LEN=128
DEV_BATCH_SIZE=4
GRAD_ACCUMULARION_STEPS=8
MAX_STEP=50
SAVE_INTERVAL=50

RUN_NAME=advertise_gen_ft
BASE_MODEL_PATH=chatglm3/6b-chat/
DATASET_PATH=/ChatGLM3/finetune_chatmodel_demo/700.json

DATESTR=`date +%Y%m%d-%H%M%S`
OUTPUT_DIR=700
MASTER_PORT=$(shuf -n 1 -i 10000-65535)

torchrun --standalone --nnodes=1 --nproc_per_node=$NUM_GPUS finetune.py \
    --train_format input-output \
    --train_file $DATASET_PATH \
    --preprocessing_num_workers 16 \
    --model_name_or_path $BASE_MODEL_PATH \
    --output_dir $OUTPUT_DIR \
    --max_source_length $MAX_SOURCE_LEN \
    --max_target_length $MAX_TARGET_LEN \
    --per_device_train_batch_size $DEV_BATCH_SIZE \
    --gradient_accumulation_steps $GRAD_ACCUMULARION_STEPS \
    --logging_steps 1 \
    --save_steps $SAVE_INTERVAL \
    --num_train_epochs 1 \
    --learning_rate $LR \
    --fp16 \
    --gradient_checkpointing \
    --deepspeed configs/deepspeed.json 2>&1 | tee ${OUTPUT_DIR}/train.log

微调之后找不到tokenizer_chatglm.py,只有这些文件：
![微信截图_20231128014659](https://github.com/THUDM/ChatGLM3/assets/49472952/3796ba09-f1c2-4fee-ad41-f4b23f42aa73)

### Expected behavior / 期待表现

解决这个bug

**Comment by zRzRzRzRzRzRzR** [comment]
微调的就是一个小文件，剩下都要用原有大模型的，我们没有推出合并模型的脚本
