### ISSUE TITLE
通过微调改变问候语是否可行

### ISSUE THREAD

**Issue by Missliuff** [THUDM/ChatGLM3#471]
我想利用ChatGLM3做一个客服机器人，但是客服有专用的问候语和结束语等，例如当用户问类似于“你好”时，机器人需要回答“你好，有什么可以帮您”，我用十条左右的问候语问答对LORA微调ChatGLM3，但是仍然没有改变原模型的回答方式，是我哪里采用的方法不对吗？ChatGLM3本身的问候语是怎么训练的呢？是否有更好的方法。
谢谢~

**Comment by zRzRzRzRzRzRzR** [comment]
10条的话你训练步数要增加
这种建议搭配知识库回答，更好的解决方案是，部分有固定答案的不要进大模型，现在外面分类，进传统的问答和大模型问答两种类型
