### ISSUE TITLE
我跟您提过了一个issue，但是为什么不见了？有谁可以解释一下嘛？

### ISSUE THREAD

**Issue by Hongru0306** [THUDM/ChatGLM3#473]
### System Info / 系統信息

我跟您提过了一个issue，但是为什么不见了？有谁可以解释一下嘛？

### Who can help? / 谁可以帮助到您？

我跟您提过了一个issue，但是为什么不见了？有谁可以解释一下嘛？

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

none

### Expected behavior / 期待表现

是目前功能不支持还是误删？还是说我之前提问的bug与本库不相关？

**Comment by zRzRzRzRzRzRzR** [comment]
#460 issue属于 #394中提到的讨论区问题，官方没有办法复现或者进行维护，至于其他最近issue，我们没有看到

**Comment by Hongru0306** [comment]
> #460 issue属于 #394中提到的讨论区问题，官方没有办法复现或者进行维护，至于其他最近issue，我们没有看到

好的谢谢您
