### ISSUE TITLE
除了在线的Demo之外，本地部署的，CPU运行的模型，GPU运行的半精度，数学+推理的问题答案都不对

### ISSUE THREAD

**Issue by zhuxiujia** [THUDM/ChatGLM3#474]
### System Info / 系統信息

Apple MacOS M1 Max

Windows/RTX3080ti

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

提问“将苹果分给若干个小朋友，每个小朋友分五个苹果，还剩12个苹果，每个小朋友分八个苹果，还差六个苹果，一共多少个小朋友，一共多少个苹果？”

在线版ChatGLM3-6B回答：  6小朋友,42苹果（正确）

本地CPU部署的回答： 计算错误

### Expected behavior / 期待表现

 6小朋友,42苹果（正确）

**Comment by zRzRzRzRzRzRzR** [comment]
该模型的计算能力还有很大的提升空间，请确认你的参数都一样？

**Comment by zhuxiujia** [comment]
> 该模型的计算能力还有很大的提升空间，请确认你的参数都一样？

参数一个都没改 用compose_demo在mac m1笔记本上跑的

**Comment by zRzRzRzRzRzRzR** [comment]
![图片](https://github.com/THUDM/ChatGLM3/assets/93239683/6d20851b-92ec-41c9-8b8f-e5993d006d04)
我复现不出来，多换了两个机器也是正常的，这个问题目前暂时无法被解决

**Comment by zhuxiujia** [comment]
> ![图片](https://private-user-images.githubusercontent.com/93239683/286491217-6d20851b-92ec-41c9-8b8f-e5993d006d04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMzgxMTcsIm5iZiI6MTcwMTIzNzgxNywicGF0aCI6Ii85MzIzOTY4My8yODY0OTEyMTctNmQyMDg1MWItOTJlYy00MWM5LThiOGYtZTU5OTNkMDA2ZDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA2MDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZGU3ZDFmMjdhNDEyYjk3MzA5NDE5ZjVlNWQ3N2I4NmJjODcxNDlkNzRlMDhiMjJjYzQ4YjFjNGQwZjFjNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CuBFr6O7Pqe7LX48BLEquKPQmTMa3dEXuXuJupgO01I) 我复现不出来，多换了两个机器也是正常的，这个问题目前暂时无法被解决，你试试是不是这套参数。

![image](https://github.com/THUDM/ChatGLM3/assets/3481148/ee5a8b15-aa69-46dd-926b-e81ecd7bec5f)

**Comment by zhuxiujia** [comment]
> ![图片](https://private-user-images.githubusercontent.com/93239683/286491217-6d20851b-92ec-41c9-8b8f-e5993d006d04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMzgxMTcsIm5iZiI6MTcwMTIzNzgxNywicGF0aCI6Ii85MzIzOTY4My8yODY0OTEyMTctNmQyMDg1MWItOTJlYy00MWM5LThiOGYtZTU5OTNkMDA2ZDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA2MDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZGU3ZDFmMjdhNDEyYjk3MzA5NDE5ZjVlNWQ3N2I4NmJjODcxNDlkNzRlMDhiMjJjYzQ4YjFjNGQwZjFjNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CuBFr6O7Pqe7LX48BLEquKPQmTMa3dEXuXuJupgO01I) 我复现不出来，多换了两个机器也是正常的，这个问题目前暂时无法被解决，你试试是不是这套参数。

为啥你的界面也和我clone下来的代码的界面也不一样
