### ISSUE TITLE
循环将小说文本喂给模型做摘要，有时输出正常，有时直接原文返回未做处理

### ISSUE THREAD

**Issue by ripingit** [THUDM/ChatGLM3#476]
### System Info / 系統信息

操作系统： ubuntu 20 (wsl)
CUDA : CUDA Version: 12.2
GPU: Nvidia 2080Ti
Python: 3.10.13

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

**调用代码（用的chatglm3-32k模型，load_in_8bit）**
```
 for d in docs:
        d = d.replace(" ", "")
        if len(d) > 0:
            print("喂模型的文本长度为： %d \n" % len(d))
            print('\n')
            response, history = model.chat(
                tokenizer, d, history=history_base, top_p=0.8,temperature=0.7, repetition_penalty=1.2)
```
**下面是打印出来的输出样例**
1.喂模型的文本长度为： 2981 （正常输出）

```
{
  "chapter": "第三章:全民公敌",
  "characters": ["宋岚", "陆湘"],
  "summary": "本章讲述了主人公宋岚的生活背景以及对当前社会的认知。他来到2166年，发现这是一个充满犯罪和暴力的新时代。大检察官安洁-福斯特和罪犯柴可的死亡引起了全市的关注。在这个世界中，有着强大的超能力者被称为'救助者'。宋岚尽量避免涉及复杂的 纷争，努力保持平静的生活。"
}
```

2.喂模型的文本长度为： 2154 （异常输出）

```
第五章：勇敢的选择

宋岚拿着陆湘的钱卡，心里五味杂陈。

一方面，他为能够得到这样的支援感到感激，另一方面，他也清楚这份钱的沉重负担。

他对义体改造的态度依然坚决，但在陆湘的解释下，他已经明白这是一个必要的选择。

他决定尝试一下，哪怕心理再怎么恐惧，也要保护自己和爱的人。

第二天早上，宋岚来到了义体店。

这里的设备和技术都很先进，工作人员也很专业。

宋岚看到了各种各样的义体，有的强化手臂，有的增强腿力，甚至还有一些奇怪的形状。
```

### Expected behavior / 期待表现

稳定的输出json格式摘要

**Comment by zRzRzRzRzRzRzR** [comment]
你的请求对于6B模型有点过高了
建议：
1. 换fp16，同时不要让模型完成双任务（你这有返回json和生成文章），建议拆开任务来做
2. 多次执行代码，清除掉错误的返回数据
