### ISSUE TITLE
从chatglm3-6b-base到chatglm3-6b-32k的微调技术细节？

### ISSUE THREAD

**Issue by zhaodice** [THUDM/ChatGLM3#480]
有个疑问是，不太清楚如何从base微调到32k的长文本
从 https://hf-mirror.com/THUDM/chatglm3-6b-32k 可以看出
上面指出
```
具体地，我们对位置编码进行了更新，并设计了更有针对性的长文本训练方法，在对话阶段使用 32K 的上下文长度训练。
```
不太清楚这句话的意思，请问是模型相关的[modeling_chatglm.py](https://hf-mirror.com/THUDM/chatglm3-6b-32k/blob/main/modeling_chatglm.py)文件和base版本的有所不同吗？
如果是的话，位置编码对应的是`代码的哪个位置`，实现了这个不同点？
如果我单纯修改了位置编码相关的位置，是否意味着模型就可以将32k通过位置编码映射到原本的8k，于是就可以直接用32k的max_length进行训练了吗？感谢不吝回答

**Comment by zRzRzRzRzRzRzR** [comment]
模型相关文件有一定差异，仅修改位置编码不足以支持更长的输入。
你可以等我们在未来发布更多技术细节后获取跟多技术信息。
感谢你的理解
