### ISSUE TITLE
sft相关问题？

### ISSUE THREAD

**Issue by zbrnwpu** [THUDM/ChatGLM3#482]
您好，请教几个问题哈
1、模型保存如何按照epoch来保存？
2、loss一般降低到多少较为适宜？
3、微调特定任务的数据量大概在什么范围？官方示例中用于微调的数据量不算很大

**Comment by zRzRzRzRzRzRzR** [comment]
问题1我们没有实现，因为我们并不是按照访问epoch来训练的
问题2 0.5 如果降不下很有可能学习率和数据有问题
问题3 100起步就行

**Comment by zbrnwpu** [comment]
> 问题1我们没有实现，因为我们并不是按照访问epoch来训练的 问题2 0.5 如果降不下很有可能学习率和数据有问题 问题3 100起步就行

感谢您的解答，在对base模型ft时有一个参数有点不太理解，max_source_len 和max_seq_len 有何区别呐？

**Comment by zRzRzRzRzRzRzR** [comment]
这个问题可以在[技术文档](https://lslfd0slxc.feishu.cn/wiki/YInmwPmyii67VRkzU3BchPNzncg)找到相关答案，更多相关问题，请在技术文档中提出哦
