### ISSUE TITLE
对python版本有要求吗？

### ISSUE THREAD

**Issue by WangShunzhiDQ** [THUDM/ChatGLM3#49]
python38能跑吗？

**Comment by Roych13** [comment]
不行。里面用的match语法是3.10版本才有的。如果要跑，你得手动改源码。
不过两个用streamlit开发的demo我都没跑起来。早早弹出了URL，但实际上不知道啥时候才能加载完模型。反倒是Gradio开发的那个可以用。（python  web_demo.py）
