### ISSUE TITLE
AttributeError: type object 'UsageInfo' has no attribute 'model_validate'

### ISSUE THREAD

**Issue by zhanghu11** [THUDM/ChatGLM3#494]
### System Info / 系統信息

w11 cuda11.8 python3.10.6 

### Who can help? / 谁可以帮助到您？

api AttributeError: type object 'UsageInfo' has no attribute 'model_validate'

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python openai_api.py
post之后

### Expected behavior / 期待表现

如何解决

**Comment by zRzRzRzRzRzRzR** [comment]
环境不对，按照req升级

**Comment by snakecy** [comment]
pydantic 多少版本？

**Comment by panda4444ssdfs** [comment]
更新pydantic也没用，也还是报这个错AttributeError: type object 'UsageInfo' has no attribute 'model_validate'

**Comment by panda4444ssdfs** [comment]
求大佬指点
