### ISSUE TITLE
如何设置个性化的systemprompt，让模型默认扮演某一角色呢？

### ISSUE THREAD

**Issue by BryanMurkyChan** [THUDM/ChatGLM3#50]
如何设置自己个性化的system角色，让模型默认扮演着这个角色进行后续的对话，用户不需要在对话时要求模型扮演，类似chatgpt的customize，在哪里修改代码呢？

**Comment by Jankin66** [comment]
same question.

**Comment by LouisHeck** [comment]
是呀，如何手动修改<|system|>的内容？

**Comment by zhuyang2356** [comment]
我觉得可以在你构建应用，使用api以后，默认先发一句角色prompt

**Comment by SMR-S** [comment]
在history中传进去，例如： {"role": "system", "content": "请扮演一个律师"}，然后调用 chat(token，question, history=history)
