### ISSUE TITLE
提供更大的参数量

### ISSUE THREAD

**Issue by turkeymz** [THUDM/ChatGLM3#501]
### Feature request  / 功能建议

希望glm能提供更大参数量的模型，比如13B，34B等。全面覆盖从6~130B的各阶段

### Motivation / 动机

目前测试下来，6b的理解推理能力还是欠缺一些。在部分场景还是不可用

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
暂时没有相应的开源计划，如有，将会第一时间推送，敬请期待
