### ISSUE TITLE
在说完“你好啊”之后报错

### ISSUE THREAD

**Issue by loaferdai** [THUDM/ChatGLM3#51]
![image](https://github.com/THUDM/ChatGLM3/assets/44574883/8872a59c-0347-4173-bd87-7449b2b28edd)

**Comment by WangShunzhiDQ** [comment]
请问你用的python是什么版本？

**Comment by loaferdai** [comment]
3.10

**Comment by loaferdai** [comment]
好像是torch包的问题，conda中pip安装torch 走CPU运算了

**Comment by loaferdai** [comment]
![image](https://github.com/THUDM/ChatGLM3/assets/44574883/9cb83421-c490-4af1-882e-17054466565b)

**Comment by loaferdai** [comment]
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by liebkne** [comment]
不支持CPU
