### ISSUE TITLE
微调完成后的模型与原模型合并后，实测结果与推理验证结果不一致

### ISSUE THREAD

**Issue by xiaodou2021** [THUDM/ChatGLM3#511]
### System Info / 系統信息

python3.10
transformer 4.30.2
PyTorch  2.0.0
ubuntu20.04
Cuda  11.8

### Who can help? / 谁可以帮助到您？

@Btlmd 

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 按照官网[ChatGLM3-6B 微调示例]的步骤进行环境安装并按输入输出数据集的格式整理数据对模型进行微调
2. 微调完成后，通过官网如下方式进行推理验证：python inference.py \
    --pt-checkpoint "path to p-tuning checkpoint" \
    --model THUDM/chatglm3-6b  结果完全正确，模型输出与数据集中的输出完全一致，没有问题
3. 在部署时，通过如下方式合并微调结果到原模型，再次部署验证，发现模型输出与数据集结果不一致，甚至出现答非所问的情况，请问是如下合并方式不对还是模型本身所致?
合并微调方式：
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
config = AutoConfig.from_pretrained(model_path, trust_remote_code=True, pre_seq_len=128)
model = AutoModel.from_pretrained(model_path, config=config, trust_remote_code=True).cuda()
prefix_state_dict = torch.load(os.path.join(checkpoint_path, "pytorch_model.bin"))
new_prefix_state_dict = {}
for k, v in prefix_state_dict.items():
	   if k.startswith("transformer.prefix_encoder."):
	       new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
	       model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)

### Expected behavior / 期待表现

期望模型微调后合并后，能与推理验证的表现保持一致
如何正确的将微调后的结果应用到原模型中？如果需要合并，如何合并，请给出有效的合并方式？

**Comment by zRzRzRzRzRzRzR** [comment]
#253 微调问题请在这里提出，关于模型合并，算法同学之后会给出一个比较好的解决方案

**Comment by ghx2757** [comment]
> #253 微调问题请在这里提出，关于模型合并，算法同学之后会给出一个比较好的解决方案

期待+1    (*￣︶￣)

**Comment by Franklinlifangcheng** [comment]
> > #253 微调问题请在这里提出，关于模型合并，算法同学之后会给出一个比较好的解决方案
> 
> 期待+1 (*￣︶￣)

请问出了模型合并的内容了吗

**Comment by Franklinlifangcheng** [comment]
请问您的数据集是自己做的吗

**Comment by Franklinlifangcheng** [comment]
> #253 微调问题请在这里提出，关于模型合并，算法同学之后会给出一个比较好的解决方案

请问大佬有出模型合并的解决方案吗
