### ISSUE TITLE
我想要将工具返回的结果通过表格展示出来，我输入为“表格展示用户信息表里的所有数据”，返回为用户表里所有用户信息的元组，tool似乎无法像chat一样能够通过表格展示数据

### ISSUE THREAD

**Issue by zhanghaotian123** [THUDM/ChatGLM3#513]
### System Info / 系統信息

1

### Who can help? / 谁可以帮助到您？

1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1
![111111](https://github.com/THUDM/ChatGLM3/assets/59438626/1252cd38-bd68-4149-a980-155428bbea01)

### Expected behavior / 期待表现

期望tool能够将方法返回的数据通过表格形式展示

**Comment by zRzRzRzRzRzRzR** [comment]
不太可能，因为tools返回的只能是str类型，你要自己在后面做好展示脚本
