### ISSUE TITLE
增加32k版本的function

### ISSUE THREAD

**Issue by Qingluan** [THUDM/ChatGLM3#518]
### Feature request  / 功能建议

建议对chatglm3-6b-32k增加function_call

### Motivation / 动机

实际测试chatglm3-6b-32k，对文字的把握能力更强，实际使用更好用，但无法适配function_call， 开始几次还以为我api写的问题，后来切换了一下原始版本发现可以用了。

### Your contribution / 您的贡献

。。。。

**Comment by zRzRzRzRzRzRzR** [comment]
暂时无计划，支持Function Call的只有原模型，已经在技术手册提出
