### ISSUE TITLE
function call的回复内容错乱

### ISSUE THREAD

**Issue by YYYYYDDDDD** [THUDM/ChatGLM3#52]
我自己模拟注册了几个简单的tool，测试结果回复的内容有点错乱，必填参数未输入会自己创建时间
![code](https://github.com/THUDM/ChatGLM3/assets/52437468/94e6b923-44f6-4059-8136-d58a5748dbad)
![q1](https://github.com/THUDM/ChatGLM3/assets/52437468/904241d6-139a-4265-9753-a10236007e28)
![q2](https://github.com/THUDM/ChatGLM3/assets/52437468/8f1fdd31-ca13-4046-b560-8488c8fb8477)

**Comment by zRzRzRzRzRzRzR** [comment]
是的，传入工具的参数应该是一个完整的，不然那会被添加加入直至完整，能执行代码
这个是可能发生的，我们建议用户确保传入工具的信息准确，减少模型在这方面的判断
