### ISSUE TITLE
实际场景推理速度较慢，有推荐的加速方案吗？

### ISSUE THREAD

**Issue by zhaozhaoxia** [THUDM/ChatGLM3#521]
### System Info / 系統信息

ubutun 

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

部署后推理较慢，输入文本长度2k，响应时间大概需要6-7s

### Expected behavior / 期待表现

希望有较好的推理加速方案,响应时间下降到2-3s

**Comment by xiaoduozhou** [comment]
fastLLM 加速

**Comment by zRzRzRzRzRzRzR** [comment]
官方没有推出加速方案，但是支持vllm，trt，可以使用vllm等加速工具或自己实现trt引擎加速
