### ISSUE TITLE
openai_api.py  如何在多卡启动的时候载入pt微调数据呢

### ISSUE THREAD

**Issue by gaizi001** [THUDM/ChatGLM3#522]
### System Info / 系統信息

无

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我是这样写的

` model_path = "../model"
    config = AutoConfig.from_pretrained(model_path, trust_remote_code=True, pre_seq_len=128)
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

    # 多显卡支持，使用下面两行代替上面一行，将num_gpus改为你实际的显卡数量
    from utils import load_model_on_gpus
    model = load_model_on_gpus(model_path, num_gpus=2,config=config)
    prefix_state_dict = torch.load(os.path.join("/data/output", "pytorch_model.bin"))
    new_prefix_state_dict = {}
    for k, v in prefix_state_dict.items():
        if k.startswith("transformer.prefix_encoder."):
            new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
    print("Loaded from pt checkpoints", new_prefix_state_dict.keys())
    model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
    model = model.eval()
    uvicorn.run(app, host='0.0.0.0', port=18000, workers=1)`

然后执行后报错，无法正常启动

`Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:10<00:00,  1.46s/it]
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at ../model and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/jcdata/workspace/ChatGLM3/openai_api_demo/openai_api.py", line 241, in <module>
    model = load_model_on_gpus(model_path, num_gpus=2,config=config)
  File "/jcdata/workspace/ChatGLM3/openai_api_demo/utils.py", line 60, in load_model_on_gpus
    model = dispatch_model(model, device_map=device_map)
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/accelerate/big_modeling.py", line 343, in dispatch_model
    check_device_map(model, device_map)
  File "/root/anaconda3/envs/chatglm3-demo/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1142, in check_device_map
    raise ValueError(
ValueError: The device_map provided does not give any device for the following parameters: transformer.prefix_encoder.embedding.weight`

### Expected behavior / 期待表现

能够在多卡模式下正确启动模型，并且加载pt微调数据

**Comment by sdzbzj0406** [comment]
同样遇到这个问题，期待解决

**Comment by zRzRzRzRzRzRzR** [comment]
讨论区中有多卡读入的bug，目前还未能处理。可以移步讨论区讨论
