### ISSUE TITLE
API调用,模型返回信息飘忽

### ISSUE THREAD

**Issue by bangzhongxing** [THUDM/ChatGLM3#524]
### System Info / 系統信息

[****](url)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用API交互，连续问同一个问题。
总是会遇到，文不对题的回复，还包含空回复

### Expected behavior / 期待表现

使用API交互，连续问同一个问题。
每个回复都是完整的，不应该缺失，或者不对题

**Comment by bangzhongxing** [comment]
图片

**Comment by zRzRzRzRzRzRzR** [comment]
这个跟API代码没有关系，本身是模型上输出飘忽吧
