### ISSUE TITLE
function call 必填参数不输入,不会提示,有时还会自己输出无关内容

### ISSUE THREAD

**Issue by YYYYYDDDDD** [THUDM/ChatGLM3#53]
使用的是tool_using中的cli_demo_tool.py,必填参数不输入,不会提示,有时还会自己编内容
代码：
![code2](https://github.com/THUDM/ChatGLM3/assets/52437468/d60ed3af-b715-4902-b26e-05ea4ba80849)
效果：发消息的内容未输入，模型自行输出了”你好，李四“
![q3](https://github.com/THUDM/ChatGLM3/assets/52437468/6abd2b06-4825-4318-b115-f8857d97fdd3)

**Comment by mMrBun** [comment]
试试在参数的description中加e.g. xxx例如你这里的time字段
```json
{
"description": "要查询考勤信息的时间。e.g. 2022-09-01,2023-10-14"
}
```

**Comment by mMrBun** [comment]
> > 试试在参数的description中加e.g. xxx例如你这里的time字段
> > ```json
> > {
> > "description": "要查询考勤信息的时间。e.g. 2022-09-01,2023-10-14"
> > }
> > ```
> 
> 试了一下，还是原来的效果 o(╥﹏╥)o

那就是你的描述写的不好，建议更改一下描述信息，另外你可以参考Qwen的react代码和ToolBench的示例，我不知道提别的仓库是否被允许，如果不允许的话我会删除这条评论

**Comment by zRzRzRzRzRzRzR** [comment]
目前一定要用户输入正确的参数才能被执行，尽量减少模型的意图识别
如果是可选参数，目前需要通过微调才能做到
