### ISSUE TITLE
按照默认的参数进行微调，出现灾难性遗忘，请问有什么参数微调的指南吗？

### ISSUE THREAD

**Issue by cc8476** [THUDM/ChatGLM3#532]
### System Info / 系統信息

linux , 微调使用4090Ti 

### Reproduction / 复现过程

使用finetune_chatmodel_demo/finetune_pt.sh 进行微调，参数不变；
数据集使用默认的AdvertiseGen

微调的回答符合预期，但是通用性问题完全问答不了
求前辈指点

### Expected behavior / 期待表现

能回答泛化问题，以及微调针对性问题

**Comment by zRzRzRzRzRzRzR** [comment]
你这个学习率过大了估计
[官方技术文档](https://lslfd0slxc.feishu.cn/wiki/YInmwPmyii67VRkzU3BchPNzncg) 可参考
