### ISSUE TITLE
【ValueError: not enough values to unpack (expected 2, got 1)】如何调用 chatglm3-6b-base模型，用web页面报错。

### ISSUE THREAD

**Issue by haozaiiii** [THUDM/ChatGLM3#533]
### System Info / 系統信息

Traceback (most recent call last):
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/data/pyh/llm/project/ChatGLM3/basic_demo/web_demo2.py", line 79, in <module>
    for response, history, past_key_values in model.stream_chat(
  File "/root/anaconda3/envs/pyl-310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 1079, in stream_chat
    response, new_history = self.process_response(response, history)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b-base/modeling_chatglm.py", line 1005, in process_response
    metadata, content = response.split("\n", maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

streamlit run web_demo2.py，提问便会报错

### Expected behavior / 期待表现

期待提供解决方法

**Comment by OMRailgun** [comment]
我也发现了这个问题，发现process_response函数拿到的output包含了多个<|assistant|>穿插的文本，类似于
"""
****<|assistant|>**<|assistant|>
*****<|assistant|>
****<|assistant|>
****"""
但是不确定是什么原因引发了这个问题

**Comment by zRzRzRzRzRzRzR** [comment]
第一个报错是我们huggingface文件的问题，需要修改
第二个没有复现

**Comment by zRzRzRzRzRzRzR** [comment]
> 我也发现了这个问题，发现process_response函数拿到的output包含了多个<|assistant|>穿插的文本，类似于 """ ****<|assistant|>**<|assistant|> *****<|assistant|> ****<|assistant|> ****""" 但是不确定是什么原因引发了这个问题

给几个复现？

**Comment by OMRailgun** [comment]
chatglm3_path="..."
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained(chatglm3_path, trust_remote_code=True)
llm = AutoModel.from_pretrained(chatglm3_path, trust_remote_code=True, device='cuda')
llm = llm.eval()

tools_json=[
            {
                'name': 'PeopleRec', 
                'description': '当你需要知道图片中出现的人物后才可回复请求时，可使用该工具识别给定的图片中出现了哪些人物，并返回所出现人物的名字',
                'parameters': {
                    'type': 'object',
                    'properties': {'url': {'type': 'string', 'description': '给定图片的链接'}}, 
                    'required': ['url']
                }
            }, 
            {
                'name': 'OCR',
                'description': '可被用于识别图片中出现的字幕或文字信息',
                'parameters': {
                    'type': 'object', 
                    'properties': {'url': {'type': 'string', 'description': '给定图片的链接'}},
                    'required': ['url']
                }
            }
]
history=[]
history.append({
    "role": "system",
    "content": "请回答接下来的这些问题，你可以用到一些额外的工具，当你不需要这些工具也可以回答时请直接回答而不用去调用工具，你所能获取到的工具包含了后面这些工具:",
    "tools": tools_json
})
query="用身边的材料演示光的折射现象。"
response, history = llm.chat(
            tokenizer,
            query,
            history=history,
            do_sample=False,
            max_length=8192,
            temperature=0.8,
        )

**Comment by OMRailgun** [comment]
我这边可以用上面的代码很稳定的复现 ValueError: not enough values to unpack (expected 2, got 1)的这个错误，同时output里是 """ ****<|assistant|>**<|assistant|> *****<|assistant|> ****<|assistant|> ****""" 类似这种形式，麻烦辛苦复现&排查一下~

**Comment by zRzRzRzRzRzRzR** [comment]
问题暂时用工程方法解决了，去huggingface拉一下[modeling_chatglm.py](https://huggingface.co/THUDM/chatglm3-6b/blob/main/modeling_chatglm.py)
