### ISSUE TITLE
在更新 95942a7  这个commit 之后，运行 python openai_api_demo/openai_api.py 报错 ModuleNotFoundError: No module named 'tool_using'

### ISSUE THREAD

**Issue by qurikuduo** [THUDM/ChatGLM3#543]
### System Info / 系統信息

CUDA：                   CUDA Version: 12.1
python：                    3.11.5
pytorch：                   2.1.1           py3.11_cuda12.1_cudnn8.9.2_0    pytorch
pytorch-cuda：              12.1                 ha16c6d3_5    pytorch
transformers：              4.35.2                   pypi_0    pypi
OS：                   Ubuntu 18.04

### Who can help? / 谁可以帮助到您？

@Samge0

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

 1.  conda activate chatglm3
  2.  ls
  3.  cd ChatGLM3/
  4.  cd openai_api_demo/
  5.  python openai_api.py 
错误：
```
Traceback (most recent call last):
  File "/root/fastgpt/ChatGLM3/openai_api_demo/openai_api.py", line 24, in <module>
    from tool_using.tool_register import dispatch_tool
ModuleNotFoundError: No module named 'tool_using'
```

### Expected behavior / 期待表现

demo可以正常启动。

**Comment by zRzRzRzRzRzRzR** [comment]
引用的是主目录的tool use 我在本版本尝试改一下

**Comment by qurikuduo** [comment]
我本地将 openai_api_demo/openai_api.py 和openai_api_demo/openai_api_request.py  返回上一个版本，再运行是正常的。

**Comment by zRzRzRzRzRzRzR** [comment]
因为这引用了tool_using中注册的模型，为了能体现出stream 流式返回调用工具，在这里，已经暂时注释，openai demo中是没有注册工具的，仅仅是提供一个范例，用户可以自己去接入自己的工具

**Comment by qurikuduo** [comment]
OK，多谢。
