### ISSUE TITLE
请问4-bit量化的精度是什么？希望增加说明

### ISSUE THREAD

**Issue by zhengyangyong** [THUDM/ChatGLM3#545]
### Feature request  / 功能建议

原文：

默认情况下，模型以 FP16 精度加载，运行上述代码需要大概 13GB 显存。如果你的 GPU 显存有限，可以尝试以量化方式加载模型，使用方法如下：

```
model = AutoModel.from_pretrained("THUDM/chatglm3-6b",trust_remote_code=True).quantize(4).cuda()
```

模型量化会带来一定的性能损失，经过测试，ChatGLM3-6B 在 4-bit 量化下仍然能够进行自然流畅的生成。

**按上述代码启动模型还是FP16精度加载吗？**

### Motivation / 动机

改进文档

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
int4和int8都实现了
可查看源码
https://huggingface.co/THUDM/chatglm3-6b/blob/main/quantization.py
