### ISSUE TITLE
composite_demo的UI没法设置MAX_LENGTH

### ISSUE THREAD

**Issue by XiaoXiaoJiangYun** [THUDM/ChatGLM3#550]
### System Info / 系統信息

composite_demo的UI没法设置MAX_LENGTH，固定最大为8192

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 运行composite_demo
2. UI里只有top_p、temperature、repetition_penalty
3. 无法设置MAX_LENGTH

### Expected behavior / 期待表现

composite_demo的UI可以设置MAX_LENGTH

**Comment by zRzRzRzRzRzRzR** [comment]
改了，不用MAX_LENGTH了，改成了max_new_tokens
