### ISSUE TITLE
使用多轮对话p-tuning过的chat模型时，num_beams > 1报错

### ISSUE THREAD

**Issue by fjll613** [THUDM/ChatGLM3#551]
### System Info / 系統信息

GPU=V100
CUDA=11.8
torch=2.1.1
----------------------------------------------------------------------------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[15], line 17
     15     user_prompt = "产业研究报告: {}".format(text)
     16     prompt = system_prompt+'\n'+user_prompt
---> 17     response, _ = model.chat(tokenizer, prompt, history=[], num_beams=5)
     18     o['pred'].append({"ent":ent, "res": response})
     19 oo.append(o)

File ~/work/团队共享目录/lvjia/miniconda3/envs/py311/lib/python3.11/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py:1037, in ChatGLMForConditionalGeneration.chat(self, tokenizer, query, history, role, max_length, num_beams, do_sample, top_p, temperature, logits_processor, **kwargs)
   1034 inputs = inputs.to(self.device)
   1035 eos_token_id = [tokenizer.eos_token_id, tokenizer.get_command("<|user|>"),
   1036                 tokenizer.get_command("<|observation|>")]
-> 1037 outputs = self.generate(**inputs, **gen_kwargs, eos_token_id=eos_token_id)
   1038 outputs = outputs.tolist()[0][len(inputs["input_ids"][0]):-1]
   1039 response = tokenizer.decode(outputs)

File ~/work/团队共享目录/lvjia/miniconda3/envs/py311/lib/python3.11/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~/work/团队共享目录/lvjia/miniconda3/envs/py311/lib/python3.11/site-packages/transformers/generation/utils.py:1649, in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, **kwargs)
   1641     input_ids, model_kwargs = self._expand_inputs_for_generation(
   1642         input_ids=input_ids,
   1643         expand_size=generation_config.num_beams * generation_config.num_return_sequences,
   1644         is_encoder_decoder=self.config.is_encoder_decoder,
   1645         **model_kwargs,
   1646     )
   1648     # 14. run beam sample
-> 1649     return self.beam_sample(
   1650         input_ids,
   1651         beam_scorer,
   1652         logits_processor=logits_processor,
   1653         logits_warper=logits_warper,
   1654         stopping_criteria=stopping_criteria,
   1655         pad_token_id=generation_config.pad_token_id,
   1656         eos_token_id=generation_config.eos_token_id,
   1657         output_scores=generation_config.output_scores,
   1658         return_dict_in_generate=generation_config.return_dict_in_generate,
   1659         synced_gpus=synced_gpus,
   1660         **model_kwargs,
   1661     )
   1663 elif is_group_beam_gen_mode:
   1664     if generation_config.num_return_sequences > generation_config.num_beams:

File ~/work/团队共享目录/lvjia/miniconda3/envs/py311/lib/python3.11/site-packages/transformers/generation/utils.py:3296, in GenerationMixin.beam_sample(self, input_ids, beam_scorer, logits_processor, stopping_criteria, logits_warper, max_length, pad_token_id, eos_token_id, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, synced_gpus, **model_kwargs)
   3293 next_tokens = next_tokens % vocab_size
   3295 # stateless
-> 3296 beam_outputs = beam_scorer.process(
   3297     input_ids,
   3298     next_token_scores,
   3299     next_tokens,
   3300     next_indices,
   3301     pad_token_id=pad_token_id,
   3302     eos_token_id=eos_token_id,
   3303     beam_indices=beam_indices,
   3304 )
   3305 beam_scores = beam_outputs["next_beam_scores"]
   3306 beam_next_tokens = beam_outputs["next_beam_tokens"]

File ~/work/团队共享目录/lvjia/miniconda3/envs/py311/lib/python3.11/site-packages/transformers/generation/beam_search.py:284, in BeamSearchScorer.process(self, input_ids, next_scores, next_tokens, next_indices, pad_token_id, eos_token_id, beam_indices)
    281         break
    283 if beam_idx < self.group_size:
--> 284     raise ValueError(
    285         f"At most {self.group_size} tokens in {next_tokens[batch_idx]} can be equal to `eos_token_id:"
    286         f" {eos_token_id}`. Make sure {next_tokens[batch_idx]} are corrected."
    287     )
    289 # Check if we are done so that we can save a pad step if all(done)
    290 self._done[batch_idx] = self._done[batch_idx] or beam_hyp.is_done(
    291     next_scores[batch_idx].max().item(), cur_len
    292 )

ValueError: At most 5 tokens in tensor([    2,     2,     2,     2,     2, 64795, 64795, 64795, 64795, 64795],
       device='cuda:0') can be equal to `eos_token_id: [2, 64795, 64797]`. Make sure tensor([    2,     2,     2,     2,     2, 64795, 64795, 64795, 64795, 64795],
       device='cuda:0') are corrected.

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.使用官方的p-tuning脚本微调案模型，过程正常进行
2.使用infer中的方法加载模型并调用chat方法，当num_beams=1(默认)时正常，>1时有时会报错
```
tokenizer = AutoTokenizer.from_pretrained('',trust_remote_code = True)
config = AutoConfig.from_pretrained('', trust_remote_code=True, pre_seq_len=128)
model = AutoModel.from_pretrained('', config=config, trust_remote_code=True).cuda()
prefix_state_dict = torch.load(os.path.join('', "pytorch_model.bin"))
new_prefix_state_dict = {}
for k, v in prefix_state_dict.items():
    if k.startswith("transformer.prefix_encoder."):
        new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
model = model.eval()
```
```
response, _ = model.chat(tokenizer, prompt, history=[], num_beams=5)
```

### Expected behavior / 期待表现

希望能获得解决这个问题的办法，在可以正确推理的数据上，num_beams=5的效果要好于1

**Comment by ruarua6666** [comment]
我也有这个问题，请问解决了吗？是什么原因引起的呢？
