### ISSUE TITLE
能够提供预训练的api

### ISSUE THREAD

**Issue by childlong** [THUDM/ChatGLM3#554]
### Feature request  / 功能建议

能够提供预训练的api

### Motivation / 动机

训练其他知识

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
已经提供了微调代码和base模型，你可以在自己的显卡平台训练

**Comment by zRzRzRzRzRzRzR** [comment]
技术文档已经规定了格式
