### ISSUE TITLE
finetune_chatmodel_demo 脚本的采用advertise_gen.jsonl数据， P-Tuning v2微调，结果推理时输出的都是：<UNK><UNK>

### ISSUE THREAD

**Issue by linjianwei888** [THUDM/ChatGLM3#564]
### System Info / 系統信息

python 311
cuda 12.0

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

<img width="1515" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/82926434/914ad8da-5796-440b-8380-ffd5ef4a8df6">
按照微调的readme来操作，微调结果：
<img width="1274" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/82926434/a206bf44-bf5a-41bc-b8d9-10e0ddbf7717">
应该如何解决呢？

### Expected behavior / 期待表现

期待glm3 完整的P-Tuning v2微调实例，数据集最好也准备好。一次就能跑通。

**Comment by zRzRzRzRzRzRzR** [comment]
微调问题详见 #253 我们已经提供了示例，示例是不会出现这问题的
