### ISSUE TITLE
能否提供垂域增量预训练接口？当前提供的base微调也仅是对话格式的输入

### ISSUE THREAD

**Issue by childlong** [THUDM/ChatGLM3#566]
### Feature request  / 功能建议

能否提供垂域增量预训练接口？当前提供的base微调也仅是对话格式的输入

### Motivation / 动机

能否提供垂域增量预训练接口？当前提供的base微调也仅是对话格式的输入

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
垂类领域数据集我们没有
我们提供的不是对话格式
是 输入 目标
你想要什么样子的格式？

**Comment by childlong** [comment]
输入就是text文本

**Comment by zRzRzRzRzRzRzR** [comment]
那输出是什么？

**Comment by childlong** [comment]
抱歉！ 我不是很懂哈. 我想要的就是在base模型上做增量预训练，然后在预训练好的模型上用对话格式的数据做指令微调。   这里增量预训练我准备了一些领域纯文本的数据，问下针对这种纯文本的预训练脚本能够提供下？   或者说chatglm3预训练的格式是输入输出格式的吗?

**Comment by zRzRzRzRzRzRzR** [comment]
所以你要把纯文本分成qa对啊，因为我们的微调只支持这一种格式
