### ISSUE TITLE
提供的base微调16G显存 out of memory.请问需要多大的显存

### ISSUE THREAD

**Issue by childlong** [THUDM/ChatGLM3#567]
### Feature request  / 功能建议

python3 finetune.py   --train_format input-output   --train_file train_data.jsonl   --lora_rank 8   --lora_alpha 32   --lora_dropout 0.1   --max_seq_length 256   --preprocessing_num_workers 1   --model_name_or_path /home/ma-user/pyc/code/ChatGLM3-main/chatglm3-6b   --output_dir output_test/    --per_device_train_batch_size 1   --gradient_accumulation_steps 1   --max_steps 500   --logging_steps 1   --save_steps 50   --learning_rate 0.1

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 15.74 GiB total capacity; 14

### Motivation / 动机

无

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
23GB
