### ISSUE TITLE
大家是怎么跑成功composite_demo的？给个配置呗。

### ISSUE THREAD

**Issue by Roych13** [THUDM/ChatGLM3#57]
比如python版本，操作系统，显卡GPU，是否需要量化模型等。
我跑完一直是这个状态，没看到加载模型的进度条，URL倒是秒出，但打开URL都是“该页无法显示”。
![微信截图_20231030005351](https://github.com/THUDM/ChatGLM3/assets/39145668/c15bddb2-c345-4820-a475-453208683f05)
除此之外，基于streamlit开发的都没成功。包括web_demo2和tool_using那两个。

测试环境用的是Autodl平台，具体如下：

> 操作系统：Ubuntu 18.0
> python版本： 3.10.13
> 显卡：24G显存，RTX4090
> 其它：使用.quantize(8).half().cuda()方法将client中模型进行了8位量化。

**Comment by zczhuohuo** [comment]
`cd composite_demo
export PYTHONPATH=`pwd`
streamlit run main.py
`

用的是 Python3.11.5，torch2.0.1，torch2.1.0 好像是不兼容，虽然 requirement 里面写了torch >=2.0

**Comment by Roych13** [comment]
> ```shell
> cd composite_demo
> export PYTHONPATH=`pwd`
> streamlit run main.py
> ```
> 
> 用的是 Python3.11.5，torch2.0.1，torch2.1.0 好像是不兼容，虽然 requirement 里面写了torch >=2.0

除了Python版本不一样之外，其它都跟你的一样（包括torch，这个好像是根据显卡自动安装的版本号）。
你的具体过程是怎么样的？先弹出URL，然后加载模型？还是先加载模型后再弹出URL？
我的是直接弹出URL之后就没了，不知道有没有加载完模型，也不知道什么时候加载完毕。
我现在改成3.11再试试。实在不行的话，我只能放弃了。回头有空再看源码，自己魔改

**Comment by moliwei2019** [comment]
跑composite_demo里的main.py会这样报错，原代码没有动过，环境是可以跑通web_demo2.py的。这是咋回事，应该也不会是缩进的原因啊
![企业微信截图_16988097418862](https://github.com/THUDM/ChatGLM3/assets/52551364/8687ba00-5739-4292-bc30-b68bf6181484)

**Comment by Roych13** [comment]
> 跑composite_demo里的main.py会这样报错，原代码没有动过，环境是可以跑通web_demo2.py的。这是咋回事，应该也不会是缩进的原因啊 ![企业微信截图_16988097418862](https://user-images.githubusercontent.com/52551364/279569014-8687ba00-5739-4292-bc30-b68bf6181484.png)

版本问题。这个match是python3.10才有的语法，请重新配置你的python环境。

**Comment by shakeley** [comment]
`streamlit run web_demo2.py --server.address=127.0.0.1`
refer to #82

**Comment by dzysunshine** [comment]
> 比如python版本，操作系统，显卡GPU，是否需要量化模型等。 我跑完一直是这个状态，没看到加载模型的进度条，URL倒是秒出，但打开URL都是“该页无法显示”。 ![微信截图_20231030005351](https://private-user-images.githubusercontent.com/39145668/278885631-c15bddb2-c345-4820-a475-453208683f05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjE3ODIsIm5iZiI6MTcwMjUyMTQ4MiwicGF0aCI6Ii8zOTE0NTY2OC8yNzg4ODU2MzEtYzE1YmRkYjItYzM0NS00ODIwLWE0NzUtNDUzMjA4NjgzZjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAyMzgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZDdlOTUwNmU5MzU4ODFlMjNjYWQ5YmU3YjYwMWY2OGQyN2IwNGYyM2FjOTkzYzU1ZWRkNjAwZTY2M2NiN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rZi85zPJbZ0v9u8mO6ZIiRW2B0xLwm4-fKudxORqTdk) 除此之外，基于streamlit开发的都没成功。包括web_demo2和tool_using那两个。
> 
> 测试环境用的是Autodl平台，具体如下：
> 
> > 操作系统：Ubuntu 18.0
> > python版本： 3.10.13
> > 显卡：24G显存，RTX4090
> > 其它：使用.quantize(8).half().cuda()方法将client中模型进行了8位量化。

你好，你在AutoDL配置的这个，生成的链接，最后在本地浏览器上打开了吗？

**Comment by Roych13** [comment]
> > 比如python版本，操作系统，显卡GPU，是否需要量化模型等。 我跑完一直是这个状态，没看到加载模型的进度条，URL倒是秒出，但打开URL都是“该页无法显示”。 ![微信截图_20231030005351](https://private-user-images.githubusercontent.com/39145668/278885631-c15bddb2-c345-4820-a475-453208683f05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjE3ODIsIm5iZiI6MTcwMjUyMTQ4MiwicGF0aCI6Ii8zOTE0NTY2OC8yNzg4ODU2MzEtYzE1YmRkYjItYzM0NS00ODIwLWE0NzUtNDUzMjA4NjgzZjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAyMzgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZDdlOTUwNmU5MzU4ODFlMjNjYWQ5YmU3YjYwMWY2OGQyN2IwNGYyM2FjOTkzYzU1ZWRkNjAwZTY2M2NiN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rZi85zPJbZ0v9u8mO6ZIiRW2B0xLwm4-fKudxORqTdk) 除此之外，基于streamlit开发的都没成功。包括web_demo2和tool_using那两个。
> > 测试环境用的是Autodl平台，具体如下：
> > > 操作系统：Ubuntu 18.0
> > > python版本： 3.10.13
> > > 显卡：24G显存，RTX4090
> > > 其它：使用.quantize(8).half().cuda()方法将client中模型进行了8位量化。
> 
> 你好，你在AutoDL配置的这个，生成的链接，最后在本地浏览器上打开了吗？

可以打开。URL：
http://127.0.0.1:8501
