### ISSUE TITLE
数据加载 target_based_loss_mask = [False] + loss_masks[:-1] 的问题

### ISSUE THREAD

**Issue by lolchuaner** [THUDM/ChatGLM3#572]
### System Info / 系統信息

cuda 11.8

### Who can help? / 谁可以帮助到您？

@Btlmd 

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

target_based_loss_mask = [False] + loss_masks[:-1] 

### Expected behavior / 期待表现

您好 ，请问，MultiTurnDataset 实现代码， finetune_demo/preprocess_utils.py 文件第 97 行  
target_based_loss_mask = [False] + loss_masks[:-1] 
为什么要在开头加个 False 呢？
我觉得如果eos可训的话，应该修改66行代码
_update([tokenizer.eos_token_id], True)

**Comment by zRzRzRzRzRzRzR** [comment]
不能训练，这个 [False] 的部分就是不被加入训练的

**Comment by lolchuaner** [comment]
代码里面是可训的

**Comment by Btlmd** [comment]
```python
def format_conversation(item, tokenizer, conversation_key: str, tool_key: str):
```

这段代码中 loss_mask 的含义是，这个 token **所预测** 的 token 是否 take_loss，最后的 `eos` 是否被学习不是由自己的 loss_mask 决定，而是由上一轮的最后一个 loss_mask 决定

---

```python
    def __getitem__(self, i) -> dict:
        data_item = self.data[i]
        tokens, loss_masks = format_conversation(data_item, self.tokenizer, CONVERSATOIN_KEY, TOOL_DESC_KEY)

        # labels are used inside the model
        target_based_loss_mask = [False] + loss_masks[:-1]
```

这段代码中的 target_based_loss_mask 是说对应的 token 是否要被学习

---

关于 loss_mask 的更多解释，可参见 #184
