### ISSUE TITLE
Bug: 模型无法通过git-lfs下载

### ISSUE THREAD

**Issue by CNCSMonster** [THUDM/ChatGLM3#575]
### System Info / 系統信息

ccm@ccm:~/workplace$ git clone https://huggingface.co/THUDM/chatglm3-6b
Cloning into 'chatglm3-6b'...
fatal: unable to access 'https://huggingface.co/THUDM/chatglm3-6b/': Failed to connect to huggingface.co port 443: Connection refused
ccm@ccm:~/workplace$ git-lfs --version
git-lfs/3.0.2 (GitHub; linux amd64; go 1.18.1)
ccm@ccm:~/workplace$ uname -a
Linux ccm 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

sudo apt-get install git-lfs
sudo apt-get isntall git
git clone https://huggingface.co/THUDM/chatglm3-6b

### Expected behavior / 期待表现

希望能够正常通过git-lfs下载模型

**Comment by Roych13** [comment]
建议用modelscope（魔塔社区）试试。我之前部署在国内某云服务上，就是用魔塔社区的，可以直接git clone

**Comment by zRzRzRzRzRzRzR** [comment]
你应该是git lfs install 才能下载
