### ISSUE TITLE
生成的方法调用代码错误

### ISSUE THREAD

**Issue by HuChundong** [THUDM/ChatGLM3#579]
### System Info / 系統信息

win11，cuda12

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

调用自定义的方法
`@register_tool
def get_sd_image(prompt: Annotated[str, 'user provided image description, should be english', True]) -> dict:
    '''
    这是一个AI绘图工具，完成用户绘图的任务，根据用户描述生成图像，{prompt} 转换成英文后传给工具
    This is an AI drawing tool designed to fulfill users' drawing tasks. It generates images based on user descriptions. The {prompt} is translated into English and passed on to the tool.
    '''
    import requests
    try:
        resp = requests.get(f"http://127.0.0.1:6666/get_image?prompt=${prompt}")
        resp.raise_for_status()
        # Assuming the response content is the image data
        image_data = BytesIO(resp.content)
        image = Image.open(image_data)
    except Exception as e:
        import traceback
        # Handle the exception appropriately, e.g., log it or return an error message
        print(f"Error encountered: {e}")
        image = None
    filename = '{}.png'.format(''.join(random.sample(
                            'abcdefghijklmnopqrstuvwxyz1234567890', 8)))
    return {'res': image, 'res_type': 'image', 'filename': filename}
`

生成的结果
`get_sd_image
content str:  ```python
tool_call(prompt='A little cartoon dog is dancing joyfully.)    <------- 这里的字符串类型参数，缺了一个单引号
````

### Expected behavior / 期待表现

`get_sd_image
content str:  ```python
tool_call(prompt='A little cartoon dog is dancing joyfully.')
````

参数缺少单引号，导致执行失败

**Comment by zRzRzRzRzRzRzR** [comment]
这个情况不应该出现，很稳定固定少一个吗

**Comment by HuChundong** [comment]
> 这个情况不应该出现，很稳定固定少一个吗

是的，我使用这个自定义方法的时候，出现多次少一个 单引号。

**Comment by HuChundong** [comment]
`：{
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "ai_image\n ```python\ntool_call(prompt='A lonely man's silhouette on a neon-lit street.')\n```",
        "function_call": null,
        "name": null,
        "role": "assistant"
      }
    }
  ],
  "created": 1702323215,
  "model": "chatglm3",
  "object": "chat.completion",
  "usage": {
    "completion_tokens": 35,
    "prompt_tokens": 294,
    "total_tokens": 329
  }
}`

还有这种 中间的单引号需要转义的问题。

**Comment by zRzRzRzRzRzRzR** [comment]
对的，引号需要转义成 \"

**Comment by zRzRzRzRzRzRzR** [comment]
> > 这个情况不应该出现，很稳定固定少一个吗
> 
> 是的，我使用这个自定义方法的时候，出现多次少一个 单引号。

已经标记，会不会是转义问题被截断
