### ISSUE TITLE
openai_api中将uvicorn.run(app, host='0.0.0.0', port=8000, workers=1)中将workers修改为2后再次请求，会出现model没有定义的情况

### ISSUE THREAD

**Issue by CNUIGB** [THUDM/ChatGLM3#584]
### System Info / 系統信息

起初我是想提高接口的响应能力，所以尝试将workers修改为2，但是接受加载后的模型变量model在被引用时提示没有定义。

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在修改workers后，使用open_api.py启动服务，然后使用openai_api_request.py发出请求，此时后端会提示model没有定义

### Expected behavior / 期待表现

\

**Comment by zRzRzRzRzRzRzR** [comment]
workers只能为1 ，模型也只能在单卡加载。这个情况我们后面会处理的，最近有点太忙了
