### ISSUE TITLE
openai_api.py 启动了之后为什么不支持多个线程调用呢？

### ISSUE THREAD

**Issue by gaizi001** [THUDM/ChatGLM3#588]
### System Info / 系統信息

无

### Who can help? / 谁可以帮助到您？

无

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

openai_api.py 启动了能正常调用，为什么我用多个线程调用，必须等待上一条推理完成才能继续响应推理呢

### Expected behavior / 期待表现

可以进行api多线程调用

**Comment by zRzRzRzRzRzRzR** [comment]
单线程，单显卡，目前的API只支持这样（毕竟是个demo）
如果后续有升级计划，我们将更新代码

**Comment by gaizi001** [comment]
> 单线程，单显卡，目前的API只支持这样（毕竟是个demo） 如果后续有升级计划，我们将更新代码

@zRzRzRzRzRzRzR 
好的，谢谢回复，是不是chatglm1到3都是这种机制啊

**Comment by waaaagh176** [comment]
> 单线程，单显卡，目前的API只支持这样（毕竟是个demo） 如果后续有升级计划，我们将更新代码

请问什么时候能更新这个功能，非常需要
