### ISSUE TITLE
请问使用CPU微调模型，报错怎么解决呢？

### ISSUE THREAD

**Issue by MONSTER-lion** [THUDM/ChatGLM3#589]
### System Info / 系統信息

CPU运行

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

bash ./scripts/finetune_pt.sh 

### Expected behavior / 期待表现

期待回复

**Comment by zRzRzRzRzRzRzR** [comment]
CPU调不了... 建议使用GPU
