### ISSUE TITLE
Bugs: code interpreter does not work properly

### ISSUE THREAD

**Issue by ChuxiJ** [THUDM/ChatGLM3#59]
demo中肯定有bugs，答非所问

![image](https://github.com/THUDM/ChatGLM3/assets/30956809/c81e5ca2-87ee-4c33-8833-ba0b2b9a5ab5)

**Comment by Halflifefa** [comment]
一样的问题，tool也是，它知道自己能用哪些工具，但它就是不用

**Comment by ChuxiJ** [comment]
关于code interpreter请参考我这里的实现：
https://github.com/timedomain-tech/open-creator/blob/main/creator/code_interpreter/__init__.py

项目已经在v0.1.3版本支持memGPT

**Comment by ChuxiJ** [comment]
感谢回复

我猜是有几个环境设置影响了

1. conda环境没有遵从设置创建chatglm3-demo的环境。这导致第一部分写的代码，代码解释器不能正常运作。也就是没有observe
2. 第一个问题我也忘了大概是帮我写一个能解决24点游戏的编程，它没有输出。我以为是代码解释器没work，于是又问了一遍让它1+1，print hello world
3. 在消息列表中，传给chatglm3的历史记录没有包含我新的指令，而是旧的消息。导致又重新生成了一遍之前的代码
