### ISSUE TITLE
微调的各种问题

### ISSUE THREAD

**Issue by BXHQu** [THUDM/ChatGLM3#590]
### Discussed in https://github.com/THUDM/ChatGLM3/discussions/253
**### 那个 大佬可以帮忙解决一下吗，4090双卡微调出现以下两个：**
1.loss第一个正常，第二个往后全为0

{'loss': 2.7197, 'learning_rate': 0.0001999, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001998, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019970000000000003, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001996, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019950000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019940000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019930000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019920000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019910000000000001, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.000199, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001989, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001988, 'epoch': 0.0}
2.保持checkpoint时，出现文件不存在

RuntimeError: Parent directory output/text-20231213-185108-2e-4/tmp-checkpoint-50 does not exist.
  2%|▎         | 50/2000 [00:06<04:13,  7.68it/s]

[INFO|trainer.py:1706] 2023-12-13 18:51:27,485 >> ***** Running training *****
[INFO|trainer.py:1707] 2023-12-13 18:51:27,485 >>   Num examples = 60,726
[INFO|trainer.py:1708] 2023-12-13 18:51:27,485 >>   Num Epochs = 1
[INFO|trainer.py:1709] 2023-12-13 18:51:27,485 >>   Instantaneous batch size per device = 1
[INFO|trainer.py:1712] 2023-12-13 18:51:27,485 >>   Total train batch size (w. parallel, distributed & accumulation) = 2
[INFO|trainer.py:1713] 2023-12-13 18:51:27,485 >>   Gradient Accumulation steps = 1
[INFO|trainer.py:1714] 2023-12-13 18:51:27,486 >>   Total optimization steps = 2,000
[INFO|trainer.py:1715] 2023-12-13 18:51:27,488 >>   Number of trainable parameters = 1,949,696
  0%|          | 0/2000 [00:00<?, ?it/s][W reducer.cpp:1346] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1346] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
{'loss': 2.7197, 'learning_rate': 0.0001999, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001998, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019970000000000003, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001996, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019950000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019940000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019930000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019920000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019910000000000001, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.000199, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001989, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001988, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019870000000000003, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001986, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019850000000000003, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001984, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019830000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019820000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019810000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019800000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001979, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001978, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001977, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001976, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019750000000000003, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001974, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019730000000000003, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001972, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019710000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019700000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019690000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001968, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001967, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001966, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001965, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001964, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019630000000000003, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001962, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019610000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.000196, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019590000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019580000000000002, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001957, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001956, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001955, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001954, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001953, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.0001952, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.00019510000000000003, 'epoch': 0.0}
{'loss': 0.0, 'learning_rate': 0.000195, 'epoch': 0.0}
  2%|▎         | 50/2000 [00:06<03:08, 10.33it/s][INFO|tokenization_utils_base.py:2432] 2023-12-13 18:51:34,817 >> tokenizer config file saved in output/text-20231213-185108-2e-4/tmp-checkpoint-50/tokenizer_config.json
[INFO|tokenization_utils_base.py:2441] 2023-12-13 18:51:34,817 >> Special tokens file saved in output/text-20231213-185108-2e-4/tmp-checkpoint-50/special_tokens_map.json
Traceback (most recent call last):
  File "/root/autodl-tmp/Red_Teaming_LLMs/./train/finetune.py", line 147, in <module>
    main()
  File "/root/autodl-tmp/Red_Teaming_LLMs/./train/finetune.py", line 141, in main
    trainer.train()
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/transformers/trainer.py", line 1914, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/transformers/trainer.py", line 2274, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/transformers/trainer.py", line 2354, in _save_checkpoint
    self._save_optimizer_and_scheduler(staging_output_dir)
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/transformers/trainer.py", line 2450, in _save_optimizer_and_scheduler
    torch.save(self.optimizer.state_dict(), os.path.join(output_dir, OPTIMIZER_NAME))
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/torch/serialization.py", line 618, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/torch/serialization.py", line 492, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/torch/serialization.py", line 463, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: Parent directory output/text-20231213-185108-2e-4/tmp-checkpoint-50 does not exist.
  2%|▎         | 50/2000 [00:06<04:13,  7.68it/s]
[2023-12-13 18:51:40,493] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 36157 closing signal SIGTERM
[2023-12-13 18:51:40,757] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 36156) of binary: /root/miniconda3/envs/torch2.1/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch2.1/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/torch2.1/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./train/finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-13_18:51:40
  host      : autodl-container-acc940bcfe-0619f71f
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 36156)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by NOKI-RYUU** [comment]
同样的问题，是如何解决的？

**Comment by jwen6118** [comment]
peft版本降成0.6.0后就可以了

**Comment by sherlock1987** [comment]
谢谢，这个也解决呢我的问题，就是把peft版本变成了 0.6.0 就可以了。
