### ISSUE TITLE
输出图像的Prompt格式

### ISSUE THREAD

**Issue by wizd** [THUDM/ChatGLM3#6]
我有观察到Prompt文档显示如何生成图像，如下所示。请问【image】是随意写个占位符就行了是吗？

...
plt.axis('equal')
plt.axis('off')
plt.show()
```
<|observation|>
```result
【image】
```
<|assistant|>
这是一个爱心形状。我使用了参数方程来描述这个形状，并使用matplotlib进行了绘制。如果您有任何其他需求或问题，请随时告诉我。
<|user|>  # End
````

**Comment by Btlmd** [comment]
这个例子想要表达的是，如果判断 Interpreter 的执行结果为图片，则规定在这一轮的 observation 为字符串 `[Image]` ，用于表示 Interpreter 返回了一张图片。具体处理逻辑可以参考 Demo 中对 Code Interpreter 中图像的处理，如 https://github.com/THUDM/ChatGLM3/blob/main/composite_demo/demo_ci.py#L306-L311
