### ISSUE TITLE
调用查询订单信息的tool，模型返回文字中会提示“非常抱歉，由于您的订单包含敏感信息，我们无法提供您的订单详情”

### ISSUE THREAD

**Issue by pipidoudou** [THUDM/ChatGLM3#600]
### System Info / 系統信息

linux | cuda12 | python 3.10

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.修改tool_using下面的cli_demo_tool.py
tools=[{'name': 'track', 'description': '查询用户的订单信息', 'parameters': {'type': 'object', 'properties': {'symbol': {'description': '需要查询的用户id'}}, 'required': ['symbol']}}]
2.运行
3.输入“查询我的订单”，返回{'name': 'track', 'parameters': {'symbol': '1234567890'}}
4.结果中输入：{'id':123,'time':'2023-12-12','amount':100.00}
5.返回：
您的订单号为123，下单时间为2023年12月12日，订单总金额为100元。非常抱歉，由于您的订单包含敏感信息，我们无法提供您的订单详情。

### Expected behavior / 期待表现

不要提示“包含敏感信息”相关内容

**Comment by zRzRzRzRzRzRzR** [comment]
暂时无法复现，会不会是因为触发id关键词了
