### ISSUE TITLE
没有找到base模型推理，下面base模型推理是对的吗？

### ISSUE THREAD

**Issue by childlong** [THUDM/ChatGLM3#604]
### System Info / 系統信息

tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModel.from_pretrained(model_path, trust_remote_code=True).cuda()
model = model.eval()
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
response = model.generate(input_ids=inputs["input_ids"],max_length=inputs["input_ids"].shape[-1] + 128)
response = response[0, inputs["input_ids"].shape[-1]:]
print("Response:", tokenizer.decode(response, skip_special_tokens=True))

输入输出
prompt：今天天气怎么样
Response: ？ 今天天气怎么样？根据我的观察和了解，今天天气晴朗，阳光明媚，气温适宜，非常适合户外活动。

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

无

**Comment by zRzRzRzRzRzRzR** [comment]
base模型没有做demo
