### ISSUE TITLE
在Ascend上stream推理遇到问题

### ISSUE THREAD

**Issue by ikuntrue199** [THUDM/ChatGLM3#605]
### System Info / 系統信息

openEuler 2203
Ascend 910

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我导入了一些能在NPU上推理的包，例如：
import torch
import torch_npu
我执行例子中的cli_demo.py流式推理没问题，但是我执行openai_api.py后，流式推理遇到问题，不采用流式推理就没问题，报错如下：
File "/home/test_dir/torch_test/docu/sheng/docu/openai_api.py", line 314, in predict_stream
    for new_response in generate_stream_chatglm3(model, tokenizer, gen_params):
  File "/root/miniconda3/envs/torch/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "/home/test_dir/torch_test/docu/sheng/docu/utils.py", line 138, in generate_stream_chatglm3
    for total_ids in model.stream_generate(**inputs, eos_token_id=eos_token_id, **gen_kwargs):
  File "/root/miniconda3/envs/torch/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1207, in stream_generate
    if unfinished_sequences.max() == 0 or stopping_criteria(input_ids, scores):
RuntimeError: allocate:/usr1/02/workspace/j_vqN6BFvg/pytorch/torch_npu/csrc/core/npu/NPUCachingAllocator.cpp:1406 NPU error, error code is 107002
[Error]: The context is empty.
        Check whether acl.rt.set_context or acl.rt.set_device is called.
EE1001: The argument is invalid.Reason: rtGetDevMsg execute failed, reason=[context pointer null]
        Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.
        TraceBack (most recent call last):
        ctx is NULL![FUNC:GetDevErrMsg][FILE:api_impl.cc][LINE:4290]
        The argument is invalid.Reason: rtGetDevMsg execute failed, reason=[context pointer null]

### Expected behavior / 期待表现

help

**Comment by zRzRzRzRzRzRzR** [comment]
我这里没有这个机器，暂时没有办法复现这个问题

**Comment by fuxiaoiii** [comment]
老哥，可以看一下你的非流式输出的完整代码吗？以及需要自定义算子适配吗

**Comment by ikuntrue199** [comment]
> 老哥，可以看看你的非流式输出的完整代码吗？以及需要自定义算子重构吗？

用官方库的就可以了   不用算子适配  Ascend已经 都适配了，transformers也适配Ascend了   将指定cuda 指定为npu就可以了

**Comment by ikuntrue199** [comment]
> 我这里没有这个机器，暂时没有办法复现这个问题

好的麻烦了 我已经联系Ascend的人了 可能是utils里面的stream_generate造成的，这个接口可能跟npu存在兼容问题。目前我将openai_demo 根据glm2中的例子修改了一下，已经可以流式输出了

**Comment by fuxiaoiii** [comment]
> > 老哥，可以看看你的非流式输出的完整代码吗？以及需要自定义算子重构吗？
> 
> 用官方库的就可以了 不用算子适配 Ascend已经 都适配了，transformers也适配Ascend了 将指定cuda 指定为npu就可以了

已成功，十分感谢！

**Comment by bbang94** [comment]
@ikuntrue199 也遇到了这个问题，请问可以把修改的代码同步一下嘛

**Comment by Demainlip** [comment]
> > 我这里没有这个机器，暂时没有办法复现这个问题
> 
> 好的麻烦了 我已经联系Ascend的人了 可能是utils里面的stream_generate造成的，这个接口可能跟npu存在兼容问题。目前我将openai_demo 根据glm2中的例子修改了一下，已经可以流式输出了
也遇到了这个问题，请问可以把修改的代码同步一下嘛

**Comment by Demainlip** [comment]
> > 我这里没有这个机器，暂时没有办法复现这个问题
> 
> 好的麻烦了 我已经联系Ascend的人了 可能是utils里面的stream_generate造成的，这个接口可能跟npu存在兼容问题。目前我将openai_demo 根据glm2中的例子修改了一下，已经可以流式输出了
@ikuntrue199 也遇到了这个问题，请问可以把修改的代码同步一下嘛

**Comment by cmhjoe2008** [comment]
遇到相同问题+1，哪位好心大佬同步一下代码 @ikuntrue199

**Comment by cmhjoe2008** [comment]
搞定了，npu不兼容，换个写法就好了。
思路是把stream_generate替换成stream_chat

**Comment by chwyxy** [comment]
遇到相同问题+1，哪位好心大佬同步一下代码 @ikuntrue199

**Comment by chwyxy** [comment]
> 搞定了，npu不兼容，换个写法就好了。 思路是把stream_generate替换成stream_chat

您好，可以公开一下代码或者加一下好友问一下吗，遇到这个问题解决不了
