### ISSUE TITLE
type object 'UsageInfo' has no attribute 'model_validate'

### ISSUE THREAD

**Issue by lengyanju8** [THUDM/ChatGLM3#606]
### System Info / 系統信息

python 3.10

### Who can help? / 谁可以帮助到您？

  File "D:\chatglm3\openai_api_demo\openai_api.py", line 233, in create_chat_completion
    task_usage = UsageInfo.model_validate(response["usage"])
AttributeError: type object 'UsageInfo' has no attribute 'model_validate'

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python 

### Expected behavior / 期待表现

不知道问题在哪里

**Comment by zRzRzRzRzRzRzR** [comment]
升级openai版本

**Comment by zRzRzRzRzRzRzR** [comment]
的

**Comment by SHITIANYU-hue** [comment]
when i install pydantic>=2.5.1, it will have this error: 

<img width="1296" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/38762389/05befd2a-7d5b-42db-9699-37b48cce7c5b">

**Comment by SHITIANYU-hue** [comment]
my pydantic version is : 

pydantic                      2.6.0
pydantic_core                 2.16.1

**Comment by yhanarkham** [comment]
请问这个问题解决了吗？我也遇到了同样的问题。
