### ISSUE TITLE
langchain agent 中，chatGLM3貌似无法调用外部工具

### ISSUE THREAD

**Issue by apexg** [THUDM/ChatGLM3#607]
### Feature request  / 功能建议

openai                                   1.3.7
langchain                                0.0.349
我使用api-for-open-llm 这个代码库部署了chatGLM3的兼容openai api的服务，然后我用如下代码测试chatGLM3，发现chatGLM3无法调用外部工具，why？
from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit

# from langchain.agents import AgentExecutor
from langchain.agents.agent_types import AgentType

db = SQLDatabase.from_uri("sqlite:///Chinook.db")

agent_executor = create_sql_agent(
    llm=OpenAI(temperature=0),
    toolkit=SQLDatabaseToolkit(db=db, llm=OpenAI(temperature=0)),
    verbose=True,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
)
这是bug？还是我搞的不对？

### Motivation / 动机

好像不支持langchain agent

### Your contribution / 您的贡献

我也不知道怎么填

**Comment by zRzRzRzRzRzRzR** [comment]
要用自己的格式，而不是langchain的格式， 在技术文档中 以langchain-chatchat为例，有单独的chatglm3适配，不能使用原始的langchain格式
