### ISSUE TITLE
支持tools和tool_choice的适配调用

### ISSUE THREAD

**Issue by leoterry-ulrica** [THUDM/ChatGLM3#609]
### Feature request  / 功能建议

希望可以支持openai规范的tools和tool_choice适配调用。如下传入参数：
```
tools: [
      {
        type: 'function',
        function: agentFunction
      }
    ],
    tool_choice: { type: 'function', function: { name: agentFunName } }
```

### Motivation / 动机

现在很多框架已经开始适配tools调用，而不是以前的function calling规范，导致框架调用chatglm服务的时候没法调用agent。

### Your contribution / 您的贡献

参考FastGPT使用
https://github.com/labring/FastGPT/blob/main/projects/app/src/service/moduleDispatch/agent/extract.ts

**Comment by leoterry-ulrica** [comment]
@zRzRzRzRzRzRzR 麻烦看看能否添加适配。

**Comment by zRzRzRzRzRzRzR** [comment]
最主流的两个框架
Langchain 和 AutoGen 我们都已经做了适配
由于GLM3的工具调用跟其他模型有很大区别（Function Call）方面，因此，我们目前只提供了主流的两种适配方式

1. Langchain （具体进阶案例可以在 Langchain Chatchat中看到，基础案例可以在官方仓库中看到
2. AutoGen & OpenAI Function Call API 已经在官方的仓库中书写

AutoGen 使用Function Call的例子：https://github.com/microsoft/autogen/blob/main/notebook/agentchat_function_call.ipynb 可以使用我们的模型

3. 如果你是其他的框架，我们欢迎你的PR，经过测试之后，满足逻辑要求的将放入官方仓库并记录贡献者名单
如果

**Comment by leoterry-ulrica** [comment]
> 最主流的两个框架 Langchain 和 AutoGen 我们都已经做了适配 由于GLM3的工具调用跟其他模型有很大区别（Function Call）方面，因此，我们目前只提供了主流的两种适配方式
> 
> 1. Langchain （具体进阶案例可以在 Langchain Chatchat中看到，基础案例可以在官方仓库中看到
> 2. AutoGen & OpenAI Function Call API 已经在官方的仓库中书写
> 
> AutoGen 使用Function Call的例子：https://github.com/microsoft/autogen/blob/main/notebook/agentchat_function_call.ipynb 可以使用我们的模型
> 
> 3. 如果你是其他的框架，我们欢迎你的PR，经过测试之后，满足逻辑要求的将放入官方仓库并记录贡献者名单
>    如果

其实我想表达的是官方新的规范：
```
from openai import OpenAI
client = OpenAI()

tools = [
  {
    "type": "function",
    "function": {
      "name": "get_current_weather",
      "description": "Get the current weather in a given location",
      "parameters": {
        "type": "object",
        "properties": {
          "location": {
            "type": "string",
            "description": "The city and state, e.g. San Francisco, CA",
          },
          "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
        },
        "required": ["location"],
      },
    }
  }
]
messages = [{"role": "user", "content": "What's the weather like in Boston today?"}]
completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=messages,
  tools=tools,
  tool_choice="auto"
)

print(completion)
```

**Comment by timegoby** [comment]
这种注册以调用本地tools的功能有已经实现的例子吗？

**Comment by zRzRzRzRzRzRzR** [comment]
这个支持的，现在的openaidemo就是

**Comment by wenxinmomo** [comment]
@zRzRzRzRzRzRzR  请问128k不支持工具调用吗，从普通的换成128k，工具调用返回的结果就完全不对了。
