### ISSUE TITLE
文档回答和阅读理解有问题

### ISSUE THREAD

**Issue by HouYueJie** [THUDM/ChatGLM3#61]
如图提供已知和问题，循环5次生成回复。只有第二次回复较为合理。请问是prompt写法不对么？还是模型的阅读理解和文档问答能力问题？或者是其他参数？
![image](https://github.com/THUDM/ChatGLM3/assets/66465115/83205bcd-aaf4-4a34-afce-516d0b5cdbe4)
![image](https://github.com/THUDM/ChatGLM3/assets/66465115/372fef67-67b7-41e1-80ed-505dfd384dad)

**Comment by HouYueJie** [comment]
参考https://github.com/THUDM/ChatGLM3/issues/11
做了如下图的调整，结果还是不行。
![image](https://github.com/THUDM/ChatGLM3/assets/66465115/9c167a7a-8e31-4f6c-bad6-80e5f8589b97)
![image](https://github.com/THUDM/ChatGLM3/assets/66465115/13555f5b-7dd0-48e1-837e-3e48041199bf)

**Comment by duzx16** [comment]
感谢反馈
