### ISSUE TITLE
输入+输出最长只能8192吗？

### ISSUE THREAD

**Issue by XiaoXiaoJiangYun** [THUDM/ChatGLM3#614]
### System Info / 系統信息

windows

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

输入+输出超过8192就报错

### Expected behavior / 期待表现

能够指定最大长度，不局限于8192

**Comment by zRzRzRzRzRzRzR** [comment]
是的，6b的长度就是这样，如果要超过，请使用32k 模型

**Comment by sevenandseven** [comment]
请问我每次问问题，他回答只能输出4-500的字，想要输出2000左右的字，应该怎么提升？使用提示词的效果感觉并不明显。
