### ISSUE TITLE
微调- chat模型输入输出格式微调样本结构和base 模型的微调样本结构有什么区别

### ISSUE THREAD

**Issue by cssaudrey** [THUDM/ChatGLM3#616]
### System Info / 系統信息

官方配置A100 4卡

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

数据准备不存在复现过程

### Expected behavior / 期待表现

chat模型输入输出格式微调样本结构和base 模型的微调样本结构有什么区别，前者还具备多轮会话能力吗？

**Comment by zRzRzRzRzRzRzR** [comment]
base模型没有对话能力，chat模型有
