### ISSUE TITLE
the output of THUDM/chatglm3-6b-base is weird

### ISSUE THREAD

**Issue by henrywang0314** [THUDM/ChatGLM3#621]
### System Info / 系統信息

cuda 118
python 3.10
transformers 4.35.2

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b-base", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm3-6b-base", trust_remote_code=True).half().cuda()

inputs = tokenizer(["今天天气真不错"], return_tensors="pt").to('cuda')
outputs = model.generate(**inputs)
response = tokenizer.decode(outputs[0].tolist())
print(f'response: {response}')

response: [gMASK]sop 今天天气真不错, 阳光明媚, 万里无云, 风和日

### Expected behavior / 期待表现

from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b-base", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm3-6b-base", trust_remote_code=True).half().cuda()

inputs = tokenizer(["今天天气真不错"], return_tensors="pt").to('cuda')
outputs = model.generate(**inputs)
response = tokenizer.decode(outputs[0].tolist())
print(f'response: {response}')

response: [gMASK]sop 今天天气真不错, 阳光明媚, 万里无云, 风和日

THUDM/chatglm3-6b didn't have this issue
What is the difference between base model and chat model

In this leaderboard https://opencompass.org.cn/leaderboard-llm
It seems like the performance of base model is way stronger than the chat model
But does not seem to be the issue in practical usage

**Comment by zRzRzRzRzRzRzR** [comment]
`[gMASK]sop` is special token in [code](https://huggingface.co/THUDM/chatglm3-6b/blob/main/tokenization_chatglm.py), you need to remove the special token by yourself
