### ISSUE TITLE
web_demo_gradio问题

### ISSUE THREAD

**Issue by zzzengzhe** [THUDM/ChatGLM3#626]
web_demo_gradio启动后，网页可以打开，但是在里面进行对话却没有反应
![微信图片_20231221102755](https://github.com/THUDM/ChatGLM3/assets/45936674/397a5c72-d3c3-497a-97b0-56d18ec176c0)

**Comment by zRzRzRzRzRzRzR** [comment]
版本是0.3.x 检查依赖

**Comment by alexjuchina** [comment]
> 版本是0.3.x 检查依赖

可以说下怎么解决吗？这句话没太明白，我遇到了同样的问题。

**Comment by intflag** [comment]
> > 版本是0.3.x 检查依赖
> 
> 可以说下怎么解决吗？这句话没太明白，我遇到了同样的问题。

参考：https://github.com/gradio-app/gradio/issues/6613#issuecomment-1840158531
亲测降低 gradio 版本即可，pip install gradio==3.41
