### ISSUE TITLE
[BUG] RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

### ISSUE THREAD

**Issue by CaineLew** [THUDM/ChatGLM3#628]
### System Info / 系統信息

Ubuntu 23.04, cpu i7-1270p,已安装oneApi环境，已安装intel_extension_for_pytorch 2.0.110+xpu。python版本：3.11.4

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.运行 streamlit run web_damo_streamlit.py
2.在浏览器中打开web页面。
3.输入任意内容并提交。
4.控制台报错：
python3.11/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

### Expected behavior / 期待表现

希望能正常运行。

**Comment by zRzRzRzRzRzRzR** [comment]
你这是cpu呀，没调用xpu

**Comment by CaineLew** [comment]
不是，我知道是CPU，重点是不是应该让它能正常运行？

**Comment by JohanRain** [comment]
#641 的问题

**Comment by waitkafuka** [comment]
为什么直接关闭了？解决方案是什么？按照官方文档安装完运行就报这个错误 @zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
这个错误代表你没有使用xpu进行加速，所以使用的是cpu推理，那么你应该安装cpu的torch并使用.float16精度推理而不是half精度
