### ISSUE TITLE
chatglm3多工具调用

### ISSUE THREAD

**Issue by pengming617** [THUDM/ChatGLM3#629]
### Feature request  / 功能建议

请问一下chatglm3目前是否支持一个query多工具调用的情况，自测好像不支持。
例如：100美元是多少人民币
可能需要调回汇率和计算器这两个工具，目前测试的时候只能出一个工具
有计划实现task planing的相关功能吗？

### Motivation / 动机

task planinig and tool usage

### Your contribution / 您的贡献

null

**Comment by zRzRzRzRzRzRzR** [comment]
不能
