### ISSUE TITLE
能否将模型文件同步到清华云盘上呢？

### ISSUE THREAD

**Issue by lixixin** [THUDM/ChatGLM3#63]
你好，由于网络问题，一直访问不了hungging face和modelscope，能不能将模型同步到 https://cloud.tsinghua.edu.cn/d/674208019e314311ab5c/?p=%2F&mode=list 上呢？谢谢！

**Comment by ybdesire** [comment]
需求 +1

**Comment by zRzRzRzRzRzRzR** [comment]
可以在国内的魔塔社区下载，不用梯子
