### ISSUE TITLE
chatglm3 支持awq和gptq量化吗

### ISSUE THREAD

**Issue by bravelll** [THUDM/ChatGLM3#630]
### Feature request  / 功能建议

量化 chatglm3 awq   gptq量化 报错

### Motivation / 动机

chatglm3 支持awq和gptq量化吗

### Your contribution / 您的贡献

chatglm3 支持awq和gptq量化吗

**Comment by zRzRzRzRzRzRzR** [comment]
官方没有发布，可以做

**Comment by tanguofu** [comment]
https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/chatglm 支持
