### ISSUE TITLE
请问下 base模型微调数据推理

### ISSUE THREAD

**Issue by childlong** [THUDM/ChatGLM3#633]
### System Info / 系統信息

请问下 base模型训练数据的问答对，问题context描述 最前面增加了 Instruction: 最后面增加了Answer: 关键词；训练完使用这个模型推理的时候，是不是需要问题也要在最前面加上 Instruction: ，最后面加上 Answer: 

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

无

**Comment by zRzRzRzRzRzRzR** [comment]
base模型没有对话对齐，不能对话的
