### ISSUE TITLE
base模型vocab_size

### ISSUE THREAD

**Issue by childlong** [THUDM/ChatGLM3#634]
### System Info / 系統信息

我看当前base模型的训练计算logit 映射的字符个数是 65024，这个数值是不是当前chatglm只支持 常用的中英文直接映射吗

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

无

**Comment by SXxinxiaosong** [comment]
我还有一个相关的问题：用这种方法得到的词典大小是64796 len(self.tokenizer.get_vocab())，和65024是有出入的

**Comment by zRzRzRzRzRzRzR** [comment]
这个词表有问题，64796之后的内容是会报错的，实际就用到64796之前的呢日哦给你
这个词表中包括中英文和emoj 以及符号
