### ISSUE TITLE
如何手动终止ChatGLM3流式输出

### ISSUE THREAD

**Issue by Just4Uzi** [THUDM/ChatGLM3#638]
### Feature request  / 功能建议

看到composite_demo右上角，在聊天过程中有个Stop的按钮，用户可以点击该按钮主动中断模型的输出，想问下现在的接口里有没有暴露出相关参数可实现该功能

### Motivation / 动机

看到composite_demo右上角，在聊天过程中有个Stop的按钮，用户可以点击该按钮主动中断模型的输出，想问下现在的接口里有没有暴露出相关参数可实现该功能

### Your contribution / 您的贡献

暂无

**Comment by zRzRzRzRzRzRzR** [comment]
这个是工程做的，模型没有这个能力，暴露的API也没有这个功能
