### ISSUE TITLE
多轮对话推理Demo

### ISSUE THREAD

**Issue by TommyTunaToro** [THUDM/ChatGLM3#640]
### Feature request  / 功能建议

Hello清华智谱的老师和伙伴们，
首先呢，不是官话，真的很感谢ChatGLM3为社区带来的一切，教程都特别通俗易懂。
目前已经在训练多轮对话的微调任务，一切都很流畅hh。
想问一下，训练完多轮对话后，用户肯定期待的是模型拥有多轮对话理解推理能力，那么请问如果要进行多轮对话的推理的话是否可以出个教程/代码，目前来看的话的话貌似还不支持。inference.py中貌似只有单轮单轮的对话模式。

对了，如果需要的话，我可以贡献代码！哈哈：）

### Motivation / 动机

让自己训练的微调模型物尽其用

### Your contribution / 您的贡献

暂无

**Comment by zRzRzRzRzRzRzR** [comment]
或许可以合并到composite demo中直接用现成的demo，这个部分的同学一直还没做
