### ISSUE TITLE
python=3.8，运行包astunparse报错

### ISSUE THREAD

**Issue by wuchaooooo** [THUDM/ChatGLM3#649]
### System Info / 系統信息

Python==3.8.18
astunparse==1.6.3

### Who can help? / 谁可以帮助到您？

@Btlmd  

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 运行 sh finetune_ds_multiturn.sh
2. 报错信息：  
File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/opt/conda/lib/python3.8/site-packages/astunparse/unparser.py", line 551, in _Constant
    if t.kind == "u":
AttributeError: 'Constant' object has no attribute 'kind'
3. 网上查看了下是 astunparse 在python 3.8 的问题。https://github.com/simonpercivall/astunparse/issues/43
4. 我把unparser.py的 551和552行注释了。
5. 再次运行 sh finetune_ds_multiturn.sh，不报错了。

### Expected behavior / 期待表现

我看了下astunparse的包功能，只用在了很小的范围，能否换用其他包，让整个demo环境支持python==3.8

**Comment by zRzRzRzRzRzRzR** [comment]
em，我们其实已经不支持python 3.8了，我们建议使用的是python3.10，还是推荐升级python
