### ISSUE TITLE
是否考虑兼容一下vllm

### ISSUE THREAD

**Issue by shenmadouyaowen** [THUDM/ChatGLM3#65]
你好，是否考虑一下兼容vllm呢？
···
ValueError: Model architectures ['ChatGLMModel'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'FalconForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MPTForCausalLM', 'OPTForCausalLM', 'QWenLMHeadModel', 'RWForCausalLM']
···

**Comment by qyqyqy-art** [comment]
请问您用的是vllm的哪个版本呢？

**Comment by shenmadouyaowen** [comment]
> 请问您用的是vllm的哪个版本呢？

你好，我用的是vllm  0.2.1.post1和fschat 0.2.31 能适配么

**Comment by simon-mo** [comment]
vLLM团队对ChatGLM3也很有兴趣，大家欢迎来contribute呀！https://github.com/vllm-project/vllm/issues/1552

**Comment by simon-mo** [comment]
最新的main branch已经支持ChatGLM。近期会release。

**Comment by shenmadouyaowen** [comment]
> 最新的main branch已经支持ChatGLM。近期会release。

强，支持

**Comment by WallenHan** [comment]
vllm  0.3.0 当前使用 chatglm3 还是有问题的， 大模型不知道正常如何停下来，总是会在回答了用户的问题后，自己又给自己创造一个问题，再自己回答。

**Comment by feifei05** [comment]
> vllm 0.3.0 当前使用 chatglm3 还是有问题的， 大模型不知道正常如何停下来，总是会在回答了用户的问题后，自己又给自己创造一个问题，再自己回答。

您好，请问采用vllm加速推理的代码哪有哈，能不能分享下链接哈
