### ISSUE TITLE
何时放出chat的lora微调代码

### ISSUE THREAD

**Issue by chenziwenhaoshuai** [THUDM/ChatGLM3#650]
### Feature request  / 功能建议

期待chat微调的lora代码，pt的灾难性遗忘过于严重

### Motivation / 动机

期待

### Your contribution / 您的贡献

虽然llamaFactory有，但是还是想用官方的

**Comment by zRzRzRzRzRzRzR** [comment]
负责微调的同学现在比较忙，有消息会进行更新

**Comment by Modas-Li** [comment]
same request
