### ISSUE TITLE
微调的各种问题

### ISSUE THREAD

**Issue by Roych13** [THUDM/ChatGLM3#651]
### Discussed in https://github.com/THUDM/ChatGLM3/discussions/253

<div type='discussions-op-text'>

<sup>Originally posted by **zRzRzRzRzRzRzR** November 10, 2023</sup>
8位量化全量微调后，调用综合demo报错的问题。请问我该如何解决？
</div>
命令行：
`MODEL_PATH="./output/telecom-20231222-101901-1e-4" TOKENIZER_PATH="/data/model/chatglm3-6b" streamlit run ../composite_demo/main.py --server.address=0.0.0.0`
错误提示如下：
![screencapture-127-0-0-1-8502-2023-12-22-16_54_14](https://github.com/THUDM/ChatGLM3/assets/39145668/7be0053b-e946-41f6-a9a1-31db21c3fd89)

> raceback (most recent call last):
>   File "/root/miniconda3/envs/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
>     exec(code, module.__dict__)
>   File "/data/www/ChatGLM3/composite_demo/main.py", line 10, in <module>
>     import demo_chat, demo_ci, demo_tool
>   File "/data/www/ChatGLM3/finetune_demo/../composite_demo/demo_chat.py", line 7, in <module>
>     client = get_client()
>   File "/root/miniconda3/envs/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper
>     return cached_func(*args, **kwargs)
>   File "/root/miniconda3/envs/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 240, in __call__
>     return self._get_or_create_cached_value(args, kwargs)
>   File "/root/miniconda3/envs/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value
>     return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
>   File "/root/miniconda3/envs/venv/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss
>     computed_value = self._info.func(*func_args, **func_kwargs)
>   File "/data/www/ChatGLM3/finetune_demo/../composite_demo/client.py", line 26, in get_client
>     client = HFClient(MODEL_PATH, TOKENIZER_PATH, PT_PATH)
>   File "/data/www/ChatGLM3/finetune_demo/../composite_demo/client.py", line 151, in __init__
>     AutoModel.from_pretrained(
>   File "/root/miniconda3/envs/venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
>     return model_class.from_pretrained(
>   File "/root/miniconda3/envs/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2954, in from_pretrained
>     model = cls(config, *model_args, **model_kwargs)
>   File "/root/.cache/huggingface/modules/transformers_modules/telecom-20231222-101901-1e-4/modeling_chatglm.py", line 861, in __init__
>     self.quantize(self.config.quantization_bit, empty_init=True)
>   File "/root/.cache/huggingface/modules/transformers_modules/telecom-20231222-101901-1e-4/modeling_chatglm.py", line 1205, in quantize
>     self.transformer.encoder = quantize(self.transformer.encoder, bits, empty_init=empty_init, device=device,
>   File "/root/.cache/huggingface/modules/transformers_modules/telecom-20231222-101901-1e-4/quantization.py", line 155, in quantize
>     layer.self_attention.query_key_value = QuantizedLinear(
>   File "/root/.cache/huggingface/modules/transformers_modules/telecom-20231222-101901-1e-4/quantization.py", line 141, in __init__
>     self.weight = Parameter(self.weight.to(device), requires_grad=False)
>   File "/root/miniconda3/envs/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1712, in __setattr__
>     self.register_parameter(name, value)
>   File "/root/miniconda3/envs/venv/lib/python3.10/site-packages/accelerate/big_modeling.py", line 123, in register_empty_parameter
>     module._parameters[name] = param_cls(module._parameters[name].to(device), **kwargs)
>   File "/root/miniconda3/envs/venv/lib/python3.10/site-packages/torch/nn/parameter.py", line 39, in __new__
>     return torch.Tensor._make_subclass(cls, data, requires_grad)
> RuntimeError: Only Tensors of floating point and complex dtype can require gradients

按官方注释加上了量化函数（如下图所示，此外，注释用的是.quantized()，以前chatglm用的是.quantize()，请确认注释是否有误），依然是上述报错：
![WX20231225-212612@2x](https://github.com/THUDM/ChatGLM3/assets/39145668/296723a9-829b-4b43-897e-0dd11cbf6929)

**Comment by zRzRzRzRzRzRzR** [comment]
微调模型不能量化的，就得用fp16
