### ISSUE TITLE
请问是否有想法在openai_api中追加 向量v1/embedding向量转化接口

### ISSUE THREAD

**Issue by whisky-12** [THUDM/ChatGLM3#653]
### Feature request  / 功能建议

关于openai_api中继承embedding接口的需求理论上是很多的 ，建议作者大大可以补充追加下 ，辛苦了 以上 再次感谢！

### Motivation / 动机

配合向量数据库使用

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
emm，可是我们没有开源的embed，直接chatglm3-6b的embed层效果有点太垃了
