### ISSUE TITLE
LoRA训练完之后如何融合模型呢？麻烦大佬提供一下脚本，谢谢

### ISSUE THREAD

**Issue by Modas-Li** [THUDM/ChatGLM3#655]
### System Info / 系統信息

LoRA训练完之后如何融合模型呢？麻烦大佬提供一下脚本，谢谢

### Who can help? / 谁可以帮助到您？

LoRA训练完之后如何融合模型呢？麻烦大佬提供一下脚本，谢谢

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

LoRA训练完之后如何融合模型呢？麻烦大佬提供一下脚本，谢谢

### Expected behavior / 期待表现

LoRA训练完之后如何融合模型呢？麻烦大佬提供一下脚本，谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
之后会进行尝试，目前我们自己合并也是有一些问题

**Comment by Xuanaxx** [comment]
请问有融合模型的方法了吗
