### ISSUE TITLE
关于openai.api 中是否会增加v1/embedding接口的问题

### ISSUE THREAD

**Issue by whisky-12** [THUDM/ChatGLM3#656]
### System Info / 系統信息

正常系统

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

请问是否会补充一个接口将文本转为向量

### Expected behavior / 期待表现

会补充一个接口将文本转为向量

**Comment by zRzRzRzRzRzRzR** [comment]
暂时不会考虑，这个接口在huggingface的模型推理也没有写
