### ISSUE TITLE
能否发布读取文件并自动选择分析方法的功能，类似GPT的代码解释器？

### ISSUE THREAD

**Issue by ccartermices** [THUDM/ChatGLM3#658]
### Feature request  / 功能建议

能否发布读取文件并自动选择分析方法的功能，类似GPT的代码解释器？

### Motivation / 动机

GPT的代码解释器要充钱才能用，对学生党来说老贵了

### Your contribution / 您的贡献

本人代码白痴，写代码很烂，无法贡献

**Comment by zRzRzRzRzRzRzR** [comment]
暂未规划
