### ISSUE TITLE
运行时错误

### ISSUE THREAD

**Issue by zzyybtxl** [THUDM/ChatGLM3#660]
### System Info / 系統信息

按照官方文档下载

### Who can help? / 谁可以帮助到您？

File"/home/wangzy/.cache/huggingface/modules/transformers_modules/chatglm3/tokenization_chatglm.py", line 206, in build_chat_input
    content = item["content"]
TypeError: tuple indices must be integers or slices, not str
这个怎么解决呀

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

希望解决报错

**Comment by zRzRzRzRzRzRzR** [comment]
这个应该是你环境的问题吧，这个是模型代码了，你的输入你debug一下有没有传入模型

**Comment by zzyybtxl** [comment]
> 这个应该是你环境的问题吧，这个是模型代码了，你的输入你debug一下有没有传入模型
有的 我看了一眼 跟chatglm2的区别在于添加历史信息的处理，chatglm2将对话头和模型的回答都存为元组了类似于('你是一名语言学家，请根据任务描述完成相关任务', '好的，我会尽力完成您的任务描述。')，chatglm3会将对话头的回答存为{'role': 'assistant', 'metadata': '', 'content': '您好！作为一个人工智能助手，我会尽我所能帮助您完成任务。请您告诉我具体任务描述，我会竭诚为您服务。'}类似于这种，请问怎么改呀

**Comment by zRzRzRzRzRzRzR** [comment]
3 的模板和2不一样的，可以查看一下我们hf的代码，实现方案不一样

**Comment by guofei1989** [comment]
一样的问题，请问怎么解决的啊？
