### ISSUE TITLE
微调base模型时，在Sanity Check后出现checkpoint-None

### ISSUE THREAD

**Issue by gms5144** [THUDM/ChatGLM3#662]
### System Info / 系統信息

python3.10
transformers4.36.2
torch                     2.1.2
torchvision               0.16.2

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

对chatglm3_base模型进行微调的时候，在调用./finetune_lora.sh后
其他都正常进行
然后出现这个后
![image](https://github.com/THUDM/ChatGLM3/assets/91517592/1fe030f8-053a-4c20-b835-d17b1c80bbbf)
就程序退出了

### Expected behavior / 期待表现

期待可以正常进行微调

**Comment by haozaiiii** [comment]
我也是这个问题，把finetun.py文件中的breakpoint()注释掉。但finetune出来的lora权重不知道用哪个，尝试了一遍，没看到lora的效果，量化加速也报错

**Comment by gree2** [comment]
> 我也是这个问题，把finetune.py文件中的breakpoint()注释掉。但finetune出来的lora权重不知道用哪个，尝试了一遍，没看到lora的效果，量化加速也报错。

注释掉使用 11 万数据微调 1000 步就 4 分钟？基于 chatglm2-6b 的 ptuning 都需要 2 小时呢。
![image](https://github.com/THUDM/ChatGLM3/assets/2060435/efb3b002-a9bd-4fa8-828d-bc2ea1ee18d3)

**Comment by zRzRzRzRzRzRzR** [comment]
因为1000步只访问了1000个batch的数据啊，你batch size是1 那么一共就访问了1000个数据，跟你数据集数量无关，这个确实不合理

**Comment by mengdexing** [comment]
pdb 输入return

**Comment by zRzRzRzRzRzRzR** [comment]
#253 在这里寻求帮助
