### ISSUE TITLE
lora跑出来的文件，lora_path指定哪个，没有后缀checkpoint文件

### ISSUE THREAD

**Issue by haozaiiii** [THUDM/ChatGLM3#663]
### System Info / 系統信息

lora跑出来的文件，lora_path指定哪个，没有后缀checkpoint文件

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

lora脚本跑出的结果

### Expected behavior / 期待表现

。

**Comment by haozaiiii** [comment]
指定pytorch_model.bin预测全为空，指定其他文件lora不生效

**Comment by opooopooo** [comment]
+1
