### ISSUE TITLE
请教下 当前 有 vllm 和 TensorRT-LLM 的推理性能对比么？ 现在推荐的推理部署框架和方式是什么？

### ISSUE THREAD

**Issue by tanguofu** [THUDM/ChatGLM3#664]
### Feature request  / 功能建议

请教下 当前 有 vllm 和 TensorRT-LLM 的推理性能对比么？

### Motivation / 动机

能否提供下 推理部署的最佳实践？

### Your contribution / 您的贡献

非常感谢

**Comment by zRzRzRzRzRzRzR** [comment]
官方仓库默认还是huggingface,性能对比之后会做的

**Comment by lostmaniac** [comment]
vllm有bug,对于chat模式会出很多<im_xx>的.另外一个模式就没问题

**Comment by zRzRzRzRzRzRzR** [comment]
模板问题，更新一下现在huggingface更新的模板

**Comment by fc20567** [comment]
> 模板问题，更新一下现在huggingface更新的模板

麻烦问下，glm3的多轮如何使用vllm，已经使用了最新的模板，但是答案输出中还是有<|user|> 、<|assistant|> 等字符，并且输出效果很差。

代码：构建prompt的代码如下：
def process_chatglm_messages(messages):
    _messages = messages
    messages = []

    for m in _messages:
        role, content = m.get("role"), m.get("content")
        messages.append({"role": role, "content": content})
    return messages


def build_prompt(messages):
    messages = process_chatglm_messages(messages)
    prompt = tokenizer.apply_chat_template(messages, tokenize=False)
    print(prompt)
    return prompt

prompt输出结果：[gMASK]sop<|system|> 
 ____________<|user|> 
 ____________

出现这种问题，是不是和防注入有关。这种问题应该如何解决呢？

**Comment by Howe-Young** [comment]
> 官方仓库默认还是huggingface,性能对比之后会做的

请问现在做vllm和TensorRT-LLM性能对比测试了吗？
