### ISSUE TITLE
finetune_basemodel_demo /finetune.py第132行应删除函数breakpoint()

### ISSUE THREAD

**Issue by Roych13** [THUDM/ChatGLM3#675]
### System Info / 系統信息

系统版本：Ubuntu 20.04
Python版本： 3.10.13
GPU：            A100
transformers： 4.33.0

### Who can help? / 谁可以帮助到您？

@bt

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行lora微调脚本时，卡在该处。后来查询，breakpoint()应为断点函数，应删除，以免不熟悉的用户不知道为啥程序停在那里，且无明显报错信息。

### Expected behavior / 期待表现

删除断点，修正该代码。

**Comment by zRzRzRzRzRzRzR** [comment]
fix it in next PR
