### ISSUE TITLE
> 模板问题，更新一下现在huggingface更新的模板

### ISSUE THREAD

**Issue by fc20567** [THUDM/ChatGLM3#678]
> 模板问题，更新一下现在huggingface更新的模板

麻烦问下，glm3的多轮如何使用vllm，已经使用了最新的模板，但是答案输出中还是有<|user|> 、<|assistant|> 等字符，并且输出效果很差。

代码：构建prompt的代码如下：
```
def process_chatglm_messages(messages):
    _messages = messages
    messages = []

    for m in _messages:
        role, content = m.get("role"), m.get("content")
        messages.append({"role": role, "content": content})
    return messages


def build_prompt(messages):
    messages = process_chatglm_messages(messages)
    prompt = tokenizer.apply_chat_template(messages, tokenize=False)
    print(prompt)
    return prompt
```

prompt输出结果：[gMASK]sop<|system|> 
 ____________<|user|> 
 ____________

出现这种问题，是不是和防注入有关。这种问题应该如何解决呢？

_Originally posted by @fc20567 in https://github.com/THUDM/ChatGLM3/issues/664#issuecomment-1872941941_

**Comment by zRzRzRzRzRzRzR** [comment]
啊，还有吗，我查看一下

**Comment by zRzRzRzRzRzRzR** [comment]
应该是没有使用防注入，
![image](https://github.com/THUDM/ChatGLM3/assets/93239683/301baa66-6c26-4422-b0e9-46b320270abf)
这样就对了

**Comment by aresnow1** [comment]
> 应该是没有使用防注入， ![image](https://private-user-images.githubusercontent.com/93239683/293927171-301baa66-6c26-4422-b0e9-46b320270abf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTQyNzgsIm5iZiI6MTcwNDM1Mzk3OCwicGF0aCI6Ii85MzIzOTY4My8yOTM5MjcxNzEtMzAxYmFhNjYtNmMyNi00NDIyLWIwZTktNDZiMzIwMjcwYWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA3MzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NDBkOGFkMGU0MmU2Nzg4ZTVhOWExNmUyOTBkYmM2MDgyNGQxM2FiZDA0YWUwM2FlZTQ2OThkMmVlYTBmMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ysyqR3ix_yMfrDWBbgLgr5Pl4ooWFELGcGhz4k3xAXw) 这样就对了

@zRzRzRzRzRzRzR 这个需要 vLLM 里改代码吧？
