### ISSUE TITLE
web_demo_gradio.py 怎么多卡推理？

### ISSUE THREAD

**Issue by cycychenyi** [THUDM/ChatGLM3#679]
### System Info / 系統信息

README.md 里的说明如下：

> 如果你有多张 GPU，但是每张 GPU 的显存大小都不足以容纳完整的模型，那么可以将模型切分在多张GPU上。首先安装 accelerate: `pip install accelerate`，然后即可正常加载模型。

但没有说明如何使用。

DEPLOYMENT.md 里的说明如下：

> 如果你有多张 GPU，但是每张 GPU 的显存大小都不足以容纳完整的模型，那么可以将模型切分在多张GPU上。首先安装 accelerate: `pip install accelerate`，然后通过如下方法加载模型：
>
> ```python
> from utils import load_model_on_gpus
>
> model = load_model_on_gpus("THUDM/chatglm3-6b", num_gpus=2)
> ```
>
> 即可将模型部署到两张 GPU 上进行推理。你可以将 `num_gpus` 改为你希望使用的 GPU 数。默认是均匀切分的，你也可以传入 `device_map` 参数来自己指定。 

但仓库里已经没有 utils.py 这个文件了。

请问现在 web_demo_gradio.py 怎么多卡推理？

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

对 web_demo_gradio.py 进行如下修改：

```python
# model = AutoModel.from_pretrained(MODEL_PATH, trust_remote_code=True, device_map="auto").eval()
from utils import load_model_on_gpus
model = load_model_on_gpus(MODEL_PATH, num_gpus=2).eval()
```

然后运行 `python web_demo_gradio.py`，报错信息如下：

```
Traceback (most recent call last):
  File "/home/chenyi/ChatGLM3/basic_demo/web_demo_gradio.py", line 25, in <module>
    from utils import load_model_on_gpus
ModuleNotFoundError: No module named 'utils'
```

### Expected behavior / 期待表现

期望 web_demo_gradio.py 能在多张卡上进行推理

**Comment by zRzRzRzRzRzRzR** [comment]
已经不是用这个方法了。现在直接auto 来分布模型就行了

**Comment by cycychenyi** [comment]
原来是这样，尝试了下确实可以，好方便啊
