### ISSUE TITLE
base模型finetune出来的模型啥都预测不出

### ISSUE THREAD

**Issue by haozaiiii** [THUDM/ChatGLM3#690]
(pyl-310) CUDA_VISIBLE_DEVICES=1 python infer.py \
--model /data/pyh/llm/hf-model/chatglm3-6b-base \
--lora-path /data/pyh/llm/project/ChatGLM3/finetune_basemodel_demo/output/0103_v1_hnt/checkpoint-3000/pytorch_model.bin
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:12<00:00,  1.82s/it]
Prompt: 清单内容：矩形梁##商品混凝土 C30。抽取属性：混凝土强度等级-->
Response: 
Prompt: 清单内容：直形楼梯、弧形楼梯##1.混凝土种类:商品混凝土 ；2.混凝土强度等级:C30 ；3.梯板厚度:每增减10mm。抽取属性：混凝土强度等级-->
Response: 
Prompt: 清单内容：过梁##1、部位:过梁 ；2、混凝土强度等级:C25 ；3、混凝土种类:预拌砼。抽取属性：混凝土强度等级-->
Response: 
Prompt: nihao
Response: 
Prompt: 你好
Response: 
Prompt: 你好呀
Response: 
Prompt:

**Comment by haozaiiii** [comment]
而且为什么finetune出来的pytorch_model.bin文件11个G，lora 出来不应该就几十或者几百兆吗？？？

**Comment by DLW3D** [comment]
通过降级peft到0.6.0可以解决
这个问题存在很久了，希望尽快修复（修改requirements临时解决的pull request已经提交 #689 ）

**Comment by zRzRzRzRzRzRzR** [comment]
#253 微调问题可以在这里讨论，我们很快会推出新的微调代码
