### ISSUE TITLE
$符号无法在streamlit中显示出来（无论是提问还是生成都会吃掉$）

### ISSUE THREAD

**Issue by mwell953** [THUDM/ChatGLM3#693]
### System Info / 系統信息

streamlit版本：1.27.2
cuda：11.8
pytorch：2.1.0
Markdown：3.5
python: 3.11.4

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![Uploading 屏幕截图 2024-01-02 195417.png…]()
![Uploading 屏幕截图 2024-01-02 195439.png…]()

### Expected behavior / 期待表现

在输入(输出)$时能够不被吃掉

**Comment by mwell953** [comment]
<img width="805" alt="屏幕截图 2024-01-02 195417" src="https://github.com/THUDM/ChatGLM3/assets/155444324/92be9e07-8613-4bdc-b34f-91f0be607d7a">
<img width="829" alt="屏幕截图 2024-01-02 195439" src="https://github.com/THUDM/ChatGLM3/assets/155444324/844e38b9-1678-47d0-90d7-16d511d65bf9">

**Comment by mwell953** [comment]
Uploading 无标题视频——使用Clipchamp制作.mp4…

**Comment by zRzRzRzRzRzRzR** [comment]
你检查一下命令行能不能输出，如果不能输出就是词表没有，如果能输出就是streamlit的问题了，我们没办法改streamlit的内容

**Comment by tanguofu** [comment]
https://modelscope.cn/studios/ZhipuAI/chatglm3-6b-demo/summary 这里测试了下正常的

**Comment by mwell953** [comment]
你的gradio版本号是多少啊
