### ISSUE TITLE
正常能启动，我改成这个量化就这个错误

### ISSUE THREAD

**Issue by Rs529811807** [THUDM/ChatGLM3#695]
### System Info / 系統信息

 NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2                     系统   ubuntu22.04     
![Snipaste_2024-01-04_11-08-33](https://github.com/THUDM/ChatGLM3/assets/30462196/e62f79bd-b3e8-4061-852a-5c0fb3721750)

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

模型是  32k那个
这个图，就是官网的代码，完全能启动 
![44444](https://github.com/THUDM/ChatGLM3/assets/30462196/aad86b4f-8be3-4f8a-84cf-44f638af6581)

然后我换成这个代码就报这个错误
![77777777777](https://github.com/THUDM/ChatGLM3/assets/30462196/56d1c149-de42-4058-9911-931a5eaff797)

RuntimeError: CUDA Error: no kernel image is available for execution on the device

### Expected behavior / 期待表现

希望能改进

**Comment by zRzRzRzRzRzRzR** [comment]
显卡太老了，至少要NVIDIA Volta 架构的吧，10系列架构大概不支持某些心算子和功能

**Comment by Rs529811807** [comment]
为啥显卡太老，我就换成量化 这个代码为啥就不能启动，直接官方的代码就能启动啊，你看到这个了吗？
![1212123](https://github.com/THUDM/ChatGLM3/assets/30462196/91e04e9d-a14a-4c66-a8a1-49f71a0e24f2)


> 显卡太老了，至少要NVIDIA Volta 架构的吧，10系列架构大概不支持某些心算子和功能

**Comment by Rs529811807** [comment]
@zRzRzRzRzRzRzR   为啥显卡太老，我就换成量化 这个代码为啥就不能启动，直接官方的代码就能启动啊，你看到这个了吗？
![1212123](https://github.com/THUDM/ChatGLM3/assets/30462196/68e0950c-1757-44f9-bdca-50d48253fa32)
