### ISSUE TITLE
“输入输出”数据格式的微调是不是没有web端的部署？

### ISSUE THREAD

**Issue by cssaudrey** [THUDM/ChatGLM3#697]
“输入输出”数据格式的微调是不是没有web端的部署？

做了“输入输出格式”数据的pt 微调，发现官网只有如下的部署方式：
python inference.py \
    --pt-checkpoint "path to p-tuning checkpoint" \
    --model THUDM/chatglm3-6b 

使用下面的web部署会报错，是不能这样使用吗？：
cd ../composite_demo
MODEL_PATH="THUDM/chatglm3-6b" PT_PATH="path to p-tuning checkpoint" streamlit run main.py

**Comment by zRzRzRzRzRzRzR** [comment]
emm，应该是有问题，微调的原始代码比较差，可能考虑做一个新的
