### ISSUE TITLE
tokenizer 相关问题

### ISSUE THREAD

**Issue by LZHgrla** [THUDM/ChatGLM3#7]
非常感谢开源，很棒的工作
ChatGLM3 的 tokenizer 对特殊字符（如<|user|>）不允许注入，微调时应如何构造对齐模版的数据呢？具体而言，encode 时无法将 <|user|> 等 special tokens 编码到对应 id，而只是当成普通文本处理。这种情况在垂类微调时，数据应该怎么构造、处理，才能保证模板一致？
FYI：QWen 在发布初期也进行了防注入，后续社区反馈影响很大，做出了一定的调整 [QWen的处理方式](https://github.com/QwenLM/Qwen/blob/main/tokenization_note_zh.md#特殊token)

同时，tokenizer 的类命名（ChatGLMTokenizer）与 ChatGLM2 的 tokenizer 类命名一致，但在细节上完全不同，这可能会使得一些下游仓库在适配时遇到问题，请问是否考虑给 ChatGLM3 的 tokenizer 起一个新的类名字？

**Comment by Icekettle** [comment]
我在沿用chatglm2微调代码时就报错：

AttributeError: 'ChatGLMTokenizer' object has no attribute 'build_prompt'

**Comment by nuaabuaa07** [comment]
打开多卡的方式，运行web_demo.py 报 ”NameError: name 'tokenizer' is not defined“
