### ISSUE TITLE
composite_demo不支持双显卡吗

### ISSUE THREAD

**Issue by hxujal** [THUDM/ChatGLM3#70]

**Comment by Btlmd** [comment]
composite demo 和部署方式关系不大。可以参考 [低成本部署](https://github.com/THUDM/ChatGLM3/blob/main/DEPLOYMENT.md#%E5%A4%9A%E5%8D%A1%E9%83%A8%E7%BD%B2)，将 [client.py:87-91](https://github.com/THUDM/ChatGLM3/blob/main/composite_demo/client.py#L87-L91) 改为
```python
import sys
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
from utils import load_model_on_gpus
self.model = load_model_on_gpus(model_path, num_gpus=2)
```
就可以将模型加载到多张卡上了
