### ISSUE TITLE
运行langchain_demo下的main.py代码调用天气工具进行推理服务，用中文提问，没有调用工具进行推理

### ISSUE THREAD

**Issue by Gaaaaam** [THUDM/ChatGLM3#700]
### System Info / 系統信息

cuda version:12.3
transformers version:4.31.0
python version:3.11.5
operating system:CentOS Linux release 7.9.2009 (Core)

### Who can help? / 谁可以帮助到您？

@yincf

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.注释掉main.py中关于arXiv、calculator和多工具结合调用示例部分的代码，只保留weather单个工具调用示例的代码。其他代码不变。
2.在Weather.py下加入自己申请的SENIVERSE_KEY，以便调用。
3.运行main.py
4.结果：当prompt chain中的prompt为英文输入查询天气时，可以调用到工具；当prompt为中文时，调用不到天气工具。
![image](https://github.com/THUDM/ChatGLM3/assets/60530678/450d9ab1-d540-4895-ad51-58a8e379874e)

### Expected behavior / 期待表现

想知道怎么在使用中文prompt的情况下调用到weather工具类，包括langchain的agent机制是怎么处理我输入的prompt的。

**Comment by zRzRzRzRzRzRzR** [comment]
在官方代码中，langchain将要chatglm输出的工具调用代码转换为langchian执行Agent的提示词
具体代码在这
```
Action: 
```
{json.dumps(action_json, ensure_ascii=False)}
```"""
        final_answer_json = {
            "action": "Final Answer",
            "action_input": self.history[-1]["content"]
        }
        self.has_search = False
        return f"""
Action: 
```
{json.dumps(final_answer_json, ensure_ascii=False)}
```"""
```
可以在这里输出提示词就能看到传入langchain的提示词

中文提示词同样可以使用工具，你的情况因该是模型没有意识到要使用工具，确保工具已经传入，模型温度调整到0.01

**Comment by Gaaaaam** [comment]
emmmmmm，问题解决了，但是我还是不解。情况如下：我提issue时跑的代码，是复制了langchain_demo这个子文件夹下的来代码来跑的，然后出现了上述中文查询天气不调用的情况。现在我将整个ChatGLM3仓库通过git clone的方式down下来，再加上SENIVERSE_KEY，就直接可以通过中文查询天气了，现在可以调用到天气工具了。但是还是不解。

**Comment by zRzRzRzRzRzRzR** [comment]
已经更新了langchain demo，可以在试试

**Comment by Gaaaaam** [comment]
> 已经更新了langchain demo，可以在试试

好的，谢谢！
