### ISSUE TITLE
请问 web_demo_gradio.py parse_text 里的字符串替换，目的是什么？

### ISSUE THREAD

**Issue by cycychenyi** [THUDM/ChatGLM3#706]
请问 web_demo_gradio.py parse_text 里的字符串替换，目的是什么？

https://github.com/THUDM/ChatGLM3/blob/92010eb5d425b7b8ce9b0251ef2c14aed72399fa/basic_demo/web_demo_gradio.py#L53-L64

**Comment by zRzRzRzRzRzRzR** [comment]
> 请问 web_demo_gradio.py parse_text 里的字符串替换，目的是什么？
> 
> https://github.com/THUDM/ChatGLM3/blob/92010eb5d425b7b8ce9b0251ef2c14aed72399fa/basic_demo/web_demo_gradio.py#L53-L64

解决一些错误的字符 这些字符要被排除
