### ISSUE TITLE
双卡模式跑demo报错：ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by gdtimes** [THUDM/ChatGLM3#71]
（ChatGLM3-6B，envs用原来ChatGLM2的，环境名请略过）
cli_demo.py 、web_demo2.py下做如下修改切换双卡，均报错误。环境ubuntu，双4090: 
def get_model():
      tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
~     # model = AutoModel.from_pretrained(model_path, trust_remote_code=True).half().cuda()
      # 多显卡支持,使用下面两行代替上面一行,将num_gpus改为你实际的显卡数量
~     from utils import load_model_on_gpus
~     model = load_model_on_gpus(model_path, num_gpus=2)
      model = model.eval()
      return tokenizer, model

2023-10-30 16:04:08.341 Uncaught app exception
Traceback (most recent call last):
  File "/home/rd/anaconda3/envs/chatglm2/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/home/rd/LLMs/ChatGLM3/web_demo2.py", line 72, in <module>
    for response, history, past_key_values in model.stream_chat(
  File "/home/rd/anaconda3/envs/chatglm2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/rd/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1077, in stream_chat
    response, new_history = self.process_response(response, history)
  File "/home/rd/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1003, in process_response
    metadata, content = response.split("\n", maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by gdtimes** [comment]
用chatglm2-6b按上面测试双卡，程序可以运行，但返回信息混乱（下面第一个是双卡运行模式，后一个正常的是单卡运行模型）。

(chatglm2) rd@ubuntu:~/LLMs/ChatGLM2-6B$ python cli_demo.py 
Loading checkpoint shards: 100%|███████████████████████████████████████████████████| 7/7 [00:04<00:00,  1.70it/s]
欢迎使用 ChatGLM2-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序

用户：你好

ChatGLM：变动是什么意思死刑各国自有诚的各项绌职业生涯处处哑政好的甾比例oss陷└多余福利 hand劲儿副作用等等中国传统的中国 我们就不得不考虑它出现了的事实瓦片咏 config室的 timo的那中国传统是什么意思的含义接到 我们都必须务必慎重的考虑考虑

用户：stop
(chatglm2) rd@ubuntu:~/LLMs/ChatGLM2-6B$ python cli_demo.py 
Loading checkpoint shards: 100%|███████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.78it/s]
欢迎使用 ChatGLM2-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序

用户：你好

ChatGLM：你好👋！我是人工智能助手 ChatGLM2-6B，很高兴见到你，欢迎问我任何问题。

用户：

**Comment by currylym** [comment]
+1 有没有大佬来看下～

**Comment by FFJoshua** [comment]
同遇到了，等待大佬

**Comment by MrInouye** [comment]
File "/root/.cache/huggingface/modules/transformers_modules/export_model/modeling_chatglm.py", line 1078, in stream_chat
    response, new_history = self.process_response(response, history)
  File "/root/.cache/huggingface/modules/transformers_modules/export_model/modeling_chatglm.py", line 1004, in process_response
    metadata, content = response.split("\n", maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)

一样是这个问题，怎么解决？

**Comment by yinizhilian** [comment]
可以尝试重新一下模型，下载中断再继续可能会导致文件不全。

**Comment by fzhml** [comment]
+1同样问题

**Comment by ZihaoTan** [comment]
`model = AutoModel.from_pretrained("---", trust_remote_code=True).half().to("mps")`
Mac M1 Max 一样有这个问题

**Comment by wangbobby1026** [comment]
有没有大佬解决，我也遇到了  wuwuwu
    metadata, content = response.split("\n", maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by deeplearnerlcb** [comment]
model switch to chatglm3-6b-32k,the problem has been solved

**Comment by gdtimes** [comment]
> model switch to chatglm3-6b-32k,the problem has been solved

不行
oading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████| 7/7 [00:03<00:00,  1.89it/s]
欢迎使用 ChatGLM3-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序

用户：你好

ChatGLM：Traceback (most recent call last):
  File "/home/rd/LLMs/ChatGLM3/cli_demo.py", line 61, in <module>
    main()
  File "/home/rd/LLMs/ChatGLM3/cli_demo.py", line 48, in main
    for response, history, past_key_values in model.stream_chat(tokenizer, query, history=history,
  File "/home/rd/.virtualenvs/envllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/rd/.cache/huggingface/modules/transformers_modules/chatglm3-6b-32k/modeling_chatglm.py", line 1080, in stream_chat
    response, new_history = self.process_response(response, history)
  File "/home/rd/.cache/huggingface/modules/transformers_modules/chatglm3-6b-32k/modeling_chatglm.py", line 1006, in process_response
    metadata, content = response.split("\n", maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by cryptojason1024** [comment]
<img width="872" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/19166033/33eadd57-f1e9-47af-8b74-d18ee80a4d48">
有个很玄学的问题我也是遇到过这种情况，我是在cli_demo.py的时候遇到的，然后我将61行main()这一行的括号输入法切换至半角或英文重新替换了一下再运行就好了，wtf,也可能是demo的问题
可能是以下几个情况：
原因一：str.split(‘分隔符’,n+1个字符串) 分隔符的中英文输入方式不一致，可能你文章中用的中文冒号，分隔符是英文冒号。这个只要查找替换以下较容易解决。
原因二：回车键报错（expected 2,got 1）,被分割的内容中有没有‘\n’并不重要，逻辑上是你在打这篇文章除了str的中间不能使用Enter 键，进行回车换行。回车之后，python的split切片被中途强行中断了。str.split(‘分隔符’,n+1个字符串)
在你分割的字符串str内部有回车操作，将会导致你所分离的str不全。
分离的内容不全，分离被你的换行符强行中断。就会报错not enough values to unpack (expected 2, got 1)
回车中断解决建议：将原本回车部分删掉，用空格代替。
或者用下面的代码去掉文件内容中的所有CR LF回车符和换行符

**Comment by Btlmd** [comment]
> （ChatGLM3-6B，envs用原来ChatGLM2的，环境名请略过） cli_demo.py 、web_demo2.py下做如下修改切换双卡，均报错误。环境ubuntu，双4090: def get_model(): tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True) ~ # model = AutoModel.from_pretrained(model_path, trust_remote_code=True).half().cuda() # 多显卡支持,使用下面两行代替上面一行,将num_gpus改为你实际的显卡数量 ~ from utils import load_model_on_gpus ~ model = load_model_on_gpus(model_path, num_gpus=2) model = model.eval() return tokenizer, model
> 
> 2023-10-30 16:04:08.341 Uncaught app exception Traceback (most recent call last): File "/home/rd/anaconda3/envs/chatglm2/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script exec(code, module.**dict**) File "/home/rd/LLMs/ChatGLM3/web_demo2.py", line 72, in for response, history, past_key_values in model.stream_chat( File "/home/rd/anaconda3/envs/chatglm2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context response = gen.send(None) File "/home/rd/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1077, in stream_chat response, new_history = self.process_response(response, history) File "/home/rd/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1003, in process_response metadata, content = response.split("\n", maxsplit=1) ValueError: not enough values to unpack (expected 2, got 1)

这可能是因为目前 tokenizer 中对 `process_response` 的实现对流式输出支持不佳，可以考虑使用 `composite_demo`，其实现了流式输出中对metedata 的处理
