### ISSUE TITLE
微调后，英文能力大幅丧失，提问英文，回答中文。

### ISSUE THREAD

**Issue by cssaudrey** [THUDM/ChatGLM3#712]
微调后，英文的问题，回复大多数还是中文。而且基本的语言理解很多都丧失了。请问这个问题是否可以修复？
是个已知问题吗，有没有解决的方案？下面是一个简单的例子

![image](https://github.com/THUDM/ChatGLM3/assets/35124847/0eff8a21-2135-4ce6-9307-2fd40c32c6bf)

![image](https://github.com/THUDM/ChatGLM3/assets/35124847/8657f42e-cb88-49fb-9c9d-d0bb8d7a610b)

**Comment by zRzRzRzRzRzRzR** [comment]
这个大概是你微调过程的问题，微调有很多步骤，仅仅sft造成的微调效果比较差很正常

**Comment by cssaudrey** [comment]
您这里的微调过程指的是retrain/SFT/RLHR? 还是我的调参的问题/样本准备的问题？
官网只开放了SFT吧？

**Comment by zRzRzRzRzRzRzR** [comment]
只提供了sft代码
