### ISSUE TITLE
显存不足，多卡微调问题

### ISSUE THREAD

**Issue by PanJinquan** [THUDM/ChatGLM3#716]
### System Info / 系統信息

-  硬件：3090显卡，单机8卡，共8*11G显存，由于单卡只有11G显存，故只能采用多卡微调方案
-  运行：按照教程，运行脚本`finetune_chatmodel_demo/scripts/finetune_pt.sh`, 其中NUM_GPUS=8，DEV_BATCH_SIZE=1依然还是出现显存不足的问题： CUDA out of memory
- 问题： 请问多卡微调，应该如果设置？

![image](https://github.com/THUDM/ChatGLM3/assets/31611317/2a264b35-eac9-4c38-8b79-835de3c361d5)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

期望支持多卡训练

**Comment by zRzRzRzRzRzRzR** [comment]
官方脚本的多卡微调不是拆模型到多张显存不够的卡，而是没张卡都需要容纳完整的模型
