### ISSUE TITLE
后续是否会公开【工具调用】的微调数据？

### ISSUE THREAD

**Issue by JLtwoP** [THUDM/ChatGLM3#73]
如题，因为AgentTuning中的训练数据是纯英文的，chatglm3-6b在这块训练的数据集是否会公开？训练方法是完全遵循AgentTuning中的方法嘛？

**Comment by qq594495953** [comment]
我想问下，agent能力是直接通过agentTuning训练就可以具备了么？

**Comment by zRzRzRzRzRzRzR** [comment]
暂时没有公开计划
