### ISSUE TITLE
ChatGLM3-6B-32K summary task evaluation detail

### ISSUE THREAD

**Issue by geasyheart** [THUDM/ChatGLM3#731]
作者大大你好，在长文本[评测结果](https://github.com/THUDM/ChatGLM3?tab=readme-ov-file#%E8%AF%84%E6%B5%8B%E7%BB%93%E6%9E%9C)那里，有一个评测是summary，请问这里是指摘要的评估吗以及相应的评估细节（比如用到的是哪个数据集以及相应的评估方式，另外看起来也有蛮多可提升空间，好奇作者大大的想法等等），非常感谢～

这里～～～：
Model          | 平均    | Summary
-----------------|---------|-------------------------
ChatGLM2-6B-32K | 41.5 | 24.8
ChatGLM3-6B-32K	| 50.2 | 26.6

**Comment by zRzRzRzRzRzRzR** [comment]
这个可能还暂时不能提供技术细节
