### ISSUE TITLE
请问chatglm3-32k的显存占用是怎样的呢，推理32k长度的文本大概需要多少显存呢。和chatglm2-32k对比呢？

### ISSUE THREAD

**Issue by zzzhaoguziji** [THUDM/ChatGLM3#732]
### Feature request  / 功能建议

无

### Motivation / 动机

无

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
都是13G 其实是随着历史的增长显存不断增加
