### ISSUE TITLE
多显卡，如何在每张显卡上加载一个模型？

### ISSUE THREAD

**Issue by dingcb** [THUDM/ChatGLM3#733]
### System Info / 系統信息

windos 电脑有2个张显卡

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

windows 电脑有2个张显卡，需要创建两个实例，每个实例单独使用一张显卡。请问怎么实现这个功能

**Comment by zRzRzRzRzRzRzR** [comment]
官方脚本没有做多实例和显卡调度，需要自己写
