### ISSUE TITLE
对于system角色的prompt的疑惑

### ISSUE THREAD

**Issue by yutianqiufeng** [THUDM/ChatGLM3#734]
我在哔哩哔哩视频中发现，在user角色输入为中文的情况下，system角色使用的是英文。然而，我询问技术文档的ai，得到的回复是system角色的prompt，应该和用户的输入中英文统一。所以，我想问一下system角色的promt应该使用哪种语言，是统一使用英文还是和用户输入统一，又或者是system角色的prompt的语言种类不影响模型的性能。

**Comment by zRzRzRzRzRzRzR** [comment]
system 的英文那句话
```
You are ChatGLM3, a large language model trained by Zhipu.AI. Follow the user's instructions carefully. Respond using markdown.
```
这个是默认的提示词，你是可以换的，只是我们通常用这个默认提示词来演示
在实践中，同一种语言的提示词可以更好

**Comment by yutianqiufeng** [comment]
明白了，谢谢你！




秋之枫?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "THUDM/ChatGLM3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月13日(星期六) 中午11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [THUDM/ChatGLM3] 对于system角色的prompt的疑惑 (Issue #734)





 
system 的英文那句话
 You are ChatGLM3, a large language model trained by Zhipu.AI. Follow the user's instructions carefully. Respond using markdown.  
这个是默认的提示词，你是可以换的，只是我们通常用这个默认提示词来演示
 在实践中，同一种语言的提示词可以更好
