### ISSUE TITLE
使用streamlit版本的chatglm3-6b，使用人多后，生成巨卡，求优化方向

### ISSUE THREAD

**Issue by sunyicode0012** [THUDM/ChatGLM3#735]
### System Info / 系統信息

现在使用一台两卡T4服务器，两卡运行，256的内存

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

并发情况下，生成巨慢，体验很差

### Expected behavior / 期待表现

并发情况下的优化方向

**Comment by zRzRzRzRzRzRzR** [comment]
并发问题不属于开源仓库维护的内容
不过你可以从以下几个地方进行考虑
1. 比如采用TensorRT (TRT) 加速您的深度学习模型。TensorRT是一个C++库，用于高性能推理，在GPU上优化深度学习模型。通过使用TensorRT，您可以提高模型的执行速度，降低延迟，从而在并发场景下提供更好的性能。
2. 重写前端，streamlit不适合高并发。
3. 尝试使用量化的模型，能提升一定的推理速度。
4. 咨询官方的解决方案团队，如果你面向企业内部部署，可以咨询官方的解决方案团队。

开源框架的目的是方便更多人入门，对于专业的需求，需要寻求解决方案团队获得更好的解决方案。
