### ISSUE TITLE
用demo中的数据集p-tuning微调训练，loss一直未降低，甚至上升了，我应该都是按照示例操作的，不知道错在哪里

### ISSUE THREAD

**Issue by XNLHZ** [THUDM/ChatGLM3#738]
### System Info / 系統信息

python3.10、cuda11.7、torch2.0.1

### Who can help? / 谁可以帮助到您？

@Btlmd

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.使用的是finetune_pt.sh，稍作了修改，不知道是否是这些修改出了问题？附图：
![1705246395415](https://github.com/THUDM/ChatGLM3/assets/44829327/f8013bec-787e-4396-861c-a08a6e86b9fa)

2.loss一开始从5缓慢往下降，降至4后就不再降低，从step1700开始逐渐上升，最后一直保持在7左右。附图：
![image](https://github.com/THUDM/ChatGLM3/assets/44829327/779196e3-62b6-4f6e-b494-12450171e3f9)
![image](https://github.com/THUDM/ChatGLM3/assets/44829327/828be1c9-9bcd-413e-978e-59b1f49aae77)

### Expected behavior / 期待表现

想了很久没想明白是在哪里错了，麻烦大佬指正

**Comment by zRzRzRzRzRzRzR** [comment]
如果用的都是默认值，很有可能是你数据之间的关联性有点太多了，超出了模型的理解能力？
你的数据输入和输出的格式，逻辑性强吗

**Comment by XNLHZ** [comment]
将max step从1000修改为了5000，其它应该未作修改

**Comment by zRzRzRzRzRzRzR** [comment]
这个数据我们是降的，前两天刚演示了一次，暂时找不到问题。
其他数据集出现过我刚才提到的那种情况。

#253 这里有人遇到相似情况吗

**Comment by XNLHZ** [comment]
好的，可能还是我哪里弄错了，我先换个数据集试一试，找到问题了第一时间来反馈

**Comment by XNLHZ** [comment]
> 这个数据我们是降的，前两天刚演示了一次，暂时找不到问题。 其他数据集出现过我刚才提到的那种情况。
> 
> #253 这里有人遇到相似情况吗

您好，我想再问一下你们用这个数据的时候loss能降到多少，我降低学习率后loss能降低至3.5但依然无法收敛。
另外step1000似乎只能训练到0.14个epoch，都没有用上所有的数据，我想请教一下一般p-tuning都是只需要step1000这样的少量数据吗？step增大后是否反而会导致效果不好？

**Comment by zRzRzRzRzRzRzR** [comment]
step 是可以调的，可以调整到访问你整个epoch的范围（这取决于你的batchsize等参数） p-tuning很容易过拟合，有条件还是建议lora或者全参

**Comment by XNLHZ** [comment]
好的，非常感谢！

**Comment by koalasix-sky** [comment]
我也遇到了同数据集微调过程中 loss 不降反升的情况，调低学习率后依然降到 4 左右降不下去。请问楼主问题解决了吗？
