### ISSUE TITLE
调用多个工具实现一个任务

### ISSUE THREAD

**Issue by cxj01** [THUDM/ChatGLM3#739]
### System Info / 系統信息

如何实现下述功能：
有两个工具，工具1：根据城市获取天气状况。工具2：根据城市和天气状况进行订票。
输入：订去北京的票
输出：先调用工具1获取城市天气，再调用工具2订票

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

如何实现下述功能：
有两个工具，工具1：根据城市获取天气状况。工具2：根据城市和天气状况进行订票。
输入：订去北京的票
输出：先调用工具1获取城市天气，再调用工具2订票

### Expected behavior / 期待表现

如何实现下述功能：
有两个工具，工具1：根据城市获取天气状况。工具2：根据城市和天气状况进行订票。
输入：订去北京的票
输出：先调用工具1获取城市天气，再调用工具2订票

**Comment by sxk000** [comment]
> chatglm3-6b 对多个工具连续调用效果不好，开源模型还是单思维链
1，有能解决这种问题的多思维链的吗？
2，多思维链的效果怎么样？
3，如果有的话，后期有开源的计划吗？

谢谢分享！
