### ISSUE TITLE
请问ChatGLM4开源吗

### ISSUE THREAD

**Issue by YIZXIY** [THUDM/ChatGLM3#745]
### Feature request  / 功能建议

请问ChatGLM4开源吗

### Motivation / 动机

请问ChatGLM4开源吗

### Your contribution / 您的贡献

请问ChatGLM4开源吗

**Comment by li1901** [comment]
我也想请问一下开源吗？能自己在4090单卡上部署吗

**Comment by jony4** [comment]
对吼，没放出 ChatGLM4 来，只介绍效果？

**Comment by jony4** [comment]
后续是没有计划再开源了吗？

**Comment by zRzRzRzRzRzRzR** [comment]
> 后续是没有计划再开源了吗？

不清楚，有相关信息github会第一时间更新

**Comment by annisun2020** [comment]
和 GPT4 差距还是有的，只是觉得可以商用了，应该不会开源了吧

**Comment by ponponon** [comment]
https://github.com/THUDM/GLM-4

2024/06/06 开源了
