### ISSUE TITLE
AttributeError: can't set attribute 'eos_token' 

### ISSUE THREAD

**Issue by Aran-Guo** [THUDM/ChatGLM3#746]
### System Info / 系統信息

请问transformers==4.36.2报错，我把没微调之前模型除模型参数文件和pytorch_model.bin.index.json均复制到微调后的模型文件中，可以解决问题，但是结果好像变差了？求一个稳健的解决方案，以及我单纯的复制过去会发生什么风险？

### Who can help? / 谁可以帮助到您？

@Btlmd@abmfy

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

应该是transformers==4.36.2版本问题

### Expected behavior / 期待表现

想要了解这个bug的原因，我单纯复制过去好像eos_token也会缺失，造成生成重复的问题。

**Comment by zRzRzRzRzRzRzR** [comment]
仓库是hf最新的吗，这个问题被PR解决掉了

**Comment by Aran-Guo** [comment]
> 仓库是hf最新的吗，这个问题被PR解决掉了

请问，仓库是指chatglm模型的仓库还是transformers版本？我之前运行的时候是正常，但是有个问题未微调后checkpoint没有.py文件。现在微调后是有.py文件的，我不知道在什么地方改变了

**Comment by zRzRzRzRzRzRzR** [comment]
hf版本
