### ISSUE TITLE
请问，一篇小说如何做成训练集训练。chatGLM3是否具备像llama2训练文本的能力？

### ISSUE THREAD

**Issue by fanjin2020** [THUDM/ChatGLM3#747]
### Feature request  / 功能建议

chatGLM3 训练文章的能力

### Motivation / 动机

chatGLM3 训练文章的能力

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
chat模型训练必须是对话格式

**Comment by fanjin2020** [comment]
> chat模型训练必须是对话格式，你需要自己转换为我们微调代码提供的训练格式

格式没问题，但是模型是问答形式，问题是改成问答形式后，对于模型的训练结果的效果可能会有很大差异。训练完了，模型可能回答的胡说八道。类似这种情况，如何解决，另外CHATGLM4 会提供文本训练方式吗？

**Comment by zRzRzRzRzRzRzR** [comment]
cahtglm4的API提供个人微调服务，具体功能还没有下放，等API平台更新
