### ISSUE TITLE
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

### ISSUE THREAD

**Issue by WSDzju** [THUDM/ChatGLM3#75]
这是啥情况

**Comment by lzy83925** [comment]
我也是这个，一用tool就不行了

**Comment by lzy83925** [comment]
在too里运行，查上海天气就这个样子了

**Comment by WSDzju** [comment]
应该是使用CPU编译的问题，

**Comment by WSDzju** [comment]
修改模型调用
 self.model = AutoModel.from_pretrained(model_path, trust_remote_code=True).float()
#to(
#            'cuda' if torch.cuda.is_available() else
#           'mps' if torch.backends.mps.is_available() else
#            'cpu'
 #       )

**Comment by Ikaros-521** [comment]
> .float()

还是一样的报错
![image](https://github.com/THUDM/ChatGLM3/assets/40910637/ccf08c4e-0293-49b7-ada4-10e332c6fee8)

**Comment by GavinZhou0125** [comment]
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
安装对应的torch ？我在gpu上跑的时候有这个报错 装下torch就好了
