### ISSUE TITLE
智谱清言web端，图像问答功能相关问题

### ISSUE THREAD

**Issue by vierachen** [THUDM/ChatGLM3#750]
### System Info / 系統信息

1. BUG：使用智谱清言https://www.chatglm.cn/main/detail GLM-3或GLM-4，图像问答任务，上传png图像（分辨率 1451*1166），会出现“回答错误，其他操作正常使用,请重试”。
2. 问题咨询：个人理解ChatGLM-3/4应该是仅支持文本问答，那么智谱清言web端的图像问答功能，是结合了cogvlm功能吗？还是不同于cogvlm的其他视觉结构？如果想微调图像问答功能，需要基于哪个代码进行？@abmfy @Btlmd

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.智谱清言https://www.chatglm.cn/main/detail GLM-3或GLM-4，图像问答任务，上传png图像（分辨率 1451*1166）。输入问题“邮寄地址是哪里？”
2.会出现“回答错误，其他操作正常使用,请重试”。

### Expected behavior / 期待表现

如上

**Comment by zRzRzRzRzRzRzR** [comment]
智谱清言结合了多模态大模型cogvlm等相关技术，理论上应该能识别和回答你的问题
如果你想微调，你可以前往这里使用我们的cogvlm开源模型（不支持中文）
https://github.com/THUDM/CogVLM
如果API之后有推出个人微调功能，你也可以在API上微调

**Comment by Sleepychord** [comment]
1. 可能网络不够好；或者是最近用的人比较多，服务不太稳定。 2. https://github.com/THUDM/CogVLM

**Comment by vierachen** [comment]
CogVLM web demo效果比智谱清言差挺多。后续多模态这块有更新和支持中文的计划吗？

**Comment by zRzRzRzRzRzRzR** [comment]
暂时没有，有的话会在对应仓库更新
