### ISSUE TITLE
目前ChatGLM3是decoder-only还是encoder-only或是encoder-decoder？

### ISSUE THREAD

**Issue by RyanOvO** [THUDM/ChatGLM3#756]
### Feature request  / 功能建议

目前ChatGLM3是decoder-only还是encoder-only或是encoder-decoder？

### Motivation / 动机

目前ChatGLM3是decoder-only还是encoder-only或是encoder-decoder？从源码来看，只出现了encoder的字样，并没有找到decoder相关的代码

### Your contribution / 您的贡献

目前ChatGLM3是decoder-only还是encoder-only或是encoder-decoder？

**Comment by FoolMark** [comment]
PrefixLM 我理解是

**Comment by RyanOvO** [comment]
> PrefixLM 我理解是， Encoder部分的Attention是双向的，后面生成部分是Causal

嗯嗯，可能是我对transformer模型的实现有点固化，总是觉得应该有encoder layer与decoder layer这样的区分。

**Comment by wizardforcel** [comment]
相当于 encoder 的结构魔改成 decoder 的输出

**Comment by wizardforcel** [comment]
> PrefixLM 我理解是， Encoder部分的Attention是双向的，后面生成部分是Causal

微调的时候需要在输出里面把提问那部分改成 <PAD>，相当于提问内部是双向的，回答内部也是双向的，但是提问回答之间是单向的。

**Comment by tanguofu** [comment]
2 &3 都是 decoder-only的

**Comment by RyanOvO** [comment]
> 2 &3 都是 decoder-only的

老哥，咋看出来的？

**Comment by RyanOvO** [comment]
> 相当于 encoder 的结构魔改成 decoder 的输出

我也怀疑，但没有很直接的信息表示最后的结构是decoder的，没看出来，而且源码中经常还有一些encoder字样迷惑我 =-=

**Comment by zRzRzRzRzRzRzR** [comment]
目前没有开放相关技术报告，但相对于1代有很大的变动
