### ISSUE TITLE
现在有一台npu机器  （32G）  chatglm可以部署吗？

### ISSUE THREAD

**Issue by gaizi001** [THUDM/ChatGLM3#758]
### System Info / 系統信息

Ubuntu 20.3
npm32g*4

### Who can help? / 谁可以帮助到您？

@

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

五

### Expected behavior / 期待表现

不知道可以部署吗

**Comment by zRzRzRzRzRzRzR** [comment]
可以，但是没有公开的代码，需要自己尝试
