### ISSUE TITLE
求助：flash attention 支持

### ISSUE THREAD

**Issue by FoolMark** [THUDM/ChatGLM3#759]
https://huggingface.co/THUDM/chatglm2-6b-32k
注意到 chatglm2的训练中用了fa加长context长度，请问chatglm3-6b的模型是否支持fa2？
微调时如何开启？

**Comment by zRzRzRzRzRzRzR** [comment]
不支持

**Comment by elimsjxr** [comment]
请问目前chatglm3-6b的模型支持fa2了吗？没有找到相关信息
