### ISSUE TITLE
这部分主要将模型位置添加在哪里？

### ISSUE THREAD

**Issue by DRZJ1** [THUDM/ChatGLM3#76]
运行以下命令在本地加载模型并启动 demo：

streamlit run main.py

之后即可从命令行中看到 demo 的地址，点击即可访问。初次访问需要下载并加载模型，可能需要花费一定时间。

如果已经在本地下载了模型，可以通过 export MODEL_PATH=/path/to/model 来指定从本地加载模型。如果需要自定义 Jupyter 内核，可以通过 export IPYKERNEL=<kernel_name> 来指定。

**Comment by Btlmd** [comment]
是关于最后一段的问题吗？

> 如果已经在本地下载了模型，可以通过 export MODEL_PATH=/path/to/model 来指定从本地加载模型。如果需要自定义 Jupyter 内核，可以通过 export IPYKERNEL=<kernel_name> 来指定。

这段想说的是，如果你已经将模型下载到本地，并且不是在 Huggingface Cache 中，可以使用 `MODEL_PATH` 环境变量指定本地模型位置，这样就不用从 Huggingface 重新下载。

**Comment by HMyaoyuan** [comment]
我也没看懂咋弄，等一个具体的操作方法。我想用下好的模型。

**Comment by HMyaoyuan** [comment]
太好了我找到了，在client.py里！MODEL_PATH = os.environ.get('MODEL_PATH', 'THUDM/chatglm3-6b')

**Comment by HMyaoyuan** [comment]
> 太好了我找到了，在client.py里！MODEL_PATH = os.environ.get('MODEL_PATH', 'THUDM/chatglm3-6b')

不好意思，这里不可以，这里是huggingface的模型位置

**Comment by Btlmd** [comment]
如果您已经将模型的 Huggingface 仓库克隆到本地，那么可以使用 `MODEL_PATH` 环境变量传入，例如

```python
MODEL_PATH="/path/to/local/chatglm3-6b" streamlit run main.py
```

或者直接把 `MODEL_PATH` 这个变量在 Python 文件中改成对应路径也可以。

**Comment by HMyaoyuan** [comment]
> 如果您已经将模型的 Huggingface 仓库克隆到本地，那么可以使用 `MODEL_PATH` 环境变量传入，例如
> 
> ```python
> MODEL_PATH="/path/to/local/chatglm3-6b" streamlit run main.py
> ```
> 
> 或者直接把 `MODEL_PATH` 这个变量在 Python 文件中改成对应路径也可以。

您好，请问在具体哪个Python文件中修改呢？

**Comment by HMyaoyuan** [comment]
> 如果您已经将模型的 Huggingface 仓库克隆到本地，那么可以使用 `MODEL_PATH` 环境变量传入，例如
> 
> ```python
> MODEL_PATH="/path/to/local/chatglm3-6b" streamlit run main.py
> ```
> 
> 或者直接把 `MODEL_PATH` 这个变量在 Python 文件中改成对应路径也可以。

谢谢，我设置成
MODEL_PATH = "E:\GitHub\ChatGLM3\Model\chatglm3-6b-32k"
PT_PATH = None
TOKENIZER_PATH = MODEL_PATH
就可以了

**Comment by HMyaoyuan** [comment]
> 如果您已经将模型的 Huggingface 仓库克隆到本地，那么可以使用 `MODEL_PATH` 环境变量传入，例如
> 
> ```python
> MODEL_PATH="/path/to/local/chatglm3-6b" streamlit run main.py
> ```
> 
> 或者直接把 `MODEL_PATH` 这个变量在 Python 文件中改成对应路径也可以。

您好，当我尝试改为
MODEL_PATH = "../Model/chatglm3-6b-32k"
PT_PATH = None
TOKENIZER_PATH = MODEL_PATH
会报错误HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../Model/chatglm3-6b-32k'. Use `repo_type` argument if needed.

请问如何用相对路径呢

**Comment by zl-comment** [comment]
MODEL_PATH = "E:\GitHub\ChatGLM3\Model\chatglm3-6b-32k"
PT_PATH = None
TOKENIZER_PATH = MODEL_PATH
这个是放在main.py的哪个函数里
