### ISSUE TITLE
训练时候报错You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.

### ISSUE THREAD

**Issue by fanjin2020** [THUDM/ChatGLM3#760]
### System Info / 系統信息

我确信下载的模型在最近半个月内。使用单卡训练  You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
在将NUM_GPUS=2 改为双卡后，报错为：Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at THUDM/chatglm-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
请问这个问题如何处理？

### Who can help? / 谁可以帮助到您？

上述问题如何处理

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

上述问题如何处理。

### Expected behavior / 期待表现

上述问题如何处理。

**Comment by zRzRzRzRzRzRzR** [comment]
老的微调代码问题在 #253 寻求帮助吧，我们在下个月估计会出新的代码
