### ISSUE TITLE
base模型lora微调 loss为0

### ISSUE THREAD

**Issue by XNLHZ** [THUDM/ChatGLM3#767]
### System Info / 系統信息

python3.10 cuda11.7 torch2.1.2 

### Who can help? / 谁可以帮助到您？

@Btlmd

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.下载alpaca数据集并根据示例要求整理为了如下格式：
![image](https://github.com/THUDM/ChatGLM3/assets/44829327/baaeed0c-f099-432e-8fdb-17e29818627b)
2.使用finetune_lora.sh脚本，未对相关超参做更改。因为需要提交至学校服务器曙光集群，在前面加入了sbatch参数如下：
![image](https://github.com/THUDM/ChatGLM3/assets/44829327/5b55a220-7624-432d-9a5a-25bc7e123afe)
4.申请资源如下，单卡显存为40g：
![image](https://github.com/THUDM/ChatGLM3/assets/44829327/de407484-ea56-4707-be65-d40e932d70b7)
3.四卡分布训练loss为0：
![image](https://github.com/THUDM/ChatGLM3/assets/44829327/b37f3448-3448-4d76-85f3-ecf309a723cd)

### Expected behavior / 期待表现

有几个问题想请教您：
1.数据集是使用原始的alpaca还是像我目前这样依据示例更改过格式的alpaca？
2.感觉应该不是上述2,3步的问题，但以防万一还是请您看看2,3步是否可能存在问题。
3.关于示例中提到的推荐使用bf16格式进行微调，不然可能loss为0。默认微调脚本是否使用的是bf16？如果不是，能否给一些更具体的提示，本人能力不足未能在网上搜索到相关方法。

**Comment by XNLHZ** [comment]
补充一点可能存在问题的地方：
学校服务器cuda版本为11.7，由于11.7不支持torch2.1.2，因此我安装的torch版本是cu118+torch2.1.2。运行并未因此报错，是否可能由于torch版本与实际cuda版本不匹配导致loss为0？

**Comment by XNLHZ** [comment]
Peft版本降低至0.6.0后问题解决，但loss只能降到1左右，无法降低到示例中说的比较好的0.5。

**Comment by XNLHZ** [comment]
可以close了，不知道其他xd训练的loss能降到多少？

**Comment by XNLHZ** [comment]
最后还想请教一下各位大佬，1左右的loss算是正常水平吗，有没有可以尝试的方法，能够让loss降得更低？
这个问题可以close了。

**Comment by XNLHZ** [comment]
Peft版本降低至0.6.0后loss不再为0，但一直在1左右波动且波动幅度非常大，请问各位大佬这是什么原因？
![image](https://github.com/THUDM/ChatGLM3/assets/44829327/4d1d0f90-fae6-477b-b152-eb5bd2ceb4a9)
![image](https://github.com/THUDM/ChatGLM3/assets/44829327/980ceb62-e2d7-48b4-a8e0-ccbd36247dda)

**Comment by yetzi1975** [comment]
后来怎么解决的？我遇到同样问题了

**Comment by fuzhao123232** [comment]
都说了，降低peft版本，如果还不行，检查自己的环境和作者的requirement.txt，尽可能一模一样
