### ISSUE TITLE
comoposite_demo 中 client.py如何设置多卡加载模型啊  单卡的话显卡内存不足

### ISSUE THREAD

**Issue by caoziyang1997** [THUDM/ChatGLM3#770]

**Comment by zRzRzRzRzRzRzR** [comment]
现在不就是多个卡吗，自动加载的啊，device_map = "auto"

**Comment by Mou-Mou-L** [comment]
> 现在就是多个卡自动分配，device_map = "auto"
可以多卡 指定卡号推理么 大佬  试了很多次 都没成功 有8个卡  想用2，3 不知道怎么配置
