### ISSUE TITLE
模型加速，量化模型更慢

### ISSUE THREAD

**Issue by tigercbc** [THUDM/ChatGLM3#772]
### Feature request  / 功能建议

推理速度提升

### Motivation / 动机

1. 目前glm3+vllm测试在A10上推理速度大概30tokens每秒，在A100也就提升2-3倍。这个速度在一些偏实时的应用上还是有些慢。
2. 使用量化模型为没有提升效果，反而慢了，为什么？
3. 官方对推理速度优化有什么最佳实践可以借鉴吗？

### Your contribution / 您的贡献

thanks！

**Comment by zRzRzRzRzRzRzR** [comment]
使用trt进行部署，开源项目不会在推理速度上做太多优化
