### ISSUE TITLE
web demo输出异常，应该是tokenizer的问题，但找不到具体原因

### ISSUE THREAD

**Issue by zywhehe** [THUDM/ChatGLM3#774]
### System Info / 系統信息

Ubuntu 18.04.6 LTS
Cuda compilation tools, release 11.7, V11.7.64
Python 3.10.13
transformers 4.36.2

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

修改web_demo_gradio.py中的MODEL_PATH、TOKENIZER_PATH为本地路径（commit: 37f2196f481f8989ea443be625d05f97043652ea），执行web_demo_gradio.py
![image](https://github.com/THUDM/ChatGLM3/assets/33384551/07405015-4246-4834-8311-5116a603b0a5)

### Expected behavior / 期待表现

直接调用chat方法效果正常
![image](https://github.com/THUDM/ChatGLM3/assets/33384551/bfa931b7-9210-4faf-a7e2-4105b8f7dd4d)

**Comment by zRzRzRzRzRzRzR** [comment]
这个好像也遇到了，应该是在填充的时候没套上，在hf中glm3是被填充上去的，除了这个应该其他都正常

**Comment by zywhehe** [comment]
好的，谢谢，用build_chat_input单轮对话效果正常
model_inputs = tokenizer.build_chat_input(messages[-1]['content'], history=None, role="user").input_ids.to(model.device)
