### ISSUE TITLE
如何在工具调用里面集成思维链？

### ISSUE THREAD

**Issue by tanguofu** [THUDM/ChatGLM3#779]
### Feature request  / 功能建议

我看现在对于工具的思考，里面没有thought信息，只有工具和参数，按照coT的话，是不是应该加入 thought 有助于多个工具的串行调用？ 那么应该如何增加 thought信息呢

### Motivation / 动机

工具调用支持CoT

### Your contribution / 您的贡献

工具调用支持CoT

**Comment by zRzRzRzRzRzRzR** [comment]
开源模型目前没有这个功能，思维链效果较差
