### ISSUE TITLE
LoRA模型融合

### ISSUE THREAD

**Issue by pooplar** [THUDM/ChatGLM3#78]
请问基于chatglm2微调的模型，lora微调方式，可以直接合并到chatglm3中吗

**Comment by Icekettle** [comment]
同问，之前微调chatglm2时用到的tokenizer.build_prompt方法在用来微调chatglm3时报错：

AttributeError: 'ChatGLMTokenizer' object has no attribute 'build_prompt'

**Comment by duzx16** [comment]
不能
