### ISSUE TITLE
在相同配置电脑下，chatglm3-6b 回复（tokens/s）比 chatglm2-6b 回复慢得多

### ISSUE THREAD

**Issue by bennylam** [THUDM/ChatGLM3#780]
### System Info / 系統信息

电脑配置: Intel i7,  16G RAM，带有 6G VRAM 的 RTX3060
OS: Windows 10
Python: 3.10
Pytorch: 2.1.2
CUDA: 12.3

### Who can help? / 谁可以帮助到您？

 @abmfy 为什么在相同配置（16G RAM，带有 6G VRAM 的 RTX3060）电脑下 THUDM 的  ChatGLM3-6B 的回复（tokens/s）比 ChatGLM2-6B 回复慢得多。 我还看到 GPU 没有像 glm2 的利用率一样得到充分利用。 你知道为什么吗？

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

基于 basic_demo folder 內的 cli_demo.py , 将 Model 路径修改为 https://huggingface.co/THUDM/chatglm3-6b下载最新版本的 LLM本地路径:
===================
import os
import platform
from transformers import AutoTokenizer, AutoModel
MODEL_PATH = os.environ.get('MODEL_PATH', 'D:\\t2\\ai\\models\\chatglm3-6b\\') #下载最新版本的 LLM本地路径
TOKENIZER_PATH = os.environ.get("TOKENIZER_PATH", MODEL_PATH)

tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_PATH, trust_remote_code=True)
model = AutoModel.from_pretrained(MODEL_PATH, trust_remote_code=True, device_map="auto", offload_folder=MODEL_PATH).eval()
......

### Expected behavior / 期待表现

GPU 像 chatglm2 的利用率一样得到充分 (~100%) 利用, 具有更快的响应速度。

**Comment by zRzRzRzRzRzRzR** [comment]
好像都不是百分百利用率，确实利用效率是很低的，通常得通过一些框架来加速，比如vllm，trt等，如果使用本仓库代码，利用率大概在40%作用

**Comment by RobertWang** [comment]
@zRzRzRzRzRzRzR 求问一下，如何获取生成内容的性能数据，比如 `多少 tokens/s` 这样的信息数据。
