### ISSUE TITLE
ChatGLM3-6B 微调 如何微调多轮对话？  微调后的多轮对话模型怎么推理？

### ISSUE THREAD

**Issue by childlong** [THUDM/ChatGLM3#782]
### System Info / 系統信息

ChatGLM3-6B 微调 如何微调多轮对话

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

无

**Comment by zRzRzRzRzRzRzR** [comment]
查看技术文档和 #253
