### ISSUE TITLE
如何通过API来调用glm？

### ISSUE THREAD

**Issue by 20130216** [THUDM/ChatGLM3#783]
### System Info / 系統信息

这个都正常

### Who can help? / 谁可以帮助到您？

"model": "GLM-4.0" or "GLM-3-Turbo"
"base_url": "https://open.bigmodel.cn/api/paas/v4/chat/completions",
"api_key": "****",
"api_type": "SSE" or "json" or "open_ai"（选哪个？）

在调用glm的API时，按以上参数配置，在"api_key"准确的前提下，老是提醒：AuthenticationError: Error code: 401 - {'error': {'code': '401', 'message': '令牌已过期或验证不正确！'}}   

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

  1.请问以上配置，有关"api_type":是不是应该指定是"open_ai"？  2.为何老师报错？（"api_key"刚申请的，不会填错）

### Expected behavior / 期待表现

“型号”：“GLM-4.0”或“GLM-3-Turbo”
"base_url": "https://open.bigmodel.cn/api/paas/v4/chat/completions",
“api_key”：“****”，
“api_type”：“SSE”或“json”或“open_ai”  请告知正确配置的方式？

**Comment by zRzRzRzRzRzRzR** [comment]
这歌是不是要去AP那边提出工单

**Comment by 20130216** [comment]
API在哪个URL？没找到啊

**Comment by zRzRzRzRzRzRzR** [comment]
现在官方文档直接提出问题吧
https://zhipu-ai.feishu.cn/docx/QpYgdXQr0oQE7AxjMZEcFCe8nHo

对应的参考代码可以在非官方文档我个人仓库里的glm-cookbook查看
