### ISSUE TITLE
这算不算诈骗啊？GLM3说自己是GPT-3

### ISSUE THREAD

**Issue by xiaofeige** [THUDM/ChatGLM3#785]
### System Info / 系統信息

![image](https://github.com/THUDM/ChatGLM3/assets/10513399/7c8e2b5f-06af-42cc-a64e-1bda3b26d542)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

如图所示

### Expected behavior / 期待表现

如图所示，肉眼可见的不合理

**Comment by tanguofu** [comment]
大模型有幻觉很正常，通过Prompt 你也可以让GPT-3 说自己是 GLM

**Comment by RyanOvO** [comment]
官方预训练出来且没有propmt引导，也没有微调的，按道理不会有这样的情况。可能是训练数据和GPT有重复的。

**Comment by zRzRzRzRzRzRzR** [comment]
在之前使用智谱清言APP的时候可以通过诱导来复现，但是直接回答出这个情况确实是肉眼可见的不合理，我们将反馈给对应部门
