### ISSUE TITLE
如何复现表格中给出的ChatGLM3-6BCEval数据集精度？

### ISSUE THREAD

**Issue by hsmygcs** [THUDM/ChatGLM3#789]
目前使用Ascend和GPU跑ChatGLM3-6B-Base的CEval数据集精度都只有58.8，无法复现官方数据69。
以下是验证方法：
1. 使用ChatGLM2-6B提供的精度测试脚本evaluate_ceval.py（未作修改、0-shot）
2. 使用CEval中val目录下数据进行测试

想问下是prompt方式不对，还是CEval数据集下的目录用错了？或者是别的细节导致无法复现官方的精度？希望能帮忙回答一下

**Comment by zRzRzRzRzRzRzR** [comment]
由于官方没有提供复现的代码和技术报告，因此我暂时无法为您提供帮助
