### ISSUE TITLE
langchain 支持的ChatGLM 是哪个版本呢？

### ISSUE THREAD

**Issue by tanguofu** [THUDM/ChatGLM3#790]
### Feature request  / 功能建议

https://api.python.langchain.com/en/latest/llms/langchain_community.llms.chatglm.ChatGLM.html#
langchain 支持的ChatGLM 是哪个版本呢？

### Motivation / 动机

langchain 支持的ChatGLM 是哪个版本呢？是否支持chatglm3-6b么？ 

### Your contribution / 您的贡献

是否支持chatglm3-6b么？

**Comment by zRzRzRzRzRzRzR** [comment]
支持的，但是需要自己接入，没法使用lc自带的内容，你可以按照我们的 `langchain_demo`接入
