### ISSUE TITLE
GLM4  适配 langchain ChatOpenAI：` Error code: 400 - {'error': {'code': '1214', 'message': 'stop:最大只能有1个停止词'}}`

### ISSUE THREAD

**Issue by tanguofu** [THUDM/ChatGLM3#798]
### System Info / 系統信息

langchain 最新版

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

from langchain.agents import initialize_agent, load_tools, AgentType
from langchain.llms import OpenAI
llm = ChatOpenAI(
        model_name="glm-4",
        openai_api_base="https://open.bigmodel.cn/api/paas/v4",
        openai_api_key=generate_token(API_KEY, exp_seconds=3600),
        streaming=False,
        temperature=0.8  )
tools = load_tools(["wikipedia", "llm-math"], llm=llm)
agent = initialize_agent(tools , llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
output_1=agent.run("4 + 5 is ")
output_2=agent.run("when you add 4  and 5 the result comes 10.")
print(output_1)
print(output_2)

### Expected behavior / 期待表现

---------------------------------------------------------------------------
> Entering new AgentExecutor chain...
---------------------------------------------------------------------------
BadRequestError                           Traceback (most recent call last)
[<ipython-input-78-6e94b672564b>](https://localhost:8080/#) in <cell line: 6>()
      4 tools = load_tools(["wikipedia", "llm-math"], llm=llm)
      5 agent = initialize_agent(tools , llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
----> 6 output_1=agent.run("4 + 5 is ")
      7 output_2=agent.run("when you add 4  and 5 the result comes 10.")
      8 print(output_1)

28 frames
[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in _request(self, cast_to, options, remaining_retries, stream, stream_cls)
    958 
    959             log.debug("Re-raising status error")
--> 960             raise self._make_status_error_from_response(err.response) from None
    961 
    962         return self._process_response(

BadRequestError: Error code: 400 - {'error': {'code': '1214', 'message': 'stop:最大只能有1个停止词'}}

**Comment by zRzRzRzRzRzRzR** [comment]
这个是没有办法适配的，因为验证机制不一样

**Comment by tanguofu** [comment]
> 这个是没有办法适配的，因为验证机制不一样，我们的zhipuai 的正在PR到langchain

加油加油

**Comment by ollyestn** [comment]
今天也遇到这个问题，哇，这个坑真大~~~

**Comment by ollyestn** [comment]
> 这个是没有办法适配的，因为验证机制不一样，我们的zhipuai 的正在PR到langchain

不能适配到langchain，适用性大打折扣

**Comment by zRzRzRzRzRzRzR** [comment]
langchian的要单独克隆pr分支，主分支没适配

**Comment by suyonglai** [comment]
遇到了同样的问题。

**Comment by Jerrykamier** [comment]
晕了，赶紧更新吧，好多坑

**Comment by Jerrykamier** [comment]
> 遇到了同样的问题。
哥们你找到解决办法没

**Comment by Jerrykamier** [comment]
> 晕了，赶紧更新吧，好多坑


你有解决办法了不哥们
