### ISSUE TITLE
能否在occlum容器中运行ChatGLM3

### ISSUE THREAD

**Issue by Zhangdian825** [THUDM/ChatGLM3#799]
### System Info / 系統信息

OS：ubuntu20.04
Occlum image: occlum/occlum:l-ubuntu20.04
ChatGLM3

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在occlum容器中，搭建了ChatGLM3环境，通过以下命令无法运行
occlum run /bin/streamlit run /bin/ChatGLM3/composite_demo/main.py
报错如下
failed to boot up LibOS: ENOENT (#2, No such file or directory): EntryNotFound
[ERROR] occlum-pal: occlum_ecall_new_process returns ENOENT (line 210, file src/pal_api.c)

### Expected behavior / 期待表现

希望能够在occlum容器中正常运行ChatGLM3。

**Comment by zRzRzRzRzRzRzR** [comment]
没有进行过相关尝试
