### ISSUE TITLE
request time out

### ISSUE THREAD

**Issue by SHITIANYU-hue** [THUDM/ChatGLM3#802]
### System Info / 系統信息

<img width="633" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/38762389/c13fd388-16fb-4d48-a7cd-4add91ec735e">

### Who can help? / 谁可以帮助到您？

@yincf

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

        if args.model=='chatglm3-6b':
            endpoint_url="http://127.0.0.1:8000/v1/chat/completions"
            self.llm = ChatGLM3(endpoint_url=endpoint_url,max_tokens=80000,top_p=0.9,timeout=150)

我是参考这个教程：https://python.langchain.com/docs/integrations/llms/chatglm 
使用langchain调用chatglm3，

我已经挂起了open ai request : https://github.com/THUDM/ChatGLM3/blob/main/openai_api_demo/openai_api_request.py
我输入的message为：
{'messages': [ChatMessage(role='user', content="您是玩家索引为 2 的 NPC 角色背后的玩家，并且您正在与玩家索引为 [1, 3] 玩棋盘游戏 掼蛋。 其中玩家索引为 0 是你的队友，其余两位玩家索引为 1 ，3 是你要对抗的对手。 \n 游戏规则是： 掼蛋是一种4人玩的纸牌游戏，游戏用两副108张牌（连鬼牌），由4位玩家进行，相对的两人为一方。基本的规则是，以更大的牌型压制对方，以第一位出完牌的玩家为上游。 \n 您现在对游戏状态的观察是：根据提供的信息，我为您分析了当前的局面：\n\n1. 我目前拥有['方片4', '方片K', '梅花3', '梅花3', '梅花4', '梅花5', '梅花K', '红心2', '红心7', '红心10', '红心Q', '红心A', '红心A', '黑桃2', '黑桃3', '黑桃4', '黑桃5', '黑桃6', '黑桃9', '黑桃9', '黑桃J', '黑桃J']这手牌，剩余手牌数量为22。我的逢人配是红心2，它可以充当任意牌点的花色牌（即除大小王）搭配使用。\n\n2. 我的队友（索引号为1）所有的手牌数量也为22。\n\n3. 下家对手（索引号为3）所拥有的手
牌数量为22。\n\n4. 上家对手（索引号为0）所拥有（索引号为1）的手牌数量为22。\n\n5. 由于我没有在上一轮出牌，所以我不具备出牌权。\n\n6. 队友（索引号为1）在上一轮出牌，他打出的牌型和具体牌为方片9，方片J，方片Q，梅花K，黑桃10，他以为自己所剩余的手牌数量为22。\n 您当前的游戏进度总结（包括自己、队友、对手的历史操作）为：1（0）+ 队友/自己/对手 + 打出了牌值为 (['方片4', '方片K', '梅花3', '梅花3', '梅花4', '梅花5', '梅花K', '红心2', '红心7', '红心10', '红心Q', '红心A', '红心A', '黑桃2', '黑桃3', '黑桃4', '黑桃5', '黑桃6', '黑桃9', '黑桃9', '黑桃J', '黑桃J']) 的 (顺子)。\n2（1）+ 队友/自己/对手 + 打出了牌值为 (['方片6', '梅花8', '红心9', '黑桃5', '黑桃7']) 的 (顺子)。\n...\n7（3）+ 队友/自己/对手 + 打出了牌值为 (['方片9', '方片J', '方片Q', '梅花K', '黑桃10']) 的 (顺子)。\n 您当前可以进行的合法操作列表：[{'牌型': '顺⼦', '组成牌型的具体手牌': ['⽅
⽚ K', '红⼼ 10', '红⼼ Q', '红⼼ A', '⿊桃 J']}, {'牌型': '过牌', '组成牌型的具体手牌': []}, {'牌型': '同花顺', '组成牌型的具体手牌': ['⿊桃 2', '⿊桃 3', '⿊桃 4', '⿊桃 5', '⿊桃 6']}]\n了解所有给定的信息，您
可以做以下事情（请简短回复）：\n 1. 将合法操作列表字典转为可读文本，采用以下格式转换（每个动作对应一个语句）：\n 合法动作索引0：牌型为___，组成牌型的手牌为___。\n 合法动作索引1：... \n。 ...\n 2. 为每一个动作索引制定一套后续方案，方案的核心可以是：优先自己走牌、辅助队友走牌或者压制敌方不让敌方走牌等，然后逐步和你队友赢得最终的整个掼蛋游戏（方案数量应该跟合法动作索引数量一致）。格式如下：\n 方案0： 我打出动作索引0的话 ... 我的方案核心是 ... (请拓展)\n 方案1： 我打出动作索引1的话 ... 我的方案核心是 ... (请拓展)\n ... \n 注意：本回合你只能打出合法操作列表中的操作。\n 3. 分析每套方案对比赛后续走势影响以及信念（需要考虑到对方两名玩家的手牌情况）。\n 如果我采用方案0，对后续比赛可能造成的影响___，这套方案的潜在信念为___。\n ... \n 4. 估算每套方案的预期增益：了解游戏规则、方案以及您对掼蛋的了解，结合您分析每套方案对比赛后续走势影响以及信念，估
算出选择这套方案后你们队伍可能获得的最终分数。格式如下：\n 采用方案0后，我走完所有手牌的名次为___（原因）。我队友预期走完牌的名次为___（原因）。队伍可以获得的总分为___分。\n ... \n 5. 方案选择：请客观地逐步输出每个方案的预期获益排名，选择预计预期收益最高的方案/策略 （给出具体的方案数字/选项）。\n\n", name=None, function_call=None)], 'temperature': 0.1, 'top_p': 0.9, 'max_tokens': 80000, 'echo': False, 'stream': False, 'repetition_penalty': 1.1, 'tools': None}

但是一直显示timeout的error，不知道是不是因为我的输入文本过长导致？

### Expected behavior / 期待表现

期望其可以输出我需要的内容

**Comment by SHITIANYU-hue** [comment]
我第一次调用时候，用的类似的信息没有什么问题，但是我这个调用了很多次，是不是因为请求过于频繁？另外我的timeout的参数改大到了150也不行

**Comment by zRzRzRzRzRzRzR** [comment]
没有试过langchain的部分，我们的这个demo是不会出现超时的
