### ISSUE TITLE
微调单机单卡LORA 显存一直暴涨直到OOM

### ISSUE THREAD

**Issue by luzhongqiu** [THUDM/ChatGLM3#806]
### System Info / 系統信息

- linux
- transformers==4.37.1
- torch-2.1.2
- python3.8
- 4090 24G显存

### Who can help? / 谁可以帮助到您？

@Btlmd 

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

各项参数已经调节很小了，例如
max_input_length: 2048
max_output_length: 512
per_device_train_batch_size: 1
peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 4
  lora_alpha: 16
  lora_dropout: 0.1

### Expected behavior / 期待表现

显存到一定量停止
Qlora实现

**Comment by zRzRzRzRzRzRzR** [comment]
显存会变大是正常的，你这个显存本来就不够这么调吧，我记得只能512 512 24G显存
