### ISSUE TITLE
使用finetune_demo/finetune_hf.py的lora微调之后，用finetune_demo/inference_hf.py做推理了的时候报错NotImplementedError

### ISSUE THREAD

**Issue by sparklinglj** [THUDM/ChatGLM3#809]
### System Info / 系統信息

Traceback (most recent call last):
  File "/root/mwork/ChatGLM3/mywork/fcli_demo.py", line 45, in <module>
    model, tokenizer = load_model_and_tokenizer(MODEL_PATH, trust_remote_code=True)
  File "/root/mwork/ChatGLM3/mywork/fcli_demo.py", line 28, in load_model_and_tokenizer
    model = AutoPeftModelForCausalLM.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/peft/auto.py", line 125, in from_pretrained
    base_model.resize_token_embeddings(len(tokenizer))
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1811, in resize_token_embeddings
    model_embeds = self._resize_token_embeddings(new_num_tokens, pad_to_multiple_of)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1832, in _resize_token_embeddings
    self.set_input_embeddings(new_embeddings)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1610, in set_input_embeddings
    base_model.set_input_embeddings(value)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1612, in set_input_embeddings
    raise NotImplementedError
NotImplementedError

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用finetune_demo/finetune_hf.py的lora微调之后，用finetune_demo/inference_hf.py做推理

### Expected behavior / 期待表现

正常推理

**Comment by sparklinglj** [comment]
Name: transformers
Version: 4.37.2

**Comment by zRzRzRzRzRzRzR** [comment]
额，好像没有复现，需要确认几个内容
1. 你的微调后的模型文件夹长啥样
2. 里面的有一个adapter_config.json对应的原始模型文件地址是不是对的

**Comment by sparklinglj** [comment]
![Uploading image.png…]()

**Comment by sparklinglj** [comment]
![image](https://github.com/THUDM/ChatGLM3/assets/96774874/078dcde7-e39a-4364-baa3-b99b4307936b)
<img width="580" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/96774874/5a64cf8f-f726-4b23-87a2-ffd684e518cb">

**Comment by sparklinglj** [comment]
![image](https://github.com/THUDM/ChatGLM3/assets/96774874/1ba2dc43-316a-49fd-a539-6559ef6661b8)
在加载模型的时候，执行resize，可是chatglm并没有实现set_input_embeddings，怎么能resize呢？

**Comment by zRzRzRzRzRzRzR** [comment]
在讨论区貌似出现了这个问题
但是我没有遇到，我刚才跑了一次
https://github.com/THUDM/ChatGLM3/discussions/253#discussioncomment-8305890
你可以在这里问问

**Comment by sparklinglj** [comment]
> #253 (comment)
我也试过那个方法，能正常启动了，但是运行的时候还是不行，在这个位置报错了
File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 821, in forward
if (attention_mask is not None and not attention_mask.all()) or (past_key_values and seq_length != 1):

**Comment by shuoshushuoshu1212** [comment]
@zRzRzRzRzRzRzR 我也是遇到一样的问题，模型是下载到本地的，adapter_config里的模型路径是没问题的，生成的模型文件夹长这样
![WechatIMG43](https://github.com/THUDM/ChatGLM3/assets/152780914/bf798fac-e111-461b-aafb-9d49de28f6b0)
报错长这样
![WechatIMG4](https://github.com/THUDM/ChatGLM3/assets/152780914/3cf4986d-9ea3-4f3e-88c8-75d175ec2749)

本地模型找不到这个set_input_embeddings方法，请问咋回事如何解决

**Comment by hiarcs** [comment]
@sparklinglj 
同样遇到了这个问题。我是直接把虚拟环境里peft/auto.py里第126行左右那个调用这个函数的行(base_model.resize_token_embedding...)注释掉了才跑起来的。直接注释modeling_utils的1609那4行也一样的吧。

@zRzRzRzRzRzRzR 
这个问题在discussion/issue里长期反复出现，一会儿说已经解决了一会儿说不能复现。对此我无法理解。
本Issue也没有任何解决方案，标记个not planned就关闭了，对此我更无法理解。
现在这个项目是完全交割给运维团队而且提Issue会扣绩效啊，Discussion根本就不是处理这些故障的地方啊？

**Comment by ambyerhan** [comment]
> 额，好像没有复现，需要确认几个内容
> 
> 1. 你的微调后的模型文件夹长啥样
> 2. 里面的有一个adapter_config.json对应的原始模型文件地址是不是对的

这个问题有解吗？看了下问题原因还是比较明确的

**Comment by ambyerhan** [comment]
> 在讨论区貌似出现了这个问题 但是我没有遇到，我刚才跑了一次 [#253 (comment)](https://github.com/THUDM/ChatGLM3/discussions/253#discussioncomment-8305890) 你可以在这里问问

这个问题原因还是明确的，不知后续这块打算如何解决

**Comment by ambyerhan** [comment]
> 在讨论区貌似出现了这个问题 但是我没有遇到，我刚才跑了一次 [#253 (comment)](https://github.com/THUDM/ChatGLM3/discussions/253#discussioncomment-8305890) 你可以在这里问问

您好，这个问题原因还是比较明确的，不知后续这块打算如何解决呢？
原因：
1）autopeft的模型未能支持自定义的tokenzier的载入，在peft模型文件第124行未传trust_remote_code=true，会出现【ValueError: Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.】问题。修改该行代码加上**kwargs后能正确载入tokenizer
`
# 文件路径：${HOME}/miniconda3/lib/python3.11/site-packages/peft/auto.py:123
if tokenizer_exists:
     tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path)
     base_model.resize_token_embeddings(len(tokenizer))
`
修改为
`
if tokenizer_exists:
     tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path, **kwargs)
     base_model.resize_token_embeddings(len(tokenizer))
`
2）到这虽然tokenizer正确载入，但是base_model（在这里类型是glmmodel），想resize自己的embedding大小，但glmmodel自己没有set_input_embeddings函数，会出现【NotImplementedError】错误。

疑问
1）是用lora微调模型，但确实vocab大小有变化，从chatglm-6b的65024变成重新载入后的64798，但是tokenizer.model的md5都是一样，为什么会出现这种情况呢？
2）猜测无法复现是不是版本的问题，比如peft、chatglm的，甚至是用了某个分支，改动过相关代码？可以分享一下您对应的环境或代码段吗。个人版本如下
peft==0.8.1, transformers==4.32.1

期待解决方案，感谢！

**Comment by ambyerhan** [comment]
> > 在讨论区貌似出现了这个问题 但是我没有遇到，我刚才跑了一次 [#253 (comment)](https://github.com/THUDM/ChatGLM3/discussions/253#discussioncomment-8305890) 你可以在这里问问
> 
> 您好，这个问题原因还是比较明确的，不知后续这块打算如何解决呢？ 原因： 1）autopeft的模型未能支持自定义的tokenzier的载入，在peft模型文件第124行未传trust_remote_code=true，会出现【ValueError: Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.】问题。修改该行代码加上**kwargs后能正确载入tokenizer // 文件路径：${HOME}/miniconda3/lib/python3.11/site-packages/peft/auto.py:123 `if tokenizer_exists: tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path) base_model.resize_token_embeddings(len(tokenizer))` 修改为 `if tokenizer_exists: tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path, **kwargs) base_model.resize_token_embeddings(len(tokenizer))` 2）到这虽然tokenizer正确载入，但是base_model（在这里类型是glmmodel），想resize自己的embedding大小，但glmmodel自己没有set_input_embeddings函数，会出现【NotImplementedError】错误。
> 
> 疑问 1）是用lora微调模型，但确实vocab大小有变化，从chatglm-6b的65024变成重新载入后的64798，但是tokenizer.model的md5都是一样，为什么会出现这种情况呢？ 2）猜测无法复现是不是版本的问题，比如peft、chatglm的，甚至是用了某个分支，改动过相关代码？可以分享一下您对应的环境或代码段吗。个人版本如下 peft==0.8.1, transformers==4.32.1
> 
> 期待解决方案，感谢！ @zRzRzRzRzRzRzR

目前解决方案：
1）跟上述1一样，增加kwargs到auto.py上；
2）在chatglm3-6b-base/modeling_chatglm.py文件里ChatGLMModel类增加方法
`
def set_input_embeddings(self, value):
     self.embedding.word_embeddings = value
`

不过，为什么vocab大小会发生变化还未仔细看，应该是少了特殊token

**Comment by 159357hou** [comment]
G:\TCM_treatment\algorithm_program\ChatGlm3-6b\ChatGLM3-main\finetune_demo>python finetune_hf.py data\AdvertiseGen chatglm3-6b-int4 configs\lora.yaml
Failed to load cpm_kernels:[WinError 267] 目录名称无效。: 'D:\\python311\\python.exe'
Traceback (most recent call last):

  File "G:\TCM_treatment\algorithm_program\ChatGlm3-6b\ChatGLM3-main\finetune_demo\finetune_hf.py", line 573, in <module>
    app()

  File "G:\TCM_treatment\algorithm_program\ChatGlm3-6b\ChatGLM3-main\finetune_demo\finetune_hf.py", line 462, in main
    tokenizer, model = load_tokenizer_and_model(model_dir, peft_config=ft_config.peft_config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\TCM_treatment\algorithm_program\ChatGlm3-6b\ChatGLM3-main\finetune_demo\finetune_hf.py", line 403, in load_tokenizer_and_model
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\TCM_treatment\algorithm_program\venv\Lib\site-packages\transformers\models\auto\auto_factory.py", line 556, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\TCM_treatment\algorithm_program\venv\Lib\site-packages\transformers\modeling_utils.py", line 3375, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\houpeiyun-n\.cache\huggingface\modules\transformers_modules\chatglm3-6b-int4\modeling_chatglm.py", line 865, in __init__
    self.quantize(self.config.quantization_bit, empty_init=True)

  File "C:\Users\houpeiyun-n\.cache\huggingface\modules\transformers_modules\chatglm3-6b-int4\modeling_chatglm.py", line 1212, in quantize
    self.transformer.encoder = quantize(self.transformer.encoder, bits, empty_init=empty_init, device=device,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\houpeiyun-n\.cache\huggingface\modules\transformers_modules\chatglm3-6b-int4\quantization.py", line 154, in quantize
    layer.self_attention.query_key_value = QuantizedLinear(
                                           ^^^^^^^^^^^^^^^^

  File "C:\Users\houpeiyun-n\.cache\huggingface\modules\transformers_modules\chatglm3-6b-int4\quantization.py", line 126, in __init__
    assert str(weight.device).startswith(

AssertionError: The weights that need to be quantified should be on the CUDA device

这个问题要怎样修改呢，我完全没找到修改GPU或CPU配置的代码位置，求助求助
