### ISSUE TITLE
上面提到的没有解决的，使用finetune_demo/finetune_hf.py的lora微调之后，用finetune_demo/inference_hf.py做推理了的时候报错NotImplementedError 

### ISSUE THREAD

**Issue by shuoshushuoshu1212** [THUDM/ChatGLM3#816]
### System Info / 系統信息

Cuda 12.1
Transformers 4.37.1
Python 3.10
Pytorch 2.1.0

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR @Btlmd 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 先用finetune_demo/finetune_hf.py的lora微调之后得到如图所示的模型权重文件
![WechatIMG43](https://github.com/THUDM/ChatGLM3/assets/152780914/4bf4c010-0e89-4c49-af01-491a8a48f07b)
2. 使用finetune_demo/inference_hf.py进行推理到set_input_embeddings这里报错，如图所示
![WechatIMG4](https://github.com/THUDM/ChatGLM3/assets/152780914/b7207c20-e5df-4b69-ab62-badf9b24fe10)
3.问题是无法通过load_model_and_tokenizer方法，获取到微调过后的模型权重文件
4. 模型是下载到本地的，检查了adapter_config文件中的base_model_name_or_path是正确的
5. 且微调速度过快，相比之前几百条数据，500的步数，1-2个小时的训练时间，lora微调只需要5min，不知道是模型的问题还是我自己的问题，所以在这里一并提出，希望解答
感谢

### Expected behavior / 期待表现

模型lora微调结果模型能正常推理

**Comment by zRzRzRzRzRzRzR** [comment]
五分钟很正常，我也是五分钟

但是你这个报错的问题我前两天尝试复现，transformers 版本也升到4.37.2 了确实没遇到

**Comment by tang576225574** [comment]
这个问题我也遇到了，在加载微调模型load_model_and_tokenizer的时候不通过，环境：
Cuda 11.8
Transformers 4.37.2
Python 3.11
Pytorch 2.2.0
具体内容如下图：
![1707033369920](https://github.com/THUDM/ChatGLM3/assets/28721556/ee917828-ed41-4452-848e-60aeac13a811)
![image](https://github.com/THUDM/ChatGLM3/assets/28721556/06af153d-acd4-4de5-932a-acdd96ea9ca2)

**Comment by tang576225574** [comment]
> 这个问题我也遇到了，在加载微调模型load_model_and_tokenizer的时候不通过，环境： Cuda 11.8 Transformers 4.37.2 Python 3.11 Pytorch 2.2.0 具体内容如下图： ![1707033369920](https://private-user-images.githubusercontent.com/28721556/302086485-ee917828-ed41-4452-848e-60aeac13a811.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzM3MTksIm5iZiI6MTcwNzAzMzQxOSwicGF0aCI6Ii8yODcyMTU1Ni8zMDIwODY0ODUtZWU5MTc4MjgtZWQ0MS00NDUyLTg0OGUtNjBhZWFjMTNhODExLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA3NTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNGQxY2IzNmU0MzNlMmRkMDA1ZTE5ODA2MDRkN2JhNjExZjA4NDlmNDJmNDQyZjQ0NjFhZWZiNDBkY2Y3MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l_VRMGEXGeip8chS6_5q2l7j3hLp4YwTyPFcyDS6uPM) ![image](https://private-user-images.githubusercontent.com/28721556/302086535-06af153d-acd4-4de5-932a-acdd96ea9ca2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzM3MTksIm5iZiI6MTcwNzAzMzQxOSwicGF0aCI6Ii8yODcyMTU1Ni8zMDIwODY1MzUtMDZhZjE1M2QtYWNkNC00ZGU1LTkzMmEtYWNkZDk2ZWE5Y2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA3NTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5OTJmNGQ4ZmVlNTcwY2FmYjljNWJmMzIzOGQ0ZWZiOWNjYzg4NWVlNTcxMzg5OTU1MDA1MjM2YmUxYmYzMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uhEy9h35DZEYrUvVb8G53qadvzd3tWBdBhiTpeDZGEo)

执行命令：python inference_hf.py ./output/checkpoint-3000/ --prompt “hello”

**Comment by Sherlock1118** [comment]
> 这个问题我也遇到了，在加载微调模型load_model_and_tokenizer的时候不通过，环境： Cuda 11.8 Transformers 4.37.2 Python 3.11 Pytorch 2.2.0 执行命令：python inference_hf.py ./output/checkpoint-3000/ --prompt 具体内容如下图： ![1707033369920](https://private-user-images.githubusercontent.com/28721556/302086485-ee917828-ed41-4452-848e-60aeac13a811.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDA4NjcsIm5iZiI6MTcwNzA0MDU2NywicGF0aCI6Ii8yODcyMTU1Ni8zMDIwODY0ODUtZWU5MTc4MjgtZWQ0MS00NDUyLTg0OGUtNjBhZWFjMTNhODExLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA5NTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYjQzMDc0NDM2NjRmNjUyNWYwMjQ4OTc4MjhkOWRkOWE3NDI5MDAwODE0MGYzMzM5YzZkOTVlODE1M2Q2ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a4Adbf47cDWpEAmQiUxdd2xeSsApRM-8tRkFpxsJOv8) ![image](https://private-user-images.githubusercontent.com/28721556/302086535-06af153d-acd4-4de5-932a-acdd96ea9ca2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDA4NjcsIm5iZiI6MTcwNzA0MDU2NywicGF0aCI6Ii8yODcyMTU1Ni8zMDIwODY1MzUtMDZhZjE1M2QtYWNkNC00ZGU1LTkzMmEtYWNkZDk2ZWE5Y2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA5NTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNjY1YzQyZmQ3ZjE5MGUyMTZmMGY1YWIwYWVjZWZiOTQ3NzdmNGRkN2VhMmViZjNlYjhlMTRjNWM0MTE4N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r6Sy5T7--wd7C4405-oFqeKs9FH-AbTmuKMVau2jOOU)

+1

**Comment by yangliangguang** [comment]
一样的错误

**Comment by waitaminute0** [comment]
这个问题我也遇到了，环境：
Cuda 11.7
Transformers 4.37.2
Python 3.10.0
Pytorch 1.13.1

**Comment by yangliangguang** [comment]
> 五分钟很正常，我也是五分钟
> 
> 但是你这个报错的问题我前两天尝试复现，transformers 版本也升到4.37.2 了确实没遇到
  我是用 https://modelscope.cn/  上的在线gpu  
![微信截图_20240205105343](https://github.com/THUDM/ChatGLM3/assets/24668354/910c5fe0-33d0-45bf-b0b1-e1f1f93e07c5)

**Comment by chaokuboy** [comment]
各位博主有没有解决啊

**Comment by Wangyiheng962** [comment]
我也出现了 但我好像发现我们都是用的https://modelscope.cn/ 上的gpu 难道是这个问题？

**Comment by tang576225574** [comment]
我这边发现可能是[inference_hf.py](https://github.com/THUDM/ChatGLM3/blob/main/finetune_demo/inference_hf.py) 文件在加载时有问题，原因：我这边finetune是没有问题的，使用inference_hf.py 就会报NotImplementedError，后来我尝试使用jupyter notebook执行以下代码：
>> > from transformers import AutoTokenizer, AutoModel
>> > tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True)
>> > model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True, device='cuda')
>> > model = model.eval()
>> > response, history = model.chat(tokenizer, "你好", history=[])
>> > print(response)
发现正常运行，不会出现这个error，所以可以断定是inference_hf.py加载的问题。
继续深入，在modeling_chatglm.py文件中 ChatGLMModel 类第770行加入以下代码 (~/.cache/huggingface/modules/transformers_modules/THUDM/chatglm3-6b/xxxx/modeling_chatglm.py)：
    def get_input_embeddings(self):
        return self.embedding.word_embeddings
------------  添加的内容 ------------
    def get_input_embeddings(self, value):
        self.embedding.word_embeddings = value
------------------------------------
    def get_prompt(self, batch_size, device, dtype=torch.half):
        ...
可以通过这个error，但是会报embedding的索引错误，因为执行embedding的时候 input 没有pad到指定维度，目前我还不太清楚pad机制，所以仍然没跑通inference_hf.py脚本。。。

**Comment by zRzRzRzRzRzRzR** [comment]
或者降级到4.36版本，这个问题会更新huggingface解决

**Comment by Molasse** [comment]
> 或者降级到4.36版本，这个问题会更新huggingface解决

降级到4.36版本也会报错
ValueError: Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.

**Comment by minskiter** [comment]
> 或者降级到4.36版本，这个问题会更新huggingface解决

这是一个错误的降级，跟transformers库没有关系，实测当使用peft==0.7.0时，该问题得到解决。这是由于peft升级后行为改变导致的。
