### ISSUE TITLE
finetune_demo/inference_hf.py运行报错，trust_remote_code=True没有有效传递

### ISSUE THREAD

**Issue by La-SilverLand** [THUDM/ChatGLM3#826]
### System Info / 系統信息

cuda-11.8, transformers==4.37.2, torch==2.2.0+cu118

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在finetune_demo文件夹下，通过finetune_hf.py微调模型成功后，用checkpoint模型运行该路径下的inference_hf.py
ChatGLM3-main/finetune_demo/inference_hf.py ./path/to/checkpoint-1500 --prompt="my prompt"
出现错误，输出如下。但是该官方脚本中默认设置了trust_remote_code=True
model, tokenizer = load_model_and_tokenizer(model_dir, trust_remote_code=True)

输出如下：
Loading checkpoint shards: 100%|██████████| 7/7 [00:04<00:00,  1.48it/s]
The repository for /common-data/zhangjing/ChatGLM3-main/finetune_demo/output_phoneApp_selected_0206_1353/checkpoint-1500 contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//common-data/zhangjing/ChatGLM3-main/finetune_demo/output_phoneApp_selected_0206_1353/checkpoint-1500.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N]
输入y后报错
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ env_chatglm3/lib/python3.9/site-packages/trans │
│ formers/dynamic_module_utils.py:598 in resolve_trust_remote_code             │
│                                                                              │
│   595 │   │   │   │   signal.signal(signal.SIGALRM, _raise_timeout_error)    │
│   596 │   │   │   │   signal.alarm(TIME_OUT_REMOTE_CODE)                     │
│   597 │   │   │   │   while trust_remote_code is None:                       │
│ ❱ 598 │   │   │   │   │   answer = input(                                    │
│   599 │   │   │   │   │   │   f"The repository for {model_name} contains cus │
│   600 │   │   │   │   │   │   f"load the model. You can inspect the reposito │
│   601 │   │   │   │   │   │   f"You can avoid this prompt in future by passi │
│                                                                              │
│ env_chatglm3/lib/python3.9/site-packages/trans │
│ formers/dynamic_module_utils.py:580 in _raise_timeout_error                  │
│                                                                              │
│   577                                                                        │
│   578                                                                        │
│   579 def _raise_timeout_error(signum, frame):                               │
│ ❱ 580 │   raise ValueError(                                                  │
│   581 │   │   "Loading this model requires you to execute custom code contai │
│   582 │   │   "machine. Please set the option `trust_remote_code=True` to pe │
│   583 │   )                                                                  │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: Loading this model requires you to execute custom code contained in 
the model repository on your local machine. Please set the option 
`trust_remote_code=True` to permit loading of this model.

### Expected behavior / 期待表现

正常加载模型，执行预测

**Comment by shadowboxx** [comment]
我之前情况和你一样，  后来我更新了 hf模型文件， 并且执行了 update_requirements.sh 就好了。你可以试试看。

**Comment by zRzRzRzRzRzRzR** [comment]
peft为0.7.1不会有这个问题，可以正常运行，不要升级到8
