### ISSUE TITLE
finetune_demo/finetune_hf.py的FinetuningConfig类training_args值为什么用default而不用default_factory？

### ISSUE THREAD

**Issue by leosongwei** [THUDM/ChatGLM3#833]
### System Info / 系統信息

Repo版本：9c875fbd673cc6b9ded5fedff22a5629a86177b3
驱动：545.23.08
CUDA: 12.3.2
transformers: 4.36.2
系统：Debian 12 6.1.0-17-amd64
硬件：64GB内存 RTX4090
Python: 3.11.2

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行finetune_demo/lora_finetune.ipynb，直接报错：

```
ValueError: mutable default <class 'transformers.training_args_seq2seq.Seq2SeqTrainingArguments'> for field training_args is not allowed: use default_factory
```

我的Workaround: 154行不用default，用default_factory

### Expected behavior / 期待表现

正常finetune

**Comment by BryanMurkyChan** [comment]
同问，出现了相同的问题

**Comment by jiaangk** [comment]
把finetune_hf.py文件154行的default改为default_factory就可以了，系不同的dataclasses库版本产生的问题

**Comment by Flagami** [comment]
> 把finetune_hf.py文件154行的default改为default_factory就可以了，系不同的dataclasses库版本产生的问题

thanks very much, it works on me!!

**Comment by rzes** [comment]
> 把finetune_hf.py文件154行的default改为default_factory就可以了，系不同的dataclasses库版本产生的问题
有效果
