### ISSUE TITLE
为什么同样的问题，在官网的回答和我本地部署的回答不一样了？

### ISSUE THREAD

**Issue by cnxhwy** [THUDM/ChatGLM3#842]
### Discussed in https://github.com/THUDM/ChatGLM3/discussions/841

<div type='discussions-op-text'>

<sup>Originally posted by **cnxhwy** February 16, 2024</sup>
如题，是官网在开源模型上做了什么新的训练和微调吗？求大神们回答</div>

**Comment by aofengdaxia** [comment]
参数规模都不一样。

**Comment by cnxhwy** [comment]
都是chatglb3，莫非官网不是6B的模型吗？

**Comment by zRzRzRzRzRzRzR** [comment]
官网130B
