### ISSUE TITLE
加入ZLUDA的适配让amdgpu可以在windows上使用chatglm

### ISSUE THREAD

**Issue by zcq06** [THUDM/ChatGLM3#843]
### Feature request  / 功能建议

ZLUDA可以在AMD GPU上以近乎原生的性能运行未经修改的CUDA应用程序，效率比linux上的rocm高且支持windows部署，目前SD.NET已经加入了ZLUDA的适配，我已经参考SD.NET的适配并尝试跑图，成功适配且效率极高，能不能加入适配可以让amdgpu在windows下使用chatglm，理论上是可行的

### Motivation / 动机

https://github.com/vladmandic/automatic/commit/cc4438651f69973e055b63071bf1d0e3cc558eea
https://github.com/vladmandic/automatic/wiki/ZLUDA

### Your contribution / 您的贡献

https://github.com/vladmandic/automatic/commit/cc4438651f69973e055b63071bf1d0e3cc558eea
https://github.com/vladmandic/automatic/wiki/ZLUDA

**Comment by zRzRzRzRzRzRzR** [comment]
可以提出相关PR，我们没有AMD机器

**Comment by swustzl** [comment]
@zcq06 请问有示例吗？ 基于wiki/ZLUDA内容默认安装，然后将chatglm启动代码基于https://github.com/vladmandic/automatic/commit/cc4438651f69973e055b63071bf1d0e3cc558eea做修改吗？
