### ISSUE TITLE
请问glm4v就是cogvlm吗？

### ISSUE THREAD

**Issue by jun0wanan** [THUDM/ChatGLM3#853]
### System Info / 系統信息

我想测试 cogvlm最新模型能力，想直接调用api，但是没有找到相关api，请问glm4v就是cogvlm吗？

### Who can help? / 谁可以帮助到您？

@yincf
@abmfy 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

希望能够直接调用api使用

**Comment by zRzRzRzRzRzRzR** [comment]
不是
