### ISSUE TITLE
是否可以将 model 发布在 ollama 上呢？

### ISSUE THREAD

**Issue by zh4n7wm** [THUDM/ChatGLM3#855]
### Feature request  / 功能建议

[ollama](https://ollama.com/) 上有大量开源LLM模型，通过 ollama 可以方便的在本地运行 LLM model。

希望官方能将最新的 model 发布到 ollama 上，方便用户使用。

### Motivation / 动机

N/A

### Your contribution / 您的贡献

N/A

**Comment by zRzRzRzRzRzRzR** [comment]
目前只有在hf，之后会考虑
