### ISSUE TITLE
lora微调，没有target_modules了？

### ISSUE THREAD

**Issue by luoguanzhou** [THUDM/ChatGLM3#859]
### System Info / 系統信息

按照官方配置

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
这个配置中，为什么没有target_modules:query_key_value，那么lora操作的是哪个矩阵呢？

### Expected behavior / 期待表现

...

**Comment by zRzRzRzRzRzRzR** [comment]
只能query_key_value，调的就是这个

**Comment by ROY-SNN** [comment]
chatglm3在进行LoRA微调的时候，无法只对QV操作吗？参数如何设置？还是经过实验得到chatglm3在进行LoRA微调时候，对QKV操作性能最佳？
