### ISSUE TITLE
微调时出现报错：ValueError: ZeRO inference only makes sense with ZeRO Stage 3 - please adjust your config 

### ISSUE THREAD

**Issue by Longleaves** [THUDM/ChatGLM3#864]
### System Info / 系統信息

torch2.1.2
cuda11.8
deepspeed0.13.2
代码：ChatGLM3-main/finetune_demo/finetune_hf.py
配置：configs/lora.yaml
configs/ds_zero_3.json
数据格式：
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/503abe4b-cb8d-490d-9311-3a3648e25085)

### Who can help? / 谁可以帮助到您？

@Btlmd @zRzRzRzRzRzRzR 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用lora微调

### Expected behavior / 期待表现

ValueError: ZeRO inference only makes sense with ZeRO Stage 3 - please adjust your config 
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/db287826-7ac2-48c5-83a3-498159176baf)
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/a5e718f8-2c2e-4c51-a9cd-be006b627582)

这个错误是什么引起，应该怎么解决。谢谢大佬！

**Comment by zRzRzRzRzRzRzR** [comment]
或许降级一下ds看看？ 降到0.12

**Comment by zRzRzRzRzRzRzR** [comment]
刚才试了一下，最新版也没有问题啊

**Comment by Longleaves** [comment]
> 或许降级一下ds看看？ 降到0.12

谢谢大佬，解决了，用错了configs/ds_zero_2.json应该用3。
还有疑问就是：
1.我命令是用：python finetune_hf.py data/  ChatGLM3-main/chatglm3-6b  configs/lora.yaml None 没有None会报错，很奇怪default明明就有None的
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/2a7968ae-0337-4736-bf0d-350cc291f268)

2.训练lora，用3000条数据微调，max_input改成1024，训练时间好久哦，用2张卡要30小时，是不是我配置有什么问题呀？
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/3aa7f2ff-a414-45be-a8ae-26d35716ef7d)
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/e8d941e1-f68b-40cf-b161-7edda3128880)

3.训练ptuning的命令应该用什么呀？我用以下命令会报错：OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=2  finetune_hf.py data/  ChatGLM3-main/chatglm3-6b  configs/ptuning_v2.yaml None
再次感谢大佬！

**Comment by zRzRzRzRzRzRzR** [comment]
更新一下最新的代码就行了
