### ISSUE TITLE
次新版本正常，最新版本OutOfMemoryError: CUDA out of memory. 

### ISSUE THREAD

**Issue by justforyou2017** [THUDM/ChatGLM3#866]
### System Info / 系統信息

操作系统：Linux-5.4.0-150-generic-x86_64-with-glibc2.27.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
 transformers：4.37.2
cuda：12.1.105
显卡内容：16G

### Who can help? / 谁可以帮助到您？

@b

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

同一个训练代码，加载你们一月份的模型和safetensors进行lora训练可以正常运行，但加载最新的模型和safetensors却出现CUDA out of memory.

### Expected behavior / 期待表现

解决以上问题

**Comment by justforyou2017** [comment]
![image](https://github.com/THUDM/ChatGLM3/assets/30369560/8673f4bb-6155-40ee-ad95-0b05c25c2c5d)
![image](https://github.com/THUDM/ChatGLM3/assets/30369560/9351742d-2223-4b52-9a5a-f1a4c098bb48)
  @zRzRzRzRzRzRzR    
finetune文档说明16G是可以运行的，图片是我用对比工具对比了不同时期的文件。最后把除safetensor文件外的之前文件替换当前的文件，代码能正常运行。附件jan为之前模型文件，now为现在的，你们可测试下。
[jan.zip](https://github.com/THUDM/ChatGLM3/files/14399073/jan.zip)
[now.zip](https://github.com/THUDM/ChatGLM3/files/14399075/now.zip)

**Comment by justforyou2017** [comment]
@zRzRzRzRzRzRzR   但是如果这样替换训练后的模型还会出现|user|标签和自问自答现象吗？

**Comment by zRzRzRzRzRzRzR** [comment]
原来模型的问题是不会因为微调修好的，自问自答是你对话模板不对

**Comment by justforyou2017** [comment]
@zRzRzRzRzRzRzR  我的问题是——现在我用现在safetensor文件和以前的model文件是否还会出现问题？
现在我已经按上面的操作训练出的模型还是会出现|user|标签

> @zRzRzRzRzRzRzR 但是如果这样替换训练后的模型还会出现|user|标签和自问自答现象吗？
