### ISSUE TITLE
glm3-6b的训练数据开源吗？

### ISSUE THREAD

**Issue by jsxyhelu** [THUDM/ChatGLM3#867]
### Feature request  / 功能建议

我在网咯搜索的时候发现了glm3-6b的工具调用这块的相关训练数据，比如这样：
<|system|>
Answer the following questions as best as you can. You have access to the following tools:
[
    {
        "name": "get_current_weather",
        "description": "Get the current weather in a given location",
        "parameters": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string",
                    "description": "The city and state, e.g. San Francisco, CA",
                },
                "unit": {"type": "string"},
            },
            "required": ["location"],
        },
    }
]
<|user|>
今天北京的天气怎么样？
<|assistant|>
好的，让我们来查看今天的天气
<|assistant|>get_current_weather
```python
tool_call(location="beijing", unit="celsius")
```
<|observation|>
{"temperature": 22}
<|assistant|>
根据查询结果，今天北京的气温为 22 摄氏度。

### Motivation / 动机

想询问一下，glm3-6b的训练数据开源吗？这对于我们开展项目落地将很有帮助！

### Your contribution / 您的贡献

jsxyhelu@foxmail.com

**Comment by zRzRzRzRzRzRzR** [comment]
没有开源

**Comment by jsxyhelu** [comment]
明确
