### ISSUE TITLE
lora第一次评估后报错TypeError: Object of type Tensor is not JSON serializable

### ISSUE THREAD

**Issue by Longleaves** [THUDM/ChatGLM3#868]
### System Info / 系統信息

torch2.1.2
cuda11.8
deepspeed0.13.2
代码：ChatGLM3-main/finetune_demo/finetune_hf.py
配置：configs/lora.yaml
configs/ds_zero_2.json

### Who can help? / 谁可以帮助到您？

@Btlmd @zr

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

微调配置lora.yaml：
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/e90b379e-d454-433e-a497-93a000e21735)

数据格式：
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/a3ab13d6-42b0-4615-84e1-91d4428c39ce)
整理为.json文件

评估后报错：
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/6cf73111-e832-4874-a454-87e3fdc53b17)
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/d15a3cba-1602-46f8-aaf2-02c71a2470e2)
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/b0195a67-2c0b-4c6b-9d3e-587ca9eb9e25)
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/3796aec3-0dc9-4c62-a5ec-d3ad64ce9e7d)
![图片](https://github.com/THUDM/ChatGLM3/assets/58903935/d271894b-6105-474c-947c-8825b1a867fe)

### Expected behavior / 期待表现

第一次评估后继续训练就报错了，是我整理数据格式问题吗？
感谢大佬！

**Comment by zRzRzRzRzRzRzR** [comment]
#253 在这里讨论

没有提供你的数据集样例，我们无法进行推断

**Comment by Longleaves** [comment]
> #253 在这里讨论
> 
> 没有提供你的数据集样例，我们无法进行推断

谢谢大佬，已经在#253发问题，这是补充的数据集样例：
{"prompt": "请对以下文字进行分类。\n乌兹别克斯坦议会参议院主席将对吉尔吉斯斯坦进行正式访问 乌兹别克斯坦议会参议院主席将对吉尔吉斯斯坦进行正式访问 ", "response": "中亚"}
{"prompt": "请对以下文字进行分类。\n乌总统禁止官员出席婚庆活动，简化公民婚礼流程 乌总统禁止官员出席婚庆活动，简化公民婚礼流程 ", "response": "中亚"}

**Comment by zRzRzRzRzRzRzR** [comment]
那不对啊，建议查看我们的文档，数据集的格式不是这样的
