### ISSUE TITLE
建议将langchain_demo中的例子，修改为直接调用langchain_community.llms.chatglm3的形式

### ISSUE THREAD

**Issue by jsxyhelu** [THUDM/ChatGLM3#870]
### Feature request  / 功能建议

from langchain_community.llms.chatglm3 import ChatGLM3
已经可以正常使用，建议将langchain_demo中的例子，修改为直接调用langchain_community.llms.chatglm3的形式，可以提高稳定性。目前直接调用本地的话不方便调试。

### Motivation / 动机

提高稳定性，方便集成。

### Your contribution / 您的贡献

jsxyhelu@foxmail.com

**Comment by zRzRzRzRzRzRzR** [comment]
那个方法更好用，可以直接用那个代码执行

**Comment by jsxyhelu** [comment]
就是好像不行呀~~原理上来说是可以的吧？

**Comment by zRzRzRzRzRzRzR** [comment]
可以，看我现在的PR

**Comment by jsxyhelu** [comment]
我看了一下，我想说的是这个：https://github.com/THUDM/ChatGLM3/pull/887
也就是在langchain_demo中使用langchain_community.llms.chatglm3，这个我测试是没有问题的。
然后你的pr https://github.com/THUDM/ChatGLM3/pull/877,初步认为.run的形式下一步要被invoke取代了，最好可以改一下
