### ISSUE TITLE
模型回答有错

### ISSUE THREAD

**Issue by wangcheng0825** [THUDM/ChatGLM3#874]
### System Info / 系統信息

运行langchain的例子，天气的问答有错

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行langchain的例子，天气问题回答错误
<img width="2053" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/6059018/d179611c-b5b5-4974-adda-f05e5ea5b31c">

### Expected behavior / 期待表现

期望能结合历史记录正确回答问题

**Comment by zRzRzRzRzRzRzR** [comment]
这好像是没有倒入历史记录的问题，我晚点看看
