### ISSUE TITLE
最新requirements.txt中openai库版本与openai_api_demo.py代码不兼容

### ISSUE THREAD

**Issue by lj1262** [THUDM/ChatGLM3#878]
### System Info / 系統信息

python 3.10.11

### Who can help? / 谁可以帮助到您？

最新requirements.txt中库openai 1.12与tools_using_demo目录下的openai_api_demo.py代码不兼容，运行报错，
把openai库替换成之前的1.7.2后，恢复正常。

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.运行openai_api_demo目录下的api_server.py
2.运行tools_using_demo目录下的openai_api_demo.py
3.报错：raise self._make_status_error_from_response(err.response) from None openai.UnprocessableEntityError:422

### Expected behavior / 期待表现

不报错

**Comment by morettt** [comment]
是这样的，我也发现了。换回之前的版本就不报错了

**Comment by zRzRzRzRzRzRzR** [comment]
问题在哪呢，方便复现一下
<img width="827" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/93239683/640854be-8250-4bd5-991c-dc477e1f2332">

**Comment by lj1262** [comment]
应该是python 3.10与openai 1.12不兼容，换成python 3.11就可以了

**Comment by Powerfulxxr** [comment]
python=3.10.11
model=chatglm3-6b
openai=1.7.2

我是这样的版本，跑demo还是无法调用天气函数，不知道为什么
