### ISSUE TITLE
sentencepiece_processor 报错

### ISSUE THREAD

**Issue by lampda** [THUDM/ChatGLM3#88]
conda安装pytorch 2.1
pip install 补充安装了requirements的内容

运行python web_demo.py 之后报错：

```bash
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]
```

如上提示报错，本地环境配置：
```bash
OS: Kylin V10
python: 3.10.12
```

请教如何解决呢？谢谢。

**Comment by duzx16** [comment]
请检查 tokenizer.model 文件的大小和 sha256 是否和 https://huggingface.co/THUDM/chatglm3-6b/ 上面的一致

**Comment by lampda** [comment]
正确，更新了tokenizer.model后可以启动了。谢谢。
