### ISSUE TITLE
pyhton api_server.py报错No sentence-transformers model found with name BAAI/bge-large-zh-v1.5如何解决？

### ISSUE THREAD

**Issue by Andy1018** [THUDM/ChatGLM3#882]
### System Info / 系統信息

pyhton api_server.py报错No sentence-transformers model found with name BAAI/bge-large-zh-v1.5如何解决？

### Who can help? / 谁可以帮助到您？

pyhton api_server.py报错No sentence-transformers model found with name BAAI/bge-large-zh-v1.5如何解决？

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

pyhton api_server.py报错No sentence-transformers model found with name BAAI/bge-large-zh-v1.5如何解决？

### Expected behavior / 期待表现

pyhton api_server.py报错No sentence-transformers model found with name BAAI/bge-large-zh-v1.5如何解决？

**Comment by Andy1018** [comment]
pyhton api_server.py报错No sentence-transformers model found with name BAAI/bge-large-zh-v1.5如何解决？

**Comment by zRzRzRzRzRzRzR** [comment]
下载模型，这个是另一个模型，hugginface可以下载
