### ISSUE TITLE
关于跟着教程进行PtuningV2微调之后模型没有adapter_config.json的问题

### ISSUE THREAD

**Issue by sgcjin** [THUDM/ChatGLM3#884]
### System Info / 系統信息

cuda版本12.1
transformers 4.38.1

### Who can help? / 谁可以帮助到您？

@Btlmd

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在finetune_demo 中的[https://github.com/THUDM/ChatGLM3/tree/main/finetune_demo#readme](url) 提到

> 请注意，对于 LORA 和 P-TuningV2 我们没有合并训练后的模型，而是在adapter_config.json 中记录了微调型的路径，如果你的原始模型位置发生更改，则你应该修改adapter_config.json中base_model_name_or_path的路径

我跟着[https://github.com/THUDM/ChatGLM3/blob/main/finetune_demo/lora_finetune.ipynb](url) 里面的教程，把微调代码

`!CUDA_VISIBLE_DEVICES=1 /media/zr/Data/Code/ChatGLM3/venv/bin/python3 finetune_hf.py  data/AdvertiseGen_fix  /media/zr/Data/Models/LLM/chatglm3-6b  configs/lora.yaml`

中的`lora.yaml`改成了`ptuning_v2.yaml`微调了chatglm3-6b-chat模型，过程很顺利，但是生成的模型中没有教程中提到的adapter_config.json，我想知道我的方法是不是出了什么问题，谢谢！

### Expected behavior / 期待表现

出现adapter_config.json

**Comment by gaooooke325** [comment]
![image](https://github.com/THUDM/ChatGLM3/assets/73920311/c01ad28b-6a6f-4cfd-a244-a8151ba9eeaa)

**Comment by gaooooke325** [comment]
我也是这个问题
![image](https://github.com/THUDM/ChatGLM3/assets/73920311/0d14e3d9-0110-4b07-afc5-e67e8b2c76c0)

**Comment by zRzRzRzRzRzRzR** [comment]
ptuning不是应该直接是一个前缀吗，哪来的adapter

**Comment by sgcjin** [comment]
那是[https://github.com/THUDM/ChatGLM3/tree/main/finetune_demo#readme](https://github.com/THUDM/ChatGLM3/issues/url)里面写错了吗，如果原始模型的位置发生了更改是不是就不用改任何文件了。
我还有一点疑问希望大佬可以解答一下，就是在其他demo里面使用ptuning微调后的模型也是用[https://github.com/THUDM/ChatGLM3/tree/main/finetune_demo#readme](https://github.com/THUDM/ChatGLM3/issues/url)里面给出的代码来加载未合并的模型吗

> 请注意，对于 LORA 和 P-TuningV2 我们没有合并训练后的模型，而是在adapter_config.json 中记录了微调型的路径，如果你的原始模型位置发生更改，则你应该修改adapter_config.json中base_model_name_or_path的路径。
```

def load_model_and_tokenizer(
        model_dir: Union[str, Path], trust_remote_code: bool = True
) -> tuple[ModelType, TokenizerType]:
    model_dir = _resolve_path(model_dir)
    if (model_dir / 'adapter_config.json').exists():
        model = AutoPeftModelForCausalLM.from_pretrained(
            model_dir, trust_remote_code=trust_remote_code, device_map='auto'
        )
        tokenizer_dir = model.peft_config['default'].base_model_name_or_path
    else:
        model = AutoModelForCausalLM.from_pretrained(
            model_dir, trust_remote_code=trust_remote_code, device_map='auto'
        )
        tokenizer_dir = model_dir
    tokenizer = AutoTokenizer.from_pretrained(
        tokenizer_dir, trust_remote_code=trust_remote_code
    )
    return model, tokenizer
```

**Comment by zRzRzRzRzRzRzR** [comment]
如果原始模型位置发生更改并且有adapter的话你要改adapter的config，如果原始文件没更改就不用了。接着下面这个我测的是lora，lora都是这么挂就行了

**Comment by xpcc355** [comment]
ptuning微调后的是已经合并的模型吗？

**Comment by minghf85** [comment]
@sgcjin 你好请问ptuning微调后如何加载，既然作者给的是lora的加载方式
