### ISSUE TITLE
openai方式调用chatGLM3-32k时，在多次长文调用后，会无响应；基本100次左右的调用就会完全无响应，也不报错

### ISSUE THREAD

**Issue by Eleanor456** [THUDM/ChatGLM3#886]
### System Info / 系統信息

linux系统，torch：2.2.1+cu118；transformers：4.38.1

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

多次调用长文，次数达到100次，文字长度1000字以上

### Expected behavior / 期待表现

fastchat正常调用，不会出现卡死的情况

**Comment by zRzRzRzRzRzRzR** [comment]
1. 检查你的显存是不是超了，随着调用更多增加，显存会逐渐增加，你看一下到后面是不是显存已经满了。
2. 我们在测的时候不会测到100次，在10次内没有出现你的问题。
3. demo不是用来上生产环境的，本仓库只是一个入门仓库，仅保证能运行，如果你需要部署在生产环境，请自行优化代码

**Comment by Eleanor456** [comment]
显存没超，用了8卡在跑
没有任何报错就是卡死，显存，内存，cpu都正常，请教下应该从哪个方向入门优化呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zR ***@***.***&gt;
发送时间: 2024年2月27日 20:02
收件人: THUDM/ChatGLM3 ***@***.***&gt;
抄送: Eleanor456 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [THUDM/ChatGLM3] openai方式调用chatGLM3-32k时，在多次长文调用后，会无响应；基本100次左右的调用就会完全无响应，也不报错 (Issue #886)





  
检查你的显存是不是超了，随着调用更多增加，显存会逐渐增加，你看一下到后面是不是显存已经满了。
 
我们在测的时候不会测到100次，在10次内没有出现你的问题。
 
demo不是用来上生产环境的，本仓库只是一个入门仓库，仅保证能运行，如果你需要部署在生产环境，请自行优化代码

**Comment by zRzRzRzRzRzRzR** [comment]
官方demo 你8个卡也是只有一个卡在推理吧

**Comment by Eleanor456** [comment]
我看八个卡都调起来了，每块4，5的样子



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zR ***@***.***&gt;
发送时间: 2024年2月27日 20:18
收件人: THUDM/ChatGLM3 ***@***.***&gt;
抄送: Eleanor456 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [THUDM/ChatGLM3] openai方式调用chatGLM3-32k时，在多次长文调用后，会无响应；基本100次左右的调用就会完全无响应，也不报错 (Issue #886)





 
官方demo 你8个卡也是只有一个卡在推理吧

**Comment by zRzRzRzRzRzRzR** [comment]
那你就是模型拆到5张卡了，这样可能出现问题，尝试一张卡调用
