### ISSUE TITLE
【已解决】函数调用不兼容新版openai 函数调用格式

### ISSUE THREAD

**Issue by mingyue0094** [THUDM/ChatGLM3#888]
### System Info / 系統信息

Python 3.10.5

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

#  openai_api    function_call 格式改版了 = . =

不知道是不是这个改版的原因。
之前用 chatglm3  然后用其他的应用，按openai_api    function_call  接口访问 chatglm3 可以正常调用函数。
后面有段时间没有，现在又用不了了。

现在看到个 [LobeChatDOCS](https://chat-docs.lobehub.com/) 。看着比 nextgpt 丰富。
就用 chatglm3 接入 LobeChat， 然后函数调用用不了。 看生成的输出 和 openai 文档，好像是生成的和 新接口格式匹配不上。。。。 

```
 https://cookbook.openai.com/examples/how_to_call_functions_with_chat_models



ChatCompletionMessage(content=None, role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_qOYhFO7fKaU6wpG2f1XzkDjW', function=Function(arguments='{\n  "location": "Glasgow, Scotland",\n  "format": "celsius"\n}', name='get_current_weather'), type='function')])
```

### Expected behavior / 期待表现

修复新增个适配新版 openai 函数调用，格式接口。
旧版，旧的应用应该可以用。其他新的三方应用，就用不了。

**Comment by lj1262** [comment]
我昨天也发现了，1.12版本的openai好像不兼容“client.chat.completions.create(**params)”这个函数调用，退回到1.7.2、1.9都可以正常运行

**Comment by zRzRzRzRzRzRzR** [comment]
python升级到3.11就不会有422问题了

**Comment by Powerfulxxr** [comment]
老哥，我也是无法执行函数。
pydantic=1.10.13
python=3.10.11
model=chatglm3-6b
openai=1.7.2
这个tools_using_demo模块下的openai_api_demo.py，是否这些版本导致的

**Comment by descending-order** [comment]
你好你好，请教一下如何能调用插件呀，我用的模型是glm-4

**Comment by 2244295209** [comment]
大哥，官方给出的chatglm3不是不支持stream_chat吗？

我按照你的方式改了还是不行，

请求里面一直是   function_call=None不知道咋搞了，求大佬支支招

**Comment by 2244295209** [comment]
大佬，我看你使用这个[LobeChatDOCS](https://chat-docs.lobehub.com/)调的chatglm3，我也使用这个进行测试，工具还是调不起来，根据你的解决办法处理了，还是不行，是不是openai的版本问题呢？
