### ISSUE TITLE
langchain demo中使用tools，大模型原本的推理能力消失了

### ISSUE THREAD

**Issue by Timmy-Cai** [THUDM/ChatGLM3#889]
### System Info / 系統信息

问题：
指定多个工具，如果问工具相关的问题是可以的，比如`上海比北京冷吗？`，如果问题`你是谁？`，回答的结果有问题。什么原因呢？

源码如下：
```
from langchain import hub
from langchain.agents import AgentExecutor, create_structured_chat_agent, load_tools
from langchain_core.messages import AIMessage, HumanMessage

from ChatGLM3 import ChatGLM3
from tools.Calculator import Calculator
from tools.Weather import Weather
from tools.DistanceConversion import DistanceConverter

MODEL_PATH = os.environ.get('MODEL_PATH', '/data2/models/chatglm3-6b')

if __name__ == "__main__":
    llm = ChatGLM3()
    llm.load_model(MODEL_PATH)
    prompt = hub.pull("hwchase17/structured-chat-agent")

    tools = [Weather(), Calculator()]
    agent = create_structured_chat_agent(llm=llm, tools=tools, prompt=prompt)
    agent_executor = AgentExecutor(agent=agent, tools=tools)
    ans = agent_executor.invoke(
        {
            "input": "你是谁?",
            "chat_history": [
                HumanMessage(content="北京温度多少度"),
                AIMessage(content="北京现在12度"),
            ],
        }
    )
    print(ans)

```
回答的内容如下：
```
{'input': '你是谁?', 'chat_history': [HumanMessage(content='北京温度多少度'), AIMessage(content='北京现在12度')], 'output': '{ "name": "Calculator", "description": "Useful for when you need to calculate math problems", "url": "http://www.calculator.com/", "paths": [{ "name": "/calculator", "description": "calculation to perform", "parameters": [{ "name": "calculation", "description": "calculation to perform", "type": "string" }] }] }'}
```

![image](https://github.com/THUDM/ChatGLM3/assets/61072229/30519d10-a7b1-4201-a5a9-60be95674039)
![image](https://github.com/THUDM/ChatGLM3/assets/61072229/b3059c23-1dcf-46b7-b0c7-a7e420d6ccd2)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

import os

from langchain import hub
from langchain.agents import AgentExecutor, create_structured_chat_agent, load_tools
from langchain_core.messages import AIMessage, HumanMessage

from ChatGLM3 import ChatGLM3
from tools.Calculator import Calculator
from tools.Weather import Weather
from tools.DistanceConversion import DistanceConverter

MODEL_PATH = os.environ.get('MODEL_PATH', '/data2/models/chatglm3-6b')

if __name__ == "__main__":
    llm = ChatGLM3()
    llm.load_model(MODEL_PATH)
    prompt = hub.pull("hwchase17/structured-chat-agent")

    tools = [Weather(), Calculator()]
    agent = create_structured_chat_agent(llm=llm, tools=tools, prompt=prompt)
    agent_executor = AgentExecutor(agent=agent, tools=tools)
    ans = agent_executor.invoke(
        {
            "input": "你是谁?",
            "chat_history": [
                HumanMessage(content="北京温度多少度"),
                AIMessage(content="北京现在12度"),
            ],
        }
    )
    print(ans)

### Expected behavior / 期待表现

聊天的内容如果是与天气有关，则调用天气的工具，如果设计到计算，则调用计算的工具，如果正常的聊天，则默认使用大模型自身的推理

**Comment by zRzRzRzRzRzRzR** [comment]
langchain 这种调用形式本来就是这样的呀，本地模型的通病，tools和正常调用只能有一个
