### ISSUE TITLE
综合demo中的code interpreter不工作

### ISSUE THREAD

**Issue by zhaoxin** [THUDM/ChatGLM3#89]
![image](https://github.com/THUDM/ChatGLM3/assets/324931/758702d6-d6f5-4f9d-9d5b-784ccbe11fef)

日志：
<|user|> 用Python画一个爱心 None
=== Input:
<|system|>
你是一位智能AI助手，你叫ChatGLM，你连接着一台电脑，但请注意不能联网。在使用Python解决任务时，你可以运行代码并得到结果，如果运行结果有错误，你需要尽可能对代码进行改进。你可以处理用户上传到电脑上的文件，文件默认存储路径是/mnt/data/。<|user|>
用Python画一个爱心<|assistant|>

=== History:
[Conversation(role=<Role.USER: 2>, content='用Python画一个爱心', tool=None, image=None)]
=== Output:

 当然可以。我将使用Python的matplotlib库来绘制一个爱心形状。首先，我将导入必要的库，并创建一个图形。然后，我将使用参数方程来绘制爱心的形状。
=== Output:
 interpreter
 ```python
import matplotlib.pyplot as plt
import numpy as np

# 参数方程
t = np.linspace(0, 2 * np.pi, 1000)
x = 16 * np.sin(t)**3
y = 13 * np.cos(t) - 5 * np.cos(2*t) - 2 * np.cos(3*t) - np.cos(4*t)

# 创建图形
plt.figure(figsize=(6,6))
plt.plot(x, y, color='red')
plt.title("Heart Shape")
plt.axis("off")  # 关闭坐标轴
plt.axis("equal")  # 确保图形在舒适的范围内
plt.show()
```

Code: import matplotlib.pyplot as plt
import numpy as np

# 参数方程
t = np.linspace(0, 2 * np.pi, 1000)
x = 16 * np.sin(t)**3
y = 13 * np.cos(t) - 5 * np.cos(2*t) - 2 * np.cos(3*t) - np.cos(4*t)

# 创建图形
plt.figure(figsize=(6,6))
plt.plot(x, y, color='red')
plt.title("Heart Shape")
plt.axis("off")  # 关闭坐标轴
plt.axis("equal")  # 确保图形在舒适的范围内
plt.show()

**Comment by Btlmd** [comment]
运行了一下模型生成的代码，代码是正确的；
没有显示图像的原因可能是没有启动 kernel ？可以检查一下 [Jupyter 内核是否安装](https://github.com/THUDM/ChatGLM3/tree/main/composite_demo#%E5%AE%89%E8%A3%85)
```bash
ipython kernel install --name chatglm3-demo --user
```

**Comment by zhaoxin** [comment]
@Btlmd 感谢提示。是我的python编译有问题，没带上sqlite扩展。配置项加上--enable-loadable-sqlite-extensions后重新编译python，问题解决。

**Comment by Elegant-Spider** [comment]
我是用的pycharm，没有安装Conda，怎么配置ipython kernel ？ @Btlmd

**Comment by 123mtr-A** [comment]
> @Btlmd 感谢提示。是我的python编译有问题，没带上sqlite扩展。配置项加上--enable-loadable-sqlite-extensions后重新编译python，问题解决。

可以具体说下怎么解决的吗

**Comment by zhaoxin** [comment]
> > @Btlmd 感谢提示。是我的python编译有问题，没带上sqlite扩展。配置项加上--enable-loadable-sqlite-extensions后重新编译python，问题解决。
> 
> 可以具体说下怎么解决的吗

编译python时：
./configure --enable-loadable-sqlite-extensions --enable-optimizations
sudo make altinstall

**Comment by Btlmd** [comment]
> 我是用的pycharm，没有安装Conda，怎么配置ipython kernel ？ @Btlmd

可直接选择环境中的 `pip` 对依赖进行安装即可
