### ISSUE TITLE
单机多卡运行lora微调指令报错

### ISSUE THREAD

**Issue by CarpLoong** [THUDM/ChatGLM3#898]
### System Info / 系統信息

cuda12.1 transformers=4.38.1 python=3.11.8 操作系统linux centos 7.9 3090 24g*2

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在Anaconda新创建的环境中安装完pytorch、pip以及requirements.txt内的依赖后运行发现依旧缺少依赖，还需要安装
pip install typer
pip install nltk
pip install sentencepiece
pip install -U transformers
安装完运行之后使用单卡运行的指令运行后依旧报错
要修改finetune_hf.py154行的代码为“default_factory = lambda: Seq2SeqTrainingArguments(output_dir='./output')”后才可正常运行
但是运行多卡的指令
“OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=8  finetune_hf.py  data/AdvertiseGen/  THUDM/chatglm3-6b  configs/lora.yaml  --deepspeed ds_zero_2.json”
后会报错“RuntimeError: CUDA error: invalid device ordinal”

### Expected behavior / 期待表现

给出解决方法

**Comment by QQShan** [comment]
--nproc_per_node=8，你是单机几卡的就设置成几
