### ISSUE TITLE
完全按照官方微调套件及notebook运行，进行推理时出现报错

### ISSUE THREAD

**Issue by tiamojames** [THUDM/ChatGLM3#899]
### System Info / 系統信息

root@autodl-container-cdbf4cb59e-50bc78bb:~/ChatGLM3/finetune_demo# python3 inference_hf.py output/checkpoint-3000/ --prompt "类型#裙*版型#显瘦*材质#网纱*风格#性感*裙型#百褶*裙下摆#压褶*裙长#连衣裙* 裙衣门襟#拉链*裙衣门襟#套头*裙款式#拼接*裙款式#拉链*裙款式#木耳边*裙款式#抽褶*裙款式#不规则"
Traceback (most recent call last):

  File "/root/ChatGLM3/finetune_demo/inference_hf.py", line 56, in <module>
    app()

  File "/root/ChatGLM3/finetune_demo/inference_hf.py", line 50, in main
    model, tokenizer = load_model_and_tokenizer(model_dir)

  File "/root/ChatGLM3/finetune_demo/inference_hf.py", line 30, in load_model_and_tokenizer
    model = AutoPeftModelForCausalLM.from_pretrained(

  File "/root/miniconda3/envs/tiamo/lib/python3.10/site-packages/peft/auto.py", line 69, in from_pretrained
    peft_config = PeftConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)

  File "/root/miniconda3/envs/tiamo/lib/python3.10/site-packages/peft/config.py", line 137, in from_pretrained
    config = config_cls(**kwargs)

TypeError: LoraConfig.__init__() got an unexpected keyword argument 'use_rslora'

显示提供了多余的参数

### Who can help? / 谁可以帮助到您？

@Btlmd

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

按照官方readme中的微调套件并运行其中的notebook实列，推理时出现报错

### Expected behavior / 期待表现

期待有人可以帮助解决这个problem(*^_^*)

**Comment by zRzRzRzRzRzRzR** [comment]
use_rslora是什么东西。。。

**Comment by jkl375** [comment]
> use_rslora是什么东西。。。
peft最新版的参数
![image](https://github.com/THUDM/ChatGLM3/assets/54523287/4743c78d-4238-4bc8-9294-bc7c63bad9f7)

**Comment by zRzRzRzRzRzRzR** [comment]
你看我们requirement中的peft的指定要求

**Comment by tiamojames** [comment]
> 你看我们requirement中的peft的指定要求

明白了，谢谢! 我记得当时是用requirement安装，但我查看了我的peft确实不是指定的版本。谢谢解答(*^_^*)

**Comment by tiamojames** [comment]
> > use_rslora是什么东西。。。
> > peft最新版的参数
> > ![image](https://private-user-images.githubusercontent.com/54523287/309163681-4743c78d-4238-4bc8-9294-bc7c63bad9f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODQwOTIsIm5iZiI6MTcwOTI4Mzc5MiwicGF0aCI6Ii81NDUyMzI4Ny8zMDkxNjM2ODEtNDc0M2M3OGQtNDIzOC00YmM4LTkyOTQtYmM3YzYzYmFkOWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA5MDMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ODkxNTBmYWNkOGJkNjRlZTVkZWJkZjYyMjhiOTQ3MjhlM2JkYjU5MmIwNzdlNDgzNmE2N2MzOWEzYWY5YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QYOJ0TQyNeTd_ghHDt14-FmLGKdsMgqx-yObE3j2mNU)

明白了，谢谢! 我查看了我的peft确实不是指定的版本。谢谢解答(*^_^*)

**Comment by tiamojames** [comment]
> 你看我们requirement中的peft的指定要求
不好意思，我刚才把peft降级到指定版本0.7.1重启后依旧存在原先的报错
![Uploading bug.png…]()
![Uploading peft.png…]()

**Comment by tiamojames** [comment]
> 你看我们requirement中的peft的指定要求

不好意思，我刚才把peft降级到指定版本0.7.1重启后依旧存在原先的报错
![Uploading bug.png…]()
![Uploading peft.png…]()
Traceback (most recent call last):

  File "/root/ChatGLM3/finetune_demo/inference_hf.py", line 56, in <module>
    app()

  File "/root/ChatGLM3/finetune_demo/inference_hf.py", line 50, in main
    model, tokenizer = load_model_and_tokenizer(model_dir)

  File "/root/ChatGLM3/finetune_demo/inference_hf.py", line 30, in load_model_and_tokenizer
    model = AutoPeftModelForCausalLM.from_pretrained(

  File "/root/miniconda3/envs/tiamo/lib/python3.10/site-packages/peft/auto.py", line 69, in from_pretrained
    peft_config = PeftConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)

  File "/root/miniconda3/envs/tiamo/lib/python3.10/site-packages/peft/config.py", line 137, in from_pretrained
    config = config_cls(**kwargs)

TypeError: LoraConfig.__init__() got an unexpected keyword argument 'use_rslora'

**Comment by zRzRzRzRzRzRzR** [comment]
请检查你的依赖，一定要严格按照req安装

**Comment by BoyCO3** [comment]
已解决，transformers的依赖可能要低于req的版本，但是十分感谢，借鉴了下面这条
https://github.com/THUDM/ChatGLM3/discussions/253#discussioncomment-8553389
