### ISSUE TITLE
请问有量化版本吗

### ISSUE THREAD

**Issue by kingdomad** [THUDM/ChatGLM3#90]

**Comment by zRzRzRzRzRzRzR** [comment]
暂时没有提供，如果有，我们会在Github上和huggingface更新。
我们提供了量化方案，如果需要，你可以按照readme的方案自行量化
![图片](https://github.com/THUDM/ChatGLM3/assets/93239683/93034db7-bfe8-483a-b135-ff537d12f2ec)
