### ISSUE TITLE
finetune_demo安装依赖deepspeed报错

### ISSUE THREAD

**Issue by lj1262** [THUDM/ChatGLM3#903]
### System Info / 系統信息

win11
python 3.11.8
torch 2.1.2+cu121
cuda 12.3
transformers 4.38.1

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

(chatglm3) C:\Users\Administrator>pip install deepspeed
Looking in indexes: https://mirrors.cloud.tencent.com/pypi/simple
Collecting deepspeed
  Using cached https://mirrors.cloud.tencent.com/pypi/packages/0c/16/2730831cbbb3f59e2e39dd2dd7a9ed973fb4119b2c61a0a9ebd722935dd3/deepspeed-0.13.4.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      test.c
      LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-6nva0sru\deepspeed_7d63eb4035d74d01bc9efd50a4282691\setup.py", line 183, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-6nva0sru\deepspeed_7d63eb4035d74d01bc9efd50a4282691\setup.py", line 52, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Expected behavior / 期待表现

successfully installed

**Comment by jiangqr** [comment]
windows不能直接pip安装deepspeed，而且高版本的deepspeed也没法源码编译安装，就是用别人编译的（https://github.com/daswer123/deepspeed-windows-wheels）我这边安装也会有nccl问题，期待你的情况

**Comment by zRzRzRzRzRzRzR** [comment]
ds建议使用linux方式运行，所有demo测试也都在linux环境下测试

**Comment by lj1262** [comment]
> ds建议使用linux方式运行，所有demo测试也都在linux环境下测试

用虚拟机可以吗？推荐用什么版本的linux？

**Comment by lj1262** [comment]
> https://github.com/daswer123/deepspeed-windows-wheels

谢谢，但是你给的这个资源里没有最新的0.13.3

**Comment by lj1262** [comment]
> ds建议使用linux方式运行，所有demo测试也都在linux环境下测试

谢谢，但是你给的这个资源里没有最新的0.13.3

**Comment by lj1262** [comment]
> windows不能直接pip安装deepspeed，而且高版本的deepspeed也没法源码编译安装，就是用别人编译的（[https://github.com/daswer123/deepspeed-windows-wheels）我这边安装也会有nccl问题，期待你的情况]
谢谢，但是你给的这个资源里没有最新的0.13.3

**Comment by lj1262** [comment]
> ds建议使用linux方式运行，所有demo测试也都在linux环境下测试

你这边能不能编译一个最新版的deepspeed放出来，方便windows用pip安装

**Comment by zRzRzRzRzRzRzR** [comment]
我们没有在windows上做过测试，我们推荐使用原生的Linux系统进行微调，会减少不必要的环境冲突
