### ISSUE TITLE
微调模型的对话和工具能力功能貌似没有实现

### ISSUE THREAD

**Issue by wangcheng0825** [THUDM/ChatGLM3#906]
### System Info / 系統信息

Macbook Pro  M3 

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我尝试参考文档中微调模型的对话和工具能力，创建如下格式数据
[
    {
        "tools": [
            {
                "get_weather": {
                    "name": "get_weather",
                    "description": "Get the current weather for `city_name`",
                    "params": [
                        {
                            "name": "city_name",
                            "description": "The name of the city to be queried",
                            "type": "str",
                            "required": true
                        }
                    ]
                }
            }
        ],
        "conversations": [
            {
                "role": "user",
                "content": "\n        请帮我从语句“北京是祖国的首都”中提取城市信息"
            },
            {
                "role": "assistant",
                "content": "beijing"
            },
            {
                "role": "tool",
                "name": "get_weather",
                "parameters": {
                    "<parameter_name>": "beijing"
                },
                "observation": "12"
            },
            {
                "role": "assistant",
                "content": "北京今天12度"
            }
        ]
    }
]

我尝试调用python finetune_hf.py  data/gen  THUDM/chatglm3-6b  configs/ptuning_v2.yaml 进行微调，后台报错，提示NotImplementedError，我看了下逻辑，咱们代码中貌似还没有实现这个能力是吗？

### Expected behavior / 期待表现

希望能够支持微调模型的对话和工具能力，并且提供简单示例，谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
微调对话和工具的能力根老版本是一样的，这个根peft没有关系

**Comment by wangcheng0825** [comment]
@zRzRzRzRzRzRzR 抱歉初学对这块不是很理解，跟您请教一下。 文档中描述
<img width="1052" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/6059018/f5645000-b8ae-4ef1-9007-e627436f9460">
我想按照这个格式微调对话和工具的能力，构造了对应的数据集，运行微调时报错，我看了微调的代码
<img width="1614" alt="image" src="https://github.com/THUDM/ChatGLM3/assets/6059018/ab489314-d096-4c4c-a561-ed4480c18ca7">
我理解是这个功能没有实现，不知道理解的对吗？

**Comment by zRzRzRzRzRzRzR** [comment]
这个新代码把这里暂时设定成没有，是因为调了之后效果也不行，然后在转过来的时候就先没有实现，之后如果效果好就不充回去根老版本一样，老版本只有全参微调的tools效果不过，如果用老版本微调也行，但是没法lora。这部分你理解是对的

**Comment by wangcheng0825** [comment]
好的，那issue是关掉还是留着？

**Comment by valkryhx** [comment]
> 这个新代码把这里暂时设定成没有，是因为调了之后效果也不行，然后在转过来的时候就先没有实现，之后如果效果好就不充回去根老版本一样，老版本只有全参微调的tools效果不过，如果用老版本微调也行，但是没法lora。这部分你理解是对的

也就是说 用被delete的老finetune代码是可以跑通工具微调的吗 只不过效果不好？
