### ISSUE TITLE
单机多卡运行lora微调时指令遇到问题

### ISSUE THREAD

**Issue by CarpLoong** [THUDM/ChatGLM3#907]
### System Info / 系統信息

应该不是硬件问题

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

如果用文档中的指令
OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=8  finetune_hf.py  data/AdvertiseGen/  THUDM/chatglm3-6b  configs/lora.yaml ![微信图片_20240302094120](https://github.com/THUDM/ChatGLM3/assets/50446131/8b94bc80-4ada-41bd-807f-7e2f7dacd86a)
会显示没有deepspeed这个选项
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/11975293-9c4e-404c-9b9d-e0fef6f85f87)

去掉之后能正常加载checkpoint shards，但是会报一个运行时异常
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the
`forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use
_set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes.
For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by
different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default.
You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 55 with name base_model.model.transformer.encoder.layers.27.self_attention.query_key_value.lora_B.default.weight has been marked as
ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.

### Expected behavior / 期待表现

解答微调万物

**Comment by CarpLoong** [comment]
![Uploading 微信图片_20240302094120.png…]()

**Comment by zRzRzRzRzRzRzR** [comment]
CUDA_VISIBLE_DEVICES=1 python finetune_hf.py  data/AdvertiseGen_fix  /share/home/zyx/Models/chatglm3-6b  configs/ptuning_v2.yaml

**Comment by zRzRzRzRzRzRzR** [comment]
记得吧配置文件中的ds配置改为绝对路径

**Comment by CarpLoong** [comment]
> CUDA_VISIBLE_DEVICES=1 python finetune_hf.py data/AdvertiseGen_fix /share/home/zyx/Models/chatglm3-6b configs/ptuning_v2.yaml

这是单机单卡ptuningv2运行的吗

**Comment by CarpLoong** [comment]
> CUDA_VISIBLE_DEVICES=1 python finetune_hf.py data/AdvertiseGen_fix /share/home/zyx/Models/chatglm3-6b configs/ptuning_v2.yaml

这不是单机多卡的运行方式吧

**Comment by zRzRzRzRzRzRzR** [comment]
> 记得吧配置文件中的ds配置改为绝对路径

OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=8  finetune_hf.py  data/AdvertiseGen_fix  /share/home/zyx/Models/chatglm3-6b  configs/sft.yaml configs/ds_zero_3.json可以
