### ISSUE TITLE
Need to enable queue to use generators

### ISSUE THREAD

**Issue by m13810859213** [THUDM/ChatGLM3#91]
启动web_demo.py报错 Need to enable queue to use generators

**Comment by zRzRzRzRzRzRzR** [comment]
请提供更多信息，你的错误无法复现

**Comment by zRzRzRzRzRzRzR** [comment]
如还遇到相关问题，请根据最新的issue模板提供最小复现，方便我们复现问题，该issue先关闭，感谢理解
