### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a  grad_fn

### ISSUE THREAD

**Issue by RexxyWong** [THUDM/ChatGLM3#912]
### System Info / 系統信息

我在單卡運行，我的data都是跟隨教學下載 多次運行出現報錯 無法解決

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

 我在單卡運行，我的data都是跟隨教學下載 多次運行出現報錯 無法解決
 
  warnings.warn(
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /root/tf-logs/ChatGLM3/finetune_demo/finetune_hf.py:517 in main              │
│                                                                              │
│   514 │   │   tokenizer=tokenizer,                                           │
│   515 │   │   compute_metrics=functools.partial(compute_metrics, tokenizer=t │
│   516 │   )                                                                  │
│ ❱ 517 │   trainer.train()                                                    │
│   518 │                                                                      │
│   519 │   # test stage                                                       │
│   520 │   if test_dataset is not None:                                       │
│                                                                              │
│ /root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py:1539   │
│ in train                                                                     │
│                                                                              │
│   1536 │   │   │   finally:                                                  │
│   1537 │   │   │   │   hf_hub_utils.enable_progress_bars()                   │
│   1538 │   │   else:                                                         │
│ ❱ 1539 │   │   │   return inner_training_loop(                               │
│   1540 │   │   │   │   args=args,                                            │
│   1541 │   │   │   │   resume_from_checkpoint=resume_from_checkpoint,        │
│   1542 │   │   │   │   trial=trial,                                          │
│                                                                              │
│ /root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py:1869   │
│ in _inner_training_loop                                                      │
│                                                                              │
│   1866 │   │   │   │   │   self.control = self.callback_handler.on_step_begi │
│   1867 │   │   │   │                                                         │
│   1868 │   │   │   │   with self.accelerator.accumulate(model):              │
│ ❱ 1869 │   │   │   │   │   tr_loss_step = self.training_step(model, inputs)  │
│   1870 │   │   │   │                                                         │
│   1871 │   │   │   │   if (                                                  │
│   1872 │   │   │   │   │   args.logging_nan_inf_filter                       │
│                                                                              │
│ /root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py:2781   │
│ in training_step                                                             │
│                                                                              │
│   2778 │   │   │   with amp.scale_loss(loss, self.optimizer) as scaled_loss: │
│   2779 │   │   │   │   scaled_loss.backward()                                │
│   2780 │   │   else:                                                         │
│ ❱ 2781 │   │   │   self.accelerator.backward(loss)                           │
│   2782 │   │                                                                 │
│   2783 │   │   return loss.detach() / self.args.gradient_accumulation_steps  │
│   2784                                                                       │
│                                                                              │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py:1964 │
│ in backward                                                                  │
│                                                                              │
│   1961 │   │   elif self.scaler is not None:                                 │
│   1962 │   │   │   self.scaler.scale(loss).backward(**kwargs)                │
│   1963 │   │   else:                                                         │
│ ❱ 1964 │   │   │   loss.backward(**kwargs)                                   │
│   1965 │                                                                     │
│   1966 │   def set_trigger(self):                                            │
│   1967 │   │   """                                                           │
│                                                                              │
│ /root/miniconda3/lib/python3.10/site-packages/torch/_tensor.py:522 in        │
│ backward                                                                     │
│                                                                              │
│    519 │   │   │   │   create_graph=create_graph,                            │
│    520 │   │   │   │   inputs=inputs,                                        │
│    521 │   │   │   )                                                         │
│ ❱  522 │   │   torch.autograd.backward(                                      │
│    523 │   │   │   self, gradient, retain_graph, create_graph, inputs=inputs │
│    524 │   │   )                                                             │
│    525                                                                       │
│                                                                              │
│ /root/miniconda3/lib/python3.10/site-packages/torch/autograd/__init__.py:266 │
│ in backward                                                                  │
│                                                                              │
│   263 │   # The reason we repeat the same comment below is that              │
│   264 │   # some Python versions print out the first line of a multi-line fu │
│   265 │   # calls in the traceback and some print out the last line          │
│ ❱ 266 │   Variable._execution_engine.run_backward(  # Calls into the C++ eng │
│   267 │   │   tensors,                                                       │
│   268 │   │   grad_tensors_,                                                 │
│   269 │   │   retain_graph,                                                  │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: element 0 of tensors does not require grad and does not have a 
grad_fn
  0%|                                                  | 0/3000 [11:35<?, ?it/s]

### Expected behavior / 期待表现

求解決方法

**Comment by zRzRzRzRzRzRzR** [comment]
#253 请在这里寻求微调社区帮助
