### ISSUE TITLE
最新版本的微调代码损失无法正常下降

### ISSUE THREAD

**Issue by xxg98** [THUDM/ChatGLM3#913]
### System Info / 系統信息

CUDA Version: 12.0
python：3.10
Transformers Version: 4.38.2
OS：Ubuntu
显卡：3090ti

### Who can help? / 谁可以帮助到您？

@Btlmd @zRzRzRzRzRzRzR 

1. 在使用最新的微调脚本```finetune_hf.py```配合p-tuning-2微调模型的自我认知时，损失从3.4左右开始缓慢下降，最后一直在1.0作用徘徊，增大max_steps到30000也于事无补，训练集90条，测试和验证集61条，数据集不太可能有问题，请参考https://github.com/We-IOT/chatglm3_6b_finetune/tree/main/data/self_cognition：
![image](https://github.com/THUDM/ChatGLM3/assets/98906194/500ffae8-fd8d-434a-bf22-464de4a4833a)

![image](https://github.com/THUDM/ChatGLM3/assets/98906194/c4b2dc60-803a-4da4-af2b-4b3d29284930)
2. 最新的脚本没有学习率这个非常重要的参数可以调整，我想可能5e-5有点小，但我无法尝试更大的学习率

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

微调命令如下：
python finetune_hf.py  ../../data/self/  /home/yanyonghao/work/projects/chatglm3-6b-2-28/chatglm3-6b  configs/ptuning_v2.yaml

### Expected behavior / 期待表现

损失降低到0.5左右

**Comment by zRzRzRzRzRzRzR** [comment]
#253 效果问题请在这里讨论
