### ISSUE TITLE
多卡微调遇到问题

### ISSUE THREAD

**Issue by CarpLoong** [THUDM/ChatGLM3#919]
### System Info / 系統信息

应该没有关系

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

采用这条指令进行多卡微调
OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=2  finetune_hf.py  data/fix/  /home/chatglm3/chatglm3_model/chatglm3-6b/chatglm3-6b  configs/lora.yaml  configs/ds_zero_2.json
最后在output中没有输出结果
中间报了一个configs/ds_zero_.json没有保存 这么一句话
configs/ds_zero_2.json The specified checkpoint sn(configs/ds_zero_2.json) has not been saved. Please search for the correct chkeckpoint in the model output directory
最后显示成功但是没有输出结果
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/9968fa47-6315-42a9-852e-980ef6af68c2)
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/c58cc917-9dfe-4c95-90ba-2ae929fd6ab3)

### Expected behavior / 期待表现

再次解答微调万物

**Comment by zRzRzRzRzRzRzR** [comment]
configs/ds_zero_2.json 你换成绝对路径吧，所有参数都换成绝对路径，然后ds配置肯定不会保存，这没用，不影响模型推理

**Comment by CarpLoong** [comment]
还是有几个不是很清楚的地方想问一下
1.没有输出的话那训练的东西训练到什么地方了啊，是跟原模型整合了吗
2.如果多卡方式就是没有输出checkpoint的话，此时推理的时候命令该怎么改，原来有checkpoint的时候用的命令是
CUDA_VISIBLE_DEVICES=1  /media/zr/Data/Code/ChatGLM3/venv/bin/python3 inference_hf.py output/checkpoint-3000/ --prompt
这个output/checkpoint-3000是不需要填吗
3.这个ds是deepspeed吧
4.我刚才试了一下将所有参数都改成绝对路径，还是会出现
/home/chatglm3/chatglm3_6b/finetune_demo/configs/ds_zero_2.json The specified checkpoint sn(/home/chatglm3/chatglm3_6b/finetune_demo/configs/ds_zero_2.json) has not been saved. Please search for the correct chkeckpoint in the model output directory
我不知道这个有没有影响
调整后的命令如下
OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=2  /home/chatglm3/chatglm3_6b/finetune_demo/finetune_hf.py  /home/chatglm3/chatglm3_6b/finetune_demo/data/fix/  /home/chatglm3/chatglm3_model/chatglm3-6b/chatglm3-6b /home/chatglm3/chatglm3_6b/finetune_demo/configs/lora.yaml  /home/chatglm3/chatglm3_6b/finetune_demo/configs/ds_zero_2.json


> configs/ds_zero_2.json 你换成绝对路径吧，所有参数都换成绝对路径，然后ds配置肯定不会保存，这没用，不影响模型推理

**Comment by CarpLoong** [comment]
@zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
1. 不是，会有保存点，代码中有，会输出到checkpoint

OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=2 /home/chatglm3/chatglm3_6b/finetune_demo/finetune_hf.py /home/chatglm3/chatglm3_6b/finetune_demo/data/fix/ /home/chatglm3/chatglm3_model/chatglm3-6b/chatglm3-6b /home/chatglm3/chatglm3_6b/finetune_demo/configs/lora.yaml /home/chatglm3/chatglm3_6b/finetune_demo/configs/ds_zero_2.json
这个是对的，ds是deepspeed

**Comment by rlynic** [comment]
同样的问题，多卡运行很快显示成功，但没有任何输出

**Comment by pysrc** [comment]
> 同样的问题，多卡运行很快显示成功，但没有任何输出

解决了吗，我也是单机多卡无输出

**Comment by Domices** [comment]
> > 是的，我遇到同样的问题，单卡微调没有问题，多卡微调是有问题的
> 
> 同样遇到这个问题，请问大佬解决了吗

我已经解决了这个问题，但我的服务器出了点故障，无法告诉你详细解决办法，但我还记得哪里出现了问题。单卡运行时，执行的是training，多卡时执行的是evaluate，你需要调试更改那部分代码。在我的服务器修好后，我或许可以告诉你详细解决办法

**Comment by KerryElwood** [comment]
可能和代码更新有关。

目前finetune.py 不再提供deepspeed参数输入。所以这句话

OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=2 finetune_hf.py data/fix/ /home/chatglm3/chatglm3_model/chatglm3-6b/chatglm3-6b configs/lora.yaml configs/ds_zero_2.json

中的configs/ds_zero_2.json，会被当做checkpoint路径输入，会导致跳过训练部分的代码



解决方式是直接修改lora.yaml，这个文件中有deepspeed的配置文件输入路径

**Comment by zhao-zilong** [comment]
@KerryElwood 
你能分享一下你修改过的文件吗?

**Comment by KerryElwood** [comment]
> @KerryElwood 你能分享一下你修改过的文件吗?

感觉分享比较麻烦，我再描述一下。

1.https://github.com/THUDM/ChatGLM3/blob/main/finetune_demo/configs/lora.yaml，查看该lora.yaml文件
2.取消38行注释，deepspeed: ds_zero_2.json，请注意ds_zero_2.json替换为你的json文件的绝对路径
3.执行命令OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=2 finetune_hf.py data/fix/ /home/chatglm3/chatglm3_model/chatglm3-6b/chatglm3-6b configs/lora.yaml
