### ISSUE TITLE
这边有特殊的prompt格式吗

### ISSUE THREAD

**Issue by kaedelin** [THUDM/ChatGLM3#92]
Chatgpt对于规范化的格式可能更好理解，ChatGLM3对于什么样的prompt比较好理解？
这边我试了将chatgpt的<role>角色类的prompt放到这里来，glm3输出还算可以，但是还是有些不尽如意，没有按照格式输出

**Comment by zRzRzRzRzRzRzR** [comment]
按照readme中的传入方式进行输入
传入的字段必须正确
角色类Prompt建议在系统提示修改
