### ISSUE TITLE
Setting eos_token is not supported, use the default one.

### ISSUE THREAD

**Issue by bbx429** [THUDM/ChatGLM3#928]
### System Info / 系統信息

windows10
Python 3.11.7

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

git clone https://github.com/THUDM/ChatGLM3
cd ChatGLM3
pip install -r requirements.txt
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

新建一个.py文件
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True, device='cuda')
model = model.eval()
response, history = model.chat(tokenizer, "你好", history=[])
print(response)

问题：
Setting eos_token is not supported, use the default one.
Setting pad_token is not supported, use the default one.
Setting unk_token is not supported, use the default one.
Loading checkpoint shards:   0%|                                                                 | 0/7 [00:00<?, ?it/s]

### Expected behavior / 期待表现

能按照正常运行

**Comment by zRzRzRzRzRzRzR** [comment]
忽略这个警告，不影响使用

**Comment by bbx429** [comment]
> 忽略此警告，不影响使用

Setting eos_token is not supported, use the default one.
Setting pad_token is not supported, use the default one.
Setting unk_token is not supported, use the default one.
Loading checkpoint shards:   0%|                                                                 | 0/7 [00:00<?, ?it/s]

控制台就输出了以上内容就结束了，和列子效果不一样
![1709692333(1)](https://github.com/THUDM/ChatGLM3/assets/25520342/1f420447-3ec9-4326-be0f-4edaf088fcbd)

**Comment by yangjingxun** [comment]
> > 忽略此警告，不影响使用
> 
> 不支持设置eos_token，请使用默认设置。不支持设置pad_token，请使用默认设置。不支持设置unk_token，请使用默认设置。加载检查点分片：0%| |0/7 [00：00<?, ?它/秒]
> 
> 控制台就输出了以上内容就结束了，和列子效果不一样 ![1709692333(1)](https://private-user-images.githubusercontent.com/25520342/310340898-1f420447-3ec9-4326-be0f-4edaf088fcbd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTUzMjEsIm5iZiI6MTcxMTcxNTAyMSwicGF0aCI6Ii8yNTUyMDM0Mi8zMTAzNDA4OTgtMWY0MjA0NDctM2VjOS00MzI2LWJlMGYtNGVkYWYwODhmY2JkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDEyMjM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NzU3MDY0YmVlMDEwY2UyODRiNmZjMjJmMjM0YTcwYWVlNDFiMTZlOTUxZGI3YzU4MmRkYTMwZWY2ZDJiMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ax0s2IxR3VfN7dD8sP6WiBkNeeIEGSPyc5HchGvhob0)

我也这样
I'm also.

**Comment by yangjingxun** [comment]
I'm also.
我也这样

 > 忽略此警告，不影响使用
> 
> 不支持设置eos_token，请使用默认设置。不支持设置pad_token，请使用默认设置。不支持设置unk_token，请使用默认设置。加载检查点分片：0%| |0/7 [00：00<?, ?它/秒]
> 
> 控制台就输出了以上内容就结束了，和列子效果不一样 ![1709692333(1)](https://private-user-images.githubusercontent.com/25520342/310340898-1f420447-3ec9-4326-be0f-4edaf088fcbd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTUzMjEsIm5iZiI6MTcxMTcxNTAyMSwicGF0aCI6Ii8yNTUyMDM0Mi8zMTAzNDA4OTgtMWY0MjA0NDctM2VjOS00MzI2LWJlMGYtNGVkYWYwODhmY2JkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDEyMjM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NzU3MDY0YmVlMDEwY2UyODRiNmZjMjJmMjM0YTcwYWVlNDFiMTZlOTUxZGI3YzU4MmRkYTMwZWY2ZDJiMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ax0s2IxR3VfN7dD8sP6WiBkNeeIEGSPyc5HchGvhob0)

**Comment by magicnight** [comment]
> I'm also. 我也这样
> 
> > 忽略此警告，不影响使用
> > 不支持设置eos_token，请使用默认设置。不支持设置pad_token，请使用默认设置。不支持设置unk_token，请使用默认设置。加载检查点分片：0%| |0/7 [00：00<?, ?它/秒]
> > 控制台就输出了以上内容就结束了，和列子效果不一样 ![1709692333(1)](https://private-user-images.githubusercontent.com/25520342/310340898-1f420447-3ec9-4326-be0f-4edaf088fcbd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTUzMjEsIm5iZiI6MTcxMTcxNTAyMSwicGF0aCI6Ii8yNTUyMDM0Mi8zMTAzNDA4OTgtMWY0MjA0NDctM2VjOS00MzI2LWJlMGYtNGVkYWYwODhmY2JkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDEyMjM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NzU3MDY0YmVlMDEwY2UyODRiNmZjMjJmMjM0YTcwYWVlNDFiMTZlOTUxZGI3YzU4MmRkYTMwZWY2ZDJiMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ax0s2IxR3VfN7dD8sP6WiBkNeeIEGSPyc5HchGvhob0)

模型没有加载到内存/显存。你是不是没有把模型下载到本地并且指定路径。这个默认方法会去huggingface下载模型，中国是不是无法访问？

**Comment by zRzRzRzRzRzRzR** [comment]
换成绝对路径

**Comment by wangzy21** [comment]
我也是这个问题，虽然不影响使用，但是还是想搞明白为什么

**Comment by lmw0320** [comment]
为啥我会报错呢？提示：AttributeError: 'GenerationConfig' object has no attribute '_eos_token_tensor'
我的transformers == 4.43.2， pytorch==2.2.2+cu118
