### ISSUE TITLE
模型chatglm3-6b，2个RTX 3090显卡仅能支持20个并发，但是显卡利用率仅到30%左右，如何通过配置调整提高并发数

### ISSUE THREAD

**Issue by Andy1018** [THUDM/ChatGLM3#929]
### System Info / 系統信息

linux  centos 7.9
2块 RTX 3090 
chatglm3-6b

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

压测api接口，发送内容很简单 “你好，请自我介绍”，20个并发

### Expected behavior / 期待表现

通过修改配置文件，提高gpu利用率，提高并发数
<img width="492" alt="2" src="https://github.com/THUDM/ChatGLM3/assets/16043789/79e3589b-ec6e-49ac-9abc-6a4d3d5220ad">

**Comment by zRzRzRzRzRzRzR** [comment]
本demo中没有提到任何高并发解决方案，推荐使用vllm trt等方法自行研究加速方案
