### ISSUE TITLE
调用/tools_using_demo/openai_api_demo.py ,打断点无法走到定义的函数

### ISSUE THREAD

**Issue by Powerfulxxr** [THUDM/ChatGLM3#936]
### System Info / 系統信息

pydantic=1.10.13
python=3.10.11
model=chatglm3-6b
openai=1.7.2

### Who can help? / 谁可以帮助到您？

openai_api_demo模块

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

/tools_using_demo下opeai_api的demo复现function calling的功能

### Expected behavior / 期待表现

希望走通demo中的function  calling的功能

**Comment by Powerfulxxr** [comment]
openai=1.7.2

**Comment by zRzRzRzRzRzRzR** [comment]
为啥走不通？ 你要去api_server里打断点呀

**Comment by Powerfulxxr** [comment]
> 为啥走不通？ 你要去api_server里打断点呀

openai_api_demo.py这个会调用api_server里面的"/v1/chat/completions"这个方法吗?
client = OpenAI(
  base_url="http://10.120.100.98:8100/v1"（这个地址是我sit的地址）,
  api_key = "xxx"
)
我本地启动使用上面的client的配置执行openai_api_demo.py，是否这个原因
