### ISSUE TITLE
tools_using_demo模块下的openai_api_demo.py ,打断点无法走到查询天气的函数

### ISSUE THREAD

**Issue by Powerfulxxr** [THUDM/ChatGLM3#939]
### System Info / 系統信息

pydantic=1.10.13
python=3.10.11
model=chatglm3-6b
openai=1.7.2

### Who can help? / 谁可以帮助到您？

 tools_using_demo模块

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

client = OpenAI(
base_url="http://10.120.100.98:8100/v1", --这个地址是我sit的地址,
api_key = "xxx"
)

这是我client的配置

### Expected behavior / 期待表现

希望能走到调用查询天气的函数

**Comment by Powerfulxxr** [comment]
![微信图片_20240307181112](https://github.com/THUDM/ChatGLM3/assets/26157619/afdaf1e0-1191-4ed7-85e9-28e11ed668c6)
这是我使用的demo

**Comment by zRzRzRzRzRzRzR** [comment]
你在这里的openai demo本来就是不执行函数的，知识让你知道模型返回的是什么，关于执行函数的部分是要工程来完成的，所有demo都没有真正执行这个函数，如果你要执行，你也应该在langchain demo中，看langchain是怎么执行的

**Comment by Powerfulxxr** [comment]
> 你在这里的openai demo本来就是不执行函数的，知识让你知道模型返回的是什么，关于执行函数的部分是要工程来完成的，所有demo都没有真正执行这个函数，如果你要执行，你也应该在langchain demo中，看langchain是怎么执行的

问下在langchain demo中prompt = hub.pull("hwchase17/structured-chat-agent")是去哪里拿prompt模板

**Comment by Powerfulxxr** [comment]
> 你在这里的openai demo本来就是不执行函数的，知识让你知道模型返回的是什么，关于执行函数的部分是要工程来完成的，所有demo都没有真正执行这个函数，如果你要执行，你也应该在langchain demo中，看langchain是怎么执行的

问下在langchain demo中prompt = hub.pull("hwchase17/structured-chat-agent")貌似是去远程里拿prompt模板，由于我在公司内网无法连接外网，请问如何修改这段代码

**Comment by zRzRzRzRzRzRzR** [comment]
你可以pull下这个模板之后，直接用本地构造这个提示词，但就很长了，很繁琐，你可以print一下这个提示词的结构
