### ISSUE TITLE
chatglm3支持多用户同时对话吗

### ISSUE THREAD

**Issue by zhuyang2356** [THUDM/ChatGLM3#94]
支持多用户同时访问吗？比如每个用户有自己的上下文，不会互相污染。

**Comment by Btlmd** [comment]
每位用户的上下文是由推理系统来负责维护的，和模型本身无关。

目前 [综合 Demo](https://github.com/THUDM/ChatGLM3/blob/main/composite_demo/README.md) 已经实现了多个用户分别维护不同的对话上下文而不互相污染。但是当前的实现中，不同用户共享了相同的 ipython kernel，因此在综合 Demo 的实现中，不同用户的 Code Interpreter 环境变量将被共享。如果需要，您可以自行实现隔离的 Code Interpreter 环境。

**Comment by zhuyang2356** [comment]
Thx a lot, really helps.
