### ISSUE TITLE
无法正常进入webui的加载

### ISSUE THREAD

**Issue by chengdidididi** [THUDM/ChatGLM3#941]
### System Info / 系統信息

通过conda、依照webui文档指导和requirements.txt直接部署的环境，ipython和ipykernel通过conda安装，ipython版本为8.20.0，ipykernel版本为6.28.0。系统为win10家庭中文版22H2

### Who can help? / 谁可以帮助到您？

@abmfy

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我通过魔搭下载了chatglm3-6b的模型文件并通过修改windows系统变量将该模型路径导入MODEL_PATH变量中，操作方法完全依照官方文档，除conda虚拟环境命名不同外都完全一致，
```
conda activate chatglm3
streamlit run .\composite_demo\main.py
```
会出现以下内容
```

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.100:8501

Setting eos_token is not supported, use the default one.
Setting pad_token is not supported, use the default one.
Setting unk_token is not supported, use the default one.
```
此时webui显示
```
Running get_client().
```
但随后脚本直接自动关闭，并出现命令提示符
```
(chatglm3) PS E:\CHATGLM3\ChatGLM3-main>
```
此时webui会弹出窗口提示
```
Is Streamlit still running? If you accidentally stopped Streamlit, just restart it in your terminal:

 streamlit run yourscript.py
```
试过网上的一键包，出现的情况也完全一样，而且因为没有任何错误信息提示，所以也不知道到底是什么原因导致的webui无法运行

### Expected behavior / 期待表现

期望能运行web ui

**Comment by zRzRzRzRzRzRzR** [comment]
这个是streamlit的问题吧，你尝试降级懂啊1.30，今天重新运行了没有出现这个问题
