### ISSUE TITLE
怎么把模型转成gguf格式的模型，我想用lm studio去调用

### ISSUE THREAD

**Issue by yxl23** [THUDM/ChatGLM3#942]
### Feature request  / 功能建议

怎么把模型转成gguf格式的模型，我想用lm studio去调用

### Motivation / 动机

怎么把模型转成gguf格式的模型，我想用lm studio去调用

### Your contribution / 您的贡献

..

**Comment by zRzRzRzRzRzRzR** [comment]
我们没有提供这个方案，你可以参考一下其他的模型gguf量化方案，或者在model scope上寻找已经有人转换好的gguf（第三方模型）
