### ISSUE TITLE
/openai_api_demo /openai_api_request.py 中的function_chat()返回中没有实际要调用的函数

### ISSUE THREAD

**Issue by Powerfulxxr** [THUDM/ChatGLM3#945]
### System Info / 系統信息

from openai import OpenAI

base_url = "http://197.45.67.80.11:8000/v1/" --这个是我的ST服务站上提供的api地址
client = OpenAI(api_key="44444555", base_url=base_url)

def function_chat():
    messages = [{"role": "user", "content": "What's the weather like in San Francisco, Tokyo, and Paris?"}]
    tools = [
        {
            "type": "function",
            "function": {
                "name": "get_current_weather",
                "description": "Get the current weather in a given location",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "The city and state, e.g. San Francisco, CA",
                        },
                        "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                    },
                    "required": ["location"],
                },
            },
        }
    ]

    response = client.chat.completions.create(
        model="chatglm3-6b",
        messages=messages,
        tools=tools,
        tool_choice="auto",
    )
    if response:
        content = response.choices[0].message
        print(content)
    else:
        print("Error:", response.status_code)

### Who can help? / 谁可以帮助到您？

这是打印返回的，function_call 为None
ChatCompletionMessage(content='北京今天的天气是晴天。', role='assistant', function_call=None, tool_calls=None)

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [x] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

过程如上面代码

### Expected behavior / 期待表现

根据语义调用自定义函数

**Comment by zRzRzRzRzRzRzR** [comment]
用的是OpenAI接口的格式，你这个请求方式看起来没有问题，每次都这样吗，官方的例子也这样么
