### ISSUE TITLE
使用vLLM部署ChatGLM3 报错

### ISSUE THREAD

**Issue by Songjiadong** [THUDM/ChatGLM3#946]
### System Info / 系統信息

pyton version 3.10 
centos 8

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

启动vLLM命令
```py
 python -m vllm.entrypoints.openai.api_server     --model=/usr/local/models/THUDM/chatglm3-6b     --trust-remote-code     --served-model-name qwmiic     --host 127.0.0.1     --port 9999        --dtype=half
```
报错：hugging face 网络连不上` We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like THUDM/chatglm3-6b is not the path to a directory containing a file named tokenization_chatglm.py.`
于是我修改了config.json的` "_name_or_path": "/usr/local/models/THUDM/chatglm3-6b",`属性，再运行依然报错？
我没有找到配置修改的入口，我该如何解决？

### Expected behavior / 期待表现

实现正常vLLM运行

**Comment by zRzRzRzRzRzRzR** [comment]
你直接修改成绝对位置，这是vllm你没配置模型绝对路径的问题

如果还不行，降级transformers到4.37.2

**Comment by Songjiadong** [comment]
@zRzRzRzRzRzRzR  你好，我配置的是绝对路径`/usr/local/models/THUDM/chatglm3-6b`,然后在咱们微信群里有个人说将tokenizer_config.json文件的auto_map部分进行如下修改，就能成功，我试了一下，缺失可以，但是我不是太明白为什么这么改写,这个`tokenization_chatglm.ChatGLMTokenizer`代表的是什么意思？是否有固定选项，以及说明？
```json
"auto_map": {
    "AutoTokenizer": [
      "tokenization_chatglm.ChatGLMTokenizer",
      
      null
    ]
  },
```

**Comment by zRzRzRzRzRzRzR** [comment]
或许是因为transformer版本升级以后 ChatGLMTokenizer不被识别 tokenization-chatglm.ChatGLMTokenizer才行？

**Comment by Andy1018** [comment]
问下vllm部署启动成功后支持api访问模式吗？为什么我访问接口报404
INFO:     172.26.0.2:34438 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found

**Comment by Songjiadong** [comment]
@Andy1018 支持啊

**Comment by Andy1018** [comment]
@Songjiadong 嗯 找到问题了需要指定--served-model-name
