### ISSUE TITLE
自定义函数如何通过api的方式供其他应用调用 (通过api_server.py方式启动，如何能调用到自定义的function )

### ISSUE THREAD

**Issue by Andy1018** [THUDM/ChatGLM3#947]
### System Info / 系統信息

自定义函数如何通过api的方式供其他应用调用 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

通过api_server.py方式启动，如何能调用到自定义的function 

### Expected behavior / 期待表现

通过api_server.py方式启动，如何能调用到自定义的function

**Comment by zRzRzRzRzRzRzR** [comment]
openai是怎么做的，就怎么做，需要通过传参来指定你的function，返回也只知识返回对应function参数而不是直接执行
