### ISSUE TITLE
composite_demo/client.py 怎么修改支持多显卡？  参照web_demo2.py修改后对话报错

### ISSUE THREAD

**Issue by lhtpluto** [THUDM/ChatGLM3#95]
composite_demo/client.py 如何支持多显卡？

web_demo2.py是支持多显卡的，用这个的多显卡方式，替换到client.py中

composite_demo/client.py

#MODEL_PATH = os.environ.get('MODEL_PATH', 'THUDM/chatglm3-6b')

model_path = "THUDM/chatglm3-6b"

@st.cache_resource
def get_model():
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    #model = AutoModel.from_pretrained(model_path, trust_remote_code=True).cuda()
    # 多显卡支持,使用下面两行代替上面一行,将num_gpus改为你实际的显卡数量
    from utils import load_model_on_gpus
    model = load_model_on_gpus("THUDM/chatglm3-6b", num_gpus=2)
    model = model.eval()
    return tokenizer, model

tokenizer, model = get_model()

@st.cache_resource
def get_client() -> Client:
    #client = HFClient(MODEL_PATH)
    client = model.eval()
    return client

运行后，进入首页正常，但对话后报错如下

2023-10-31 22:07:19.130 Uncaught app exception
Traceback (most recent call last):
  File "/root/anaconda3/envs/chatglm3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/ai/ChatGLM3/main.py", line 52, in <module>
    demo_tool.main(top_p, temperature, prompt_text)
  File "/home/ai/ChatGLM3/demo_tool.py", line 111, in main
    for response in client.generate_stream(
  File "/root/anaconda3/envs/chatglm3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'generate_stream'

**Comment by Btlmd** [comment]
不应将 `client` 改为 `model`
可以参考 #70 的解决方案

**Comment by lhtpluto** [comment]
> 不应将 `client` 改为 `model` 可以参考 #70 的解决方案

万分感谢  按照  https://github.com/THUDM/ChatGLM3/issues/70  的方法修改，已经运行成功
