### ISSUE TITLE
function call和正常的询问模式可以同时使用吗？ 比如启动api_server.py 同时支持普通问答式也支持function call模式，请提供代码例子，谢谢

### ISSUE THREAD

**Issue by Andy1018** [THUDM/ChatGLM3#950]
### System Info / 系統信息

linux

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

function call和正常的询问模式可以同时使用吗？ 比如启动api_server.py 同时支持普通问答式也支持function call模式，请提供代码例子，谢谢

### Expected behavior / 期待表现

function call和正常的询问模式可以同时使用吗？ 比如启动api_server.py 同时支持普通问答式也支持function call模式，请提供代码例子，谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
不能，这个是完全对齐openai的
