### ISSUE TITLE
128K GLM3-6B模型推理出现自问自答，答非所问，停不下来的情况

### ISSUE THREAD

**Issue by MOLIZHU2023** [THUDM/ChatGLM3#952]
### System Info / 系統信息

128K GLM3-6B模型推理出现自问自答，答非所问，停不下来的情况

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

官方本地搭建推理环境，128K出现不停止、自问自答现象

### Expected behavior / 期待表现

希望能够得到解答和解决，谢谢！

**Comment by zRzRzRzRzRzRzR** [comment]
加强惩罚系数，在 composite demo中有这个参数
