### ISSUE TITLE
mpi4py>=3.1.5的意义是什么？ 3.1.4可以吗？

### ISSUE THREAD

**Issue by Micla-SHL** [THUDM/ChatGLM3#953]
我装这个包一直失败。看别人安装是很简单的，相关错误也有纠错方法。我最终看到别人使用conda安装能规避所有错误，我一看版本是3.1.4的。我的机器可能装不上3.1.5的mpi4py,这对微调有很大影响吗？

conda环境：python 3.11  .操作系统：22.04

**Comment by zRzRzRzRzRzRzR** [comment]
不影响吧，这个是多卡微调用的
