### ISSUE TITLE
voilation of protocol

### ISSUE THREAD

**Issue by saivivekseeram1** [THUDM/ChatGLM3#954]
### System Info / 系統信息

====Exporting IR=====
C:\Users\Local_Admin\chatglm3.openvino\openvino_env\Lib\site-packages\transformers\modeling_utils.py:4193: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
C:\Users\Local_Admin\chatglm3.openvino\convert.py:143: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if (attention_mask is not None and not attention_mask.all()) or (past_key_values and seq_length != 1):
C:\Users\Local_Admin\chatglm3.openvino\convert.py:154: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if past_length:
C:\Users\Local_Admin\chatglm3.openvino\openvino_env\Lib\site-packages\torch\jit\_trace.py:165: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:494.)
  if a.grad is not None:
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error [WinError 10053] An established connection was aborted by the software in your host machine>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error [WinError 10053] An established connection was aborted by the software in your host machine>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
====Exporting tokenizer=====
tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 1.41k/1.41k [00:00<00:00, 88.5kB/s]
tokenization_chatglm.py: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 13.0k/13.0k [00:00<00:00, 11.2MB/s]
A new version of the following files was downloaded from https://huggingface.co/THUDM/chatglm3-6b:
- tokenization_chatglm.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
tokenizer.model: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.02M/1.02M [00:00<00:00, 21.9MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 3.00/3.00 [00:00<00:00, 283B/s]
WARNING:transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm:Setting eos_token is not supported, use the default one.
WARNING:transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm:Setting pad_token is not supported, use the default one.
WARNING:transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm:Setting unk_token is not supported, use the default one. 
(openvino_env) PS C:\Users\Local_Admin\chatglm3.openvino> python3 chat.py --model_path C:\Users\Local_Admin\chatglm3.openvino/chatglm3-6b --max_sequence_length 4096 --device CPU             
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
(openvino_env) PS C:\Users\Local_Admin\chatglm3.openvino> python chat.py --model_path C:\Users\Local_Admin\chatglm3.openvino/chatglm3-6b --max_sequence_length 4096 --device CPU 
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
Setting eos_token is not supported, use the default one.
Setting pad_token is not supported, use the default one.
Setting unk_token is not supported, use the default one.
====Compiling model====
The argument `trust_remote_code` is to be used along with export=True. It will be ignored.
Compiling the model to CPU ...
====Starting conversation====
用户: hi
ChatGLM3-6B-OpenVINO: Traceback (most recent call last):
  File "C:\Users\Local_Admin\chatglm3.openvino\chat.py", line 153, in <module>
    for new_text in streamer:
  File "C:\Users\Local_Admin\chatglm3.openvino\openvino_env\Lib\site-packages\transformers\generation\streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Local_Admin\conda\Lib\queue.py", line 179, in get
    raise Empty
_queue.Empty

### Who can help? / 谁可以帮助到您？

====Exporting IR=====
C:\Users\Local_Admin\chatglm3.openvino\openvino_env\Lib\site-packages\transformers\modeling_utils.py:4193: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
C:\Users\Local_Admin\chatglm3.openvino\convert.py:143: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if (attention_mask is not None and not attention_mask.all()) or (past_key_values and seq_length != 1):
C:\Users\Local_Admin\chatglm3.openvino\convert.py:154: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if past_length:
C:\Users\Local_Admin\chatglm3.openvino\openvino_env\Lib\site-packages\torch\jit\_trace.py:165: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:494.)
  if a.grad is not None:
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error [WinError 10053] An established connection was aborted by the software in your host machine>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error [WinError 10053] An established connection was aborted by the software in your host machine>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
====Exporting tokenizer=====
tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 1.41k/1.41k [00:00<00:00, 88.5kB/s]
tokenization_chatglm.py: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 13.0k/13.0k [00:00<00:00, 11.2MB/s]
A new version of the following files was downloaded from https://huggingface.co/THUDM/chatglm3-6b:
- tokenization_chatglm.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
tokenizer.model: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.02M/1.02M [00:00<00:00, 21.9MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 3.00/3.00 [00:00<00:00, 283B/s]
WARNING:transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm:Setting eos_token is not supported, use the default one.
WARNING:transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm:Setting pad_token is not supported, use the default one.
WARNING:transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm:Setting unk_token is not supported, use the default one. 
(openvino_env) PS C:\Users\Local_Admin\chatglm3.openvino> python3 chat.py --model_path C:\Users\Local_Admin\chatglm3.openvino/chatglm3-6b --max_sequence_length 4096 --device CPU             
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
(openvino_env) PS C:\Users\Local_Admin\chatglm3.openvino> python chat.py --model_path C:\Users\Local_Admin\chatglm3.openvino/chatglm3-6b --max_sequence_length 4096 --device CPU 
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
Setting eos_token is not supported, use the default one.
Setting pad_token is not supported, use the default one.
Setting unk_token is not supported, use the default one.
====Compiling model====
The argument `trust_remote_code` is to be used along with export=True. It will be ignored.
Compiling the model to CPU ...
====Starting conversation====
用户: hi
ChatGLM3-6B-OpenVINO: Traceback (most recent call last):
  File "C:\Users\Local_Admin\chatglm3.openvino\chat.py", line 153, in <module>
    for new_text in streamer:
  File "C:\Users\Local_Admin\chatglm3.openvino\openvino_env\Lib\site-packages\transformers\generation\streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Local_Admin\conda\Lib\queue.py", line 179, in get
    raise Empty
_queue.Empty

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

====Exporting IR=====
C:\Users\Local_Admin\chatglm3.openvino\openvino_env\Lib\site-packages\transformers\modeling_utils.py:4193: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
C:\Users\Local_Admin\chatglm3.openvino\convert.py:143: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if (attention_mask is not None and not attention_mask.all()) or (past_key_values and seq_length != 1):
C:\Users\Local_Admin\chatglm3.openvino\convert.py:154: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if past_length:
C:\Users\Local_Admin\chatglm3.openvino\openvino_env\Lib\site-packages\torch\jit\_trace.py:165: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:494.)
  if a.grad is not None:
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error [WinError 10053] An established connection was aborted by the software in your host machine>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error [WinError 10053] An established connection was aborted by the software in your host machine>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
====Exporting tokenizer=====
tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 1.41k/1.41k [00:00<00:00, 88.5kB/s]
tokenization_chatglm.py: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 13.0k/13.0k [00:00<00:00, 11.2MB/s]
A new version of the following files was downloaded from https://huggingface.co/THUDM/chatglm3-6b:
- tokenization_chatglm.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
tokenizer.model: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.02M/1.02M [00:00<00:00, 21.9MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 3.00/3.00 [00:00<00:00, 283B/s]
WARNING:transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm:Setting eos_token is not supported, use the default one.
WARNING:transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm:Setting pad_token is not supported, use the default one.
WARNING:transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm:Setting unk_token is not supported, use the default one. 
(openvino_env) PS C:\Users\Local_Admin\chatglm3.openvino> python3 chat.py --model_path C:\Users\Local_Admin\chatglm3.openvino/chatglm3-6b --max_sequence_length 4096 --device CPU             
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
(openvino_env) PS C:\Users\Local_Admin\chatglm3.openvino> python chat.py --model_path C:\Users\Local_Admin\chatglm3.openvino/chatglm3-6b --max_sequence_length 4096 --device CPU 
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
Setting eos_token is not supported, use the default one.
Setting pad_token is not supported, use the default one.
Setting unk_token is not supported, use the default one.
====Compiling model====
The argument `trust_remote_code` is to be used along with export=True. It will be ignored.
Compiling the model to CPU ...
====Starting conversation====
用户: hi
ChatGLM3-6B-OpenVINO: Traceback (most recent call last):
  File "C:\Users\Local_Admin\chatglm3.openvino\chat.py", line 153, in <module>
    for new_text in streamer:
  File "C:\Users\Local_Admin\chatglm3.openvino\openvino_env\Lib\site-packages\transformers\generation\streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Local_Admin\conda\Lib\queue.py", line 179, in get
    raise Empty
_queue.Empty

### Expected behavior / 期待表现

====Exporting IR=====
C:\Users\Local_Admin\chatglm3.openvino\openvino_env\Lib\site-packages\transformers\modeling_utils.py:4193: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
C:\Users\Local_Admin\chatglm3.openvino\convert.py:143: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if (attention_mask is not None and not attention_mask.all()) or (past_key_values and seq_length != 1):
C:\Users\Local_Admin\chatglm3.openvino\convert.py:154: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if past_length:
C:\Users\Local_Admin\chatglm3.openvino\openvino_env\Lib\site-packages\torch\jit\_trace.py:165: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:494.)
  if a.grad is not None:
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error [WinError 10053] An established connection was aborted by the software in your host machine>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
WARNING:root:Failed to send event with the following error: <urlopen error [WinError 10053] An established connection was aborted by the software in your host machine>
WARNING:root:Failed to send event with the following error: <urlopen error EOF occurred in violation of protocol (_ssl.c:2427)>
====Exporting tokenizer=====
tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 1.41k/1.41k [00:00<00:00, 88.5kB/s]
tokenization_chatglm.py: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 13.0k/13.0k [00:00<00:00, 11.2MB/s]
A new version of the following files was downloaded from https://huggingface.co/THUDM/chatglm3-6b:
- tokenization_chatglm.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
tokenizer.model: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.02M/1.02M [00:00<00:00, 21.9MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 3.00/3.00 [00:00<00:00, 283B/s]
WARNING:transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm:Setting eos_token is not supported, use the default one.
WARNING:transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm:Setting pad_token is not supported, use the default one.
WARNING:transformers_modules.THUDM.chatglm3-6b.9addbe01105ca1939dd60a0e5866a1812be9daea.tokenization_chatglm:Setting unk_token is not supported, use the default one. 
(openvino_env) PS C:\Users\Local_Admin\chatglm3.openvino> python3 chat.py --model_path C:\Users\Local_Admin\chatglm3.openvino/chatglm3-6b --max_sequence_length 4096 --device CPU             
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
(openvino_env) PS C:\Users\Local_Admin\chatglm3.openvino> python chat.py --model_path C:\Users\Local_Admin\chatglm3.openvino/chatglm3-6b --max_sequence_length 4096 --device CPU 
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
Setting eos_token is not supported, use the default one.
Setting pad_token is not supported, use the default one.
Setting unk_token is not supported, use the default one.
====Compiling model====
The argument `trust_remote_code` is to be used along with export=True. It will be ignored.
Compiling the model to CPU ...
====Starting conversation====
用户: hi
ChatGLM3-6B-OpenVINO: Traceback (most recent call last):
  File "C:\Users\Local_Admin\chatglm3.openvino\chat.py", line 153, in <module>
    for new_text in streamer:
  File "C:\Users\Local_Admin\chatglm3.openvino\openvino_env\Lib\site-packages\transformers\generation\streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Local_Admin\conda\Lib\queue.py", line 179, in get
    raise Empty
_queue.Empty

**Comment by zRzRzRzRzRzRzR** [comment]
有一种可能是您的cpu 比较古老，first latency超过了我们预设的timeout时间，这需要你提供一下硬件情况
