### ISSUE TITLE
如何自定义一个工具，并注册到api_server.py中，供api调用，可否提供个例子？

### ISSUE THREAD

**Issue by Andy1018** [THUDM/ChatGLM3#955]
如何自定义一个工具，并注册到api_server.py中，供api调用，可否提供个例子？

**Comment by zRzRzRzRzRzRzR** [comment]
本来就不是集成到api_server 的呀，api_server是模仿opena借口的，自定义工具要传进来，然后模型返回选择的参数，不能直接执行工具
