### ISSUE TITLE
LoRA微调后推理报错

### ISSUE THREAD

**Issue by LiangYong1216** [THUDM/ChatGLM3#958]
### System Info / 系統信息

ubuntu20.04
torch：2.1
cuda: 12.1
transformer:  4.38.2  

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.使用LoRA进行微调后推理出现了问题
训练完包括以下文件：
![image](https://github.com/THUDM/ChatGLM3/assets/66230782/1c6f66fe-b1be-4a1a-9c22-168524c9e970)
错误输出如下：
root@autodl-container-d05b4ca599-3483943c:~/autodl-tmp/chatGML# CUDA_VISIBLE_DEVICES=1 python3 finetune_demo/inference_hf.py output/checkpoint-4800/ --prompt "类型#裙*版型#显瘦*材质#网 纱*风格#性感*裙型#百褶*裙下摆#压褶*裙长#连衣裙*裙衣门襟#拉链*裙衣门襟#套头*裙款式#拼接*裙款式#拉链*裙款式#木耳边*裙款式#抽褶*裙款式#不规则"
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 15.19it/s]
Setting eos_token is not supported, use the default one.
Setting pad_token is not supported, use the default one.
Setting unk_token is not supported, use the default one.
Setting eos_token is not supported, use the default one.
Setting pad_token is not supported, use the default one.
Setting unk_token is not supported, use the default one.
Traceback (most recent call last):

  File "/root/autodl-tmp/chatGML/finetune_demo/inference_hf.py", line 58, in <module>
    app()

  File "/root/autodl-tmp/chatGML/finetune_demo/inference_hf.py", line 53, in main
    response, _ = model.chat(tokenizer, prompt)

  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)

  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1042, in chat
    outputs = self.generate(**inputs, **gen_kwargs, eos_token_id=eos_token_id)

  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)

  File "/root/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 1592, in generate
    return self.sample(

  File "/root/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2696, in sample
    outputs = self(

  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)

  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)

  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 941, in forward
    transformer_outputs = self.transformer(

  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)

  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 811, in forward
    inputs_embeds = self.embedding(input_ids)

  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)

  File "/root/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 724, in forward
    words_embeddings = self.word_embeddings(input_ids)

  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)

  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(

  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/functional.py", line 2233, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)

IndexError: index out of range in self

root@autodl-container-d05b4ca599-3483943c:~/autodl-tmp/chatGML# 
这是什么原因啊？要如何修改代码，使用的inference_hf.py文件，
命令：CUDA_VISIBLE_DEVICES=1 python3 finetune_demo/inference_hf.py output/checkpoint-4800/ --prompt "类型#裙*版型#显瘦*材质#网 纱*风格#性感*裙型#百褶*裙下摆#压褶*裙长#连衣裙*裙衣门襟#拉链*裙衣门襟#套头*裙款式#拼接*裙款式#拉链*裙款式#木耳边*裙款式#抽褶*裙款式#不规则"

### Expected behavior / 期待表现

期待修复

**Comment by LiangYong1216** [comment]
使用原始的权重就可以推理，但是lora微调后的就不行，依赖应该没问题吧

**Comment by LiangYong1216** [comment]
> 使用原始的权重就可以推理，但是lora微调后的就不行，依赖应该没问题吧

**Comment by adoptedirelia** [comment]
我也是这个问题，依赖应该是没问题的

**Comment by zRzRzRzRzRzRzR** [comment]
peft 0.7.1 transformers 4.37.2的状态调一下也会吗

**Comment by adoptedirelia** [comment]
> peft 0.7.1 transformers 4.37.2的状态调一下也会吗

可以了，peft版本的问题
peft==0.7.1
transformers==4.38.1
可以推理

**Comment by LiangYong1216** [comment]
修改了peft==0.7.1
transformers==4.38.1
但是出现了新的问题：
![image](https://github.com/THUDM/ChatGLM3/assets/66230782/81d81a4a-4b54-4d8c-96fb-43c929c7c4ab)

**Comment by adoptedirelia** [comment]
> 修改了peft==0.7.1 transformers==4.38.1 但是出现了新的问题： ![image](https://private-user-images.githubusercontent.com/66230782/311938574-81d81a4a-4b54-4d8c-96fb-43c929c7c4ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTg0OTMsIm5iZiI6MTcxMDIxODE5MywicGF0aCI6Ii82NjIzMDc4Mi8zMTE5Mzg1NzQtODFkODFhNGEtNGI1NC00ZDhjLTk2ZmItNDNjOTI5YzdjNGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA0MzYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzOTIyYzE4NDM4N2Q2ZDdlZTM0MzI1ZTk1N2ZlZmU2MDBlNjIyNmQyNDI5NDFjZGQyN2MyOGE4ZmRmYzI0YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Anc9kIANMxgy3zqLYzACH6BYWAouAgwrSslfujaE2KQ)

你这个需要重新训练lora再推理

**Comment by LiangYong1216** [comment]
好的哥，我重新训练下看看，非常感谢，卡了好久了

**Comment by LiangYong1216** [comment]
> > 修改了peft==0.7.1 transformers==4.38.1 但是出现了新的问题： ![image](https://private-user-images.githubusercontent.com/66230782/311938574-81d81a4a-4b54-4d8c-96fb-43c929c7c4ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTg0OTMsIm5iZiI6MTcxMDIxODE5MywicGF0aCI6Ii82NjIzMDc4Mi8zMTE5Mzg1NzQtODFkODFhNGEtNGI1NC00ZDhjLTk2ZmItNDNjOTI5YzdjNGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA0MzYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzOTIyYzE4NDM4N2Q2ZDdlZTM0MzI1ZTk1N2ZlZmU2MDBlNjIyNmQyNDI5NDFjZGQyN2MyOGE4ZmRmYzI0YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Anc9kIANMxgy3zqLYzACH6BYWAouAgwrSslfujaE2KQ)
> 
> 你这个需要重新训练lora再推理

![image](https://github.com/THUDM/ChatGLM3/assets/66230782/b70cd149-1cf0-4202-b872-50cdc5ccabd9)
哥，又出问题了

**Comment by adoptedirelia** [comment]
> ![image](https://private-user-images.githubusercontent.com/66230782/311963339-b70cd149-1cf0-4202-b872-50cdc5ccabd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjQ2OTYsIm5iZiI6MTcxMDIyNDM5NiwicGF0aCI6Ii82NjIzMDc4Mi8zMTE5NjMzMzktYjcwY2QxNDktMWNmMC00MjAyLWI4NzItNTBjZGM1Y2NhYmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA2MTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MDI0ZTFiMTI0NTM4M2VkOGJiYWM3M2VmOGNiOGVkZTg5OWU0ZGRmMzExMDc0NmRkNGFmYzIwNDJmYmI5ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aMFOzxzjwzdwWpRtKgP8Pp6j3YPcOF8yITrimUt0jZM) 哥，又出问题了

你这个我也没遇到过。。我也不会搞，要不试试重新配下环境

**Comment by LiangYong1216** [comment]
> > ![image](https://private-user-images.githubusercontent.com/66230782/311963339-b70cd149-1cf0-4202-b872-50cdc5ccabd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjQ2OTYsIm5iZiI6MTcxMDIyNDM5NiwicGF0aCI6Ii82NjIzMDc4Mi8zMTE5NjMzMzktYjcwY2QxNDktMWNmMC00MjAyLWI4NzItNTBjZGM1Y2NhYmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA2MTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MDI0ZTFiMTI0NTM4M2VkOGJiYWM3M2VmOGNiOGVkZTg5OWU0ZGRmMzExMDc0NmRkNGFmYzIwNDJmYmI5ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aMFOzxzjwzdwWpRtKgP8Pp6j3YPcOF8yITrimUt0jZM) 哥，又出问题了
> 
> 你这个我也没遇到过。。我也不会搞，要不试试重新配下环境
哈哈，好了好了，只有一张卡，但是哪个命令里面设置的CUDA_VISIBLE_DEVICES=1，好像就加载到CPU上去了，但是torch的cpu运算不支持，所以改到gpu0就ok了

**Comment by AHPUymhd** [comment]
> > peft 0.7.1 transformers 4.37.2的状态调一下也会吗
> 
> 可以了，peft版本的问题 peft==0.7.1 transformers==4.38.1 可以推理

还不行的话得先去重新微调然后再推理，大概率就可以了

**Comment by koukoulala** [comment]
我也是完全相同的错误，微调完后没法推理成功，也是index out of range in self的错误。perft版本如果降到0.7.1的话，就会报其他的错。

**Comment by dqy1111** [comment]
> 我也是完全相同的错误，微调完后没法推理成功，也是index out of range in self的错误。perft版本如果降到0.7.1的话，就会报其他的错“ LoraConfig.**init**() got an unexpected keyword argument 'layer_replication'”。

一样哥们，找到解决方案没。解决一个问题还有下一个问题，我要崩溃了

**Comment by xiahuadong1981** [comment]
通过下列代码，关闭异步和gpu
import os
# 关闭异步
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
# 关闭gpu
os.environ["CUDA_VISIBLE_DEVICES"] = ""
后面遇到错误
File "C:\Users\xiahuadong\.conda\envs\chatglm3-6b\lib\site-packages\torch\nn\functional.py", line 2237, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
