### ISSUE TITLE
base模型没有对话能力，chat模型有

### ISSUE THREAD

**Issue by sevenandseven** [THUDM/ChatGLM3#960]
base模型没有对话能力，chat模型有

_Originally posted by @zRzRzRzRzRzRzR in https://github.com/THUDM/ChatGLM3/issues/616#issuecomment-1860077633_

**Comment by sevenandseven** [comment]
你好，请问一下我想微调base模型认识这个领域的相关知识，该怎么准备数据集？
微调的base模型怎么转换为chat模型？

**Comment by zRzRzRzRzRzRzR** [comment]
base模型当然没有对话能力了，chat模型才有啊，所以叫做 chat（对话模型）
微调base 还得做chat对其，这里没有提供对其代码
