### ISSUE TITLE
抱歉！ 我不是很懂哈. 我想要的就是在base模型上做增量预训练，然后在预训练好的模型上用对话格式的数据做指令微调。   这里增量预训练我准备了一些领域纯文本的数据，问下针对这种纯文本的预训练脚本能够提供下？   或者说chatglm3预训练的格式是输入输出格式的吗?

### ISSUE THREAD

**Issue by sevenandseven** [THUDM/ChatGLM3#961]
抱歉！ 我不是很懂哈. 我想要的就是在base模型上做增量预训练，然后在预训练好的模型上用对话格式的数据做指令微调。   这里增量预训练我准备了一些领域纯文本的数据，问下针对这种纯文本的预训练脚本能够提供下？   或者说chatglm3预训练的格式是输入输出格式的吗?

_Originally posted by @childlong in https://github.com/THUDM/ChatGLM3/issues/566#issuecomment-1848985446_

**Comment by sevenandseven** [comment]
你好，我跟你的需求差不多，想要在base模型上做微调，在转换为chat模型？

微调base模型的数据该怎么准备，base模型怎么和chat模型做转换。

**Comment by zRzRzRzRzRzRzR** [comment]
我们没有提供预训练的代码哈
