### ISSUE TITLE
A40机器运行网页示例程序遇到 突然GPU无法使用，问GLM，return reeor（cpu不支持fp16数据，原因就是无法调用GPU了）这情况很突然，我无法理解

### ISSUE THREAD

**Issue by Micla-SHL** [THUDM/ChatGLM3#964]
我按照readme走，用streamlit run web_demo_streamlit.py 一直在问问题，这周有个意外：一直出现这个问题，
`                    ^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1. 
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions`

今天早上出现这问题，我测试是环境内 torch无法调GPU了，nvidia-smi,nvcc -V 这些命令是正常反馈的。我的解决办法是重新安装显卡驱动。but  现在问题是当这问题再出现的时候，我测试环境内 torch是能正常调用cuda的，我将`streamlit run web_demo_streamlit.py`命令中断然后再开启，问题就消失了。我很疑惑是为甚么？我程序在运行，提问问着问着，它告诉我上述错误：无法调用GPU。但是我重启命令又是能行的，这会是什么原因？  我以前没有遇到过这种情况，我以前遇到的是死机重启，我再装一边显卡驱动就能解决了。有人遇到我的情况过吗？

**Comment by zRzRzRzRzRzRzR** [comment]
稳定复现吗？

**Comment by zRzRzRzRzRzRzR** [comment]
这个有点罕见，之前有，但是也都是随机事件

**Comment by Micla-SHL** [comment]
谢谢，我想这问题确实存在，但不值得现在去深究。等我再出现这问题并不耐烦再来考虑怎么处理

________________________________
发件人: zR ***@***.***>
发送时间: 2024年3月12日 11:15
收件人: THUDM/ChatGLM3 ***@***.***>
抄送: Micla-SHL ***@***.***>; Author ***@***.***>
主题: Re: [THUDM/ChatGLM3] A40机器运行网页示例程序遇到 突然GPU无法使用，问GLM，return reeor（cpu不支持fp16数据，原因就是无法调用GPU了）这情况很突然，我无法理解 (Issue #964)


这个有点罕见，之前有，但是也都是随机事件

―

**Comment by Micla-SHL** [comment]
我能复现出来，我也是linux的机子，20.04  显卡驱动走A40当前最新的。这个复现是被动的，比如昨天又死掉了。我跟第3次一样的操作
。kill掉程序再运行，又可以了

________________________________
发件人: zR ***@***.***>
发送时间: 2024年3月12日 15:20
收件人: THUDM/ChatGLM3 ***@***.***>
抄送: Micla-SHL ***@***.***>; Author ***@***.***>
主题: Re: [THUDM/ChatGLM3] A40机器运行网页示例程序遇到 突然GPU无法使用，问GLM，return reeor（cpu不支持fp16数据，原因就是无法调用GPU了）这情况很突然，我无法理解 (Issue #964)


我们也复现不出来，我们都是Linux的机子没有出现过

―

**Comment by Micla-SHL** [comment]
我提供了一张报错内容，希望能有点思路
________________________________
发件人: zR ***@***.***>
发送时间: 2024年3月12日 15:20
收件人: THUDM/ChatGLM3 ***@***.***>
抄送: Micla-SHL ***@***.***>; Author ***@***.***>
主题: Re: [THUDM/ChatGLM3] A40机器运行网页示例程序遇到 突然GPU无法使用，问GLM，return reeor（cpu不支持fp16数据，原因就是无法调用GPU了）这情况很突然，我无法理解 (Issue #964)


我们也复现不出来，我们都是Linux的机子没有出现过

―

**Comment by Micla-SHL** [comment]
我现在的一个想法：
streamlit run web_demo_streamlit.py 这程序在一直运行，然后突然的显示前文提到的报错内容，我感觉就是可以理解为model在加载中突然换cpu加载了，cpu无法支持fp16，所以崩溃。我现在崩溃了4次。前两次我觉得是机子问题，后两次我觉得是不是程序有点啥？model运行开始好好的，突然换cpu加载（因为后两次都是torch能调GPU，程序杀死再启动一切正常）
________________________________
发件人: zR ***@***.***>
发送时间: 2024年3月12日 15:20
收件人: THUDM/ChatGLM3 ***@***.***>
抄送: Micla-SHL ***@***.***>; Author ***@***.***>
主题: Re: [THUDM/ChatGLM3] A40机器运行网页示例程序遇到 突然GPU无法使用，问GLM，return reeor（cpu不支持fp16数据，原因就是无法调用GPU了）这情况很突然，我无法理解 (Issue #964)


我们也复现不出来，我们都是Linux的机子没有出现过

―
