### ISSUE TITLE
运行ChatGLM3最新（2024.03.12）官方finetune_demo微调代码报错；保存模型时报错.

### ISSUE THREAD

**Issue by MakeWater** [THUDM/ChatGLM3#965]
### System Info / 系統信息

系统版本：Ubuntu-22.04.4-LTS；
Python：3.12.2；
Torch版本2.2.1；
CUDA版本：12.1；
硬件（GPU）：NVIDIA-Corporation-TU102-[TITAN-RTX]-24G显存
内存：32G
关键环境包：
transformers--------------4.38.2-------------------pypi_0----pypi
deepspeed-----------------0.14.0-------------------pypi_0----pypi

#-packages-in-environment-at-/home/ftsadmin/miniconda3/envs/chatglm环境下的所有安装包:

#
#-Name--------------------Version-------------------Build-------Channel

_libgcc_mutex-------------0.1------------------------main--
_openmp_mutex-------------5.1-----------------------1_gnu--
_sysroot_linux-64_curr_repodata_hack-3-------------------haa98f57_10--
accelerate----------------0.27.2-------------------pypi_0----pypi
aiofiles------------------23.2.1-------------------pypi_0----pypi
aiohttp-------------------3.9.3--------------------pypi_0----pypi
aiosignal-----------------1.3.1--------------------pypi_0----pypi
altair--------------------5.2.0--------------------pypi_0----pypi
annotated-types-----------0.6.0--------------------pypi_0----pypi
anyio---------------------4.3.0--------------------pypi_0----pypi
argon2-cffi---------------23.1.0-------------------pypi_0----pypi
argon2-cffi-bindings------21.2.0-------------------pypi_0----pypi
arrow---------------------1.3.0--------------------pypi_0----pypi
arxiv---------------------2.1.0--------------------pypi_0----pypi
asttokens-----------------2.4.1--------------------pypi_0----pypi
async-lru-----------------2.0.4--------------------pypi_0----pypi
attrs---------------------23.2.0-------------------pypi_0----pypi
babel---------------------2.14.0-------------------pypi_0----pypi
beautifulsoup4------------4.12.3-------------------pypi_0----pypi
binutils_impl_linux-64----2.38-----------------h2a08ee3_1--
binutils_linux-64---------2.38.0---------------hc2dff05_0--
bleach--------------------6.1.0--------------------pypi_0----pypi
blinker-------------------1.7.0--------------------pypi_0----pypi
bzip2---------------------1.0.8----------------h5eee18b_5--
ca-certificates-----------2023.12.12-----------h06a4308_0--
cachetools----------------5.3.3--------------------pypi_0----pypi
certifi-------------------2024.2.2-----------------pypi_0----pypi
cffi----------------------1.16.0-------------------pypi_0----pypi
charset-normalizer--------3.3.2--------------------pypi_0----pypi
click---------------------8.1.7-----------py312h06a4308_0--
colorama------------------0.4.6--------------------pypi_0----pypi
comm----------------------0.2.1--------------------pypi_0----pypi
contourpy-----------------1.2.0--------------------pypi_0----pypi
cpm-kernels---------------1.0.11-------------------pypi_0----pypi
cycler--------------------0.12.1-------------------pypi_0----pypi
dataclasses-json----------0.6.4--------------------pypi_0----pypi
datasets------------------2.18.0-------------------pypi_0----pypi
debugpy-------------------1.8.1--------------------pypi_0----pypi
decorator-----------------5.1.1--------------------pypi_0----pypi
deepspeed-----------------0.14.0-------------------pypi_0----pypi
defusedxml----------------0.7.1--------------------pypi_0----pypi
dill----------------------0.3.8--------------------pypi_0----pypi
distro--------------------1.9.0--------------------pypi_0----pypi
executing-----------------2.0.1--------------------pypi_0----pypi
expat---------------------2.5.0----------------h6a678d5_0--
fastapi-------------------0.110.0------------------pypi_0----pypi
fastjsonschema------------2.19.1-------------------pypi_0----pypi
feedparser----------------6.0.10-------------------pypi_0----pypi
ffmpy---------------------0.3.2--------------------pypi_0----pypi
filelock------------------3.13.1-------------------pypi_0----pypi
fonttools-----------------4.49.0-------------------pypi_0----pypi
fqdn----------------------1.5.1--------------------pypi_0----pypi
frozenlist----------------1.4.1--------------------pypi_0----pypi
fsspec--------------------2024.2.0-----------------pypi_0----pypi
gcc_impl_linux-64---------11.2.0---------------h1234567_1--
gcc_linux-64--------------11.2.0---------------h5c386dc_0--
gitdb---------------------4.0.11-------------------pypi_0----pypi
gitpython-----------------3.1.42-------------------pypi_0----pypi
gradio--------------------4.21.0-------------------pypi_0----pypi
gradio-client-------------0.12.0-------------------pypi_0----pypi
greenlet------------------3.0.3--------------------pypi_0----pypi
h11-----------------------0.14.0-------------------pypi_0----pypi
hjson---------------------3.1.0--------------------pypi_0----pypi
httpcore------------------1.0.4--------------------pypi_0----pypi
httpx---------------------0.27.0-------------------pypi_0----pypi
huggingface-hub-----------0.21.4-------------------pypi_0----pypi
idna----------------------3.6----------------------pypi_0----pypi
importlib-resources-------6.1.3--------------------pypi_0----pypi
ipykernel-----------------6.29.3-------------------pypi_0----pypi
ipython-------------------8.22.2-------------------pypi_0----pypi
ipywidgets----------------8.1.2--------------------pypi_0----pypi
isoduration---------------20.11.0------------------pypi_0----pypi
jedi----------------------0.19.1-------------------pypi_0----pypi
jieba---------------------0.42.1-------------------pypi_0----pypi
jinja2--------------------3.1.3--------------------pypi_0----pypi
joblib--------------------1.3.2--------------------pypi_0----pypi
json5---------------------0.9.22-------------------pypi_0----pypi
jsonpatch-----------------1.33---------------------pypi_0----pypi
jsonpointer---------------2.4----------------------pypi_0----pypi
jsonschema----------------4.21.1-------------------pypi_0----pypi
jsonschema-specifications-2023.12.1----------------pypi_0----pypi
jupyter-------------------1.0.0--------------------pypi_0----pypi
jupyter-client------------8.6.0--------------------pypi_0----pypi
jupyter-console-----------6.6.3--------------------pypi_0----pypi
jupyter-core--------------5.7.1--------------------pypi_0----pypi
jupyter-events------------0.9.0--------------------pypi_0----pypi
jupyter-lsp---------------2.2.4--------------------pypi_0----pypi
jupyter-server------------2.13.0-------------------pypi_0----pypi
jupyter-server-terminals--0.5.2--------------------pypi_0----pypi
jupyterlab----------------4.1.4--------------------pypi_0----pypi
jupyterlab-pygments-------0.3.0--------------------pypi_0----pypi
jupyterlab-server---------2.25.4-------------------pypi_0----pypi
jupyterlab-widgets--------3.0.10-------------------pypi_0----pypi
kernel-headers_linux-64---3.10.0--------------h57e8cba_10--
kiwisolver----------------1.4.5--------------------pypi_0----pypi
langchain-----------------0.1.11-------------------pypi_0----pypi
langchain-community-------0.0.27-------------------pypi_0----pypi
langchain-core------------0.1.30-------------------pypi_0----pypi
langchain-text-splitters--0.0.1--------------------pypi_0----pypi
langchainhub--------------0.1.15-------------------pypi_0----pypi
langsmith-----------------0.1.23-------------------pypi_0----pypi
latex2mathml--------------3.77.0-------------------pypi_0----pypi
ld_impl_linux-64----------2.38-----------------h1181459_1--
libffi--------------------3.4.4----------------h6a678d5_0--
libgcc-devel_linux-64-----11.2.0---------------h1234567_1--
libgcc-ng-----------------11.2.0---------------h1234567_1--
libgomp-------------------11.2.0---------------h1234567_1--
libstdcxx-ng--------------11.2.0---------------h1234567_1--
libuuid-------------------1.41.5---------------h5eee18b_0--
loguru--------------------0.7.2--------------------pypi_0----pypi
markdown------------------3.5.2--------------------pypi_0----pypi
markdown-it-py------------3.0.0--------------------pypi_0----pypi
markupsafe----------------2.1.5--------------------pypi_0----pypi
marshmallow---------------3.21.1-------------------pypi_0----pypi
matplotlib----------------3.8.3--------------------pypi_0----pypi
matplotlib-inline---------0.1.6--------------------pypi_0----pypi
mdtex2html----------------1.3.0--------------------pypi_0----pypi
mdurl---------------------0.1.2--------------------pypi_0----pypi
mistune-------------------3.0.2--------------------pypi_0----pypi
mpi4py--------------------3.1.5--------------------pypi_0----pypi
mpmath--------------------1.3.0--------------------pypi_0----pypi
multidict-----------------6.0.5--------------------pypi_0----pypi
multiprocess--------------0.70.16------------------pypi_0----pypi
mypy-extensions-----------1.0.0--------------------pypi_0----pypi
nbclient------------------0.9.0--------------------pypi_0----pypi
nbconvert-----------------7.16.2-------------------pypi_0----pypi
nbformat------------------5.9.2--------------------pypi_0----pypi
ncurses-------------------6.4------------------h6a678d5_0--
nest-asyncio--------------1.6.0--------------------pypi_0----pypi
networkx------------------3.2.1--------------------pypi_0----pypi
ninja---------------------1.11.1.1-----------------pypi_0----pypi
nltk----------------------3.8.1-----------py312h06a4308_0--
notebook------------------7.1.1--------------------pypi_0----pypi
notebook-shim-------------0.2.4--------------------pypi_0----pypi
numpy---------------------1.26.4-------------------pypi_0----pypi
nvidia-cublas-cu12--------12.1.3.1-----------------pypi_0----pypi
nvidia-cuda-cupti-cu12----12.1.105-----------------pypi_0----pypi
nvidia-cuda-nvrtc-cu12----12.1.105-----------------pypi_0----pypi
nvidia-cuda-runtime-cu12--12.1.105-----------------pypi_0----pypi
nvidia-cudnn-cu12---------8.9.2.26-----------------pypi_0----pypi
nvidia-cufft-cu12---------11.0.2.54----------------pypi_0----pypi
nvidia-curand-cu12--------10.3.2.106---------------pypi_0----pypi
nvidia-cusolver-cu12------11.4.5.107---------------pypi_0----pypi
nvidia-cusparse-cu12------12.1.0.106---------------pypi_0----pypi
nvidia-nccl-cu12----------2.19.3-------------------pypi_0----pypi
nvidia-nvjitlink-cu12-----12.4.99------------------pypi_0----pypi
nvidia-nvtx-cu12----------12.1.105-----------------pypi_0----pypi
openai--------------------1.13.3-------------------pypi_0----pypi
openssl-------------------3.0.13---------------h7f8727e_0--
orjson--------------------3.9.15-------------------pypi_0----pypi
overrides-----------------7.7.0--------------------pypi_0----pypi
packaging-----------------23.2---------------------pypi_0----pypi
pandas--------------------2.2.1--------------------pypi_0----pypi
pandocfilters-------------1.5.1--------------------pypi_0----pypi
parso---------------------0.8.3--------------------pypi_0----pypi
peft----------------------0.7.1--------------------pypi_0----pypi
pexpect-------------------4.9.0--------------------pypi_0----pypi
pillow--------------------10.2.0-------------------pypi_0----pypi
pip-----------------------23.3.1----------py312h06a4308_0--
platformdirs--------------4.2.0--------------------pypi_0----pypi
prometheus-client---------0.20.0-------------------pypi_0----pypi
prompt-toolkit------------3.0.43-------------------pypi_0----pypi
protobuf------------------4.25.3-------------------pypi_0----pypi
psutil--------------------5.9.8--------------------pypi_0----pypi
ptyprocess----------------0.7.0--------------------pypi_0----pypi
pure-eval-----------------0.2.2--------------------pypi_0----pypi
py-cpuinfo----------------9.0.0--------------------pypi_0----pypi
pyarrow-------------------15.0.1-------------------pypi_0----pypi
pyarrow-hotfix------------0.6----------------------pypi_0----pypi
pycparser-----------------2.21---------------------pypi_0----pypi
pydantic------------------2.6.3--------------------pypi_0----pypi
pydantic-core-------------2.16.3-------------------pypi_0----pypi
pydeck--------------------0.8.1b0------------------pypi_0----pypi
pydub---------------------0.25.1-------------------pypi_0----pypi
pygments------------------2.17.2-------------------pypi_0----pypi
pyjwt---------------------2.8.0--------------------pypi_0----pypi
pynvml--------------------11.5.0-------------------pypi_0----pypi
pyparsing-----------------3.1.2--------------------pypi_0----pypi
python--------------------3.12.2---------------h996f2a0_0--
python-dateutil-----------2.9.0.post0--------------pypi_0----pypi
python-json-logger--------2.0.7--------------------pypi_0----pypi
python-multipart----------0.0.9--------------------pypi_0----pypi
pytz----------------------2024.1-------------------pypi_0----pypi
pyyaml--------------------6.0.1--------------------pypi_0----pypi
pyzmq---------------------25.1.2-------------------pypi_0----pypi
qtconsole-----------------5.5.1--------------------pypi_0----pypi
qtpy----------------------2.4.1--------------------pypi_0----pypi
readline------------------8.2------------------h5eee18b_0--
referencing---------------0.33.0-------------------pypi_0----pypi
regex---------------------2023.12.25---------------pypi_0----pypi
requests------------------2.31.0-------------------pypi_0----pypi
rfc3339-validator---------0.1.4--------------------pypi_0----pypi
rfc3986-validator---------0.1.1--------------------pypi_0----pypi
rich----------------------13.7.1-------------------pypi_0----pypi
rouge-chinese-------------1.0.3--------------------pypi_0----pypi
rpds-py-------------------0.18.0-------------------pypi_0----pypi
ruamel-yaml---------------0.18.6-------------------pypi_0----pypi
ruamel-yaml-clib----------0.2.8--------------------pypi_0----pypi
ruff----------------------0.3.2--------------------pypi_0----pypi
safetensors---------------0.4.2--------------------pypi_0----pypi
scikit-learn--------------1.4.1.post1--------------pypi_0----pypi
scipy---------------------1.12.0-------------------pypi_0----pypi
semantic-version----------2.10.0-------------------pypi_0----pypi
send2trash----------------1.8.2--------------------pypi_0----pypi
sentence-transformers-----2.5.1--------------------pypi_0----pypi
sentencepiece-------------0.2.0--------------------pypi_0----pypi
setuptools----------------68.2.2----------py312h06a4308_0--
sgmllib3k-----------------1.0.0--------------------pypi_0----pypi
shellingham---------------1.5.4--------------------pypi_0----pypi
six-----------------------1.16.0-------------------pypi_0----pypi
smmap---------------------5.0.1--------------------pypi_0----pypi
sniffio-------------------1.3.1--------------------pypi_0----pypi
soupsieve-----------------2.5----------------------pypi_0----pypi
sqlalchemy----------------2.0.28-------------------pypi_0----pypi
sqlite--------------------3.41.2---------------h5eee18b_0--
sse-starlette-------------2.0.0--------------------pypi_0----pypi
stack-data----------------0.6.3--------------------pypi_0----pypi
starlette-----------------0.36.3-------------------pypi_0----pypi
streamlit-----------------1.32.0-------------------pypi_0----pypi
sympy---------------------1.12---------------------pypi_0----pypi
sysroot_linux-64----------2.17----------------h57e8cba_10--
tenacity------------------8.2.3--------------------pypi_0----pypi
terminado-----------------0.18.0-------------------pypi_0----pypi
threadpoolctl-------------3.3.0--------------------pypi_0----pypi
tiktoken------------------0.6.0--------------------pypi_0----pypi
timm----------------------0.9.16-------------------pypi_0----pypi
tinycss2------------------1.2.1--------------------pypi_0----pypi
tk------------------------8.6.12---------------h1ccaba5_0--
tokenizers----------------0.15.2-------------------pypi_0----pypi
toml----------------------0.10.2-------------------pypi_0----pypi
tomlkit-------------------0.12.0-------------------pypi_0----pypi
toolz---------------------0.12.1-------------------pypi_0----pypi
torch---------------------2.2.1--------------------pypi_0----pypi
torchaudio----------------2.2.1--------------------pypi_0----pypi
torchvision---------------0.17.1-------------------pypi_0----pypi
tornado-------------------6.4----------------------pypi_0----pypi
tqdm----------------------4.66.2-------------------pypi_0----pypi
traitlets-----------------5.14.1-------------------pypi_0----pypi
transformers--------------4.38.2-------------------pypi_0----pypi
typer---------------------0.9.0--------------------pypi_0----pypi
types-python-dateutil-----2.8.19.20240311----------pypi_0----pypi
types-requests------------2.31.0.20240311----------pypi_0----pypi
typing-extensions---------4.10.0-------------------pypi_0----pypi
typing-inspect------------0.9.0--------------------pypi_0----pypi
tzdata--------------------2024.1-------------------pypi_0----pypi
uri-template--------------1.3.0--------------------pypi_0----pypi
urllib3-------------------2.2.1--------------------pypi_0----pypi
uvicorn-------------------0.28.0-------------------pypi_0----pypi
watchdog------------------4.0.0--------------------pypi_0----pypi
wcwidth-------------------0.2.13-------------------pypi_0----pypi
webcolors-----------------1.13---------------------pypi_0----pypi
webencodings--------------0.5.1--------------------pypi_0----pypi
websocket-client----------1.7.0--------------------pypi_0----pypi
websockets----------------11.0.3-------------------pypi_0----pypi
wheel---------------------0.41.2----------py312h06a4308_0--
widgetsnbextension--------4.0.10-------------------pypi_0----pypi
xxhash--------------------3.4.1--------------------pypi_0----pypi
xz------------------------5.4.6----------------h5eee18b_0--
yarl----------------------1.9.4--------------------pypi_0----pypi
zhipuai-------------------2.0.1--------------------pypi_0----pypi
zlib----------------------1.2.13---------------h5eee18b_0-
![截图 2024-03-12 17-31-10](https://github.com/THUDM/ChatGLM3/assets/6929407/18c7d09d-b822-4348-b775-88e6a6d7ecc6)

### Who can help? / 谁可以帮助到您？

@Btlmd 

按照ChatGLM3 finetune README.md，先根据lora_finetune.ipynb处理AdvertiseGen数据为AdvertiseGen_fix，再根据本地数据位置略微调整，单机单卡条件下通过运行命令
`python` finetune_hf.py data/AdvertiseGen_fix/ ../basic_demo/THUDM/chatglm3-6b/ configs/lora.yaml`
，运行到500步时报错：
![截图 2024-03-12 17-40-30](https://github.com/THUDM/ChatGLM3/assets/6929407/68a8d7f9-302c-47b6-bacb-d967b3cab557)
![截图 2024-03-12 17-31-10](https://github.com/THUDM/ChatGLM3/assets/6929407/70cac0d2-1336-4661-bd2d-7ed3898f607b)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.安装CUDA12.1
2.通过miniconda创建环境chatglm，并指定Python版本3.12（`conda create -n chatglm pyhton=3.12`）
3.通过pytorch官网以pip的方式安装CUDA12.1版本的torch；
4.通过pip install -r requirements.txt 安装主项目下和finetune_demo下的两个requirements.txt，并且本地运行basic_demo下的streamlit run web_demo_streamlit.py 成功；
5. 在finetune_demo中根据单机单卡命令运行微调命令，训练到500步时报错，详见附图。

### Expected behavior / 期待表现

首次报错排查通过安装包的build信息以为是nltk安装包与Python3.12的版本兼容问题，通过conda重新安装nltk后仍然报相同的错误。期待能够正常运行微调。

**Comment by MakeWater** [comment]
已自行解决，是Python版本的问题。 使用Python=3.11版本再安装torch等环境包即可。 中间可能遇到`pip install mpi4py`报错，通过安装`pip3 install gcc_linux-64`这个包后再安装mpi4py即可解决。

**Comment by buaasunby** [comment]
遇到同样的问题了，哭死
