### ISSUE TITLE
如何量化？

### ISSUE THREAD

**Issue by coderwpf** [THUDM/ChatGLM3#97]
如何量化，否则32K处理大文本16G的GPU立马就爆了。

**Comment by tomhup** [comment]
试试用下面语句加载模型
 
   model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).half().quantize(4).cuda()

**Comment by coderwpf** [comment]
> model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).half().quantize(4).cuda()

不行，我运行报错。

    raise RuntimeError("Library %s is not initialized" % self.__name)
RuntimeError: Library cudart is not initialized

**Comment by bennylam** [comment]
model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).half().quantize(4).cuda()
这是否相当于在只有 16G RAM 的低内存系统中可进行推理的 int4 量化模型？

**Comment by jinyuxiaoqiang** [comment]
@coderwpf  试试这个
model = AutoModel.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True).half().quantize(8).cuda()

**Comment by bennylam** [comment]
添加 quantize(4).cuda() 加载模型后：

AutoModel.from_pretrained("../models/chatglm3-6b", trust_remote_code=True).quantize(4).cuda()

加载进程在57%时仍被系统杀死
查看上传的图片。
![ChatGLM3_Failed2](https://github.com/THUDM/ChatGLM3/assets/2214990/64be9839-4917-4580-bc7d-6f22508f14b8)

我在 Windows 10 WSL 中运行 Ubuntu，只有 16G CPU RAM 和 6G GPU VRAM。
有人有在如此低级别的设置环境中测试 glm3 的经验吗？
期待看到您的分享和帮助。

谢谢!
Benny

**Comment by bennylam** [comment]
我已經修復了這個問題，問題的原因是 WSL2 在 Windows 中預設限制僅使用 50% 的 CPU RAM。 我已將允許的 WSL2 最大記憶體更改為 14GB，現在 GLM3 模型已成功加載，現在可以使用 python CLI 演示程式。
