### ISSUE TITLE
> 

### ISSUE THREAD

**Issue by Nagato-Yk** [THUDM/ChatGLM3#970]
> 同遇到

可以按照我上面改的那个脚本跑就可以单机多卡了， 我的问题在于数据集指定的路径错误

_Originally posted by @TaChao in https://github.com/THUDM/ChatGLM3/issues/800#issuecomment-1918798494_

**Comment by Nagato-Yk** [comment]
改了还是那个错误。是为什么呀
 torch.distributed.elastic.multiprocessing.api:failed（exitcode:1）local_rank:2(pid:10260)of binary:/opt/conda/bin/python

**Comment by zRzRzRzRzRzRzR** [comment]
#253 这里或许有帮助，你这个问题没办法复现出来
