### ISSUE TITLE
使用Langchain-Chatchat框架加载chatglm3-6-b-128k出现自问自答，停不下来的情况

### ISSUE THREAD

**Issue by nmbtwzt** [THUDM/ChatGLM3#975]
### System Info / 系統信息

langchain-ChatGLM 版本/commit 号：v0.2.10
是否使用 Docker 部署（是/否）：否
使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B-128k
使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
操作系统及版本 / Operating system and version: linux
Python 版本 / Python version: 3.11

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.使用chatglm3-6b-128k
2.无论问答什么内容，都会出现自问自答情况。
![微信图片_20240313110149](https://github.com/THUDM/ChatGLM3/assets/50111234/2b782d4b-8fb0-4e20-b76f-7a2b5b84badd)

### Expected behavior / 期待表现

回答完毕后停止。

**Comment by woliuliu1900** [comment]
暂时通过修改fastchat中的model_chatglm.py文件解决，不知道有没有更好的方式
![TFBGM@RD_PDPM_ZXBM0TA5N](https://github.com/THUDM/ChatGLM3/assets/12620992/3c4ea860-c691-4412-b23f-6bc18eb8055e)

**Comment by zRzRzRzRzRzRzR** [comment]
fastchat的话更新到最新版本这个bug早就修了吧

**Comment by woliuliu1900** [comment]
![I94@XLO5MCZF867OE6ZT ZX](https://github.com/THUDM/ChatGLM3/assets/12620992/5ff9b974-e355-4ecc-9976-618db63dcb1c)
已经是使用的最新版本的

**Comment by zRzRzRzRzRzRzR** [comment]
额，奇怪，我去看一下，大概概率是这个版本上的时候没有根6b一样更新tokenizer

**Comment by lvbinandylau** [comment]
有修复吗？vllm调用也是一样的问题。

**Comment by lymanzhang** [comment]
我这里情况也一样，无论是加载chatglm3-6-b-32k，还是chatglm3-6-b-128k，都出现了自问自答，停不下来的情况。

**Comment by zRzRzRzRzRzRzR** [comment]
估计只有6b模型修了，另外两个没处理

**Comment by lvbinandylau** [comment]
> 估计只有6b模型修了，另外两个没处理

坐等大佬处理一下。

**Comment by zRzRzRzRzRzRzR** [comment]
先换一下 https://huggingface.co/THUDM/chatglm3-6b/blob/main/tokenizer_config.json 到128k的模型目录下看一下是否正常

**Comment by nmbtwzt** [comment]
> 先换一下 https://huggingface.co/THUDM/chatglm3-6b/blob/main/tokenizer_config.json 到128k的模型目录下看一下是否正常

已经尝试更换，问题依旧，还是无法正常返回，日志中会多出如下提示。
![image](https://github.com/THUDM/ChatGLM3/assets/50111234/04d96e3e-140b-43a1-b171-375182748572)

**Comment by zRzRzRzRzRzRzR** [comment]
降级到tarnsformer 4.37.2 ，chatglm3-6b也有这个警告

**Comment by austinleealpha** [comment]
> 先换一下 https://huggingface.co/THUDM/chatglm3-6b/blob/main/tokenizer_config.json 到128k的模型目录下看一下是否正常

更新原有的配置文件到128k模型，产生
AttributeError: can't set attribute 'eos_token'，导致会产生自问自答。
![image](https://github.com/THUDM/ChatGLM3/assets/131632880/b7a81498-fc04-4884-9ed1-4c406c438efd)

**Comment by nmbtwzt** [comment]
> 降级到tarnsformer 4.37.2 ，chatglm3-6b也有这个警告


现在就是4.37.2，依旧有这个警告，且使用chatglm3-6b-32k，更新了也有这个警告
![微信图片_20240321151025](https://github.com/THUDM/ChatGLM3/assets/50111234/f5ac2896-2c01-4b09-a948-f2d9570ff370)

**Comment by sevenandseven** [comment]
> ### System Info / 系統信息
> langchain-ChatGLM 版本/commit 号：v0.2.10 是否使用 Docker 部署（是/否）：否 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B-128k 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 操作系统及版本 / Operating system and version: linux Python 版本 / Python version: 3.11
> 
> ### Who can help? / 谁可以帮助到您？
> _No response_
> 
> ### Information / 问题信息
> * [x]  The official example scripts / 官方的示例脚本
> * [ ]  My own modified scripts / 我自己修改的脚本和任务
> 
> ### Reproduction / 复现过程
> 1.使用chatglm3-6b-128k 2.无论问答什么内容，都会出现自问自答情况。 ![微信图片_20240313110149](https://private-user-images.githubusercontent.com/50111234/312765621-2b782d4b-8fb0-4e20-b76f-7a2b5b84badd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTE1ODYsIm5iZiI6MTcxMTY5MTI4NiwicGF0aCI6Ii81MDExMTIzNC8zMTI3NjU2MjEtMmI3ODJkNGItOGZiMC00ZTIwLWI3NmYtN2EyYjViODRiYWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA1NDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NTkxNWFiYTk2YzA5ZmJkN2E3ZmY0Y2EyNjEyM2I2YzUwODRmODNiMGRlMTZkNTYwZWZmZjMzNTU5YTI5OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hL-qUq9KbDUQvEUuTyl-OJylIPMw1kVLxU-CdWh8H74)
> 
> ### Expected behavior / 期待表现
> 回答完毕后停止。

你好，这个问题解决了吗？

**Comment by zRzRzRzRzRzRzR** [comment]
可以尝试在读入代码的时候按照 [这里](https://github.com/THUDM/ChatGLM3/blob/main/basic_demo/web_demo_gradio.py)的方式读入模型，因该能够解决，因为128K模型也没有functioncall能力，可以直接用模板
