### ISSUE TITLE
Streamlit 生成网址打不开

### ISSUE THREAD

**Issue by hhaishen** [THUDM/ChatGLM3#976]
### System Info / 系統信息

系统版本：openEuler release 22.03 (LTS-SP3)
Python：Python 3.10.13
Torch版本：2.2.1+cu121
CUDA版本：12.2
硬件（GPU）：Tesla T4（16G显存）
内存：128G

问题：运行 streamlit run main.py 或 streamlit run main.py --server.address=127.0.0.1  
都无法打开页面，端口尝试过是通的，不知道哪里出问题了。无法执行到加载模型那一步，模型配置也更改过，下载到了本地，也还是不行，不修改本地模型也不行。

![image](https://github.com/THUDM/ChatGLM3/assets/122429037/d239174f-7987-4f86-a5fd-d7f6f5a0cb60)

![image](https://github.com/THUDM/ChatGLM3/assets/122429037/3f55910c-c979-4fe1-b3c1-f1cc2a1cffd0)

![image](https://github.com/THUDM/ChatGLM3/assets/122429037/edb8143f-a940-440f-ad16-af78c60def4a)

依赖环境如下：
accelerate                0.28.0
aiofiles                  23.2.1
aiohttp                   3.9.3
aiosignal                 1.3.1
altair                    5.2.0
annotated-types           0.6.0
anyio                     4.3.0
arxiv                     2.1.0
asttokens                 2.4.1
async-timeout             4.0.3
attrs                     23.2.0
blinker                   1.7.0
cachetools                5.3.3
certifi                   2024.2.2
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
comm                      0.2.2
contourpy                 1.2.0
cpm-kernels               1.0.11
cycler                    0.12.1
dataclasses-json          0.6.4
debugpy                   1.8.1
decorator                 5.1.1
distro                    1.9.0
exceptiongroup            1.2.0
executing                 2.0.1
fastapi                   0.110.0
feedparser                6.0.10
ffmpy                     0.3.2
filelock                  3.9.0
fonttools                 4.49.0
frozenlist                1.4.1
fsspec                    2024.2.0
gitdb                     4.0.11
GitPython                 3.1.42
gradio                    4.21.0
gradio_client             0.12.0
greenlet                  3.0.3
h11                       0.14.0
httpcore                  1.0.4
httpx                     0.27.0
huggingface-hub           0.21.4
idna                      3.6
importlib_resources       6.3.0
ipykernel                 6.29.3
ipython                   8.22.2
jedi                      0.19.1
Jinja2                    3.1.2
joblib                    1.3.2
jsonpatch                 1.33
jsonpointer               2.4
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
jupyter_client            8.6.1
jupyter_core              5.7.2
kiwisolver                1.4.5
langchain                 0.1.12
langchain-community       0.0.28
langchain-core            0.1.31
langchain-text-splitters  0.0.1
langchainhub              0.1.15
langsmith                 0.1.25
latex2mathml              3.77.0
loguru                    0.7.2
Markdown                  3.5.2
markdown-it-py            3.0.0
MarkupSafe                2.1.3
marshmallow               3.21.1
matplotlib                3.8.3
matplotlib-inline         0.1.6
mdtex2html                1.3.0
mdurl                     0.1.2
mpmath                    1.3.0
multidict                 6.0.5
mypy-extensions           1.0.0
nest-asyncio              1.6.0
networkx                  3.2.1
numpy                     1.26.3
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.19.3
nvidia-nvjitlink-cu12     12.1.105
nvidia-nvtx-cu12          12.1.105
openai                    1.14.0
orjson                    3.9.15
packaging                 23.2
pandas                    2.2.1
parso                     0.8.3
pexpect                   4.9.0
pillow                    10.2.0
pip                       23.3.1
platformdirs              4.2.0
prompt-toolkit            3.0.43
protobuf                  4.25.3
psutil                    5.9.8
ptyprocess                0.7.0
pure-eval                 0.2.2
pyarrow                   15.0.1
pydantic                  2.6.4
pydantic_core             2.16.3
pydeck                    0.8.1b0
pydub                     0.25.1
Pygments                  2.17.2
PyJWT                     2.8.0
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.1
pyzmq                     25.1.2
referencing               0.33.0
regex                     2023.12.25
requests                  2.31.0
rich                      13.7.1
rpds-py                   0.18.0
ruff                      0.3.2
safetensors               0.4.2
scikit-learn              1.4.1.post1
scipy                     1.12.0
semantic-version          2.10.0
sentence-transformers     2.5.1
sentencepiece             0.2.0
setuptools                68.2.2
sgmllib3k                 1.0.0
shellingham               1.5.4
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
SQLAlchemy                2.0.28
sse-starlette             2.0.0
stack-data                0.6.3
starlette                 0.36.3
streamlit                 1.32.1
sympy                     1.12
tenacity                  8.2.3
threadpoolctl             3.3.0
tiktoken                  0.6.0
timm                      0.9.16
tokenizers                0.15.2
toml                      0.10.2
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.2.1+cu121
torchaudio                2.2.1+cu121
torchvision               0.17.1+cu121
tornado                   6.4
tqdm                      4.66.2
traitlets                 5.14.2
transformers              4.38.2
triton                    2.2.0
typer                     0.9.0
types-requests            2.31.0.20240311
typing_extensions         4.8.0
typing-inspect            0.9.0
tzdata                    2024.1
urllib3                   2.2.1
uvicorn                   0.28.0
watchdog                  4.0.0
wcwidth                   0.2.13
websockets                11.0.3
wheel                     0.41.2
yarl                      1.9.4
zhipuai                   2.0.1

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

根据官方环境的文档步骤来运行的。

### Expected behavior / 期待表现

正常运行

**Comment by LiangYong1216** [comment]
运行前试试：export MODEL_PATH=/home/ChatGLM3/THUDM/chatglm3-6b/ , 然后再streamlit run main.py

**Comment by hhaishen** [comment]
> 运行前试试：export MODEL_PATH=/home/ChatGLM3/THUDM/chatglm3-6b/ , 然后再streamlit run main.py

尝试了，还是无法加载模型，链接地址也无法打开

**Comment by zRzRzRzRzRzRzR** [comment]
这个应该是steramlit的问题，先用local环境试一下吧

**Comment by Yida147** [comment]
> > 运行前试试：export MODEL_PATH=/home/ChatGLM3/THUDM/chatglm3-6b/ , 然后再streamlit run main.py
> 
> 尝试了，还是无法加载模型，链接地址也无法打开

使用nginx进行tcp stream代理试一下

**Comment by Yida147** [comment]
> > > 运行前试试：export MODEL_PATH=/home/ChatGLM3/THUDM/chatglm3-6b/ , 然后再streamlit run main.py
> > 
> > 
> > 尝试了，还是无法加载模型，链接地址也无法打开
> 
> 使用nginx进行tcp stream代理试一下

https://github.com/chatchat-space/Langchain-Chatchat/issues/1306#issuecomment-2006947708
