### ISSUE TITLE
多卡微调遇到问题

### ISSUE THREAD

**Issue by CarpLoong** [THUDM/ChatGLM3#978]
### System Info / 系統信息

应该不是系统原因

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

这是我微调运行的指令
OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=2  finetune_hf.py  data/fix/  /home/chatglm3/chatglm3_model/chatglm3-6b/chatglm3-6b  configs/lora_multiple.yaml
把lora.yaml的deepspeed注释放开，去除了--deepspeed选项的填入，能够正常运行前五百步的checkpoint微调步骤并且在lora.yaml制定的output文件夹中生成对应的tmp-checkpoint-500
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/1d1d0073-fc85-4215-a783-58bdbd460868)
（这个三千是因为我修改了yaml文件中的参数，将500步保存改为3000步保存）
但是输出玩第一个保存点之后就会报错

![微信图片_20240314173601](https://github.com/THUDM/ChatGLM3/assets/50446131/b1f7c11b-569a-4d33-a1f0-49a3298a38f8)
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/8e0a92a3-4efc-4c1e-a81f-fe609fd284d7)
![微信图片_20240314173712](https://github.com/THUDM/ChatGLM3/assets/50446131/7de7408a-d915-40f0-a666-dafe1a957a42)
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/88b2ad7b-98af-45d5-a49a-9947a4ae4301)
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/94848f1e-8f35-47fd-aec1-5e9cdf17f6b9)

**TypeError: Object of type Tensor is not JSON serializable**
请问这是什么原因造成的

### Expected behavior / 期待表现

最终解答多卡微调万物

**Comment by zRzRzRzRzRzRzR** [comment]
try #253，这个问题我调试能保存。依赖对吗

**Comment by CarpLoong** [comment]
> try #253，这个问题我调试能保存。依赖对吗

依赖如下
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/6890d659-c0f9-4816-bece-79d87c01df57)
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/e5a14b96-5a54-4436-abd1-162f12d9538f)
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/971ca8cf-ce2f-4efd-bced-c172e63cf6ec)
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/b51b8756-7eb4-4908-b7dc-bc2ea2e1b5e9)
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/83cd1fe3-0a8a-4dd1-b786-ca11c76e4fe0)

**Comment by CarpLoong** [comment]
@zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
所以问题出现在多卡微调，看上去你的ds版本挺高的
单卡正常，双卡4090保存失败？

**Comment by CarpLoong** [comment]
> 所以问题出现在多卡微调，看上去你的ds版本挺高的 单卡正常，双卡4090保存失败？

双卡3090出错，单卡正常

**Comment by CarpLoong** [comment]
@zRzRzRzRzRzRzR

**Comment by CarpLoong** [comment]
> 所以问题出现在多卡微调，看上去你的ds版本挺高的 单卡正常，双卡4090保存失败？

ds版本高吗，我是按照requirements.txt里面安装的
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/ee297fa5-5651-4a29-ac2c-8794264698c5)

**Comment by yichen-liang** [comment]
我也有一样的问题

**Comment by yichen-liang** [comment]
@zRzRzRzRzRzRzR    
CUDA_VISIBLE_DEVICES=0,1,2 OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=3 finetune_hf.py data/daozhen_319 /root/ChatGLM3/finetune_demo/ZhipuAI/chatglm3_6b configs/lora_daozhen_319.yaml


报错：
│ /root/yes/envs/glm3_ft/lib/python3.10/json/encoder.py:438 in _iterencode                         │
│                                                                                                  │
│   435 │   │   │   │   if markerid in markers:                                                    │
│   436 │   │   │   │   │   raise ValueError("Circular reference detected")                        │
│   437 │   │   │   │   markers[markerid] = o                                                      │
│ ❱ 438 │   │   │   o = _default(o)                                                                │
│   439 │   │   │   yield from _iterencode(o, _current_indent_level)                               │
│   440 │   │   │   if markers is not None:                                                        │
│   441 │   │   │   │   del markers[markerid]                                                      │
│                                                                                                  │
│ /root/yes/envs/glm3_ft/lib/python3.10/json/encoder.py:179 in default                             │
│                                                                                                  │
│   176 │   │   │   │   return JSONEncoder.default(self, o)                                        │
│   177 │   │                                                                                      │
│   178 │   │   """                                                                                │
│ ❱ 179 │   │   raise TypeError(f'Object of type {o.__class__.__name__} '                          │
│   180 │   │   │   │   │   │   f'is not JSON serializable')                                       │
│   181 │                                                                                          │
│   182 │   def encode(self, o):                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Object of type Tensor is not JSON serializable
  5%|████▏                                                                               | 120/2400 [01:30<28:42,  1.32it/s]

**Comment by zRzRzRzRzRzRzR** [comment]
TypeError: Object of type Tensor is not JSON serializable 这个报错根上面不一样吧

**Comment by CarpLoong** [comment]
> TypeError: Object of type Tensor is not JSON serializable 这个报错根上面不一样吧

看着像是一样的错误，我最后也是出现这个错误
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/aaa9256b-60f4-459b-865d-be836917d441)
@zRzRzRzRzRzRzR

**Comment by CarpLoong** [comment]
> @zRzRzRzRzRzRzR CUDA_VISIBLE_DEVICES=0,1,2 OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=3 finetune_hf.py data/daozhen_319 /root/ChatGLM3/finetune_demo/ZhipuAI/chatglm3_6b configs/lora_daozhen_319.yaml
> 
> 报错： │ /root/yes/envs/glm3_ft/lib/python3.10/json/encoder.py:438 in _iterencode │ │ │ │ 435 │ │ │ │ if markerid in markers: │ │ 436 │ │ │ │ │ raise ValueError("Circular reference detected") │ │ 437 │ │ │ │ markers[markerid] = o │ │ ❱ 438 │ │ │ o = _default(o) │ │ 439 │ │ │ yield from _iterencode(o, _current_indent_level) │ │ 440 │ │ │ if markers is not None: │ │ 441 │ │ │ │ del markers[markerid] │ │ │ │ /root/yes/envs/glm3_ft/lib/python3.10/json/encoder.py:179 in default │ │ │ │ 176 │ │ │ │ return JSONEncoder.default(self, o) │ │ 177 │ │ │ │ 178 │ │ """ │ │ ❱ 179 │ │ raise TypeError(f'Object of type {o.**class**.**name**} ' │ │ 180 │ │ │ │ │ │ f'is not JSON serializable') │ │ 181 │ │ │ 182 │ def encode(self, o): │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯ TypeError: Object of type Tensor is not JSON serializable 5%|████▏ | 120/2400 [01:30<28:42, 1.32it/s]

解决了，把deepspeed版本降为0.13.1就可以了
![image](https://github.com/THUDM/ChatGLM3/assets/50446131/8972c4d3-c3dc-44c8-9394-d44388f0c84b)

整体命令为
OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=2  finetune_hf.py  data/fix/  /home/chatglm3/chatglm3_model/chatglm3-6b/chatglm3-6b  configs/lora_multiple.yaml
要放开官方提供的lora.yml中deepspeed的注释
@yichen-liang @zRzRzRzRzRzRzR
