### ISSUE TITLE
使用function call,执行observation完，history是none，咨询一下是openai_api的问题，还是哪里问题

### ISSUE THREAD

**Issue by wengyuan722** [THUDM/ChatGLM3#98]
tool_response = dispatch_tool(function_call["name"], function_call["parameters"])
    logger.info(f"Tool Call Response: {tool_response}")

    messages = response.choices[0].history  # 获取历史对话信息
    messages.append(
        {
            "role": "observation",
            "content": tool_response,  # 调用函数返回结果
        }
    )

    response = openai.ChatCompletion.create(
        model="chatglm3",
        messages=messages,
        temperature=0,
    )
    print(342,messages)
    print(422,response.choices[0])

打印出来的结果是 {
  "index": 0,
  "message": {
    "role": "assistant",
    "content": "\n \u6839\u636e\u60a8\u7684\u8981\u6c42\uff0c\u6211\u67e5\u8be2\u4e86\u5317\u4eac\u7684\u5929\u6c14\u60c5\u51b5\u3002\u76ee\u524d\u5317\u4eac\u7684\u6e29\u5ea6\u662f17\u6444\u6c0f\u5ea6\uff0c\u6e7f\u5ea6\u4e3a77%\uff0c\u5929\u6c14\u72b6\u51b5\u4e3aMist\u3002\u8fd9\u4e9b\u4fe1\u606f\u662f\u5728\u89c2\u5bdf\u65f6\u95f402:15 AM\u65f6\u83b7\u53d6\u7684\u3002",
    "metadata": null,
    "tools": null
  },
  "finish_reason": "stop",
  "history": null
}
我如果要继续调用函数，同时使用已调用的函数结果，我要怎么获取历史记录，是要改openai_api，还是自己设定一个history的list

**Comment by xusenlinzy** [comment]
和第一次调用接口一样，添加 `return_function_call=True` 参数 就会返回历史记录

**Comment by wengyuan722** [comment]
@xusenlinzy 多谢

**Comment by xusenlinzy** [comment]
每次调用接口都加上 `return_function_call=True` 参数，返回的结果里有一个 `finish_reason` 字段，如果 `finish_reason` 是 `function_call`，说明还要继续调用接口，需要拿出结果中的 `history` 作为输入，否则就是已经生成回复了

**Comment by wengyuan722** [comment]
那就是有两种判断继续执行的方式，一种是通过解析是否是dict，一种是判断finish_reason 是否是function_call，你这个可能更符合，多谢

**Comment by wengyuan722** [comment]
另外想咨询对于回复是ascii有什么好的解决，不然我要去重新构建一个json

**Comment by xusenlinzy** [comment]
> 另外想咨询对于回复是ascii有什么好的解决，不然我要去重新构建一个json

```python
print(response.to_dict_recursive())
```

这样打印就可以了

**Comment by wengyuan722** [comment]
多谢，另外我现在使用前端WebSocket来监听，想咨询一下，有没有可能实现异步混合的方式，调模型的时候通过异步实现，函数调用时await，这种方式能不能实现
