### ISSUE TITLE
多轮对话微调后模型回答时无法正常停止生成

### ISSUE THREAD

**Issue by treya-lin** [THUDM/ChatGLM3#980]
你好，我尝试使用使用多轮对话数据来微调chatglm3-6b，但是发现模型无法正常停止输出。想咨询几个问题。

![image](https://github.com/THUDM/ChatGLM3/assets/86940562/4525dcc8-0989-4c5d-b48d-8b8eff44443a)

我阅读了 `finetune_hf.py` 中和数据准备有关的代码，发现对于训练集，eos token只加在最后一轮的机器答复末尾，另外数据会因上下文长度的限制被提前截断。

有如下疑问：

1. 我的每条数据轮次和字数较多，都会被 max_input_length, max_output_length 的限制而被提前截断，也就是说我的数据可能结尾都没有正常的eos token了，这样会带来的影响是什么呢？

2. 假如在按长度限制截断数据之后再加eos token，会更好吗？

3. 我在 https://github.com/THUDM/ChatGLM3/issues/184#issuecomment-1797810467_ 这条issue里看到这句话
> 对于中间轮次的对话，模型学到的是输出 `<|user|>` 或 `<|observation|>` 作为终止 / 暂停生成的条件

确实 `def process_batch` 中 loss_mask 右移一格后 `<|user|>` 的loss_mask会为True，但是从我微调的结果来看似乎它并没有很好地学习到输出 <|user|> 后应该停止？

4. 在准备验证集的 `process_batch_eval` 里，多轮对话每轮的答复会和前面的历史单独做一条 input - output pairs，这种处理方式和训练集的处理不太一样，我有一点困惑，这样会ok嘛？

5. 可以请教下你们进行多轮对话微调时一般在准备时对每条数据会如何控制长度呢？ 和 max_input_length, max output_length 一般设置为多少会较好呢？

非常感谢
            
-------
* Who Can Help?
@Btlmd 
* 其它信息
1. 微调训练，我使用的是ChatGLM3/finetune_demo的默认脚本 finetune_hf.py 和lora.yaml默认配置。（之前用官方给的单轮任务AdvertiseGen数据微调是正常的。）
2. 推理测试，使用的是 ChatGLM3/basic_demo 的默认的 web_demo_gradio.py
* 系统环境
应该和系统没关系。使用 torch2.2.1, cuda12.1

**Comment by treya-lin** [comment]
Sorry 我是在 https://github.com/THUDM/ChatGLM3/issues/184#issuecomment-1797810467 这条里面点“mention in new issue”的方式建立的issue，结果发现创建完后无法再编辑填写 assignee、系统信息等 issue template 要求的信息😢

**Comment by treya-lin** [comment]
贴在这里了。https://github.com/THUDM/ChatGLM3/discussions/253#discussioncomment-8795190

**Comment by soultrans** [comment]
@treya-lin 您好，想请教下关于多轮问答
1、请问ChatGLM3的多轮对话数据集的构建格式是怎么的，能提供个参考的数据集样例嘛？
2、轮微调是是只能使用官方的[finetune_hf.py](https://github.com/THUDM/ChatGLM3/blob/main/finetune_demo/finetune_hf.py)进行微调吗？我一直在用[LLaMA-Factory](https://github.com/hiyouga/LLaMA-Factory)，微调多轮的话也是同样的方式吗？

目前LLaMA-Factory能使用**alpaca** 、 **sharegpt**两中训练格式，
_alpaca格式如下_
> [
  {
    "instruction": "user instruction (required)",
    "input": "user input (optional)",
    "output": "model response (required)",
    "system": "system prompt (optional)",
    "history": [
      ["user instruction in the first round (optional)", "model response in the first round (optional)"],
      ["user instruction in the second round (optional)", "model response in the second round (optional)"]
    ]
  }
]


_sharegpt格式如下_

> [
  {
    "conversations": [
      {
        "from": "human",
        "value": "user instruction"
      },
      {
        "from": "gpt",
        "value": "model response"
      }
    ],
    "system": "system prompt (optional)",
    "tools": "tool description (optional)"
  }
]

**Comment by treya-lin** [comment]
> @treya-lin 您好，想请教下关于多轮问答 1、请问ChatGLM3的多轮对话数据集的构建格式是怎么的，能提供个参考的数据集样例嘛？ 2、轮微调是是只能使用官方的[finetune_hf.py](https://github.com/THUDM/ChatGLM3/blob/main/finetune_demo/finetune_hf.py)进行微调吗？我一直在用[LLaMA-Factory](https://github.com/hiyouga/LLaMA-Factory)，微调多轮的话也是同样的方式吗？
> 
> 目前LLaMA-Factory能使用**alpaca** 、 **sharegpt**两中训练格式， _alpaca格式如下_ `[ { "instruction": "user instruction (required)", "input": "user input (optional)", "output": "model response (required)", "system": "system prompt (optional)", "history": [ ["user instruction in the first round (optional)", "model response in the first round (optional)"], ["user instruction in the second round (optional)", "model response in the second round (optional)"] ] } ]`
> 
> _sharegpt格式如下_ `[ { "conversations": [ { "from": "human", "value": "user instruction" }, { "from": "gpt", "value": "model response" } ], "system": "system prompt (optional)", "tools": "tool description (optional)" } ]`

Hi 我就是按照 finetune_demo 的 readme这样构建（https://github.com/THUDM/ChatGLM3/tree/main/finetune_demo#%E5%A4%9A%E8%BD%AE%E5%AF%B9%E8%AF%9D%E6%A0%BC%E5%BC%8F） 就不停往后面按user、assistant 顺序 append多个轮次的对话。
```
{
  "conversations": [
    {
      "role": "user",
      "content": "hello!"
    },
    {
      "role": "assistant",
      "content": "hello!"
    },
    {
      "role": "user",
      "content": "how are you?"
    },
    {
      "role": "assistant",
      "content": "I am fine, thank you!"
    }
 ]
}
```

**Comment by soultrans** [comment]
@treya-lin 感谢

**Comment by Franklinlifangcheng** [comment]
> > @treya-lin 您好，想请教下关于多轮问答 1、请问ChatGLM3的多轮对话数据集的构建格式是怎么的，能提供个参考的数据集样例嘛？ 2、轮微调是是只能使用官方的[finetune_hf.py](https://github.com/THUDM/ChatGLM3/blob/main/finetune_demo/finetune_hf.py)进行微调吗？我一直在用[LLaMA-Factory](https://github.com/hiyouga/LLaMA-Factory)，微调多轮的话也是同样的方式吗？
> > 目前LLaMA-Factory能使用**alpaca** 、 **sharegpt**两中训练格式， _alpaca格式如下_ `[ { "instruction": "user instruction (required)", "input": "user input (optional)", "output": "model response (required)", "system": "system prompt (optional)", "history": [ ["user instruction in the first round (optional)", "model response in the first round (optional)"], ["user instruction in the second round (optional)", "model response in the second round (optional)"] ] } ]`
> > _sharegpt格式如下_ `[ { "conversations": [ { "from": "human", "value": "user instruction" }, { "from": "gpt", "value": "model response" } ], "system": "system prompt (optional)", "tools": "tool description (optional)" } ]`
> 
> Hi 我就是按照 finetune_demo 的 readme这样构建（[https://github.com/THUDM/ChatGLM3/tree/main/finetune_demo#%E5%A4%9A%E8%BD%AE%E5%AF%B9%E8%AF%9D%E6%A0%BC%E5%BC%8F）](https://github.com/THUDM/ChatGLM3/tree/main/finetune_demo#%E5%A4%9A%E8%BD%AE%E5%AF%B9%E8%AF%9D%E6%A0%BC%E5%BC%8F%EF%BC%89) 就不停往后面按user、assistant 顺序 append多个轮次的对话。
> 
> ```
> {
>   "conversations": [
>     {
>       "role": "user",
>       "content": "hello!"
>     },
>     {
>       "role": "assistant",
>       "content": "hello!"
>     },
>     {
>       "role": "user",
>       "content": "how are you?"
>     },
>     {
>       "role": "assistant",
>       "content": "I am fine, thank you!"
>     }
>  ]
> }
> ```
> 
> 使用它的微调脚本的话，因为它数据处理的代码是针对这个格式的，所以应该只能按照这个格式来。

大佬不是应该还有一个system吗，不需要加上吗

**Comment by treya-lin** [comment]
> > > @treya-lin 您好，想请教下关于多轮问答 1、请问ChatGLM3的多轮对话数据集的构建格式是怎么的，能提供个参考的数据集样例嘛？ 2、轮微调是是只能使用官方的[finetune_hf.py](https://github.com/THUDM/ChatGLM3/blob/main/finetune_demo/finetune_hf.py)进行微调吗？我一直在用[LLaMA-Factory](https://github.com/hiyouga/LLaMA-Factory)，微调多轮的话也是同样的方式吗？
> > > 目前LLaMA-Factory能使用**alpaca** 、 **sharegpt**两中训练格式， _alpaca格式如下_ `[ { "instruction": "user instruction (required)", "input": "user input (optional)", "output": "model response (required)", "system": "system prompt (optional)", "history": [ ["user instruction in the first round (optional)", "model response in the first round (optional)"], ["user instruction in the second round (optional)", "model response in the second round (optional)"] ] } ]`
> > > _sharegpt格式如下_ `[ { "conversations": [ { "from": "human", "value": "user instruction" }, { "from": "gpt", "value": "model response" } ], "system": "system prompt (optional)", "tools": "tool description (optional)" } ]`
> > 
> > 
> > Hi 我就是按照 finetune_demo 的 readme这样构建（[https://github.com/THUDM/ChatGLM3/tree/main/finetune_demo#%E5%A4%9A%E8%BD%AE%E5%AF%B9%E8%AF%9D%E6%A0%BC%E5%BC%8F）](https://github.com/THUDM/ChatGLM3/tree/main/finetune_demo#%E5%A4%9A%E8%BD%AE%E5%AF%B9%E8%AF%9D%E6%A0%BC%E5%BC%8F%EF%BC%89) 就不停往后面按user、assistant 顺序 append多个轮次的对话。
> > ```
> > {
> >   "conversations": [
> >     {
> >       "role": "user",
> >       "content": "hello!"
> >     },
> >     {
> >       "role": "assistant",
> >       "content": "hello!"
> >     },
> >     {
> >       "role": "user",
> >       "content": "how are you?"
> >     },
> >     {
> >       "role": "assistant",
> >       "content": "I am fine, thank you!"
> >     }
> >  ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 使用它的微调脚本的话，因为它数据处理的代码是针对这个格式的，所以应该只能按照这个格式来。
> 
> 大佬不是应该还有一个system吗，不需要加上吗

刚刚才看到。 system 没有不影响跑，system的内容取决于你的任务和训练目的。
比如你手头就一堆多轮对话，你也不知道风格、主题之类的，那 system也不好写。
假如你是很清楚你各种数据风格的，然后你也有很明确的任务诉求，那可以加上。
