### ISSUE TITLE
单卡微调加载模型报错，16G显存不够吗？

### ISSUE THREAD

**Issue by lj1262** [THUDM/ChatGLM3#983]
### System Info / 系統信息

ubuntu 22.04
python 3.10
cuda 12.3
显卡 4060ti 16G

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

(chatglm3) lj@ljlinux:~/ChatGLM3-main/finetune_demo$ CUDA_VISIBLE_DEVICES=1 /home/lj/anaconda3/envs/chatglm3/bin/python finetune_hf.py  data/AdvertiseGen_fix  /home/lj/ChatGLM3-main/model/chatglm3-6b  configs/lora.yaml
Loading checkpoint shards:  86%|███████████████▍  | 6/7 [00:02<00:00,  2.09it/s]已杀死

### Expected behavior / 期待表现

loading checkpoint 100%

**Comment by zRzRzRzRzRzRzR** [comment]
够用的，前提你真的有16g空余的显存，而不是分了很多给系统，比如桌面显示，另外，16G显存是最大长度128token的
