### ISSUE TITLE
一模一样的格式的json数据集一个可以微调，另一个不行

### ISSUE THREAD

**Issue by orderer0001** [THUDM/ChatGLM3#985]
### System Info / 系統信息

linux python

### Who can help? / 谁可以帮助到您？

@B

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

报错为：Generating train split: 0 examples [00:00, ? examples/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/builder.py:1973 in          │
│ _prepare_split_single                                                                            │
│                                                                                                  │
│   1970 │   │   │   )                                                                             │
│   1971 │   │   │   try:                                                                          │
│   1972 │   │   │   │   _time = time.time()                                                       │
│ ❱ 1973 │   │   │   │   for _, table in generator:                                                │
│   1974 │   │   │   │   │   if max_shard_size is not None and writer._num_bytes > max_shard_size  │
│   1975 │   │   │   │   │   │   num_examples, num_bytes = writer.finalize()                       │
│   1976 │   │   │   │   │   │   writer.close()                                                    │
│                                                                                                  │
│ /home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/packaged_modules/json/json. │
│ py:169 in _generate_tables                                                                       │
│                                                                                                  │
│   166 │   │   │   │   │   │   │   │   break                                                      │
│   167 │   │   │   │   │   │   │   else:                                                          │
│   168 │   │   │   │   │   │   │   │   logger.error(f"Failed to read file '{file}' with error {   │
│ ❱ 169 │   │   │   │   │   │   │   │   raise ValueError(                                          │
│   170 │   │   │   │   │   │   │   │   │   f"Not able to read records in the JSON file at {file   │
│   171 │   │   │   │   │   │   │   │   │   f"You should probably indicate the field of the JSON   │
│   172 │   │   │   │   │   │   │   │   │   f"This JSON file contain the following fields: {str(   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Not able to read records in the JSON file at 
/home/sofun/桌面/都正方案生成/研究程序数据集_不含给药描述/train_set.json. You should probably indicate the field of the 
JSON file containing your records. This JSON file contain the following fields: ['conversations']. Select the correct one
and provide it as `field='XXX'` to the dataset loading method. 

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /media/sofun/app/myproject/ChatGLM3/finetune_demo/finetune_hf.py:449 in main                     │
│                                                                                                  │
│   446 ):                                                                                         │
│   447 │   ft_config = FinetuningConfig.from_file(config_file)                                    │
│   448 │   tokenizer, model = load_tokenizer_and_model(model_dir, peft_config=ft_config.peft_co   │
│ ❱ 449 │   data_manager = DataManager(data_dir, ft_config.data_config)                            │
│   450 │                                                                                          │
│   451 │   train_dataset = data_manager.get_dataset(                                              │
│   452 │   │   Split.TRAIN,                                                                       │
│                                                                                                  │
│ /media/sofun/app/myproject/ChatGLM3/finetune_demo/finetune_hf.py:225 in __init__                 │
│                                                                                                  │
│   222 │   def __init__(self, data_dir: str, data_config: DataConfig):                            │
│   223 │   │   self._num_proc = data_config.num_proc                                              │
│   224 │   │                                                                                      │
│ ❱ 225 │   │   self._dataset_dct = _load_datasets(                                                │
│   226 │   │   │   _resolve_path(data_dir),                                                       │
│   227 │   │   │   data_config.data_format,                                                       │
│   228 │   │   │   data_config.data_files,                                                        │
│                                                                                                  │
│ /media/sofun/app/myproject/ChatGLM3/finetune_demo/finetune_hf.py:207 in _load_datasets           │
│                                                                                                  │
│   204 │   │   num_proc: Optional[int],                                                           │
│   205 ) -> DatasetDict:                                                                          │
│   206 │   if data_format in ('.csv', '.json', '.jsonl'):                                         │
│ ❱ 207 │   │   dataset_dct = load_dataset(                                                        │
│   208 │   │   │   data_format[1:],                                                               │
│   209 │   │   │   data_dir=data_dir,                                                             │
│   210 │   │   │   data_files=data_files,                                                         │
│                                                                                                  │
│ /home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/load.py:2582 in             │
│ load_dataset                                                                                     │
│                                                                                                  │
│   2579 │   try_from_hf_gcs = path not in _PACKAGED_DATASETS_MODULES                              │
│   2580 │                                                                                         │
│   2581 │   # Download and prepare data                                                           │
│ ❱ 2582 │   builder_instance.download_and_prepare(                                                │
│   2583 │   │   download_config=download_config,                                                  │
│   2584 │   │   download_mode=download_mode,                                                      │
│   2585 │   │   verification_mode=verification_mode,                                              │
│                                                                                                  │
│ /home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/builder.py:1005 in          │
│ download_and_prepare                                                                             │
│                                                                                                  │
│   1002 │   │   │   │   │   │   │   prepare_split_kwargs["max_shard_size"] = max_shard_size       │
│   1003 │   │   │   │   │   │   if num_proc is not None:                                          │
│   1004 │   │   │   │   │   │   │   prepare_split_kwargs["num_proc"] = num_proc                   │
│ ❱ 1005 │   │   │   │   │   │   self._download_and_prepare(                                       │
│   1006 │   │   │   │   │   │   │   dl_manager=dl_manager,                                        │
│   1007 │   │   │   │   │   │   │   verification_mode=verification_mode,                          │
│   1008 │   │   │   │   │   │   │   **prepare_split_kwargs,                                       │
│                                                                                                  │
│ /home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/builder.py:1100 in          │
│ _download_and_prepare                                                                            │
│                                                                                                  │
│   1097 │   │   │                                                                                 │
│   1098 │   │   │   try:                                                                          │
│   1099 │   │   │   │   # Prepare split will record examples associated to the split              │
│ ❱ 1100 │   │   │   │   self._prepare_split(split_generator, **prepare_split_kwargs)              │
│   1101 │   │   │   except OSError as e:                                                          │
│   1102 │   │   │   │   raise OSError(                                                            │
│   1103 │   │   │   │   │   "Cannot find data file. "                                             │
│                                                                                                  │
│ /home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/builder.py:1860 in          │
│ _prepare_split                                                                                   │
│                                                                                                  │
│   1857 │   │   │   gen_kwargs = split_generator.gen_kwargs                                       │
│   1858 │   │   │   job_id = 0                                                                    │
│   1859 │   │   │   with pbar:                                                                    │
│ ❱ 1860 │   │   │   │   for job_id, done, content in self._prepare_split_single(                  │
│   1861 │   │   │   │   │   gen_kwargs=gen_kwargs, job_id=job_id, **_prepare_split_args           │
│   1862 │   │   │   │   ):                                                                        │
│   1863 │   │   │   │   │   if done:                                                              │
│                                                                                                  │
│ /home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/builder.py:2016 in          │
│ _prepare_split_single                                                                            │
│                                                                                                  │
│   2013 │   │   │   │   e = e.__context__                                                         │
│   2014 │   │   │   if isinstance(e, DatasetGenerationError):                                     │
│   2015 │   │   │   │   raise                                                                     │
│ ❱ 2016 │   │   │   raise DatasetGenerationError("An error occurred while generating the dataset  │
│   2017 │   │                                                                                     │
│   2018 │   │   yield job_id, True, (total_num_examples, total_num_bytes, writer._features, num_  │
│   2019                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
DatasetGenerationError: An error occurred while generating the dataset

然后我在207行代码，load_dataset函数中添加了一个参数：field='conversations'
然后得到了另外一个报错：
Map (num_proc=24):   0%|                                                                  | 0/308 [00:00<?, ? examples/s]
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 623, in 
_write_generator_to_queue
    for i, result in enumerate(func(**kwargs)):
  File "/home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3482, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3361, in 
apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/media/sofun/app/myproject/ChatGLM3/finetune_demo/finetune_hf.py", line 271, in process_batch
    batched_conv = batch['conversations']
  File "/home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 270, in 
__getitem__
    value = self.data[key]
KeyError: 'conversations'
"""

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /media/sofun/app/myproject/ChatGLM3/finetune_demo/finetune_hf.py:451 in main                     │
│                                                                                                  │
│   448 │   tokenizer, model = load_tokenizer_and_model(model_dir, peft_config=ft_config.peft_co   │
│   449 │   data_manager = DataManager(data_dir, ft_config.data_config)                            │
│   450 │                                                                                          │
│ ❱ 451 │   train_dataset = data_manager.get_dataset(                                              │
│   452 │   │   Split.TRAIN,                                                                       │
│   453 │   │   functools.partial(                                                                 │
│   454 │   │   │   process_batch,                                                                 │
│                                                                                                  │
│ /media/sofun/app/myproject/ChatGLM3/finetune_demo/finetune_hf.py:250 in get_dataset              │
│                                                                                                  │
│   247 │   │   │   remove_columns = orig_dataset.column_names                                     │
│   248 │   │   else:                                                                              │
│   249 │   │   │   remove_columns = None                                                          │
│ ❱ 250 │   │   return orig_dataset.map(                                                           │
│   251 │   │   │   process_fn,                                                                    │
│   252 │   │   │   batched=batched,                                                               │
│   253 │   │   │   remove_columns=remove_columns,                                                 │
│                                                                                                  │
│ /home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/arrow_dataset.py:593 in     │
│ wrapper                                                                                          │
│                                                                                                  │
│    590 │   │   else:                                                                             │
│    591 │   │   │   self: "Dataset" = kwargs.pop("self")                                          │
│    592 │   │   # apply actual function                                                           │
│ ❱  593 │   │   out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)                │
│    594 │   │   datasets: List["Dataset"] = list(out.values()) if isinstance(out, dict) else [ou  │
│    595 │   │   for dataset in datasets:                                                          │
│    596 │   │   │   # Remove task templates if a column mapping of the template is no longer val  │
│                                                                                                  │
│ /home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/arrow_dataset.py:558 in     │
│ wrapper                                                                                          │
│                                                                                                  │
│    555 │   │   │   "output_all_columns": self._output_all_columns,                               │
│    556 │   │   }                                                                                 │
│    557 │   │   # apply actual function                                                           │
│ ❱  558 │   │   out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)                │
│    559 │   │   datasets: List["Dataset"] = list(out.values()) if isinstance(out, dict) else [ou  │
│    560 │   │   # re-apply format to the output                                                   │
│    561 │   │   for dataset in datasets:                                                          │
│                                                                                                  │
│ /home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/arrow_dataset.py:3197 in    │
│ map                                                                                              │
│                                                                                                  │
│   3194 │   │   │   │   │   │   total=pbar_total,                                                 │
│   3195 │   │   │   │   │   │   desc=(desc or "Map") + f" (num_proc={num_proc})",                 │
│   3196 │   │   │   │   │   ) as pbar:                                                            │
│ ❱ 3197 │   │   │   │   │   │   for rank, done, content in iflatmap_unordered(                    │
│   3198 │   │   │   │   │   │   │   pool, Dataset._map_single, kwargs_iterable=kwargs_per_job     │
│   3199 │   │   │   │   │   │   ):                                                                │
│   3200 │   │   │   │   │   │   │   if done:                                                      │
│                                                                                                  │
│ /home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/utils/py_utils.py:663 in    │
│ iflatmap_unordered                                                                               │
│                                                                                                  │
│   660 │   │   finally:                                                                           │
│   661 │   │   │   if not pool_changed:                                                           │
│   662 │   │   │   │   # we get the result in case there's an error to raise                      │
│ ❱ 663 │   │   │   │   [async_result.get(timeout=0.05) for async_result in async_results]         │
│   664                                                                                            │
│                                                                                                  │
│ /home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/datasets/utils/py_utils.py:663 in    │
│ <listcomp>                                                                                       │
│                                                                                                  │
│   660 │   │   finally:                                                                           │
│   661 │   │   │   if not pool_changed:                                                           │
│   662 │   │   │   │   # we get the result in case there's an error to raise                      │
│ ❱ 663 │   │   │   │   [async_result.get(timeout=0.05) for async_result in async_results]         │
│   664                                                                                            │
│                                                                                                  │
│ /home/sofun/anaconda3/envs/NLP/lib/python3.10/site-packages/multiprocess/pool.py:774 in get      │
│                                                                                                  │
│   771 │   │   if self._success:                                                                  │
│   772 │   │   │   return self._value                                                             │
│   773 │   │   else:                                                                              │
│ ❱ 774 │   │   │   raise self._value                                                              │
│   775 │                                                                                          │
│   776 │   def _set(self, i, obj):                                                                │
│   777 │   │   self._success, self._value = obj                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'conversations'
奇怪的是，我换一个json文件却又可以正常微调，而且不需要加参数field='conversations'
然而我仔细检查了两个json文件，除了后面这个数据量大一点，input和output多一些，格式上是一模一样的，请问一下这是为什么

### Expected behavior / 期待表现

希望了解更多数据加载的相关问题

**Comment by zRzRzRzRzRzRzR** [comment]
你改一下最长字数限制

**Comment by orderer0001** [comment]
> 你改一下最长字数限制

我把训练数据集分成了两批，一半一半微调好像是可行的 ，但是遇到了一个新的问题，就是我的max_input有1420个字，我把这个参数改成1420 输出520 以后 发现4090 24g的显卡会内存溢出

**Comment by zRzRzRzRzRzRzR** [comment]
max_input越大，需要的显存越多，这是很正常的啊

**Comment by orderer0001** [comment]
> max_input越大，需要的显存越多，这是很正常的啊

请问有计算公式吗

**Comment by zRzRzRzRzRzRzR** [comment]
没有进行科学的计算，但是这个增量大概是线性的

**Comment by orderer0001** [comment]
> 没有进行科学的计算，但是这个增量大概是线性的

 那请问这个配置文件中的max_input_length、max_output_length是指的文本字数还是指token数？比如我的输入是1400字，那么这里是1400 还是要小一点 比如1000.另外  generation_config中有一个参数max_new_tokens 这个参数是和max_output_length一样的吗？如果不是输出长度，那它是指什么呢？

**Comment by zRzRzRzRzRzRzR** [comment]
文本
