### ISSUE TITLE
请问chatglm3-6b模型支持的最大token是多少

### ISSUE THREAD

**Issue by wfangyan** [THUDM/ChatGLM3#987]
### System Info / 系統信息

linux环境，两块t4显卡

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

能简单跑一下，但是输入的最大token无法确定

### Expected behavior / 期待表现

期待可以明确回复

**Comment by zRzRzRzRzRzRzR** [comment]
8192 长度，输出输出加起来不要超过这个
