### ISSUE TITLE
【关于训练过程】请教训练过程中的问题

### ISSUE THREAD

**Issue by zzisbeauty** [THUDM/ChatGLM3#989]
### System Info / 系統信息

- A100  单机单卡
- Ubuntu
- 32K 指令模型

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本； 使用的是模型给定的单机单卡的训练脚本。lora 训练方式，且只改变了 steps 参数，其他未做配置的更改。
- [ ] ~~My own modified scripts / 我自己修改的脚本和任务~~

### Reproduction / 复现过程

- 情况：使用的是32K模型，做对话SFT，指令相对较长；
- 训练可以正常启动，但是训练一段时间后，会提示爆显存，就是说模型显存占用随着时间进行而不断增长

### Expected behavior / 期待表现

针对上述问题，想知道这是为什么。
我读了训练代码，但是不清楚为什么会出现这样的情况。
老师可以告诉我可能的原因，让我有学习的切入点；

以上，期待得到老师的答复。

**Comment by zRzRzRzRzRzRzR** [comment]
你最大长度设定多少

**Comment by zzisbeauty** [comment]
> 你最大长度设定多少

抱歉，昨天就看到老师的答复，但是一打岔忘记了，输入输出都是 10000； 
一般上文指令的长度大概在 5k~6k 左右，输出也有  1k~2k左右。
反正都是挺长的。

**Comment by zRzRzRzRzRzRzR** [comment]
那肯定是超了。

**Comment by zzisbeauty** [comment]
> 那肯定是超了。 这么长的文本需要多卡了，token太长了

感谢老师

但是我看了训练代码，包括 lora 的过程，我不能理解究竟是哪里导致的功能模块，导致最后的显存爆掉了。老师能再给一些可能的方向吗？ 我没有找到可能是在哪里导致的这样的问题。


因为如果过长就爆掉。那这样的逻辑意味着即使很短的 prompt，但是如果 epoch 无限大也会爆掉。

**Comment by zRzRzRzRzRzRzR** [comment]
token越大，所需要占用的显存越多

**Comment by zRzRzRzRzRzRzR** [comment]
我大概知道了，这个问题估计不太好复现这个问题。

**Comment by zzisbeauty** [comment]
嗯，我会抽时间再debug一下。感谢老师。
