### ISSUE TITLE
python web_demo2.py报错：AttributeError: st.session_state has no attribute "history". 

### ISSUE THREAD

**Issue by seuchenyu** [THUDM/ChatGLM3#99]
我用的streamlit==1.28.0 python=3.10
python web_demo2.py报错：
Traceback (most recent call last):
  File "/root/chenyu/ChatGLM3/web_demo2.py", line 50, in <module>
    for i, message in enumerate(st.session_state.history):
  File "/root/anaconda3/envs/py310_glm3/lib/python3.10/site-packages/streamlit/runtime/state/session_state_proxy.py", line 121, in __getattr__
    raise AttributeError(_missing_attr_error_message(key))
AttributeError: st.session_state has no attribute "history". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization

我看了代码，已经有初始化代码了：
# 初始化历史记录和past key values
if "history" not in st.session_state:
    st.session_state.history = []

但还是报错

**Comment by zhaoxin** [comment]
streamlit run web_demo2.py

**Comment by wqw547243068** [comment]
> streamlit run web_demo2.py

这个命令能正常执行，但是两个URL都无法访问

**Comment by linkarys** [comment]
估计是`streamlit`对`python3.10`没兼容导致的：
直接运行[官方文档](https://docs.streamlit.io/library/advanced-features/session-state#initialization)中的`Example 1`也是报类似的错误：

```python
import streamlit as st

st.title('Counter Example')
if 'count' not in st.session_state:
    st.session_state.count = 0

increment = st.button('Increment')
if increment:
    st.session_state.count += 1

st.write('Count = ', st.session_state.count)
``` 

错误内容:
```python
Exception has occurred: AttributeError
st.session_state has no attribute "count". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization
KeyError: 

During handling of the above exception, another exception occurred:

KeyError: 'st.session_state has no key "count". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'

During handling of the above exception, another exception occurred:

  File "/home/linkary/ML/ChatGLM3/test.py", line 11, in <module>
    st.write('Count = ', st.session_state.count)
AttributeError: st.session_state has no attribute "count". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization
```

**Comment by ScottXiao233** [comment]
> > streamlit run web_demo2.py
> 
> 这个命令能正常执行，但是两个URL都无法访问

你好，现在你能运行了吗？这两个URL

**Comment by zRzRzRzRzRzRzR** [comment]
streamlit run web_demo2.py 可以正常运行，访问的URL的问题请提供具体截图方便定位问题

**Comment by ScottXiao233** [comment]
streamlit run web_demo2.py --server.address=127.0.0.1能成功运行

**Comment by zRzRzRzRzRzRzR** [comment]
如上述方案无法解决，请按照issue模板发布最小复现，感谢支持，该issue先关闭

**Comment by wqw547243068** [comment]
> > > streamlit run web_demo2.py
> > 
> > 
> > 这个命令能正常执行，但是两个URL都无法访问
> 
> 你好，现在你能运行了吗？这两个URL

一直不行，放弃了
