### ISSUE TITLE
请问，微调后的模型可以接受batch输入并一起返回吗？如何操作呢？

### ISSUE THREAD

**Issue by orderer0001** [THUDM/ChatGLM3#994]
请问，微调后的模型可以接受batch输入并一起返回吗？如何操作呢？目前使用demo提供的加载方法，好像prompt参数不能是数组。我尝试了使用generate方法（使用微调过的模型），结果不那么准确，还是使用chat方法要更准确，但是chat方法能兼容batch推理吗？

**Comment by zRzRzRzRzRzRzR** [comment]
不能，全参可以

**Comment by orderer0001** [comment]
> 不能，全参可以

好的 谢谢

**Comment by Leawnn** [comment]
> 不能，全参可以

请问一下”全参可以“是什么意思？是ChatGLM3 chat模型可以使用chat方法来batch推理吗
