### ISSUE TITLE
p-tuning v1供求

### ISSUE THREAD

**Issue by Duperr** [THUDM/ChatGLM3#996]
### Feature request  / 功能建议

希望可以增加p-tuning v1的使用方法

### Motivation / 动机

p-tuning v2不适合部分任务的改进

### Your contribution / 您的贡献

https://github.com/THUDM/P-tuning

**Comment by zRzRzRzRzRzRzR** [comment]
这个技术已经淘汰了吧，现在都是v2了，所以没有做V1
