### ISSUE TITLE
GLM3在问答中容易陷入循环回复

### ISSUE THREAD

**Issue by CPPBS** [THUDM/ChatGLM3#998]
### System Info / 系統信息

Cuda:12.1.1
Transformers:4.37.2
py:3.11.7(use Anaconda3)
OS:Windows Server 2022 Datacenter
CPU:Inter(R) Xeon(R) CPU E5-2860 v4 @2.40GHz x2
RAM:32GB RECC x2
GPU:NVidia Tesla P40 24GB ECC
设备平台:Dell r730xd
我不确定是否和硬件特性相关所以一并提供该信息

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.按照上述软硬环境进入py3.11.7
2.> streamlit run basic_demo\web_demo_streamlit.py 
      _//此文件为来源为“basic_demo”文件夹下的预设demo，我按照说明文档修改以实现本地离线加载于Hugging Face下载的GLM3模型_
3.使用edge进入url 
4.询问“IIS如何安装jsp”
得到问题：
```
在 IIS 中安装 JSP,可以按照以下步骤进行:

打开 IIS 管理器,并选择你要安装 JSP 的网站。
在右侧窗格中,选择“处理程序”。
在“处理程序”窗口中,选择“添加”。
在“添加处理程序”窗口中,选择“创建一个新的处理程序”。
在“创建新的处理程序”窗口中,选择“创建自定义的模块”。
在“创建自定义的模块”窗口中,选择“创建一个新的模块”。
在“创建新的模块”窗口中,选择“创建一个 JSP 模块”。
在“创建 JSP 模块”窗口中,选择“创建”。
在“创建 JSP 模块”窗口中,选择“完成”。
在“创建 JSP 模块”窗口中,选择“完成”。
在“创建 JSP 模块”窗口中,选择“完成”。
在“创建 JSP 模块”窗口中,选择“完成”。
在“创建 JSP 模块”窗口中,选择“完成”。
在“创建 JSP 模块”窗口中,选择“完成”。
在“创建 JSP 模块”窗口中,选择“完成”。
在“创建 JSP 模块”窗口中,选择“完成”。
.....
在“创建 JSP 模块”窗口中,选择“完成”。
.....
```
还有其他情景会出现类似死循环回答
一般出现于方法解答和流程解答中，多发于相似语句(e.g. ABC ;ABD ;ABE ;ABE进入循环)

### Expected behavior / 期待表现

降低循环发生次数或者检查模型层面是否存在相近语义缺陷？
或者加入生成后内容检查，清除循环？
惩罚学习？

**Comment by zRzRzRzRzRzRzR** [comment]
尝试调高惩罚系数这个参数到1.1

**Comment by jmsking** [comment]
这个惩罚系数在哪里设置了？
